### ISSUE TITLE
Intermittent sound and voice on two-way audio RTSP, ISAPI, Hikvision DS-KV6113, GO2RTC, WEBRTC, WEBRTC-CAMERA, media_player:   - platform: webrtc

### ISSUE THREAD

**Issue by TokarevSergey** [AlexxIT/go2rtc#1000]
Good afternoon. Please help.
I have a Hikvision DS-KV6113 doorbell added to Home Assistant via Frigate go2rtc in this way:
```
go2rtc:
   streams:
     DoorBell:
       - rtsp://admin:00@10.0.0.11:554/ISAPI/Streaming/Channels/101
       - isapi://admin:00@10.0.0.11:80/
     DoorBellCh2:
       - rtsp://admin:00@10.0.0.11:554/ISAPI/Streaming/Channels/102
       - isapi://admin:00@10.0.0.11:80/
```
I added media players to the configuration.yaml file like this:
```
media_player:
   - platform: webrtc
     name: PlayerDoorBell
     stream: DoorBell
     audio: pcmu/8000

   - platform: webrtc
     name: PlayerDoorBellCh2
     stream: DoorBellCh2
     audio: pcmu/8000
```
In the web interface I added a camera via the webrtc-camera video and sound card:
```
type: custom:webrtc-camera
url: DoorBellCh2
mode: webrtc
media: video, audio
muted: true
background: true
style: 'video {aspect-ratio: 16/9; object-fit: fill;}'
```
And the camera via the webrtc-camera card video, sound and microphone:
```
type: custom:webrtc-camera
url: DoorBellCh2
mode: webrtc
media: video, audio, microphone
muted: true
background: true
style: 'video {aspect-ratio: 16/9; object-fit: fill;}'
```
So, if you make multiple connections to a two-way audio camera, or while watching a two-way audio camera, play some audio file through the media player, the sound on that camera will become quiet and choppy, and if you speak into the microphone, the voice will become choppy. I tried changing different firmware on the camera, but it didn't help. If you reboot the frigate go2rtc everything becomes normal and works for some time.
I also noticed that when this happens, the microphone on the camera and on the browser tab works for a long time, and the Android phone can generally transmit sound and voice even after closing and unloading the application.
Is it possible to somehow fix this or add some command to reload the stream very quickly. Help me please. Thank you.
