### ISSUE TITLE
Missing first seconds of audio when playing two way audio

### ISSUE THREAD

**Issue by blanknam3d** [AlexxIT/go2rtc#1008]
Forgive me for perhaps being a bit naive here... I'm currently using Tapo C200 cameras, I got 2-way audio working, however when the cameras play the audio sent to them they miss the first second or so of audio. Given that the cameras are only playing 8khz audio, I figure that's simply a result of the camera's hardware limits & not a fault of go2rtc.

Is it possible to set FFmpeg options for only audio streamed to the cameras, so I could add a short 1 second of silence in the audio sent to the cameras? I've read through just about all the documentation & I'm not sure how I could do so, though I'm also the kind of person to miss the obvious solution after reading it several times. I don't want to add any delay in audio or video from the cameras, just the audio streamed to them.

**Comment by AlexxIT** [comment]
I'll check on my camera. Maybe the 1-second problem can be fixed.

**Comment by AlexxIT** [comment]
It was a really hard task...

**Comment by blanknam3d** [comment]
It seems something else that was changed in the update might've broken the ability to play back audio files through Home Assistant... Previously this worked, however in 1.9.3, this seems to have stopped working suddenly. Two-way audio with a video+audio stream over HTTPS still works fine, however I can no longer play audio files to the cameras locally after updating to 1.9.3.

In my HAss configuration.yaml:

```
media_player:
  - platform: webrtc
    entity_id: media_player.lrtapo
    name: Livingroom Camera
    stream: lrtapo
    audio: pcma
  - platform: webrtc
    entity_id: media_player.kitapo
    name: Kitchen Camera
    stream: kitapo
    audio: pcma
```

go2rtc configuration:

```
streams:
  kitchen: tapo://PASSWORD@192.168.0.xx
  livingroom: tapo://PASSWORD@192.168.0.xx
```

Is there something I'm doing wrong, or was something else changed? Searched other issues pretty extensively & read through both README's for WebRTC and go2rtc, not sure what isn't right with how I've configured the virtual media players.
