### ISSUE TITLE
I have created a this same issue on frigate repo, but it seems that it better to be reported here.


### ISSUE THREAD

**Issue by morenod** [AlexxIT/go2rtc#1017]
I have a camera capture working with go2rtc and I can see it as frigate camera, but Im trying to publish it as a youtube stream, but I dont see any reference to it on the logs, and if I click on the system > streams info link, I dont see any reference neither

Version

0.13.2-6476F8A

Frigate config file

go2rtc: publish: camara_11: - rtmps://a.rtmps.youtube.com/live2/xxxxxxx - rtmps://b.rtmps.youtube.com/live2?backup=1/xxxxxx streams: camara_11: # BirdCAM - http://esp32-birdcam.local:8080 - ffmpeg:camara_11#video=h264#hardware cameras: birdcam: ffmpeg: inputs: - path: rtsp://127.0.0.1:8554/camara_11 roles: - detect - record

Relevant log output

No logs references to that publish. Searching for youtube hostname do not output any result

Frigate stats

No response

Operating system

Other Linux

Install method

Docker CLI

Coral version

USB

Any other information that may be helpful

**Comment by troykelly** [comment]
I'm having the same issue, not sure how to debug, but YouTube never gives any indication of their even being an attempt to start the stream.

```yaml
  log:
    format: text
    level: info  # default level
    api: info
    exec: info
    ngrok: info
    rtsp: info
    streams: info
    webrtc: info
  streams:
    webcam_sydney:
    - ffmpeg:rtsp://camera:password@example.invalid/#video=copy
    webcam_sydneyh264:
    - ffmpeg:webcam_sydney#video=h264#hardware
  webrtc:
    listen: :8555    # address of your local server and port (TCP/UDP)
    candidates:
    - stun:8555
  publish:
    webcam_sydneyh264:
      - rtmps://a.rtmp.youtube.com/live2/aaaa-bbbb-cccc-dddd-eeee
      - rtmp://b.rtmp.youtube.com/live2/aaaa-bbbb-cccc-dddd-eeee?backup=1
```
