### ISSUE TITLE
I can't link display+speaker, please help

### ISSUE THREAD

**Issue by Barabba11** [AlexxIT/go2rtc#1022]
Hi, I?ve followed the instructions:
Create empty stream in the go2rtc.yaml
    Go to go2rtc WebUI
    Open links page for you stream
    Select camera+microphone or display+speaker option
    Open webrtc local page (your go2rtc should work over HTTPS!) or share link via [WebTorrent](https://github.com/AlexxIT/go2rtc#module-webtorrent) technology (work over HTTPS by default)

I didn't know how to create an empty stream and couldn't find this anywhere, so I created a temporary stream by the api with address 127.0.0.1 (epty address won't be saved on config) and restarted, then on config I've deleted 127.0.0.1 so it became empty. 
Then I clicked on links and there I clicked on display+speaker = broadcast software, but there isn't a button to save this on config, the next time it became again empty. So I clicked on [webrtc.html](http://127.0.0.1:1984/webrtc.html?dst=test&media=display+speaker) local WebRTC viewer bu I see black screen, it doesn't work.

Can somebody please simply post here an example config yaml file for broadcasting RTC the desktop? It can be also with ffmpeg, I can't figure out myself. Thank you!

**Comment by Barabba11** [comment]
I have this error:

![go2rtc-error](https://github.com/AlexxIT/go2rtc/assets/13357642/ec036315-8377-4425-bd79-fdcf0c9c791f)

**Comment by Barabba11** [comment]
I've tried with ffmpeg trying to collect together random examples, bu i don't know the proper syntax

```
streams:
  test: ffmpeg:dshow -i video="screen-capture-recorder"
ffmpeg:
  bin: c:\ffmpeg.exe
```

I have this error:
![go2rtc-error](https://github.com/AlexxIT/go2rtc/assets/13357642/6191984d-81f4-46ad-a8f7-5492bd2c9695)

**Comment by Barabba11** [comment]
I hope somebody can help me, thanks

**Comment by AlexxIT** [comment]
Empty stream - just name without source.

**Comment by Barabba11** [comment]
> Empty stream - just name without source.

Thank you for your answer, can you please post me a correct script to use ffmpeg, in particular to open the desktop. I can't find an example that shows me how can I paasa arguments to ffmpeg. Thank you!!

**Comment by AlexxIT** [comment]
I don't know how to share desktop via FFmpeg from windows

**Comment by Barabba11** [comment]
With this command I'm able to record the desktop into a file, how can I use these parameters with go2rtc?
Thank you!
`ffmpeg -f gdigrab -framerate 30 -i desktop c:log\output.mkv`

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-exec

**Comment by Barabba11** [comment]
I can't figure out how to make it work, I?ve tried the following config:
```
ffmpeg:
  bin: c:\go2rtc\ffmpeg.exe
  
api:
  listen: ":80"    # default ":1984", HTTP API port ("" - disabled)
  origin: "*"        # default "", allow CORS requests (only * supported)
  
streams:
    exec: c:\go2rtc\ffmpeg.exe -f gdigrab -framerate 30 -i desktop

webrtc:
    candidates:
    - stun:8555
```
as result I have:
mse streams streams unsupported scheme c \go2rtc\ffmpeg exe -f gthgrab -framerate 30 -1 desktop                  error 

if I type on DOS ffmpeg -f gdigrab -framerate 30 -i desktop c:log\output.mkv I can save the file video, so it works on this PC, but I can't grab video on go2rtc.

Can somebody please please please write me a working script to grab the screen and send to HLS? Thank you!!!!! I really don't know what to do for a such simple thing :(

**Comment by Barabba11** [comment]
I've tried again, created empty file, then on links selected screen+audio, I got this error in log:

01:13:00.590 INF [webrtc] listen addr=:8555/tcp
01:13:33.844 ERR github.com/AlexxIT/go2rtc/internal/webrtc/webrtc.go:183 > error="SetRemoteDescription called with no ice-ufrag"

**Comment by Barabba11** [comment]
```
This is m config, almost empty ad suggested: 
api:
  listen: ":80"    # default ":1984", HTTP API port ("" - disabled)
  origin: "*"        # default "", allow CORS requests (only * supported)
 
streams:
    boia:
```
then I use the 2 links available in links page
http://127.0.0.1/webrtc.html?dst=boia&media=display+speaker
http://127.0.0.1/links.html?src=boia# (this reminds the same page)

and I have the error ERR github.com/AlexxIT/go2rtc/internal/webrtc/webrtc.go:183 > error="SetRemoteDescription called with no ice-ufrag"

I can't understand why it's so complicated (
