### ISSUE TITLE
Unable to get any streams from go2rtc

### ISSUE THREAD

**Issue by Morphy99** [AlexxIT/go2rtc#103]
I'm using HA OS and gortc addon. Then installed RTSPtoWebRTC and set up as specified http://127.0.0.1:1984/

I get these errors when trying to view RTMP cameras and no stream:
WRN [api.webrtc] add consumer error="couldn't find the matching tracks"
ERR [api.hass] exchange SDP error="couldn't find the matching tracks"

When trying RTSP cameras this error:
WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:109 > error="read tcp hass-ip:53710->camera-ip:554: i/o timeout"

I've also tried adding RTSP streams from them to the config file in /config/go2rtc.yaml:

```
streams:
  front: rtsp://x:x@192.168.1.222:554/h264Preview_01_main
  drive: rtsp://x:x@192.168.1.212:554/h264Preview_01_main
  yard: rtsp://x:x@192.168.1.103:554/h264Preview_01_main
```
But I get timeout when trying to add a generic camera:

![image](https://user-images.githubusercontent.com/5853979/200938527-06a78ca2-b68e-4630-8b18-e42cb1b49494.png)
