### ISSUE TITLE
Reolink video doorbell WiFi - Output is very choppy and start is cut off when sending mp3 files

### ISSUE THREAD

**Issue by cooltings** [AlexxIT/go2rtc#1038]
My Reolink doorbell produces choppy audio when sending mp3s. Here is my config:
```
api:
  origin: '*'
ffmpeg:
  bin: ffmpeg
  h264/rk: -c:v h264_rkmpp_encoder -g 50 -bf 0
  h265/rk: -c:v hevc_rkmpp_encoder -g 50 -bf 0
  rtsp: -fflags nobuffer -flags low_delay -stimeout 5000000 -user_agent go2rtc/ffmpeg
    -rtsp_transport tcp -i {input}
  volume: -af "volume=30dB"
hass:
  config: /config
log:
  format: text
rtsp:
  default_query: mp4
streams:
  reolink:
  - ffmpeg:http://192.168.0.33/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=UNAME&password=PSD#video=copy#audio=copy#audio=pcma
  - rtsp://UNAME:PSD@192.168.0.33:554/h264Preview_01_sub
  reolink_rec:
  - rtsp://UNAME:PSD@192.168.0.33:554/h264Preview_01_sub#backchannel=0
  - ffmpeg:reolink_rec#audio=pcma
webrtc:
  candidates:
  - 192.168.0.219:8555
  - stun:8555
```
I have tried both media player and api calls, here is my config for media player:
media_player:
  - platform: webrtc
    name: Doorbell
    stream: reolink
    audio: '-af "volume=10dB,adelay=2s,apad=pad_dur=6" -c:a pcm_alaw -ar:a 8000 -ac:a 1'
Anyone else having this issue?

**Comment by AlexxIT** [comment]
#331

**Comment by AlexxIT** [comment]
I don't have this device and can't improve performance remotely

**Comment by ruant** [comment]
@cooltings 
Did you figure out the distortion part?  
My 2way audio from with a mic is clear as day, playing a TTS mp3 I can more or less hear nothing, so much static and distortion, also some times just parts of the mp3.

**Comment by cooltings** [comment]
My 2 way audio works fine now however my tts/ sending mp3 files doesn't work most of the time and when it does there is about 10 seconds at the start of the file cutout. However, when it does eventually play the quality is as expected.

**Comment by ruant** [comment]
@cooltings 
Hmm, ok. Mine plays everytime I try to play something, but as I said it's static noise and distorted so you can't make out anything being said. And often with a few seconds delay.

Don't understand why the 2way talking with mic through the frigatecard in HA is clear as day and the TTS mp3 playing is so crap :/

Do you mind show me your `media_player` and go2rtc stream config?

> frigate.yml
```
go2rtc:
  webrtc:
  streams:
    frontdoor:
      - ffmpeg:http://192.168.1.20/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password#video=copy#audio=copy#audio=opus
      - rtsp://user:password@192.168.1.20/Preview_01_sub
    frontdoor_sub:
      - ffmpeg:http://192.168.1.20/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=password
```
> configuration.yaml
```
media_player:
  - platform: webrtc
    name: Frontdoor
    stream: frontdoor
    audio: pcma
    # audio: '-af "volume=20dB"'
    # audio: '-af "volume=20dB,adelay=2s,apad=pad_dur=6"'
    # audio: '-af "volume=10dB,adelay=2s,apad=pad_dur=6" -c:a pcm_alaw -ar:a 48000 -ac:a 1'
    # audio: '-af "volume=10dB,adelay=2s,apad=pad_dur=6" -c:a opus -ar:a 48000 -ac:a 1'
    # audio: '-af "volume=10dB,apad=pad_dur=6" -c:a libopus -ar 48000 -b:a 128k -ac 2'
```
