### ISSUE TITLE
Audio from Webcam under Windows

### ISSUE THREAD

**Issue by Aroxed** [AlexxIT/go2rtc#1042]
I try to stream my laptop webcam under Windows so I use a config as the following:
```
streams:
  windows_webcam: 
    - ffmpeg:device?video=0#video=h264
http:
    listen: ":1984"    
```
The video is streamed well but no sound. What should I do to hear audio?
And tell me please if it's possible to record the streamed video/audio?

Sorry for the beginner's questions and thanks for the amazing project.
