### ISSUE TITLE
mse: streams: wrong user/pass

### ISSUE THREAD

**Issue by miqmago** [AlexxIT/go2rtc#1065]
I've seen this closed issue: https://github.com/AlexxIT/go2rtc/issues/63

In my case I have a tapo cam. I'm using this config in go2rtc:

```yml
    camara_s1:
        - rtsp://MyUser:MyPass123@192.168.1.239:554/stream2
    camara_s2:
        - rtsp://MyUser:MyPass123@192.168.1.239:554/stream1
```

If I open the link on the browser it opens VLC and the stream works fine. MyUser and MyPass123 only have letters and numbers. If I use tapo stream it works all fine, but I would like to access to stream2.
