### ISSUE TITLE
Re-using homekit URL from HomeAssistant results in ffmpeg initialization error

### ISSUE THREAD

**Issue by visigoth** [AlexxIT/go2rtc#1082]
I am using Frigate's builtin go2rtc running in a docker instance. I have a HomeAssistant docker instance on the same box. The config path for HomeAssistant is mapped into the Frigate docker instance at /hass_config.

I have go2rtc configured like this inside the frigate configuration, and the frigate configuration is below that

```

go2rtc:
  rtsp:
    username: "camera"
    password: "XXXXXXXXX"
  hass:
    config: "/hass_config"
  streams:
    doorbell:
      - homekit://192.168.0.71:49152?client_id=...&client_private=...&device_id=...&device_public=...


cameras:
  doorbell:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-stream
          roles:
            - detect
            - record
      hwaccel_args: preset-intel-qsv-h264
```

note i have a number of other plain PoE RTSP cameras that are working fine with go2rtc + frigate doing both detection and recording. the above snippet just shows the one HomeKit camera i have for the doorbell. also note that i tried `hass:camera.doorbell` as well for the URL but i kept getting `no entity_id` and 404 errors in the log. i manually formatted the `homekit://` URL as above.

when i start things up, i get `Could not find codec parameters for stream 0 (Video: h264, 1 reference frame, none): unspecified size`

i tried increasing the `analyzeduration` and `probesize` values as suggested, but that didn't work either.

the information ffmpeg is able to get out of go2rtc is:
```
[tcp @ 0x557adb5cd580] Successfully connected to 127.0.0.1 port 8554
[rtsp @ 0x557adb5ca540] SDP:
v=0
o=- 1 1 IN IP4 0.0.0.0
s=go2rtc/1.8.4
c=IN IP4 0.0.0.0
t=0 0
m=video 0 RTP/AVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=4D001F
a=control:trackID=0
```
