### ISSUE TITLE
Allow to use stream name as stream input (without ffmpeg)

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/go2rtc#109]
Since v0.1-rc.3 we can do the following:

```yaml 
streams:
  camera.morro:
    - rtsp://admin:admin@192.168.1.34:6554/stream_1
    - ffmpeg:camera.morro#audio=aac
```

But it would be also useful if the same notation could also be used without ffmpeg. Something like:

```diff
streams:
  rua_hd_aac:
    - ffmpeg:rtsp://admin:12345@192.168.1.33:554/0/av0#video=copy#audio=aac
  camera.rua:
    - rtsp://admin:12345@192.168.1.33:554/0/av1
-   - rtsp://localhost:8554/rua_hd_aac?audio=copy
+   - rua_hd_aac?audio=aac
```
