### ISSUE TITLE
From one camera stream, provide one with and one without audio?

### ISSUE THREAD

**Issue by rschaeuble** [AlexxIT/go2rtc#1096]
I'm using go2rtc within Frigate, with the following configuration. So far, it's working well.

```
go2rtc:
  streams:
    Tapo_C210:
    - tapo://password@a.b.c.d
    - "ffmpeg:Tapo_C210#audio=aac"
    - "ffmpeg:Tapo_C210#audio=opus"
```

Now what I would like to achieve: out of the one camera stream (which contains audio), I'd like go2rtc to provide two output streams: one with audio, and one without.
The final goal is to have the stream with audio being used by Frigate for detection, while the one without audio is used for recording and live viewing (I don't want the audio here for privacy reasons).

How would I configure that? I know how to add additional options (like adding AAC and OPUS in the configuration above), but I don't know how to suppress audio completely. And ideally, if possible, go2rtc would only open one stream on the camera.

**Comment by AlexxIT** [comment]
1. You don't need OPUS audio, because tapo provide PCMA audio. It's compatible with WebRTC and MSE.
2. You need AAC only if you want audio inside Frigate's mp4 storage.

It depends, where you wan stream without audio.
For example, WebRTC card support request only video  with `media: video` setting.
Go2rtc RTSP server also support return stream with only video with `?video` query param.

**Comment by rschaeuble** [comment]
Thanks for the quick answer :)

1. Good to know => I'll remove it.
2. That's a left-over from when the initial setup => I'll remove it.

So, does the following look reasonable?
```
go2rtc:
  streams:
    # Full stream with audio and video
    Tapo_C210_full:
    - tapo://password@a.b.c.d
    # Limited stream with audio stripped
    Tapo_C210:
    - "ffmpeg:Tapo_C210_full?video"
```

In Frigate I'd then call the camera "Tapo_C210", so the non-audio stream would be picked up for live preview (afaik, it's not possible to specify a stream URL for the live view manually). For recording I would also use that stream, but for audio detection I'd use "Tapo_C210" (and Frigate would only request the audio stream).

**Comment by AlexxIT** [comment]
Not best idea, because you get internal rtsp loop. But that's the only option at the moment

```yaml
go2rtc:
  streams:
    Tapo_C210_full: tapo://password@a.b.c.d
    Tapo_C210: rtsp://localhost:8554/Tapo_C210_full?video
```
