### ISSUE TITLE
Docker install not using config file

### ISSUE THREAD

**Issue by maxi1134** [AlexxIT/go2rtc#11]
Hey there,
Me again!

I ran this docker-compose file to get the docker to run:

```
version: '3.3'
services:
    go2rtc:
        volumes:
            - '/home/maxi1134/docker/go2rtc/go2rtc.yaml:/app/go2rtc.yaml'
        network_mode: host
        restart: always
        logging:
            options:
                max-size: 1m
        image: 'alexxit/go2rtc:latest'
        container_name: go2rtc
```

But it seems like the file is not picked up.

Could someone head me in the right direction? My go2rtc.yaml file looks like this:

```
streams:
  front_door_camera:
    - rtsp://user:password@192.168.0.210/h264Preview_01_main
    - rtsp://user:password@192.168.0.210/h264Preview_01_sub
  patio_camera:
    - rtmp://192.168.50.10:1935/livemain
  faceshot_camera:
    - rtsp://user:password@192.168.50.9:8554/12
  back_door_camera:
    - rtsp://192.168.50.1:8554/CH001.sdp
```

![image](https://user-images.githubusercontent.com/1342643/186278507-e269f9d1-be78-40e4-bb71-cc6d2b66b446.png)
