### ISSUE TITLE
H264 MSE Stream freezes on Chrome

### ISSUE THREAD

**Issue by franconoronha** [AlexxIT/go2rtc#1102]
I have a mix of H265 and H264 sources on my config file:
```
api:
  origin: "*"
log:
  format: text

streams:
  T01_v: rtsp://...
  T01_r: rtsp://...

  T02_v: rtsp://...
  T02_r: rtsp://...
...and so on
```

All H265 sources work fine on Chrome/Edge. Whenever I access a H264 stream through http://localhost:1984/stream.html?src=T01_v&mode=mse, it freezes after some time have passed (some times almost immediately). Websocket messages keep coming, but the video freezes.

{
    "type": "mse",
    "value": "video/mp4; codecs=\"avc1.420028\""
}

chrome://media-internals/ logs:
00:00:18.652 | error | {"cause":{"code":6,"data":{"VDA Error":0},"group":"D3D11Status","message":"","stack":[{"file":"media\\gpu\\windows\\d3d11_video_decoder.cc","line":678}]},"code":1,"data":{},"group":"DecoderStatus","message":"","stack":[{"file":"media\\gpu\\windows\\d3d11_video_decoder.cc","line":980}]}
-- | -- | --
00:00:18.652 | error | "video decode error!"
00:00:18.776 | error | {"cause":{"code":108,"data":{},"group":"DecoderStatus","message":"","stack":[{"file":"media\\filters\\decoder_stream.cc","line":191}]},"code":3,"data":{},"group":"PipelineStatus","message":"","stack":[{"file":"media\\renderers\\video_renderer_impl.cc","line":592}]}
