### ISSUE TITLE
homekit device_id cannot be set

### ISSUE THREAD

**Issue by mnakada** [AlexxIT/go2rtc#1103]
Even if the device_id of the homekit item in the config file is set, it is not reflected.
When trying to use multiple sets with different device_id, the device_id is set to the same value and the second or later set cannot be registered to the iPhone.

Could this be due to the fact that the struct tag in internal/homekit/homekit.go:25-30 is json?
I think that keys with underscores or capital letters are not recognised correctly.

go2rtc_linux_mipsel version: v1.9.1

Below is the go2rtc.yaml.
``` yaml
log:
  level: info
  api: warn
  exec: debug
  ngrok: info
  rtsp: warn
  streams: error
  webrtc: fatal
streams:
  video0:
  - rtsp://localhost:8554/video0_unicast

rtsp:
  listen: ""
 
homekit:
  video0:
    pin: 12345678
    name: "camera1"
    device_id: "AA:BB:CC:DD:EE:FF"
```
