### ISSUE TITLE
Unable to Display Timestamp Overlay in Go2RTC Streams

### ISSUE THREAD

**Issue by joopdo** [AlexxIT/go2rtc#1105]
Summary:
I'm experiencing difficulties adding a timestamp overlay to the video streams in Go2RTC. The goal is to have the timestamp overlay displayed in the video streams generated by Go2RTC so that I can reuse the streams in Frigate and other applications.
I have reviewed: https://github.com/AlexxIT/go2rtc/issues/402, https://github.com/AlexxIT/go2rtc/issues/127, https://github.com/AlexxIT/go2rtc/issues/487

Configuration:
    
```yaml

    go2rtc:
      streams:
        front: "ffmpeg:http://192.168.1.1:8080#video=h264"
        back: "ffmpeg:http://192.168.1.2:8080#video=h264"
```

**What I have tried**
List of the attempts made to add the timestamp overlay to the Go2RTC streams:

**1. Directly within ffmpeg configuration block:**
Added drawtext filter directly within the ffmpeg configuration block in Go2RTC, using timestamp_back and timestamp_front flags.

```yaml

    ffmpeg:
      timestamp_back: -vf "drawtext=text='%{localtime}':x=w/25:y=(h-th)-h/25:fontsize=h/25:fontcolor=white:shadowx=2:shadowy=2"
      timestamp_front: -vf "drawtext=text='%{localtime}':x=w/25:y=(h-th)-h/25:fontsize=h/25:fontcolor=white:shadowx=2:shadowy=2"

```
**2. Directly in stream configuration:**
Attempted to add drawtext filter directly in the stream configuration for the front camera using extra_args or appending the filter directly to the ffmpeg command.

```yaml
    go2rtc:
      streams:
        front:
          ffmpeg: "ffmpeg:http://192.168.1.1:8080#video=h264"
          extra_args: "-vf drawtext=text='DEBUG_TEXT':x=10:y=10:fontsize=24:fontcolor=white:shadowx=2:shadowy=2"

```
**3. Using separate timestamp flags in stream configuration:**

Attempted to add separate timestamp_back and timestamp_front flags directly in the stream configuration.

```yaml
    go2rtc:
      streams:
        front: "ffmpeg:http://192.168.1.1:8080#video=h264#{timestamp_front}"
        back: "ffmpeg:http://192.168.1.2:8080#video=h264#{timestamp_back}"
```

**4. Directly within stream configuration with drawtext filter:**

Tried to directly include the drawtext filter within the stream configuration for the front camera.
    
    
```yaml
        go2rtc:
          streams:
            front: "ffmpeg:http://192.168.1.1:8080#video=h264#-vf drawtext=text='DEBUG_TEXT':x=10:y=10:fontsize=24:fontcolor=white:shadowx=2:shadowy=2"
            back: "ffmpeg:http://192.168.1.2:8080#video=h264"

```
Despite these attempts, the timestamp overlay did not appear on the video streams generated by Go2RTC. The issue persists, and additional assistance or suggestions would be greatly appreciated.

Observe that the camera footage is displayed correctly, but attempts to add a timestamp overlay using ffmpeg flags or other methods have been unsuccessful.

**Expected Behavior:**
The timestamp overlay should be displayed on the video streams generated by Go2RTC, allowing for easy reuse of the streams in Frigate and other applications.

**Actual Behavior:**
Despite various attempts to add the timestamp overlay using different methods, including direct ffmpeg flags and additional configuration options, the timestamp overlay does not appear on the video streams.

**Additional Information:**

    I've tried adding the drawtext filter directly in the ffmpeg command within the Go2RTC configuration, but it didn't work.
    I've also attempted to apply the drawtext filter directly in the stream configuration for the front camera, but the issue persists.
    The error logs from Go2RTC indicate "unknown error" when attempting to apply additional ffmpeg arguments or filters.

**Environment:**

    Go2RTC version: 1.8.4

Logs:

```lua
2024-05-10 16:16:58.172208034  [INFO] Preparing new go2rtc config...
2024-05-10 16:16:58.576585406  [INFO] Starting go2rtc...
2024-05-10 16:16:58.670841556  16:16:58.670 INF go2rtc version 1.8.4 linux/arm64
2024-05-10 16:16:58.671604017  16:16:58.671 INF [api] listen addr=:1984
2024-05-10 16:16:58.671608498  16:16:58.671 INF [rtsp] listen addr=:8554
2024-05-10 16:16:58.671909312  16:16:58.671 INF [webrtc] listen addr=:8555
2024-05-10 16:17:08.021380886  [INFO] Starting go2rtc healthcheck service...
```
Note: Any assistance in resolving this issue and successfully displaying the timestamp overlay on the Go2RTC streams would be greatly appreciated.
