### ISSUE TITLE
External access RTSP does not work, request a login and user

### ISSUE THREAD

**Issue by filhocassiano** [AlexxIT/go2rtc#1124]
I am attempting to use VLC to verify the functionality of RTSP from go2rtc. While VLC works properly in localhost, it prompts for a login when accessed externally and does not function. I have tried using the credentials "admin" and "pass."

Could you Help me please:

go2rtc:
```
log:
  format: text
  level: info  # default level
  api: trace
  exec: debug
  ngrok: info
  rtsp: warn
  streams: error
  webrtc: fatal
rtsp:
  listen: ":8554"    # RTSP Server TCP port, default - 8554
  username: "admin"  # optional, default - disabled
  password: "pass"   # optional, default - disabled
  default_query: "video&audio"  # optional, default codecs filters 
streams:
 PTZ01:
    - rtsp://admin:3815@192.168.0.112/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast
 PTZ02:
    - rtsp://g4s:3815@192.168.0.115/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast
 DOMEPOSTE01:
    - rtsp://admin:3815@192.168.0.111/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast
```
![VLC](https://github.com/AlexxIT/go2rtc/assets/170195831/18ec0c25-4741-4a9c-b22f-4066354fafff)
