### ISSUE TITLE
Backchannel on Dahua VTO without `unicast=true&proto=Onvif`?!

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/go2rtc#1135]
Ok, I have no idea if this is an issue with go2rtc or my device. But out of the blue, I have this backchannel appearing in my source which was not configured with `unicast=true&proto=Onvif` (which is needed for activating backchannel):

![image](https://github.com/AlexxIT/go2rtc/assets/29582865/6abdcb8e-5b3d-4aad-b48e-c94894ff2998)

I also noticed it on the substream, in AAC format.

My config:

```yaml
  streams:
    vto_two_way_audio:
      # H264, G.711A, 2-way audio
      - echo:/config/scripts/fix_vto_codecs.sh rtsp://admin:pass@192.168.1.40/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    vto:
      # H264, G.711A
      - echo:/config/scripts/fix_vto_codecs.sh rtsp://admin:pass@192.168.1.40/cam/realmonitor?channel=1&subtype=0
      # AAC
      - rtsp://127.0.0.1:8554/video_porteiro_hd?audio=aac
    vto_hd:
      # H264, AAC
      - echo:/config/scripts/fix_vto_codecs.sh rtsp://admin:pass@192.168.1.40/cam/realmonitor?channel=1&subtype=1
      # PCMA
      - rtsp://127.0.0.1:8554/video_porteiro?audio=pcma
```

The screenshot above is from `vto` stream.

I am just opening this ticket to write my findings down in case some other people realize it too.

Fortunately, adding `#backchannel=0` to the streams I don't want backchannel seems to solve it:

```yaml
  streams:
    vto_two_way_audio:
      # H264, G.711A, 2-way audio
      - echo:/config/scripts/fix_vto_codecs.sh rtsp://admin:pass@192.168.1.40/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    vto:
      # H264, G.711A
      - echo:/config/scripts/fix_vto_codecs.sh rtsp://admin:pass@192.168.1.40/cam/realmonitor?channel=1&subtype=0#backchannel=0
      # AAC
      - rtsp://127.0.0.1:8554/video_porteiro_hd?audio=aac
    vto_hd:
      # H264, AAC
      - echo:/config/scripts/fix_vto_codecs.sh rtsp://admin:pass@192.168.1.40/cam/realmonitor?channel=1&subtype=1#backchannel=0
      # PCMA
      - rtsp://127.0.0.1:8554/video_porteiro?audio=pcma
```
