### ISSUE TITLE
Adding RTSP to HomeKit

### ISSUE THREAD

**Issue by shadowgrapher** [AlexxIT/go2rtc#1140]
Running 1.8.5-4  as a package on Synology (latest build from SynoCommunity)
 go2rtc.yaml:
```
api:
  listen: ":1984"
  username: username
  password: password

log:
  format: "text"
  level: "debug"
  homekit: "debug"
  rtsp: "debug"
  streams: "debug"

rtsp:
  listen: ":8554"

srtp:
  # force use of ipv4
  listen: "0.0.0.0:18443"

#webrtc:
  listen: ":8555"
  
streams:
  orangery: rtsp://10.0.1.10:5544/live0.264

homekit:
  orangery:                   # same stream ID from streams list
```
![image](https://github.com/AlexxIT/go2rtc/assets/10960863/8a98c429-cb41-42dc-b3b9-67b280b9efaf)

camera and syno sharing same network 10.0.1.*
Home.app discovers go2rtc-3f6D accessory but stuck on adding.

![IMG_1994](https://github.com/AlexxIT/go2rtc/assets/10960863/4598a832-7ce0-4b65-9140-069e17201d23)
![IMG_1995](https://github.com/AlexxIT/go2rtc/assets/10960863/a07d1e13-0b25-4100-a5bf-13360439cea4)
logs:

```
Time	Level	Message
26.05.2024, 16:24:07	info	go2rtc version 1.8.5 linux/arm
26.05.2024, 16:24:07	info	[api] listen addr=:1984
26.05.2024, 16:24:07	info	[rtsp] listen addr=:8554
26.05.2024, 16:24:07	info	[webrtc] listen addr=:8555
26.05.2024, 16:24:07	debug	[hass] can't import config: open .storage/core.config_entries: no such file or directory
```
Note I'm not using HomeAssistant

What I am missing in config, any thoughts?
