### ISSUE TITLE
Black screen - Tapo Camera

### ISSUE THREAD

**Issue by Lockie85** [AlexxIT/go2rtc#1158]
Hi,

I'm having an issue with one of my Tapo cameras, the others appear to function fine but this one is displaying a black screen when I select "stream" and I can see anything with debug logs enabled of use.

Camera with issue:
`bedroom_1_driveway_stream: tapo://admin:SHA-256@192.168.1.24`

Image:
![image](https://github.com/AlexxIT/go2rtc/assets/7091582/8777cfca-baa3-4844-9332-cc028a793a1d)

Config:
```
log:
  level: debug  #info / debug info warn error fatal
streams:
  bedroom_1_stream: tapo://admin:SHA-256@192.168.1.65
  bedroom_1_driveway_stream: tapo://admin:SHA-256@192.168.1.24
  bedroom_2_tigger_stream: hass:Camera-Hub-G3-E44E
  bedroom_3_stream: tapo://admin:SHA-256@192.168.1.56
  bedroom_4_driveway_stream: tapo://admin:SHA-256@192.168.1.43
  kitchen_worktop_stream: tapo://admin:SHA-256@192.168.1.44
  kitchen_millie_stream: tapo://admin:SHA-256@192.168.1.30
```

Log:
```
Time	Level	Message
6/2/2024, 11:41:47 AM	info	go2rtc version=1.9.2 platform=linux/amd64 revision=
6/2/2024, 11:41:47 AM	debug	build version=go1.21.10 vcs.time=
6/2/2024, 11:41:47 AM	info	config path=/config/go2rtc.yaml
6/2/2024, 11:41:47 AM	info	[rtsp] listen addr=:8554
6/2/2024, 11:41:47 AM	info	[webrtc] listen addr=:8555/tcp
6/2/2024, 11:41:47 AM	info	[api] listen addr=:1984
6/2/2024, 11:41:47 AM	debug	[hass] load config url=hass:Aqara-Hub-M2-B4D3
6/2/2024, 11:41:47 AM	debug	[hass] load config url=hass:Camera-Hub-G3-E44E
6/2/2024, 11:41:47 AM	debug	[hass] load config url=hass:Presence-Sensor-FP2-5EB6
6/2/2024, 11:41:53 AM	debug	[webrtc] new consumer src=bedroom_1_driveway_stream
6/2/2024, 11:41:53 AM	debug	[streams] start producer url=tapo://admin:SHA-256@192.168.1.24
6/2/2024, 11:41:57 AM	debug	[rtsp] new consumer stream=bedroom_2_tigger_stream
6/2/2024, 11:41:57 AM	debug	[streams] start producer url=hass:Camera-Hub-G3-E44E
6/2/2024, 11:41:58 AM	debug	[webrtc] new consumer src=bedroom_1_driveway_stream
6/2/2024, 11:42:01 AM	debug	[webrtc] new consumer src=bedroom_1_driveway_stream
6/2/2024, 11:42:07 AM	debug	[webrtc] new consumer src=bedroom_1_driveway_stream
6/2/2024, 11:42:10 AM	debug	[webrtc] new consumer src=bedroom_1_driveway_stream
6/2/2024, 11:42:23 AM	debug	[webrtc] new consumer src=bedroom_1_driveway_stream
6/2/2024, 11:42:53 AM	warn	undefined error=multipart: NextPart: EOF url=tapo://admin:SHA-256@192.168.1.24 caller=github.com/AlexxIT/go2rtc/internal/streams/producer.go:171
6/2/2024, 11:42:53 AM	debug	[streams] retry=0 to url=tapo://admin:SHA-256@192.168.1.24
6/2/2024, 11:43:54 AM	warn	undefined error=multipart: NextPart: EOF url=tapo://admin:SHA-256@192.168.1.24 caller=github.com/AlexxIT/go2rtc/internal/streams/producer.go:171
6/2/2024, 11:43:54 AM	debug	[streams] retry=0 to url=tapo://admin:SHA-256@192.168.1.24
6/2/2024, 11:44:54 AM	warn	undefined error=multipart: NextPart: EOF url=tapo://admin:SHA-256@192.168.1.24 caller=github.com/AlexxIT/go2rtc/internal/streams/producer.go:171
6/2/2024, 11:44:54 AM	debug	[streams] retry=0 to url=tapo://admin:SHA-256@192.168.1.24
```

Any idea what I might be doing wrong?
