### ISSUE TITLE
tapo c110 and c120 stream

### ISSUE THREAD

**Issue by sammo987** [AlexxIT/go2rtc#1161]
I'm running go2rtc v1.9.2 standalone on raspberry pi.
I have add the tapo c110 and c120 to go2rtc and can view both of them on vlc.
On the tapo c110, the picture is smooth, but on the tapo c120 it stutter, freeze and continue.
I gave tried adding -use_wallclock_as_timestamps 1 -rtsp_transport tcp -i <STREAM>, but still a problem.
The only way to resolve this was using vlc intermediary restreamer and connect go2rtc to local vlc port
cvlc --intf dummy --network-caching=2000 rtsp://@$camerapi:554/stream1 --sout "#rtp{sdp=rtsp://:localport/cam}" :no-sout-all :sout-keep :rtsp-tcp :sout-rtp-proto=tcp vlc://quit

can you help?

**Comment by AlexxIT** [comment]
Probably you need to use custom rtsp input without `nobuffer` and `low_delay`:

https://github.com/AlexxIT/go2rtc/blob/bd73b07ed809d40ee75632f2ff06069976c2d321/internal/ffmpeg/ffmpeg.go#L65

**Comment by sammo987** [comment]
Thank you for prompt reply and I know its hard to diagnoses a problem without the actual hardware present. The above parameters did not resolve the issue and it reminds. Let me know if you want so output logs

**Comment by kpelzel** [comment]
If anyone stumbles across this thread, I was experiencing the exact same issue. my tapo c120 looked great when streaming directly to vlc but was very choppy when streaming through go2rtc. After using wireshark to snoop on the vlc traffic, I found that it was using udp when streaming directly to the camera. My issue was resolved when I added the rtsp/udp input param to my go2rtc config:

```
go2rtc:
  streams:
    outside_camera:
      - ffmpeg:rtsp://kpelzel:password@10.0.2.42:554/stream1#audio=copy#video=copy#input=rtsp/udp
    outside_camera_sub:
      - ffmpeg:rtsp://kpelzel:password@10.0.2.42:554/stream2#audio=copy#video=copy#input=rtsp/udp
```
