### ISSUE TITLE
RTSP streams exposed to HomeKit become unavailable in any version above 1.9.1

### ISSUE THREAD

**Issue by IliasEagle** [AlexxIT/go2rtc#1173]
After updating go2rtc from 1.9.1 to either 1.9.2 or 1.9.3 all the RTSP streams exposed to HomeKit become unreachable.
I don't see any errors in the logs. 

Reverting back to 1.9.1 fixes the issue.

Config file is:
```
streams:
  camera.doorbell: 
    - rtsp://user:password@192.168.1.174:554/h264Preview_01_main
    - ffmpeg:doorbell#audio=opus
    
...
homekit:
  camera.doorbell:
    pin: [REDACTED]
    name: reolink
    device_id: reolink
    device_private: reolink
    pairings:
      - client_id=[REDACTED]....&permissions=1
      - client_id=[REDACTED]....&permissions=0
      - client_id=[REDACTED]....&permissions=1
      - client_id=[REDACTED]....&permissions=0
      - client_id=[REDACTED]....&permissions=1
      - client_id=[REDACTED]....&permissions=0
      - client_id=[REDACTED]....&permissions=1
```
