### ISSUE TITLE
Please help me with syntax ffmpeg as input, I can't figure put

### ISSUE THREAD

**Issue by Barabba11** [AlexxIT/go2rtc#1185]
Hi! I'm looking for a kind soul which gives me an example, a simple text working ready to copy into the editor, please no guides/examples, I've tried to figure out myself spending different hours and I can't, I'm an idiot I now, but I feel I won't be smarter than that :(( Please help me!

The following command works on my Win10 64 and produce the video file:
`ffmpeg -f gdigrab -framerate 30 -i desktop output.mkv`

Now how can I tell Go2rtc to use ffpeg as input with such arguments?
The screen+speaker capture of Go2RTC isn't workingm my obly chance is to use ffmpeg

I've tried this:
```
ffmpeg:
  bin: c:\go2rtc\ffmpeg.exe
  
streams:
    exec: c:\go2rtc\ffmpeg.exe -f gdigrab -framerate 30 -i desktop 

webrtc:
    candidates:
    - stun:8555
```

I've also tried to open a video following the examples of the author, and I have error
```
ffmpeg:
  bin: c:\go2rtc\ffmpeg.exe
  
api:
  listen: ":80"    # default ":1984", HTTP API port ("" - disabled)
  origin: "*"        # default "", allow CORS requests (only * supported)

streams:
    exec:ffmpeg.exe -re -i c:\go2rtc\arca.mp4 -c copy 

webrtc:
    candidates:
    - stun:8555
```
 
WRN error="yaml: unmarshal errors:\n  line 9: cannot unmarshal !!str `exec:ff...` into map[string]interface {}"

PLEASE haelp me!! THANK YOU!
