### ISSUE TITLE
Aqara G4 two way audio configuration

### ISSUE THREAD

**Issue by goal778899** [AlexxIT/go2rtc#1190]
Hi AlexxIT, I am currently able to perform a camera stream via go2rtc. However, I am unable to configure and make the two-way audio to work. Will appreciate if you can provide me with some tips on how to approach it.

These are my current configurations:

go2rtc.yaml
```
log:
  format: ""
  level: "trace"

streams: 
  aqara_doorbell: 
    - hass:Doorbell Repeater-EB67
    - ffmpeg:aqara_doorbell#audio=aac#audio=opus#async
```

WebRTC Lovelace Card
```
type: custom:webrtc-camera
url: rtsp://<ip>:8554/aqara_doorbell?video=all&audio=all#backchannel=0
ui: true
digital_ptz:
  mouse_drag_pan: true
  mouse_wheel_zoom: true
  mouse_double_click_zoom: true
  touch_drag_pan: true
  touch_pinch_zoom: true
  touch_tap_drag_zoom: true
  persist: true
```
