### ISSUE TITLE
[Feature Request] Transposing/Rotation support for FFMPEG

### ISSUE THREAD

**Issue by maxi1134** [AlexxIT/go2rtc#12]
As the title state, an easy way to rotate cameras would be amazing!

Thanks again for this cool tool!

**Comment by AlexxIT** [comment]
You already can do this via `exec:` source. You can write any ffmpeg arguments there.
Or you can create your own templates for `ffmpeg:` source.
```
ffmpeg:
  rotate: -arg xyz
sources:
  camera1: ffmpeg:rtsp://.....#video=rotate
```
