### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x68acc1]

### ISSUE THREAD

**Issue by dz-dot** [AlexxIT/go2rtc#1220]
Hello!
Periodically go2rtc stopping with below error
```
[user@xlom-app-002 ~]$ docker logs b490777f51ff
19:28:50.502 INF go2rtc platform=linux/amd64 revision=a4885c2 version=1.9.4
19:28:50.502 INF config path=/config/go2rtc.yaml
19:28:50.503 INF [api] listen addr=:1984
19:28:50.503 INF [rtsp] listen addr=:8554
19:28:50.504 INF [webrtc] listen addr=:8555
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x68acc1]

goroutine 5835 [running]:
bufio.(*Writer).Write(0xc000139500, {0xc0005f2000?, 0xc00049b808?, 0xc00018e940?})
        bufio/bufio.go:679 +0xe1
net/http.(*response).write(0xc0007a0380, 0x2663, {0xc0005f2000, 0x2663, 0x29f7}, {0x0, 0x0})
        net/http/server.go:1653 +0x2fe
net/http.(*response).Write(0x29f7?, {0xc0005f2000?, 0x0?, 0xc0005f2000?})
        net/http/server.go:1611 +0x2a
github.com/AlexxIT/go2rtc/pkg/core.(*WriteBuffer).Write(0xc000139540, {0xc0005f2000?, 0xc0005d5b90?, 0xc000120ed8?})
        github.com/AlexxIT/go2rtc/pkg/core/writebuffer.go:33 +0x92
github.com/AlexxIT/go2rtc/pkg/mp4.(*Consumer).AddTrack.func2(0xc00131c000?)
        github.com/AlexxIT/go2rtc/pkg/mp4/consumer.go:106 +0xae
github.com/AlexxIT/go2rtc/pkg/mp4.(*Consumer).AddTrack.RTPDepay.func4(0xc0005d4090)
        github.com/AlexxIT/go2rtc/pkg/h265/rtp.go:87 +0x8c6
github.com/AlexxIT/go2rtc/pkg/core.NewSender.func2(0xc000735b00?)
        github.com/AlexxIT/go2rtc/pkg/core/track.go:112 +0x1b
github.com/AlexxIT/go2rtc/pkg/core.(*Sender).Start.func1()
        github.com/AlexxIT/go2rtc/pkg/core/track.go:144 +0x47
created by github.com/AlexxIT/go2rtc/pkg/core.(*Sender).Start in goroutine 5766
        github.com/AlexxIT/go2rtc/pkg/core/track.go:142 +0x10a
```
Config:
```
api:
    base_path: ""
    listen: :${go2rtc_api_port:1984}
    origin: '*'
    username: '' #${go2rtc_api_login:admin}
    password: '' #${go2rtc_api_password:pass}
       # "admin" if env "RTSP_USER" not set
    static_dir: ""


webrtc:
    candidates: []
    ice_servers:
        - credential: ""
          urls:
            - stun:stun.l.google.com:19302
          username: ""
    listen: :${go2rtc_webrtc_port:8555}

streams:
        stream_2_15: rtsp://admin:*@10.0.0.1:554/Streaming/channels/102
        stream_2_10: rtsp://admin:*@10.0.0.2:554/Streaming/channels/102
        stream_1_15: rtsp://admin:*@10.0.0.3:554/Streaming/channels/102
```
 
The camera sends h265, the client receives in Mp4/h265
