### ISSUE TITLE
Aqara G4 - HKSV and Object Detection not working

### ISSUE THREAD

**Issue by barenddev** [AlexxIT/go2rtc#1224]
Ive got this most of the way working- HA can detect the doorbell press, i can view the doorbell stream from the go2rtc web ui, i can still see the camera in Home app, and i do get notifications on my phone and Apple TV. Whats missing is

HKSV, ive lost recordings. I still see them in the Aqara app, but i still would rather use Home.  I do have it set to record, but it doesnt anymore since this integration.

Object Detection - I do get notifications of basic motion, but when i switch it to notify on people or packages etc it stops notifying.

My go2rtc config is:

```
streams:
  front_door: 
    - homekit://192.168.0.111:36465?client_id=MY_CLIENT_ID&device_id=MY_DEVICE_ID&device_public=MY_DEVICE_PUBLIC
    - ffmpeg:front_door#audio=opus

homekit:
  front_door:
    pin: 419-12-540
    name: Aqara G4 Doorbell
    device_id: front_door
    device_private: front_door
    pairings:
      - client_id=MY_CLIENT_ID&client_public=MY_CLIENT_PUBLIC&permissions=1
```
any idea of what i can do to make these two bits work?
