### ISSUE TITLE
High RAM usage and unexpected restart of Home Assistant

### ISSUE THREAD

**Issue by pico1881** [AlexxIT/go2rtc#1241]
For a few days I have encountered the unexpected restart of Home Assistant, after some analysis I found that the problem was due to excessive use of RAM above 90%. After further analysis I saw that the RAM was being used by go2rtc (see screenshot), but I don't see any errors in the log.
After manually restart of go2rtc addon the RAM usage is about 2-5%
![go2rtc ram](https://github.com/AlexxIT/go2rtc/assets/82042085/29253022-d6ef-41f3-bed7-d87590d7f4fe)

**Comment by porly1985** [comment]
I can confirm this behaviour. After restarting go2rtc the RAM usage is fine again.

<img width="395" alt="image" src="https://github.com/AlexxIT/go2rtc/assets/7367953/5ab5184f-cc44-40f5-a0ad-8b9b1a851cdf">

**Comment by dagleaves** [comment]
I'm not Alex, but I've been investigating similar issues

1. What version of go2rtc are you on?
2. Are you using audio on any of your cameras via a secondary audio ffmpeg stream?
3. If 2 is yes, do you notice a large number of consumers on your stream when your memory usage is high?

I would also double check that your log level is set to debug or trace if you aren't seeing errors. If you are on info, most errors won't get reported.

**Comment by alexandreghez** [comment]
Same problem : 
I'm using go2RTC  1.9.4 i have a raspberry 4 and 3 cameras : 2 homekit (Aquara G2HPRO et EUFY) et 1 tapo C220
![image](https://github.com/AlexxIT/go2rtc/assets/64720630/f849ac6e-c0a5-46e2-a987-4a9a8d99802c)

**Comment by dagleaves** [comment]
> Same problem : 
> 
> I'm using go2RTC  1.9.4 i have a raspberry 4 and 3 cameras : 2 homekit (Aquara G2HPRO et EUFY) et 1 tapo C220
> 
> 

Are you using an audio stream with it? I would encourage you to check the things I listed above to help identify the source of the issue

**Comment by porly1985** [comment]
> I'm not Alex, but I've been investigating similar issues
> 
> 1. What version of go2rtc are you on?
> 2. Are you using audio on any of your cameras via a secondary audio ffmpeg stream?
> 3. If 2 is yes, do you notice a large number of consumers on your stream when your memory usage is high?
> 4. What brand of cameras are you using?
> 
> I would also double check that your log level is set to debug or trace if you aren't seeing errors. If you are on info, most errors won't get reported.

Hi dagleaves,

1. 1.9.4 (WebRTC Camera + HA Addon)
2. yes, all the audio goes through ffmpeg
3. I will check it when it happens again, the high ram usage only occures from time to time in my case.
4. 3 x Reolink + 1 x Tap C210

Thanks and greetings!

**Comment by AlexxIT** [comment]
Memory graph screenshots are not much help to understand and detect the problem.
The config part is already better. I don't know if it will be enough for the repeating of the problem.

**Comment by pico1881** [comment]
In my case I solved removing this entry from config:
"camera.camera1_sub": ffmpeg:{input}#video=copy#audio=opus#audio=aac

**Comment by alexandreghez** [comment]
this is my configuration for streams part : 
``` 
streams:
  eufy:
    - homekit://[IP]:46778?device_id=MACADDR&device_public=[PUBLIC]&client_id=[CLIENT_ID]&client_private=[CLIENT_PRIVATE]
   - ffmpeg:eufy#audio=aac#audio=opus
  aqara: 
    - homekit://[IP]:37833?device_id=MACADDR&device_public=[PUBLIC]&client_id=[CLIENT_ID]&client_private=[CLIENT_PRIVATE]
    - ffmpeg:aqara#audio=aac#audio=opus#bitrate=299K
  tapo: 
    - tapo://admin:[PASSWORD]@[IP]
    - ffmpeg:tapo#audio=aac

```

**Comment by pico1881** [comment]
My actual "solution" in an automation that restart go2rtc addon when it use more than 20% of RAM

**Comment by Uriziel01** [comment]
@pico1881 Could you share that automation please? Just discoverem I'm also affected by this issue and my HA server is restarting every few days/weeks.

**Comment by pico1881** [comment]
this is my automation:

```
alias: Restart go2rtc
description: ""
triggers:
  - trigger: numeric_state
    entity_id:
      - sensor.go2rtc_memory_use_percent
    for:
      hours: 0
      minutes: 0
      seconds: 30
    above: 20
conditions: []
actions:
  - action: hassio.addon_restart
    metadata: {}
    data:
      addon: a889bffc_go2rtc
mode: single
```
