### ISSUE TITLE
No audio on Webrtc card and HomeKit  despite being present present on go2rtc interface and Frigate

### ISSUE THREAD

**Issue by IliasEagle** [AlexxIT/go2rtc#1244]
Hello!

with the following go2rtc configuration for a RLC-520A Reolink camera
```
  Living Room: 
    - rtsp://user:pass@192.168.1.114:554/h264Preview_01_main 
    - ffmpeg:Living Room#audio=opus
```

when I open the camera stream via the go2rtc dashboard

![image](https://github.com/AlexxIT/WebRTC/assets/93916516/68ffeba0-ecbe-43b5-9b02-1f524df8da7b)

 I can hear the audio which is also seen below
![image](https://github.com/AlexxIT/WebRTC/assets/93916516/5e9671ee-319f-475d-8f56-f002dfc8126e)

When use the webrtc card though there is no audio as can be seen below

![image](https://github.com/AlexxIT/WebRTC/assets/93916516/e635164e-74fb-44e2-af6d-d2c19d86ae11)

Below is the webrtc card config
```
type: custom:webrtc-camera
ui: true
style: '.screenshot {display: none}'
shortcuts:
  - name: Central
    icon: mdi:light-switch
    service: light.toggle
    service_data:
      entity_id: light.lounge_central
streams:
  - url: Living Room
    name: Lounge
    mode: webrtc
    media: video,audio
  - url: ''
    name: Poster
```

The same applies when trying to view the camera via HomeKit
![image](https://github.com/AlexxIT/WebRTC/assets/93916516/8903b793-75e0-47b0-91df-d1a7cd336299)

----
This issue is not unique to the aforementioned Reolink camera. The same applies to the Eufy Solo IndoorCam C24, 2K
Also, if a camera is recorded by Frigate audio is passed to it as expected. So the issue seems to appear only on webrtc card

**Comment by dagleaves** [comment]
Check your logs, it seems like the ffmpeg producer fails to start or dies. With MSE/FMP4, it is using the AAC audio. The OPUS audio is never sent.

**Comment by AlexxIT** [comment]
I have this camera. It has awful unusable RTSP. Maybe it related to camera firmware. I don't know how you can use it as rtsp source.

**Comment by IliasEagle** [comment]
@dagleaves 

this is what I got in logs when opening the stream using the webrtc card:

![image](https://github.com/user-attachments/assets/d3c36f07-fa93-4357-9289-2465663786ec)


forcing the webrtc card to mode:mse solved the issue for the webrtc card 
![image](https://github.com/user-attachments/assets/269c8df2-1a6f-4291-875c-049b2104ea66)

but the problem still exists when streaming to homekit:
![image](https://github.com/user-attachments/assets/891f9042-4b9f-4428-aff0-9cb3b5b1eb15)

**Comment by IliasEagle** [comment]
@AlexxIT funny you should say it. 
I did see in the go2rtc documentation where you said Reolink cameras are temperamental _(paraphrasing)_, but my experience first with the Reolink Doorbell was so good that I tired Reolink E1 Pro which has also been very stable and only recently I got the RLC-520A.
They are all running the latest firmware. 

When I say I had good experience that has to do primarily with the image. You can let the stream for hours and it won't break, unlike all Eufy cameras which I am in the process of decommissioning.  

I have no issues with using the Reolink cameras with Frigate and it seems now with the webrtc card(forcing mode to MSE) in terms of both image and sound. 
It seems that the only problematic case to be streaming to HomeKit.

Below you can see the  RLC-520A steam being consumed by the WebRTC card (top) and HomeKit (below). It makes no difference in which order I start the consumers. The result is always the same. 

![image](https://github.com/user-attachments/assets/f557c3d8-e9e6-4989-9f18-3ae9c8b155a0)

**Comment by AlexxIT** [comment]
You issue with space in stream name.

PS. What firmware is on your RLC-520A camera?

**Comment by IliasEagle** [comment]
@AlexxIT  I thought the space was the issue but I doubt it is as the same problem appear on the "Bedroom-1" (reolink) and "Bedroom-2" (Eufy) cameras

```
  Bedroom1: #reolink e1pro
    - rtsp://user:password@192.168.1.210:554/h264Preview_01_main 
    - ffmpeg:Bedroom1#audio=opus
  Bedroom2: #Eufy Solo IndoorCam C24, 2K
    - rtsp://user:password@192.168.1.77/live0
    - ffmpeg:Bedroom2#audio=opus
  Living Room:  #RLC-520A
    - rtsp://user:password@192.168.1.114:554/h264Preview_01_main 
    - ffmpeg:Living Room#audio=opus

homekit:
  Living Room:
    pin: xxxxx
    name: Living Room
    pairings:
       .....
  Bedroom1:
    pin: xxxxx
    name: Bedroom-1
    pairings:
       .....
  Bedroom2:
    pin: xxxxx
    name: Bedroom-2
    pairings:
```

My RLC-520A is on v3.0.0.2839_23102301 firmware (HW IPC_MS1NA45MP)
