### ISSUE TITLE
Q: Where to find/map static files for docker version

### ISSUE THREAD

**Issue by pelaxa** [AlexxIT/go2rtc#125]
Just started using this (docker version)  and for the life of me I cannot figure out how to map static files.  The files in the www folder here are not in the docker image (e.g. webrtc.html) and I cannot find how to map a volume to serve them properly.

am i just missing this on the instruction page or is this not documented currently?

my docker-compose file.  I created webrtc.html in www folder but cannot hit from the browser.
```
version: "3.6"

services:
  go2rtc:
    image: alexxit/go2rtc
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./config/go2rtc.yaml:/config/go2rtc.yaml
      - ./www:/static
      -
```

**Comment by AlexxIT** [comment]
You should set any path you want in config and use it
https://github.com/AlexxIT/go2rtc#module-api

**Comment by pelaxa** [comment]
My config is exactly as you have it there, but how does that map out to to a host folder so I can add static files? 

Www is not an absolute path that can be mapped.

**Comment by AlexxIT** [comment]
You need enter path to static folder (inside container) in go2rtc.yaml file. And map your www folder (on host) to that path.

**Comment by pelaxa** [comment]
Thanks for the quick response.  Can you please clarify with an example?  Here is what I tried and it does not work.  In the config I tried both www and /www and neither work.

docker-compose.yml
```
version: "3.6"

services:
  go2rtc:
    image: alexxit/go2rtc
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./config/go2rtc.yaml:/config/go2rtc.yaml
      - ./www:/www # <== This needs to be a full path to a folder in the container
 ```

do2rtc.yml
```
api:
  listen: ":1984"    
  base_path: "/rtc"  
  static_dir: "www"  # what is this folder relative to?  the absolute path needs to be in docker-compose.yml
  origin: "*"

webrtc:
  listen: ":8555"

streams:
  front_door: rtsp://X.Y.Z.Z:7447/TwQqAAAAsuLD3lr

log:
  level: trace
  api: trace
  exec: debug
  ngrok: info
  rtsp: warn
  streams: error
  webrtc: debug
```
