### ISSUE TITLE
Webtorrent connections are not closing

### ISSUE THREAD

**Issue by M0nik** [AlexxIT/go2rtc#1250]
When /api/frame.jpeg?src=xxx is called, webtorrent connections remain active.

**Server 1** (webtorrent publishing)

```
streams:
  test_device: rtsp://l:p@192.168.16.128:554/stream2
webtorrent:
    shares:
        xxx:
            pwd: yyy
            src: test_device
```
			
**Server 2** (webtorrent listening)

```
streams:
    cam: webtorrent:?share=xxx&pwd=yyy
```
	
Call http://127.0.0.1:1984/api/frame.jpeg?src=cam on **Server 2** several times

![screen](https://github.com/AlexxIT/go2rtc/assets/36361680/e4a8f9d2-2f3c-44db-8101-4630a6639c36)
