### ISSUE TITLE
Error reading rtsp stream 

### ISSUE THREAD

**Issue by holger-tangermann** [AlexxIT/go2rtc#1269]
Hello, 

thank you for supporting go2rtc. 

I want to use go2rtc 1.8.4 as part of frigate on HA running on RPI 5.

If I configure go2rtc in frigate.yml: 
```
go2rtc:
  streams:
    hwr: 
      - rtsp://192.168.188.70:554/stream0
```
Go2rtc shows an error connecting the rtsp stream:
`2024-07-20 17:30:02.145658449  19:30:02.145 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 172.30.33.8:38826->192.168.188.70:554: i/o timeout" url=rtsp://192.168.188.70:554/stream0`
I understand this looks like a normal network error. Go2rtc cannot connect the rtsp stream.

However, if I configure the same rtsp stream of the camera directly as frigate input in frigate.yml, the stream works fine. 
```
cameras:
 HWR_CAM:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.188.70:554/stream0
          roles:
            - record
```

So frigate can connect the stream and go2rtc not? Wile both are part of the same HA add-on? What am I doing wrong?

**Comment by AlexxIT** [comment]
You right. This is simple network error. You can try ffmpeg source. Because Frigate uses FFmpeg by default.

**Comment by holger-tangermann** [comment]
Yes OK. That helped. Thanks a lot! Configuration below works. Still a bit strange, that ffmpeg can start the stream - while there is network error, if go2rtc does so. 
```
go2rtc:
  streams:
    hwr: 
      - "ffmpeg:rtsp://192.168.188.70:554/stream0#video=copy#audio=copy#audio=aac"
```
