### ISSUE TITLE
Issue with Bidirectional Audio Integration on Reolink RLC-823A Camera

### ISSUE THREAD

**Issue by barzag** [AlexxIT/go2rtc#1280]
Hello,

Go2RTC version: 1.9.2
Remote access : Wireguard
Core 2024.7.3
Supervisor 2024.06.2
Operating System 12.4
Browser used: chrome
Firmware RLC-823A : v3.1.0.2831_23102509_v1.0.0.31
Normal NAT

Remote access : Wireguard
<img width="355" alt="Capture d'écran 2024-07-26 185821" src="https://github.com/user-attachments/assets/becca758-29ff-480f-ac08-917bc3cb7167">

Local network : 
<img width="253" alt="Capture d'écran 2024-07-26 191608" src="https://github.com/user-attachments/assets/2209ae78-5ff4-449a-bb9f-27f737144d34">

I am experiencing an issue with integrating bidirectional audio on my Reolink RLC-823A camera using Go2RTC. I have configured the HTTP and RTSP streams as follows:
```
go2rtc:
  streams:
    reolink_camera_4:
      - ffmpeg:https://10.22.10.144/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=********#video=copy#audio=copy#audio=opus
      - rtsp://admin:********@10.22.10.144:554/h264Preview_01_main
    reolink_camera_4_sub:
      - ffmpeg:https://10.22.10.144/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=********
  webrtc:
    candidates:
      - 10.22.10.30:8555
      - stun:8555

cameras:
  reolink_camera_4:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_camera_4_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/reolink_camera_4
          input_args: preset-rtsp-restream
          roles:
            - record
    onvif:
      host: 10.22.10.144
      port: 8000
      user: admin
      password: ********
    detect:
      enabled: false
      width: 640
      height: 360
      fps: 15
    objects:
      track:
        - person
        - cat
        - dog
        - mouse
        - hedgehog
      filters:
        person:
          threshold: 0.60
          min_area: 500
          max_area: 50000
```

```
{
  "producers": [
    {
      "type": "RTSP passive producer",
      "url": "rtsp://127.0.0.1:8554/1220b1934924134f8e7f8a8de26fc3b7",
      "remote_addr": "127.0.0.1:37160",
      "user_agent": "ffmpeg/go2rtc",
      "sdp": "v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=No Name\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat LIBAVFORMAT_VERSION\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKAoALWQ,aO48sA==; profile-level-id=640033\r\na=control:streamid=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000/1\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408\r\na=control:streamid=1\r\nm=audio 0 RTP/AVP 98\r\nb=AS:64\r\na=rtpmap:98 opus/48000/2\r\na=control:streamid=2\r\n",
      "medias": [
        "video, recvonly, H.264 High 5.1",
        "audio, recvonly, MPEG4-GENERIC/16000",
        "audio, recvonly, OPUS/48000/2"
      ],
      "receivers": [
        "96 H264, bytes=696020906, senders=2",
        "97 MPEG4-GENERIC/16000, bytes=7111120, senders=1",
        "98 OPUS/48000/2, bytes=8388818, senders=1"
      ],
      "recv": 717981120
    },
    {
      "url": "rtsp://admin:**********@10.22.10.144:554/h264Preview_01_main"
    }
  ],
  "consumers": [
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/reolink_camera_4",
      "remote_addr": "127.0.0.1:37156",
      "user_agent": "FFmpeg Frigate/0.14.0-a4eb435",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKAoALWQ,aO48sA==; profile-level-id=640033\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408\r\na=control:trackID=1\r\n",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "senders": [
        "96 H264, bytes=696020906, receivers=1",
        "97 MPEG4-GENERIC/16000, bytes=7111120, receivers=1"
      ],
      "send": 711019018
    },
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "udp4 prflx 10.22.11.4:35942 related :0",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, VP8, VP9, H264, AV1",
        "audio, sendonly, OPUS/48000/2, G722/8000, PCMU/8000, PCMA/8000, L16, PCML"
      ],
      "senders": [
        "102 H264, bytes=301550015, receivers=1",
        "111 OPUS/48000/2, bytes=3629411, receivers=1"
      ],
      "send": 308625147
    }
  ]
```
```
{
  "producers": [
    {
      "type": "RTSP passive producer",
      "url": "rtsp://127.0.0.1:8554/1220b1934924134f8e7f8a8de26fc3b7",
      "remote_addr": "127.0.0.1:37160",
      "user_agent": "ffmpeg/go2rtc",
      "sdp": "v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=No Name\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat LIBAVFORMAT_VERSION\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKAoALWQ,aO48sA==; profile-level-id=640033\r\na=control:streamid=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000/1\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408\r\na=control:streamid=1\r\nm=audio 0 RTP/AVP 98\r\nb=AS:64\r\na=rtpmap:98 opus/48000/2\r\na=control:streamid=2\r\n",
      "medias": [
        "video, recvonly, H.264 High 5.1",
        "audio, recvonly, MPEG4-GENERIC/16000",
        "audio, recvonly, OPUS/48000/2"
      ],
      "receivers": [
        "96 H264, bytes=844060036, senders=3",
        "97 MPEG4-GENERIC/16000, bytes=8626250, senders=2",
        "98 OPUS/48000/2, bytes=10182585, senders=2"
      ],
      "recv": 870705931
    },
    {
      "type": "RTSP active producer",
      "url": "rtsp://10.22.10.144/h264Preview_01_main/",
      "remote_addr": "10.22.10.144:554",
      "user_agent": "go2rtc/1.9.2",
      "sdp": "v=0\r\no=- 1722004826568654 1 IN IP4 10.22.10.144\r\ns=Session streamed by \"preview\"\r\ni=h264Preview_01_main\r\nt=0 0\r\na=tool:LIVE555 Streaming Media v2020.08.12\r\na=type:broadcast\r\na=control:*\r\na=range:npt=0-\r\na=x-qt-text-nam:Session streamed by \"preview\"\r\na=x-qt-text-inf:h264Preview_01_main\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:500\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKAoALWQ,aO48sA==\r\na=control:track1\r\nm=audio 0 RTP/AVP 97\r\nc=IN IP4 0.0.0.0\r\nb=AS:256\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=control:track2\r\n",
      "medias": [
        "video, recvonly, H.264 High 5.1",
        "audio, recvonly, MPEG4-GENERIC/16000"
      ],
      "receivers": [
        "96 H264, bytes=0, senders=1",
        "97 MPEG4-GENERIC/16000, bytes=0, senders=1"
      ]
    }
  ],
  "consumers": [
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/reolink_camera_4",
      "remote_addr": "127.0.0.1:37156",
      "user_agent": "FFmpeg Frigate/0.14.0-a4eb435",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.2\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKAoALWQ,aO48sA==; profile-level-id=640033\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408\r\na=control:trackID=1\r\n",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "senders": [
        "96 H264, bytes=844060036, receivers=1",
        "97 MPEG4-GENERIC/16000, bytes=8626250, receivers=1"
      ],
      "send": 862254286
    },
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "udp4 prflx 10.22.11.4:35942 related :0",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, VP8, VP9, H264, AV1",
        "audio, sendonly, OPUS/48000/2, G722/8000, PCMU/8000, PCMA/8000, L16, PCML"
      ],
      "senders": [
        "102 H264, bytes=449589145, receivers=1",
        "111 OPUS/48000/2, bytes=5423178, receivers=1"
      ],
      "send": 460152630
    },
    {
      "type": "probe",
      "remote_addr": "10.22.11.4:21844",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, ALL",
        "audio, sendonly, ALL",
        "audio, recvonly, ANY"
      ],
      "senders": [
        "96 H264, bytes=0, receivers=1",
        "96 H264, bytes=0, receivers=1",
        "97 MPEG4-GENERIC/16000, bytes=0, receivers=1",
        "98 OPUS/48000/2, bytes=0, receivers=1",
        "97 MPEG4-GENERIC/16000, bytes=0, receivers=1"
      ]
    }
  ]
}

```
I have activated the stream on a Lovelace Frigate card that relays the Go2RTC stream via WebRTC. I have enabled the microphone in the menu, but when I click on the microphone, it remains crossed out and the button does not turn red. Additionally, when on the local network, the microphone icon turns red, but no audio is transmitted to the camera.

Any help or guidance to resolve this issue would be greatly appreciated.
Thank you very much for your assistance!
