### ISSUE TITLE
[Feature Request] Card for Home Assistant

### ISSUE THREAD

**Issue by wonderiuy** [AlexxIT/go2rtc#13]
Hello AlexxIt,
i'm very pleased you are working oin this project. Is possible to add a card in Home Assistant that uses go2rtc as a source?
I didn't find any new card after installation. Should we use Glance card maybe? What's the address for various go2rtc stream to point at?
Thank you

**Comment by wonderiuy** [comment]
Oops, i've found the instruction, thank you anyway

**Comment by wonderiuy** [comment]
I've looked at the process, which is not so clear. A dedicated card would be the best user friendly option for HASSIO, so I'm reopening the issue

**Comment by AlexxIT** [comment]
You may use generic camera and Lovelace card as usual. As you using it before. But after install this add-on and setup buildin integration you will get WebRTC stream.

**Comment by conorlap** [comment]
Is there any possibility of 2 way audio within a Home Assistant card? Would this require a brand new card? 
Would need ability to mute & unmute microphone etc also

**Comment by AlexxIT** [comment]
Well. Someone needs to extend default Lovelace card or write new one. I plan to spend my time on advanced server features in near futures.

**Comment by maxi1134** [comment]
For all of your information, you can feed the Go2rtc RTSP feed into https://github.com/dermotduffy/frigate-hass-card

This is very useful if you use frigate

**Comment by wonderiuy** [comment]
Thank you but the fact here is that we passed from AlexxIT WebRTC Camera, with lovelace card with PTZ support (1 product, no config needed) to:
- go2rtc
- RTSPtoWebRTC
- Generic Camera
- Glance card
which is a step back in user friendlyness: need to configure everything, add single generic camera, etc

**Comment by thinkjk** [comment]
> For all of your information, you can feed the Go2rtc RTSP feed into https://github.com/dermotduffy/frigate-hass-card
> 
> This is very useful if you use frigate

Can you quickly explain how to do that? Where do I reference the stream from go2rtc in the frigate card? I think it will just use the default RTSP stream and not from go2rtc?

**Comment by AlexxIT** [comment]
If you install go2rtc and RTSPtoWebRTC, you can use instructions "Native WebRTC".

**Comment by calisro** [comment]
> I haven't tested it completely, because I don't have a microphone on my PC. But the browser asks for microphone permissions, so it seems to work.
> 
> Can anyone test it?

I just tested it and it works in a browser and in the companion app.  I'll likely use it as a card-mod popup card.  It's a good temporary solution but it lacks a mute button which makes it risky. :)

**Comment by aderusha** [comment]
I've been using the glance card and then added PTZ control via a separate integration (foscam in my case, ONVIF etc would also work).

Here's an example:

```yaml
type: picture-glance
camera_view: live
title: Front Door
camera_image: camera.front_door
tap_action:
  action: more-info
entities:
  - entity: camera.front_door_camera_control
    name: Home
    icon: mdi:home
    tap_action:
      action: call-service
      service: foscam.ptz_preset
      service_data:
        entity_id: camera.front_door_camera_control
        preset_name: Home
  - entity: camera.front_door_camera_control
    name: Pan Left
    icon: mdi:arrow-left
    tap_action:
      action: call-service
      service: foscam.ptz
      service_data:
        entity_id: camera.front_door_camera_control
        movement: left
        travel_time: 0.75
  - entity: camera.front_door_camera_control
    name: Tilt Up
    icon: mdi:arrow-up
    tap_action:
      action: call-service
      service: foscam.ptz
      service_data:
        entity_id: camera.front_door_camera_control
        movement: up
        travel_time: 0.75
  - entity: camera.front_door_camera_control
    name: Tilt Down
    icon: mdi:arrow-down
    tap_action:
      action: call-service
      service: foscam.ptz
      service_data:
        entity_id: camera.front_door_camera_control
        movement: down
        travel_time: 0.75
  - entity: camera.front_door_camera_control
    name: Pan Right
    icon: mdi:arrow-right
    tap_action:
      action: call-service
      service: foscam.ptz
      service_data:
        entity_id: camera.front_door_camera_control
        movement: right
        travel_time: 0.75
```

`camera.front_door` is my go2rtc stream, `amera.front_door_camera_control` is the foscam integration used solely for PTZ control.
