### ISSUE TITLE
Support input_format in ffmpeg:device

### ISSUE THREAD

**Issue by svenstaro** [AlexxIT/go2rtc#130]
Currently, the supported parameters are `video`, `audio`, `framerate`, and `resolution`. I think you should support an additional flag `input_format` which maps to the ffmpeg `input_format`. It will allow you to choose a particular input stream from a webcam in case a webcam supports multiple different outputs. Using this then it allows users to natively stream h264 without re-encoding.

**Comment by pravardhanreddy** [comment]
Yes please. This would also allow the webcams to output at a higher framerate using a compressed stream rather than outputting raw

**Comment by AlexxIT** [comment]
@pravardhanreddy you can do whatever you want with exec source. FFmpeg source it's just more simpler shortcuts to original ffmpeg arguments

**Comment by pravardhanreddy** [comment]
@AlexxIT Thank you so much. I just figured it out. Posting the config here incase others find it useful.
```
streams:
  exec_sw: exec:ffmpeg -f v4l2 -input_format mjpeg -video_size 1280x960 -framerate 5 -i /dev/video0 -pix_fmt yuv420p -c:v libx264 -preset ultrafast -tune zerolatency -rtsp_transport tcp -f rtsp {output}
  exec_hw: exec:ffmpeg -f v4l2 -input_format mjpeg -video_size 1280x960 -framerate 5 -i /dev/video0 -pix_fmt yuv420p -c:v h264_nvenc -g 50 -profile:v high -level:v auto -preset:v p2 -tune:v ll -rtsp_transport tcp -f rtsp {output}
  
  raw_sw: exec:ffmpeg -f v4l2 -video_size 1280x960 -framerate 5 -i /dev/video0 -pix_fmt yuv420p -c:v libx264 -preset ultrafast -tune zerolatency -rtsp_transport tcp -f rtsp {output}
  raw_hw: exec:ffmpeg -f v4l2 -video_size 1280x960 -framerate 5 -i /dev/video0 -pix_fmt yuv420p -c:v h264_nvenc -g 50 -profile:v high -level:v auto -preset:v p2 -tune:v ll -rtsp_transport tcp -f rtsp {output}
  
  ff_sw: ffmpeg:device?video=0&resolution=1280x960&framerate=5#video=h264
  ff_hw: ffmpeg:device?video=0&resolution=1280x960&framerate=5#video=h264#hardware
```

According to my understanding, the `ff_` streams should be similar to `raw_`

**Comment by AlexxIT** [comment]
Also you can override existing ffmpeg templates and add your own.

**Comment by AlexxIT** [comment]
Some research
```
streams:
  usb1: ffmpeg:-#input=-f v4l2 -input_format yuyv422 -video_size 1280x960 -i /dev/video0#video=h264#raw=-pix_fmt yuv420p
  usb2: ffmpeg:-#input=-f v4l2 -input_format mjpeg -video_size 1280x960 -i /dev/video0#video=copy
  usb3: ffmpeg:-#input=-f v4l2 -input_format yuyv422 -video_size 640x480 -i /dev/video2#video=h264#raw=-pix_fmt yuv420p
  usb4: ffmpeg:-#input=-f v4l2 -input_format bayer_grbg8 -video_size 640x480 -i /dev/video2#video=h264#raw=-pix_fmt yuv420p
```

```
[video4linux2,v4l2 @ 0x204e1c0] Compressed:       mjpeg :          Motion-JPEG : 640x360 1280x720 1920x1080
[video4linux2,v4l2 @ 0x204e1c0] Raw       :     yuyv422 :           YUYV 4:2:2 : 640x360 1280x720 1920x1080
[video4linux2,v4l2 @ 0x204e1c0] Compressed:        h264 :                H.264 : 640x360 1280x720 1920x1080

[video4linux2,v4l2 @ 0x55fddc42a940] Raw       :     yuyv422 :           YUYV 4:2:2 : 1920x1080
[video4linux2,v4l2 @ 0x55fddc42a940] Raw       :        nv12 :         Y/CbCr 4:2:0 : 1920x1080
[video4linux2,v4l2 @ 0x55fddc42a940] Raw       :     yuv420p :     Planar YUV 4:2:0 : 1920x1080

[video4linux2,v4l2 @ 0x1fb7660] Raw       :   yuyv422 :     YUV 4:2:2 (YUYV) : 640x480 160x120 176x144 320x176 320x240 352x288 432x240 544x288 640x360
[video4linux2,v4l2 @ 0x1fb7660] Compressed:     mjpeg :                MJPEG : 640x480 160x120 176x144 320x176 320x240 352x288 432x240 544x288 640x360
```
