### ISSUE TITLE
Possible to point webtorrent to custom domain/server?

### ISSUE THREAD

**Issue by erouten** [AlexxIT/go2rtc#1301]
Hello! I've read through the docs and have been able to create a permanent webtorrent link by editing the yaml file. But it seems that it always goes through https://alexxit.github.io/go2rtc/...

Is there any way I can have my local instance of Go2RTC point to a different webtorrent server? How would I setup a server with my own domain to act as the outside server rather than routing through the github URL?

Thank you!

**Comment by AlexxIT** [comment]
`https://alexxit.github.io/go2rtc/` it's just static HTML page without any server logic.
It does not depend on GitHub or the go2rtc project. You can place it anywhere.

You can set custom WebTorrent server on client:
https://github.com/AlexxIT/go2rtc/blob/afc8f4fdf615d6026ba1ecef5452c39f71e5afca/website/index.html#L183

You can set custom WebTorrent server in go2rtc config:
https://github.com/AlexxIT/go2rtc/blob/afc8f4fdf615d6026ba1ecef5452c39f71e5afca/internal/webtorrent/init.go#L21

PS. This is not documented feature.

**Comment by erouten** [comment]
I see! thank you!

**Comment by Nurmukhamed** [comment]
May you explain me more concrete please?
I just cannot get it.

I have installed frigate nvr, which included go2rtc package.
so my config is here, for example

```yaml
go2rtc:
  streams:
    eyeball01:
      - rtsp://admin:admin@192.168.1.5:554/cam/realmonitor?channel=1&subtype=0
    eyeball01_sub:
      - rtsp://admin:admin@192.168.1.5:554/cam/realmonitor?channel=1&subtype=1
  webtorrent:
    astana-eyeball01:
      astana-eyeball01:  # share name, should be unique among all go2rtc users!
        pwd: "password"
        src: eyeball01   # stream name from streams section
```

what i need add to my configuration to get it hosted on my site?
