### ISSUE TITLE
Application crashed (panic: close of closed channel)

### ISSUE THREAD

**Issue by KnutEricJelden** [AlexxIT/go2rtc#1330]
Hello, 

I am using go2rtc as solution to stream translations for a small event over WiFi. The signal is picked up over ffmpeg from an audio interface, configured over Alsa.
The following error occurs from time to time (not yet known if consistently reproducable by any direct action):

```
panic: close of closed channel
goroutine 1797 [running]:
github.com/AlexxIT/go2rtc/pkg/core. (*Sender).Close(0x0?)
github.com/AlexxIT/go2rtc/pkg/core/track.go:174 +0x96
github.com/AlexxIT/go2rtc/pkg/core. (*Connection).Stop(0xc0005da420)
github.com/AlexxIT/go2rtc/pkg/core/connection.go:74 +0x90
github.com/AlexxIT/go2rtc/internal/streams. (*Stream). RemoveConsumer (0xc00015c840, {0xd91400, 0xc0005da420})
github.com/AlexxIT/go2rtc/internal/streams/stream.go:58 +0x30
github.com/AlexxIT/go2rtc/internal/webrtc.asyncHandler.func1({0xb6f6a0?,
github.com/AlexxIT/go2rtc/internal/webrtc/webrtc.go:131 +0x9b
github.com/AlexxIT/go2rtc/pkg/core.(*Listener).Fire(...)
github.com/AlexxIT/go2rtc/pkg/core/listener.go:16
github.com/AlexxIT/go2rtc/pkg/webrtc.NewConn.func5(0x6)
github.com/AlexxIT/go2rtc/pkg/webrtc/conn.go:128 +0x68
0x1221950?})
created by github.com/pion/webrtc/v3. (*PeerConnection).onConnectionStateChange in goroutine 1796
github.com/pion/webrtc/v3@v3.2.40/peerconnection.go:500 +0x16f
[1] + Exit 2
```

My configuration so far:

```
streams:
  original: ffmpeg:device?audio=inchannel0&channels=1&sample_rate=16000&#audio=opus
  polish: ffmpeg:device?audio=inchannel1&channels=1&sample_rate=16000&#audio=opus
  russian: ffmpeg:device?audio=inchannel3&channels=1&sample_rate=16000&#audio=opus
  czech: ffmpeg:device?audio=inchannel2&channels=1&sample_rate=16000&#audio=opus

api:
  listen: ":1984"

ffmpeg:
  bin: "ffmpeg"
  aac: "-re -codec:a libmp3lame -fflags nobuffer"

log:
  format: "color"
  level: "info"
  output: "stdout"
  time: "UNIXMS"

rtsp:
  listen: ":8554"
  default_query: "video&audio"

srtp:
  listen: ":8443"

webrtc:
  listen: ":8555/tcp"
  ice_servers:
    - urls: [ "stun:stun.l.google.com:19302" ]
```

Thanks for your work, making this software publicly available. 
Hopefully this bug report helps to tackle that bug.

Greetings
