### ISSUE TITLE
Can't see GO2RTC Streams in homekit

### ISSUE THREAD

**Issue by derekngibbs** [AlexxIT/go2rtc#1334]
Running 0.14.1 Frigate on Ubuntu with docker compose. I am trying to get the cameras in homekit IOS Home app. The cameras are not showing up in the app. I'm concerned there is a networking issue. Here is what I see in the go2rtc web UI from the add.html.

![image](https://github.com/user-attachments/assets/959ad8f8-00e9-4556-bea9-818b0e0df8e4)

```
api:
  origin: '*'
hass:
  config: /config
homekit:
  your_oco_camera:
    device_id: oco1
    device_private: oco1
    name: boat house
    pin: 19550224
  your_reolink_camera:
    device_id: reo1
    device_private: reo1
    name: workout
    pin: 19550224
log:
  format: text
network_mode: host
rtsp:
  default_query: mp4
streams:
  your_oco_camera:
  - rtsp://admin:Password@192.168.1.237:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
  your_oco_camera_sub:
  - rtsp://admin:Password@192.168.1.237:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
  your_reolink_camera:
  - ffmpeg:http://192.168.2.206/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Reolinkpw-1#video=copy#audio=copy#audio=opus
  your_reolink_camera_sub:
  - rtsp://admin:Reolinkpw-1@192.168.2.206:554/h264Preview_01_sub
webrtc:
  candidates:
  - stun:8555
```
