### ISSUE TITLE
Video Freezing Issue with WebRTC via WireGuard VPN

### ISSUE THREAD

**Issue by barzag** [AlexxIT/go2rtc#1358]
Hello everyone,

I am experiencing an issue with configuring WebRTC over a WireGuard VPN, and I hope someone can help me resolve it.

Context
I have a setup using Go2RTC to stream video via WebRTC. My Go2RTC server is locally accessible at the following address: 10.14.4.39:1984. The server is configured to receive RTSP streams from several Reolink cameras.

I want to access these video streams remotely using a WireGuard VPN. Here are the details of my configuration:

Go2RTC Configuration:

```
api:
  origin: '*'
hass:
  config: /config
log:
  format: text
rtsp:
  default_query: mp4
streams:
  reolink_camera_3:
  - ffmpeg:https://10.22.10.145/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=$$$$$$$$@nvhhC#video=copy#audio=copy#audio=opus
  reolink_camera_4:
  - ffmpeg:https://10.22.10.144/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=$$$$$$$@nvhhC#video=copy#audio=copy#audio=opus
  reolink_camera_5:
  - ffmpeg:https://10.22.10.148/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=$$$$$$$@nvhhC#video=copy#audio=copy#audio=opus
webrtc:
  candidates:
  - stun:8555
```
When I configure the client’s AllowedIPs to only the local subnet (10.22.10.0/24), the videos freeze after 35 seconds. However, with AllowedIPs set to 0.0.0.0/0, the videos work correctly without interruptions.

Why does the video freeze when AllowedIPs is limited to the local subnet?
What adjustments should I make in the WireGuard client configuration to avoid this issue?
Are there any additional checks or recommended tests to diagnose this problem?
Thank you in advance for any help or suggestions you might have. Please feel free to ask for more information if needed.
