### ISSUE TITLE
Cannot get ffmpeg to work - An established connection was aborted by the software in your host machine (Solved)

### ISSUE THREAD

**Issue by catboyschrody** [AlexxIT/go2rtc#1372]
I am using ffmpeg version 2024-09-22, go2rtc version=1.9.4
I have the following, which works:
```
   streams:
     cam3:
       type: rtsp
       url: rtsp://10.0.0.45:80/ch2_0.264
       control: false
       record: false
       options:
         reconnect: true
         reconnect_interval: 60 # seconds
         max_retries: 5
```

Now, I want to handle this with ffmpeg. According to the documentation, with the format being `ffmpeg:{input}#{param1}#{param2}#{param3}` the following simple stream should work:
`test: ffmpeg:rtsp://localhost:8554/cam3`
But I am getting the error: error="read tcp 127.0.0.1:8554->127.0.0.1:50731: wsarecv: An established connection was aborted by the software in your host machine."

Now the following works:

```
  test:
     type: ffmpeg
     url: rtsp://localhost:8554/cam3
```

But I cant apply operations like `#rotate=90` or `options: rotate: 90' to work

The following doesnt work either:
`test: ffmpeg:rtsp://10.0.0.45:80/ch2_0.264`

My end goal is to create a new rtsp stream by taking 4 camera streams, cam1, cam2, cam3 and cam4 and applying the following: `-filter_complex "[0:v][1:v]hstack[top];[2:v][3:v]hstack[bottom];[top][bottom]vstack"`
I want to use the camera stream created by go2rtc as opposed to from the camera source because I need the functionality of reconnect_interval.

I have ensured both go2rtc.exe and ffmpeg.exe are in windows antivirus and firewall exclusion list

But I'm failing at basically step two, getting ffmpeg to work
