### ISSUE TITLE
reuse stream in exec source

### ISSUE THREAD

**Issue by Suxsem** [AlexxIT/go2rtc#1374]
Hi, not really an issue sorry,
but I'm trying to have a mosaic of my security cameras using xstack.

To keep the network traffic low, i would like to resume an existing stream. Is it possible to reference an existing stream in an "exec" source?

Something like that

```
streams:
  sonoff_camera: rtsp://rtsp:12345678@192.168.1.123/av_stream/ch0
  dahua_camera:
    - rtsp://admin:password@192.168.1.123/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    - rtsp://admin:password@192.168.1.123/cam/realmonitor?channel=1&subtype=1
  amcrest_doorbell:
    - rtsp://username:password@192.168.1.123:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
  mosaic: exec:ffmpeg -i sonoff_camera -i dahua_camera -vcodec libx264 -tune zerolatency -filter_complex "[0:v]scale=640:-1[v0];[v0][1:v]hstack=inputs=2" -f rtsp {output}

```
