### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by JoeHogan** [AlexxIT/go2rtc#1380]
Are there lifecycle hooks in go2rtc? I didn't see anything about this in the docs. I'd like to be able to run a command when a stream connects or disconnects. My use case is that ffmpeg is generating images from my streams every few seconds and putting them in a folder. I'd like to delete the image when the respective stream goes down. I was formerly using MediaMtx to do this, but I have moved to go2rtc to take advantage of hardware acceleration. Here is an example from MediaMtx that may help explain:

```
pathDefaults:
  runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -vf fps=1/3 -update 1 -y /img/$MTX_PATH.jpg
  runOnReadyRestart: yes
  runOnNotReady: rm /img/$MTX_PATH.jpg
```
