### ISSUE TITLE
Reolink Video Doorbell - stream won't close after 2 way audio

### ISSUE THREAD

**Issue by cooltings** [AlexxIT/go2rtc#1381]
Hi,
I am using the frigate hass card with 2 way audio which works great with the doorbell. The only issue is that after finishing 2 way talk the stream doesn't seem to close and the blue status ring on the doorbell stays blue indicating it still receiving audio. 
![Screenshot 2024-10-02 at 22 59 44](https://github.com/user-attachments/assets/07666521-fbc4-4aa2-ad3b-122790b27276)
Here is my config in case it has something to do with that:
```
api:
  ffmpeg:
    bin: /usr/local/bin/ffmpeg
  origin: '*'
ffmpeg:
  rtsp: -fflags nobuffer -flags low_delay -stimeout 5000000 -user_agent go2rtc/ffmpeg
    -rtsp_transport tcp -i {input}
hass:
  config: /config
log:
  format: text
rtsp:
  default_query: mp4
streams:
  reolink:
  - ffmpeg:http://192.168.0.33/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=smartcam#video=copy#audio=opus
  - rtsp://REDACTED@192.168.0.33:554/h264Preview_01_main
  reolink_rec:
  - rtsp://REDACTED@192.168.0.33:554/h264Preview_01_main#backchannel=0
  - ffmpeg:reolink_rec#audio=pcma
webrtc:
  candidates:
  - 192.168.0.219:8555
  - stun:8555
  listen: :8555
```
