### ISSUE TITLE
Allow udp restream on go2rtc

### ISSUE THREAD

**Issue by hannesroth88** [AlexxIT/go2rtc#1383]
Hi,

I have a Reolink Camera and some Intercom. I want to read the video stream from the camera by the intercom to later view the video in a call. It doesn't let me connect it because of codec issues.
I am running frigate over truenas, so i wanted to use the restream capability and see if the intercom is able to read the video stream via rtsp from there.

The stream is shown on frigate ui. But when i try to connect the intercom I get. 
"Unsupported Transport". 
As I played around a bit already with cocker-compose ffmpeg + aler9/rtsp-simple-server. I could fix this error by allowing udp. But having troubles with disconnects :(

**Is it possible to allow udp on go2rtc?**.
I hope this question is correctly placed in here as go2rtc sets up the server right?

Heres my frigate config:

```
mqtt:
  enabled: false
cameras:
  hauseingang:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/hauseingang # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
go2rtc:
  streams:
    hauseingang: # <- for RTSP streams
      - "ffmpeg:http://192.168.0.11/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=mySecurePw#video=copy#audio=copy#audio=opus"
      - ffmpeg:hauseingang#audio=opus#video=h264#hardware   # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
version: 0.14
camera_groups:
  Haus:
    order: 1
    icon: LuSprout
    cameras:
      - hauseingang
```
