### ISSUE TITLE
Tapo 2 way audio stops working

### ISSUE THREAD

**Issue by leaskovski** [AlexxIT/go2rtc#1385]
Hi there... so I am running frigate with go2rtc 1.9.2 (the version they back into their container).  The system works fine, and no real issues apart from a 2 way audio issue that I have noticed with my tapo c200 camera (v2 hardware).

Here is my config...
```
api:
  origin: '*'
candidates:
- 192.168.0.196:8555
- stun:8555
hass:
  config: /config
log:
  format: text
  level: debug
rtsp:
  default_query: mp4
streams:
  dog_cam: tapo://xxx:xxx@192.168.0.108
  dog_cam_sub: rtsp://xxx:xxx@192.168.0.108/stream2
  doorbell_cam:
  - ffmpeg:https://192.168.0.111/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxx&password=xxx#video=copy#audio=copy#audio=opus
  - rtsp://xxx:xxx@192.168.0.111:554/h264Preview_01_sub
  doorbell_cam_sub:
  - ffmpeg:https://192.168.0.111/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxx&password=xxx
  drive_cam: rtsp://xxx:xxx@192.168.0.109/Streaming/Channels/101/
  drive_cam_sub: rtsp://xxx:xxx@192.168.0.109/Streaming/Channels/102/
  garden_cam: rtsp://xxx:xxx@192.168.0.110/Streaming/Channels/101/
  garden_cam_sub: rtsp://xxx:xxx@192.168.0.110/Streaming/Channels/102/
webrtc:
  candidates:
  - stun:8555
```
What happens is that 2 way audio will work fine after a restart of the go2rtc service, so if I open the internal webrtc.html link with vid+audio+mic for the camera, it works fine.  If I then close that browser session, and reopen up the browser and go back to that page after a few minutes, the 2 way audio doesn't work.

What log levels do I need to enable to get sufficient logging for the problem?  This could be a repeat of this issue (https://github.com/AlexxIT/go2rtc/issues/547), as it seems very similar.
