### ISSUE TITLE
Camerstream lost, but no connect retry from go2rtc 

### ISSUE THREAD

**Issue by vigeland** [AlexxIT/go2rtc#1389]
I have 3 cameras, one stream is lost. No Error in the log.

I see two tcp connections go2rtc to the left cameras. 
If I open with go2rtc gui the missing on, nothing happens. ( Black screen :-) ) 
No logfile error, I see no tcp connections try to the missing camera.
Restart of go2rtc, all 3 cameras are working well.
Any Idea ?

**Comment by AlexxIT** [comment]
You need to start with the go2rtc version and stream info.

**Comment by vigeland** [comment]
Sorry, I am new in go2rtc, what mean  "go2rtc version and stream info."
"go2rtc version 1.9.4 (a4885c2) linux/amd64"

**Comment by AlexxIT** [comment]
You can check stream from from go2rtc WebUI

**Comment by vigeland** [comment]
I try to write it in my first comment.
All trys only with the go2rtc web at port 1984
0 Stream used at the third camera, one at camera 1 and 2. Web gui left side.
When I click on the right side on the stream link, the stream window open and no stream was displayed ( black ).
No Error log writen by go2rtc, no Network Connection displayed with netstat to the camera ip.
Restart go2rtc, stream link display the Stream instandly.

**Comment by AlexxIT** [comment]
Stream info. And stream probe.

**Comment by popy2k14** [comment]
Same issue as stated here: https://github.com/AlexxIT/WebRTC/issues/631
The issue arised to me because of the webrtc 3.6.0 update, which comes with go2rtc 1.9.4.
I downgraded to webrtc 3.5.2 which has go2rtc 1.8.4, and i works flawlessly since a day with my reolink doorbell wifi.

With the new webrtc 3.6.0, every few hours a reconnect/progress circle is shown in front of the last picture, which freezed.
But i never reconnects.

How can i provide a log and help debug?

**Comment by popy2k14** [comment]
@AlexxIT 3.5.2 with go2rtc 1.8.4 works wihtout any reconnect issue since ~4 days.
So it seem there is an issue 1.9.4.

Is it possible for you to downgrade the included go2rtc to 1.8.4 until the issues with newer versions are sorted?

**Comment by AlexxIT** [comment]
You can use any version you want. If you are sure it is compatible with the new integration version.
https://github.com/AlexxIT/WebRTC/blob/121d7558d0a2f1d19452f7b51a6237e048153528/custom_components/webrtc/utils.py#L28

**Comment by aarnaud** [comment]
I have the same issue with  1.9.4 recently update from 1.8.4  2 weeks ago 
```
go2rtc version 1.9.4 (a4885c2) linux/amd64
```
Works fine with 1.8.4

```
api:
  origin: '*'
ffmpeg:
  h264/rk: -c:v h264_rkmpp_encoder -g 50 -bf 0
  h265/rk: -c:v hevc_rkmpp_encoder -g 50 -bf 0
hass:
  config: /config
log:
  format: text
rtsp:
  default_query: video
  password: CHANGEME
  username: frigate
streams:
  camera1: ffmpeg:rtsp://root:CHANGEME@192.168.xxx.yyy:554/stream=0#video=copy#audio=copy
  camera1-LD: ffmpeg:rtsp://root:CHANGEME@192.168.xxx.yyy:554/stream=1#video=copy#audio=copy
  camera2: ffmpeg:rtsp://root:CHANGEME@192.168.xxx.yyy:554/stream=0#video=copy#audio=copy
  camera2-LD: ffmpeg:rtsp://root:CHANGEME@192.168.xxx.yyy:554/stream=1#video=copy#audio=copy
webrtc:
  candidates:
  - 192.168.xxx.yyy:8555
  - stun:8555
  listen: :8555
```
