### ISSUE TITLE
Is there any way to remuxing, re-coding, transfer streams to other tcp/udp endpoint or a file ?

### ISSUE THREAD

**Issue by jiekechoo** [AlexxIT/go2rtc#1398]
As my question, MediaMTX provides a feature: https://github.com/bluenviron/mediamtx/?tab=readme-ov-file#remuxing-re-encoding-compression , I need using go2rtc to do the same thing. 

Any help would be appreciate.

Thanks.

Jieke

**Comment by jiekechoo** [comment]
```
ffmpeg:
  bin: ffmpeg  # path to ffmpeg binary
  h264: "-codec:v libx264 -g:v 30 -preset:v superfast -tune:v zerolatency -profile:v main -level:v 4.1"
  mycodec: "-any args that supported by ffmpeg..."
  myinput: "-fflags nobuffer -flags low_delay -timeout 5000000 -i {input}"
  myraw: "-ss 00:00:20"

streams:
  camera1:
    - rtsp://rtsp:12345678@192.168.1.123/av_stream/ch0
    - ffmpeg:camera1#video=mjpeg
```
I think, go2rtc able to do it, how to use custom formats in `streams/ffmpeg`?
