### ISSUE TITLE
RTSP/ Home Assistant Homekit  - no audio

### ISSUE THREAD

**Issue by haitham506** [AlexxIT/go2rtc#1401]
Hello,

go2rtc config:
```
streams:
  Entrancego2rtc: ffmpeg:rtsp://user:psss@192.168.3.3/Preview_04_sub#video=copy#audio=opus
```
Home Assistant Homekit config:
```
homekit:
- name: Entrance Cam
  port: 21088
  mode: accessory
  filter:
    include_entities:
      - camera.entrance_sub
  entity_config:
    camera.entrance_sub:
      stream_source: rtsp://192.168.3.3:8554/Entrancego2rtc
      support_audio: True
      video_codec: copy
      audio_codec: copy
      linked_motion_sensor: binary_sensor.binary_sensor_entrance_person
```
Playing the camera on the browser or VLC works fine with audio.
When playing the camera in Home app (AppleTV/iPad) there is no sound even though it is OPUS

But if I add the camera to Homekit through go2rtc directly the audio works fine

I want it this way to link the motion sensor to the camera for push notifications with thumbnail + if I add it to homekit through HA without go2rtc the audio will be Choppy because of the transcoding aac to opus 

What is the issue here?

Thank you :)
