### ISSUE TITLE
I'm not able to get rotated camera to auto start.

### ISSUE THREAD

**Issue by caublet** [AlexxIT/go2rtc#1403]
Using frigate  0.14,  rotated camera is not starting unless I clicck  on stream : 
Go2rtc config  :
```
go2rtc:
  streams:
    Side:
      - ffmpeg:rtsp://999:{FRIGATE_RTSP_PASSWORD}@192.168.1.23:554/Streaming/Channels/1#video=h264#rotate=90#audio=aac#hardware
```
All logs are in this support config support thread : https://github.com/blakeblackshear/frigate/discussions/14344
