### ISSUE TITLE
How to config an onvif camera with three streams

### ISSUE THREAD

**Issue by latel** [AlexxIT/go2rtc#1410]
```
log:
  level: debug

streams:
  Hikvision:
    - rtsp://admin:xxxxxxx@11.10.22.22:554/Streaming/Channels/101
    - rtsp://admin:xxxxxxx@11.10.22.22:554/Streaming/Channels/102
    - rtsp://admin:xxxxxxx@11.10.22.22:554/Streaming/Channels/103
```

how do I turn into something like this?
```
streams:
  Hikvision:
    - onvif://admin:xxxxxxx@11.10.22.22
```
