### ISSUE TITLE
Reolink No Audio in WebRTC mode

### ISSUE THREAD

**Issue by paull27** [AlexxIT/go2rtc#1411]
Hi. I've seen a few similar issues, like [this](https://github.com/AlexxIT/go2rtc/issues/506). However, they haven't really helped me.

I'm using frigate and go2rtc version 1.9.4.
The camera is a Reolink E1 Pro.
I'm getting audio in mse mode, but not in webrtc, although I configured the transcoding to opus.

config:
```
api:
  origin: '*'
ffmpeg:
  rtsp: -fflags nobuffer -flags low_delay -stimeout 5000000 -user_agent go2rtc/ffmpeg
    -rtsp_transport tcp -i {input}
hass:
  config: /config
log:
  format: text
rtsp:
  default_query: mp4
  #listen: ":554"
streams:
  e1:
  - rtsp://admin:xxx@192.168.20.50/Preview_01_main
  - ffmpeg:rtsp://admin:xxx@192.168.20.50/Preview_01_main#audio=opus
webrtc:
  candidates:
  - 192.168.20.2:8555
  - stun:8555
```

camera probe:
```
{
  "producers": [
    {
      "id": 15,
      "format_name": "rtsp",
      "protocol": "rtsp+tcp",
      "remote_addr": "192.168.20.50:554",
      "url": "rtsp://admin:xxx@192.168.20.50/Preview_01_main",
      "sdp": "v=0\r\no=- 1562112017753892 1 IN IP4 192.168.20.50\r\ns=Session streamed by \"preview\"\r\nt=0 0\r\na=tool:BC Streaming Media v202210012022.10.01\r\na=type:broadcast\r\na=control:*\r\na=range:npt=now-\r\na=x-qt-text-nam:Session streamed by \"preview\"\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKB4AiflQA==,aO48sA==\r\na=recvonly\r\na=control:track1\r\nm=audio 0 RTP/AVP 97\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=recvonly\r\na=control:track2\r\nm=audio 0 RTP/AVP 0\r\na=control:track3\r\na=rtpmap:0 PCMU/8000\r\na=sendonly",
      "user_agent": "go2rtc/1.9.4",
      "medias": [
        "video, recvonly, H264",
        "audio, recvonly, MPEG4-GENERIC/16000",
        "audio, sendonly, PCMU/8000"
      ],
      "receivers": [
        {
          "id": 16,
          "codec": {
            "codec_name": "h264",
            "codec_type": "video",
            "level": 51,
            "profile": "High"
          },
          "childs": [
            17
          ]
        },
        {
          "id": 18,
          "codec": {
            "codec_name": "aac",
            "codec_type": "audio",
            "sample_rate": 16000
          },
          "childs": [
            19
          ]
        }
      ],
      "senders": [
        {
          "id": 21,
          "codec": {
            "codec_name": "pcm_mulaw",
            "codec_type": "audio",
            "sample_rate": 8000
          },
          "parent": 20
        }
      ]
    },
    {
      "url": "ffmpeg:rtsp://admin:xx@192.168.20.50/Preview_01_main#audio=opus"
    }
  ],
  "consumers": [
    {
      "id": 14,
      "format_name": "probe",
      "protocol": "http",
      "remote_addr": "192.168.20.3:63573",
      "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Safari/605.1.15",
      "medias": [
        "video, sendonly, ALL",
        "audio, sendonly, ALL",
        "audio, recvonly, ANY"
      ],
      "receivers": [
        {
          "id": 20,
          "codec": {
            "codec_name": "ANY",
            "codec_type": ""
          },
          "childs": [
            21
          ]
        }
      ],
      "senders": [
        {
          "id": 17,
          "codec": {
            "codec_name": "h264",
            "codec_type": "video",
            "level": 51,
            "profile": "High"
          },
          "parent": 16
        },
        {
          "id": 19,
          "codec": {
            "codec_name": "aac",
            "codec_type": "audio",
            "sample_rate": 16000
          },
          "parent": 18
        }
      ]
    }
  ]
}
```

Seems like ffmpeg is not doing the transcoding? Thanks for helping
