### ISSUE TITLE
On 1.9.5 tapo cams stucks in loading

### ISSUE THREAD

**Issue by xitters** [AlexxIT/go2rtc#1415]
Whit this configuration my cams dont show image, stuck on loading

type: custom:webrtc-camera
url: rtsp://albin****:MA***55@192.168.10.50:554/stream1
poster: https://home-assistant.io/images/cast/splash.png

on 1.9.4 works perfectly, why?

**Comment by GeorgeCastanza** [comment]
All my Unifi cams too. I rolled back and its working again.

**Comment by rinners** [comment]
> All my Unifi cams too. I rolled back and its working again.

Same here

**Comment by blanknam3d** [comment]
I figured it out: if you are using the WebRTC Home Assistant card, it seems the API now expects to be told the name of a stream present in the go2rtc config, rather than being able to accept a given RTSP link for either `src` or `url`.

Not sure why it needs to be that way to work now, but that seems to be how it now works. ex:
```
type: custom:webrtc-camera
ui: true
poster: http://192.168.X.XXX:1984/api/frame.jpeg?src=kitchen
streams:
  - url: ""
    name: PLAY
  - url: kitchen
    name: HD
    mode: webrtc,webrtc/tcp,onvif
    media: video,audio
    
```
As opposed to `kitchen` being something like `rtsp://skyna:SecurePassword@192.168.X.XXX`. Suspect it's related to this: #1407
