### ISSUE TITLE
RTSP Audio combine Onvif Video

### ISSUE THREAD

**Issue by daxxis** [AlexxIT/go2rtc#1420]
Help me set up, I have two streams, the first is rtsp audio and the second is onvif video, I need to combine them and rebroadcast them along with the sound, I managed to do this and it works, the most important thing is how to set the delay for the sound in order to synchronize it for the stream output

My config:
```
ffmpeg:
  bin: /usr/local/bin/ffmpeg7

streams:
  axis_34:
    - ffmpeg:rtsp://admin:123ert678@192.168.0.47:554/channel=2#audio=copy
    - onvif://admin:123ert678@192.168.0.34
```
I don’t understand how and where to apply arguments for ffmpeg

Please help🙏
