### ISSUE TITLE
Two-way audio issues on streams with multiple sources

### ISSUE THREAD

**Issue by seydx** [AlexxIT/go2rtc#1424]
✅ Two-way audio works for streams with single RTSP (with backchannel) source

Exp:

```
streams:
  test:
    - rtsp://abc@192.1.2.3.4:554/ihavebackchannel
```

WebRTC Connection to `test` works without any issues, two-way audio works as intended

✅ Two-way also works for streams mith multiple sources when eg `tapo://`is used for two-way audio as a second source

Exp:

```
streams:
  test:
    - tapo://abc@192.1.2.3.4
  test_pcma:
    - ffmpeg:test#video=copy#audio=pcma
    - tapo://abc@192.1.2.3.4
```

WebRTC Connection to `test_pcma` works without any issues, two-way audio works as intended

❌ Two-way audio does not work for streams with multiple sources when RTSP (with backchannel) is used for two-way audio as a second source.

Exp:

```
streams:
  test:
    - rtsp://abc@192.1.2.3.4:554/ihavebackchannel
  test_pcma:
    - ffmpeg:test#video=copy#audio=pcma
    - rtsp://abc@192.1.2.3.4:554/ihavebackchannel
```

WebRTC Connection to `test_pcma` works without any issues, but two-way does `NOT` work
