### ISSUE TITLE
Frequent freezes while streaming from Tapo C200 cameras that require restarting the plugin

### ISSUE THREAD

**Issue by blanknam3d** [AlexxIT/go2rtc#1433]
I'm experiencing a problem where if I play a stream from my Tapo C200 cameras, it eventually freezes up & will not load again if I refresh & try to play the stream once more, unless I go & restart the go2rtc plugin.

Streams in my go2rtc config:
```
streams:
  kitchen: tapo://HighlySecurePassword@192.168.x.xx
  livingroom: tapo://AnotherSecurePassword@192.168.x.xx
...
```
Lovelace card config example:
```
type: custom:webrtc-camera
ui: true
poster: http://192.168.x.xx:1984/api/frame.jpeg?src=livingroom
streams:
  - url: ""
    name: PLAY
  - url: livingroom
    name: HD
    mode: webrtc,webrtc/tcp,onvif
    media: video,audio
```
Logs from addon startup to when video stream freezes & won't reload:
```
09:05:45.215 INF go2rtc platform=linux/amd64 revision=8cca8de version=1.9.6
09:05:45.217 INF config path=/config/go2rtc.yaml
09:05:45.217 INF [rtsp] listen addr=:8554
09:05:45.218 INF [api] listen addr=:1984
09:05:45.219 INF [webrtc] listen addr=:8333
09:25:27.490 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:170 > error="malformed MIME header: missing colon: \"Cont----device-stream-boundary--\"" url=tapo://SecurePassword@192.168.x.xx
```
The last line sometimes doesn't come up when the video stream from either of the Tapo cameras freezes, however I always find that when the video stream freezes the addon's CPU usage in Home Assistant goes up to 99% & stays there until it's restarted. I also observe that whatever stream freezes, it cannot generate any still frame thumbnail for it, but still can generate one for other streams that haven't had the sudden freeze happen to them. As for generating the thumbnail of a stream that has suddenly frozen, however, it seemingly leaves the client eternally waiting for a response.

I observe this behavior highly consistently, if I simply view a camera stream for more than 2 minutes it will happen & then I have to restart the addon to be able to view that stream again with go2rtc. So far I only see this happening with streams using `tapo://`, it doesn't appear to happen with standard RTSP streams from other cameras.
