### ISSUE TITLE
how to specify stream in tapo module?

### ISSUE THREAD

**Issue by latel** [AlexxIT/go2rtc#1437]
My tapo c120 has 2 streams, high and low, how can I specify the stream to use in tapo module?

```
streams:
  # cloud password without username
  camera1: tapo://cloud-password@192.168.1.123
  # admin username and UPPERCASE MD5 cloud-password hash
  camera2: tapo://admin:UPPERCASE-MD5@192.168.1.123
  # admin username and UPPERCASE SHA256 cloud-password hash
  camera3: tapo://admin:UPPERCASE-SHA256@192.168.1.123
```

is it something like this?
```
streams:
  camera1: tapo://cloud-password@192.168.1.123/stream2
```
