### ISSUE TITLE
Allow to only "consume" backchannel but not inbound audio from rtsp source

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/go2rtc#1442]
For example, I would like to discard the inbound audio of my Dahua VTO:

```yaml
streams:
  vto_audio:
    # AAC, OPUS
    - echo:/config/scripts/fix_vto_codecs.sh 
      ffmpeg:rtsp://admin:pass@192.168.1.40/cam/realmonitor?channel=1&subtype=1#audio=copy#audio=opus
  vto:
    # H264
    - echo:/config/scripts/fix_vto_codecs.sh 
      rtsp://admin:pass@192.168.1.40/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif#media=video#backchannel=1
    # AAC, OPUS
    - rtsp://127.0.0.1:8554/video_porteiro_audio?audio=all
```

Note I'm using `#media=video#backchannel=1` in the RTSP URL. That is because I want to discard audio from that stream, but I still want backchannel and video from it.

However, what happens is that `#media=video` discards all audio tracks, including the backchannel one.

I believe the best would be to NOT discard the backchannel track if `#backchannel=1`.
