### ISSUE TITLE
HA managed version not running properly or updating

### ISSUE THREAD

**Issue by bmorgan99** [AlexxIT/go2rtc#1451]
go2rtc has a pid but is not responding on port 11984 (or 1984) and what I think is it's config file only shows 1 camera.  How can I restart it, and will it then get the cameras from config/go2rtc.yaml?  Rebooting didn't help.

ps -ef | grep go2
`  178 root      0:00 /bin/go2rtc -c /tmp/go2rtc_mvp3jup8.yaml
`

tmp/go2rtc_mvp3jup8.yaml
```
# This file is managed by Home Assistant
# Do not edit it manually

api:
  listen: "127.0.0.1:11984"

rtsp:
  listen: "127.0.0.1:18554"

webrtc:
  listen: ":18555/tcp"
  ice_servers: []
streams:
  camera.garden_orginal:
    - rtsp://admin:ndc999!!@192.168.1.28/h264Preview_01_main
  camera.garden:
    - rtsp://127.0.0.1:18554/camera.garden_orginal
    - ffmpeg:camera.garden_orginal#audio=opus

```
