### ISSUE TITLE
2-way audio with ICSee/dvrip cameras 

### ISSUE THREAD

**Issue by srocupado** [AlexxIT/go2rtc#1472]
Hey there, 

I´m using a cheap chinese camera (https://aliexpress.com/item/1005005731238053.html) with the following streams:

```
streams:
  camera.scale:
   - dvrip://username:password@192.168.1.123:34567?channel=0&subtype=0
   - dvrip://username:password@192.168.1.123:34567?backchannel=1

```
Webrtc card:

```
type: custom:webrtc-camera
 ui: true
  streams:
    - url: camera.scale
      mode: webrtc
      name: Mic on'
      media: video,audio,microphone

    - url: camera.scale
      mode: webrtc      
      name: Mic off
      media: video,audio

```
The two way audio work as expected, but the rtc stream doesn´t (just black screen). If I remove the "mode: webrct" from the card, the stream is shown as "MSE" and is fine. But the 2 way audio doesn´t work.

Did I miss something ?
Best Regards.
