### ISSUE TITLE
lost audio after changing camera's fps, bit rate, and i-frame

### ISSUE THREAD

**Issue by Cold-Lemonade** [AlexxIT/go2rtc#1476]
I have several Dahua-branded cameras. I was able to connect to them and receive the video and audio feed without issue using the go2rtc included in Frigate 0.13.2 and 0.14.1 (and earlier versions too). Yesterday, I started changing the cameras' fps, bit rates, and i-frames, and now I've lost audio.

When I open a camera's live view in Frigate (which I understand to be the restream from go2rtc), I hear just less than 1 second of audio then nothing. These are 2MP and 4MP cameras with fps set 20 and bit rate at the max (8092) and i-frame set to match fps at 20.

I haven't changed the config file at all. Here is what the relevant line for each two-way camera looks like, for the other one-way ones there is no "#backchannel=0":

```
go2rtc:
  streams:
    front_south:
      - rtsp://user:password@ipaddress:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
```

Audio encoding is AAC at 16000.

I've tried changing the settings by lowering the bit rate, etc., to no avail. I'm at a loss on what to try next. I believe go2rtc receives audio because I can here audio for the first second in MSE.
