### ISSUE TITLE
Synology Container Manager (Docker) Setup

### ISSUE THREAD

**Issue by skyynet** [AlexxIT/go2rtc#1484]
I want to use my UniFi Protect camera's stream in a browser and installer go2rtc on my Synology as Docker.
As configuration, I only added the variable "camera1" with content to the stream rtsps://192.168.1.1:7441/xxxxxxxxxxxx?enableSrtp where xxx is the token. I also forwarded ports 1984, 8554. 8555, 7441.

When I access http://synologyip:1984/api/stream.m3u8?src=camera1
I get "stream not found". Opening the stream's URL on VLC works fine.

Probably just a simple configuration problem, but I couldn't figure it outwith the wiki.

**Comment by skyynet** [comment]
To be honest, I just entered the RTSP location of the stream. Since the certificate of the RTSPS stream seemed problematic for some clients, I also used the RTSP stream. Still "get stream not found".

![go2rtc](https://github.com/user-attachments/assets/4f5b900d-1bda-4c99-8bac-7254f8e0bae4)

**Comment by AlexxIT** [comment]
What makes you think such a config should even work? go2rtc does not read environment variables with random names.

**Comment by skyynet** [comment]
In the readme.md the env vars are described at https://github.com/AlexxIT/go2rtc/blob/master/internal/app/README.md
Here I see:

```
streams:
  camera1: rtsp://rtsp:${CAMERA_PASSWORD}@192.168.1.123/av_stream/ch0

rtsp:
  username: ${RTSP_USER:admin}   # "admin" if "RTSP_USER" not set
  password: ${RTSP_PASS:secret}  # "secret" if "RTSP_PASS" not set

```

AFAIK, there is no possibility to define nested vars in Container Manager (Docker) at my Synology NAS. Thus I didn't knew how to define streams camara1 and only defined camera1. For RTSP I have no usr nor pwd since the stream is only in my LAN.

So how do I define the source for the stream correctly? Thanks for advice.
