### ISSUE TITLE
disable audio for transcode h265>h264 to lower cpu utilization

### ISSUE THREAD

**Issue by levski** [AlexxIT/go2rtc#1490]
i got go2rtc on frigate.
stream is from 4k reolink h265 transcoded using nvidia gpu (1080ti) to h264.
cpu utilization on an r5 2600x is between 70-80%.
from what i gathered, the gpu only does video, the audio is still done by the cpu.
i've removed the audio recording from the source cameras but cpu utilization didn't change. i figured i needed to tell ffmpeg not to do the audio to free up those cycles.
i tried to add #an but that doesn't seem to work.
here's my current config.
help getting audio disregarded by ffmpeg or better optimization is greatly appreciated.

```
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - cuda

go2rtc:
  streams:
    perimetercam1_main: >
      ffmpeg:rtsp://username:password@ipaddress:554/h265Preview_01_main#video=h264#hardware=cuda
```
