### ISSUE TITLE
 RTMP server output stream error

### ISSUE THREAD

**Issue by freedomxie** [AlexxIT/go2rtc#1500]
this is go2rtc.yarm
```
streams:
  hello: ffmpeg:rtmp://192.168.0.175:1935/live/131
ffmpeg:
  bin: /sdk/xd/ffmpeg-v7/ffmpeg
rtmp:
  listen: ":1935"
```
```
ffplay -i  rtmp://
```

**Comment by freedomxie** [comment]
Unable to play video, countless video data

**Comment by freedomxie** [comment]
thanks. but rtsp can be played successfully！

**Comment by AlexxIT** [comment]
I can't confirm problem. Latest master version.

```yaml
rtmp:
  listen: ":1935"

streams:
  rtmp-reolink1: ffmpeg:rtmp://192.168.10.92/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=password
```

And

```
ffplay rtmp://192.168.10.101/rtmp-reolink1
```

Maybe your problem related to your stream, environment, old go2rtc version, ffmpeg version or something else.

Maybe with additional detail something will become clearer.
