### ISSUE TITLE
Transcoding OPUS to AAC yields a muted audio track

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/go2rtc#1505]
I flashed [Thingino](https://github.com/themactep/thingino-firmware) in one of my cameras, and this firmware is capable of sending audio in OPUS format, which is great.

My go2rtc config is like the following:

```yaml
streams:
  my_cam:
    - rtsp://thingino:thingino@192.168.1.31/ch1
    - ffmpeg:my_cam#audio=aac
```

When I play in VLC with:

```
rtsp://go2rtc:8554/my_cam?video&audio=opus
```

Everything works ok. I can hear audio just fine.

![image](https://github.com/user-attachments/assets/d76a38b1-4d99-4f5d-9780-177bc311eb99)

But when I play with:

```
rtsp://go2rtc:8554/my_cam?video&audio=aac
```

There is no audio. In fact, the AAC track is included, but it's muted.

![image](https://github.com/user-attachments/assets/9ebff581-b6a3-45fb-995d-b82b820fd3b1)

I wonder, have you ever tried transcoding OPUS to AAC? Maybe I'm not alone.

PS: I don't see any error in my logs.
