### ISSUE TITLE
Reolink doorbell 2-way audio not working

### ISSUE THREAD

**Issue by sharoon65** [AlexxIT/go2rtc#1513]
I am not able to get 2 way audio working with my reolink doorbell. I use frigate as a standalone docker container and home assistant 

Here is my go2rtc config in frigate:
```

go2rtc:
  streams:
    FrontCamera:
      - "ffmpeg:http://192.168.0.225/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=admin#video=copy#audio=copy#audio=opus"
      - rtsp://192.168.0.225/Preview_01_sub
    FrontCamera_sub:
      - "ffmpeg:http://192.168.0.225/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=admin"
    BackCamera:
      - "ffmpeg:http://192.168.0.249/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Chuppai@123#video=copy#audio=copy#audio=opus"
      - rtsp://192.168.0.249/Preview_01_sub
    BackCamera_sub:
      - "ffmpeg:http://192.168.0.249/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Chuppai@123"
  webrtc:
    listen: :8555
    candidates:
      - 192.168.0.117:8555
      - stun:8555
```

my go2rtc version is 1.9.2

I tried verifying by going to http://frigate_ip:1984/webrtc.html?src=BackCamera&media=video+audio+microphone to access the stream and holding down the microphone button in the frigate card on the home assistant app but dont hear any audio. 1 way audio (from doorbell to phone) works fine. I am not sure what I am missing here, appreciate any help!
