### ISSUE TITLE
[FR]: Custom -vf command - crop video stream

### ISSUE THREAD

**Issue by mr-manuel** [AlexxIT/go2rtc#1524]
Hello,

thank you very much for this awesome piece of software!

I would like to crop a stream and make it available to other devices.

Normally I would add `-vf fps=8,hwdownload,format=yuv420p,crop=510:610:1900:130 -threads 1 -f rawvideo`to ffmpeg, but in the README and docs I found no way to do so.

Is there already a way to add this or could you add that?

**Comment by AlexxIT** [comment]
Just use exec source.

**Comment by mr-manuel** [comment]
It took me a few monthy and trillion of tests, but finally I got it working!

If someone other searches how to crop the video feed here is how I achieved it:

## H.264 output
```yml
streams:
  Porch: rtsp://192.168.1.80:554/11
  Cropped: "exec:/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -rtsp_transport tcp -timeout 10000000 -i rtsp://127.0.0.1:8554/Porch -vf hwdownload,format=yuv420p,crop=510:610:1900:130 -c:v libx264 -f h264 pipe:"
```

## MJPEG output
```yml
streams:
  Porch: rtsp://192.168.1.80:554/11
  Cropped: "exec:/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -rtsp_transport tcp -timeout 10000000 -i rtsp://127.0.0.1:8554/Porch -vf hwdownload,format=yuv420p,crop=510:610:1900:130 -c:v mjpeg -f mjpeg pipe:"
```

You can also swap `rtsp://127.0.0.1:8554/Porch` with the direct stream of the camera without re-streaming it.
