### ISSUE TITLE
Stream to html page

### ISSUE THREAD

**Issue by DATPOL** [AlexxIT/go2rtc#1528]
Hi,

```
# Restrict API and RTSP to local access only
api:
  listen: 192.168.10.246:1984
  # Add basic authentication
  login: uiyiuyiyu
  password: Ouyi6767!

rtsp:
  listen: 192.168.10.246:8554

# WebRTC needs external access
webrtc:
  candidates:
    - x.x.x.x:8555  # if you have static public IP-address  

streams:
  Sgfde01:
    - rtsp://333:53532@5.185.181.175:4554/Streaming/Channels/301
  Stagfdgfde02:
    - rtsp://444:4353yt34@5.185.181.175:4554/Streaming/Channels/401
```
```
script:
  create_camera_link:
    alias: Create temporary camera link
    sequence:
      - variables:
          link_id: hjhgjhgJTHJTR6345634YrehgEhe

      - service: webrtc.create_link
        data:
          link_id: hjhgjhgJTHJTR6345634YrehgEhe
          url: rtsp://333:53532@5.185.181.175:4554/Streaming/Channels/301

      - service: persistent_notification.create
        data:
          message: '<a href="/webrtc/embed?url={{ hjhgjhgJTHJTR6345634YrehgEhe }}" target="_blank">Open Camera</a>'
```

I've instaled on proxmox ct in docker
app has public ip behind CHR router - port forwarding.
What I'm doing wrong?

In want to publish few cameras on static html page for people so they can watch. (for example malbork's castle and other form Poland)

How can I do this?
