### ISSUE TITLE
Have to manually start the high quality stream.

### ISSUE THREAD

**Issue by illusive-c** [AlexxIT/go2rtc#1545]
Kind of a stupid situation but despite trying for weeks now. I haven't been able to find a solution. 

Here's the situation. I got Reolink WiFi doorbell connected to go2rtc and frigate. I'm using the _low stream to do detection. High stream to record. 

At random intervals(sometimes a day, sometimes a week), the connection to the camera drops and then reconnects. This is not surprising. I'm aware WiFi is not that reliable, and I don't mind losing a couple of minutes of footage every once in a while. 

The problem is, afterwards, go2rtc opens the _low stream back up and Frigate starts processing it but the _high, doesn't come back online. Hence, no recordings in Frigate and tons and tons of messages in the log about stream being corrupted etc. 

The only way to fix this is to go to the go2rtc UI and click the "stream" button next to the _high camera. It takes about 10 seconds the first time I do this. Eventually, the stream starts, and suddenly, Frigate is able to record again. 

It feels like Frigate isn't able to make the go2rtc start streaming automatically. 

As a test, I removed the _low channel and only left the _high in the config and when it's like that, it was working perfectly fine. However, my tablets don't have the juice to display that stream, so I had to add the low quality stream again. 

Here's my config:
```
api:
  origin: '*'
ffmpeg:
  bin: ffmpeg
  volume: -af "volume=5dB"
hass:
  config: /config
log:
  format: text
rtsp:
  default_query: mp4
streams:
  front_door_high:
  - ffmpeg:http://10.0.2.6/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=HomeAssistant&password=PASSWORD#video=copy#audio=copy#audio=opus#backchannel=0
  front_door_low:
  - ffmpeg:http://10.0.2.6/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=HomeAssistant&password=PASSWORD#video=copy#audio=copy#audio=opus#backchannel=0
webrtc:
  candidates:
  - stun:8555

``` 

Just updated to go2rtc version=1.9.8 platform=linux/amd64 revision=199fdd6 but the problem is still there. 

Any help would be appreciated. 

EDIT:

Here are some clarifications and steps to reproduce this issue. 

1)Restart Frigate (this does NOT restart go2rtc in my case. Not sure if that is normal)#
2)Once the Frigate is up and running, the error logs are filled with this:
![image](https://github.com/user-attachments/assets/2f8e622e-2f3b-4c37-9f72-98dd10895cf7)
3)These error messages just keep going, no matter how long I wait. 
4)I check go2rtc UIand this is what I see:
![image](https://github.com/user-attachments/assets/681aa427-53c7-4da6-b5c3-b95e97c1047b)
Note the "0" open stream for the "high" channel. 
5)I click "stream" button on the _high channel. Take about 10 seconds to open the camera. But eventually it opens. 
6)I got back to Frigate and everything is working as expected.
