### ISSUE TITLE
streams: websocket: bad handshake

### ISSUE THREAD

**Issue by MiroG225** [AlexxIT/go2rtc#1548]
after months of use webtorrent I have this error on all three Tapo cameras:

23:18:02.861 ERR github.com/AlexxIT/go2rtc/internal/mp4/mp4.go:107 > error="streams: websocket: bad handshake"

Local streams work fine.

source config:
```
streams:
  chata_door2: 
        - rtsp://aaa:bbb@192.168.45.112:554/stream2

webtorrent:
  shares:
    door-xxxxxx:
      pwd: yyyyyy
      src: chata_door2
``` 
receive config:
```
streams:
  chata_door: 
        - webtorrent:?share=door-xxxxxx&pwd=yyyyyy
```
        
It was working until yesterday. I've change nothing. Using latest version of go2rtc.
Any idea wat's going on? Could be cloudflare issue? But all other cloudflare connections works (even Remote Home-assistant integration)
