### ISSUE TITLE
ffmpeg: unsupported version: 4.3.8-0+deb11u1+rpt1

### ISSUE THREAD

**Issue by jneilliii** [AlexxIT/go2rtc#1556]
Is there a minimum ffmpeg/OS version supported by go2rtc, confused about this error. 

![Image](https://github.com/user-attachments/assets/2472b46d-5dc0-4b1e-89db-7de0598078b2)

10:34:00.911 PM | debug | [ffmpeg] bin version=4.3.8-0+deb11u1+rpt1 libavformat=58. 45.100
10:34:00.911 PM | debug | [mp4] add consumer error=streams: ffmpeg: unsupported version: 4.3.8-0+deb11u1+rpt1
10:34:00.911 PM | debug | [webrtc] add consumer error=streams: ffmpeg: unsupported version: 4.3.8-0+deb11u1+rpt1
10:34:00.919 PM | trace | [api] ws msg type=mjpeg
10:34:00.919 PM | debug | [mjpeg] add consumer error=streams: ffmpeg: unsupported version: 4.3.8-0+deb11u1+rpt1

The USB camera is detected by the add interface and I copied and pasted the example output (tried both).

![Image](https://github.com/user-attachments/assets/6bc81112-6f89-4e62-ae4a-b9f1e63640b2)

```
api:
  origin: '*'
ffmpeg:
  bin: /usr/bin/ffmpeg
streams:
  webcam_yuyv: ffmpeg:device?video=/dev/video0&input_format=yuyv422&video_size=640x480#video=h264#hardware=v4l2m2m
  webcam_mjpeg: 
  ```
