### ISSUE TITLE
Lots of active connections since v0.1-rc.7

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/go2rtc#156]
It seems to just increase over time, endlessly.

https://user-images.githubusercontent.com/29582865/211223101-75512d42-bd83-489e-8d73-83ac7dce7ffb.mp4

**Comment by felipecrs** [comment]
Logs give me this:

![image](https://user-images.githubusercontent.com/29582865/211223140-8370db94-5368-4fc9-9306-b614f688905c.png)

**Comment by NickM-27** [comment]
Interesting, I'm not seeing this personally on my setup

**Comment by felipecrs** [comment]
I guess my logs could help explain why

**Comment by AlexxIT** [comment]
Show your config for problem streams

**Comment by avico78** [comment]
Same here - only one page open for cameras but its shows more online 
+ no audio on webrtc for all cameras

go2rtc 0.1-rc.7 - running on docker 
![image](https://user-images.githubusercontent.com/9049952/211267033-e884cbc5-a157-441f-b70a-ceaf41e88c06.png)

On on
Compose:
```
services:
  go2rtc:
    container_name: go2rtc  
    image: alexxit/go2rtc:3.0-beta.4
    network_mode: host   
    restart: always
    volumes:
      - ./go2rtc.yaml:/config/go2rtc.yaml
```

go2rtc.yaml
```

    
streams:
  salon_ceiling_go2rtc: rtsp://hauser:xxxxxx@192.168.1.138/cam/realmonitor?channel=1&subtype=0
  salon_desk_go2rtc: 
    - rtsp://hauser:xxxxxx@192.168.1.92/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif    
    - ffmpeg:rtsp://hauser:xxxxxx@192.168.1.92/cam/realmonitor?channel=1&subtype=0#audio=opus
  pergula_go2rtc: rtsp://hauser:xxxxxx@192.168.1.200/cam/realmonitor?channel=1&subtype=0
  front_go2rtc: rtsp://hauser:xxxxxx@192.168.1.55/cam/realmonitor?channel=1&subtype=0
  intercom_go2rtc: rtsp://hauser:xxxxxx@192.168.1.110:554/cam/realmonitor?channel=1&subtype=0  

log:
  level: error  # default level
  api: error
  rtsp: error
  streams: error

api:
  listen: ":1984" 

rtsp:
  listen: ":8554" 

webrtc:
  listen: ":8556"  # address of your local server (TCP)
  candidates:
    - stun:8556  # if you have dynamic public IP-address

# not in use currently
ngrok:
  command: ngrok start --all --config ngrok.yaml

````

**Comment by avico78** [comment]
+
```
08:40:30.896 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:51 > error="sdp: invalid value ``" url=rtsp://192.168.1.113:8554/intercom_go2rtc
08:40:30.975 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:51 > error="sdp: invalid value ``" url=rtsp://192.168.1.113:8554/intercom_go2rtc
08:40:30.998 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:51 > error="sdp: invalid value ``" url=rtsp://192.168.1.113:8554/intercom_go2rtc
08:40:31.024 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:51 > error="sdp: invalid value ``" url=rtsp://192.168.1.113:8554/intercom_go2rtc
08:40:31.060 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:51 > error="sdp: invalid value ``" url=rtsp://192.168.1.113:8554/intercom_go2rtc
08:40:31.060 ERR github.com/AlexxIT/go2rtc/cmd/mjpeg/mjpeg.go:120 > error="source 0 error: sdp: invalid value ``"

```

**Comment by felipecrs** [comment]
Here is my config:

```
webrtc:
  listen: ":8555"
  candidates:
    - 192.168.1.10:8555
    - stun:8555

# log:
#   level: debug
#   api: debug
#   exec: debug
#   ngrok: debug
#   rtsp: debug
#   streams: debug
#   webrtc: debug

streams:
  rua_hd_aac:
    - ffmpeg:rtsp://192.168.1.33:554/0/av0#video=copy#audio=aac
  camera.rua:
    - rtsp://192.168.1.33:554/0/av1
    # - rtsp://localhost:8554/rua_hd_aac?audio=aac
    - ffmpeg:camera.rua#audio=aac
  camera.morro:
    - rtsp://192.168.1.34:6554/stream_1
    - ffmpeg:camera.morro#audio=aac
  camera.portao:
    - rtsp://192.168.1.32:6554/stream_1
    - ffmpeg:camera.portao#audio=aac
  camera.terreiro:
    - rtsp://192.168.1.31:6554/stream_1
    - ffmpeg:camera.terreiro#audio=aac
  video_porteiro_hd_aac:
    - ffmpeg:rtsp://192.168.1.40/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif#video=copy#audio=aac
  camera.video_porteiro:
    - rtsp://192.168.1.40/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    - ffmpeg:camera.video_porteiro#audio=aac
```
