### ISSUE TITLE
Hardware encoding seems to wipe off the timestamp

### ISSUE THREAD

**Issue by SkyWriter** [AlexxIT/go2rtc#1564]
Thank you for the wonderful product! I've spent hours fighting ffmpeg before I was able to find a turnkey go2rtc solution.

I am however experiencing some issues while trying to replicate my setup: have both hardware accelerated encoding and add a timestamp to the video. Performance is a non-issue for me, since I am transcoding a webcam stream into H264 anyway.

I am using `go2rtc version 1.9.7 () linux/amd64`.

Here's the setup that works:

```
streams:
  linux_usbcam: ffmpeg:device?input_format=yuyv422&framerate=20&video_size=800x600&video=/dev/video0#raw=timestamp#video=h264

ffmpeg:
  timestamp: "-vf \"drawtext=fontfile=DroidSansMono.ttf: text='%{localtime}': x=w-tw-10: y=h-(2*lh): fontcolor=white: box=1: boxcolor=0x00000099\"" 
```

Here's the setup that doesn't (note the `#hardware` thing):

```
streams:
  linux_usbcam: ffmpeg:device?input_format=yuyv422&framerate=20&video_size=800x600&video=/dev/video0#raw=timestamp#video=h264#hardware

ffmpeg:
  timestamp: "-vf \"drawtext=fontfile=DroidSansMono.ttf: text='%{localtime}': x=w-tw-10: y=h-(2*lh): fontcolor=white: box=1: boxcolor=0x00000099\"" 
```

Changing the order to `#video=h264#hardware#raw=timestamp` doesn't seem to fix anything.

I suspect this is due to the way go2rtc calls ffmpeg:

```
DBG [exec] run rtsp args=["ffmpeg","-hide_banner","-v","error","-hwaccel","vaapi","-hwaccel_output_format","vaapi","-hwaccel_flags","allow_profile_mismatch","-f","v4l2","-input_format","yuyv422","-framerate","20","-video_size","800x600","-i","/dev/video0","-vf","drawtext=fontfile=DroidSansMono.ttf: text='%{localtime}': x=w-tw-10: y=h-(2*lh): fontcolor=white: box=1: boxcolor=0x00000099","-c:v","h264_vaapi","-g","50","-bf","0","-profile:v","high","-level:v","4.1","-sei:v","0","-an","-vf","format=vaapi|nv12,hwupload,scale_vaapi=out_color_matrix=bt709:out_range=tv:format=nv12","-user_agent","ffmpeg/go2rtc","-rtsp_transport","tcp","-f","rtsp","rtsp://127.0.0.1:8554/b49cff100b545443b381c966c660abb9"]
```

Making this ffmpeg call more verbose reveals that only the last `-vf` gets used, so that my drawing code is ignored:

```
Multiple -filter/-af/-vf options specified for stream 0, only the last option '-filter:v format=vaapi|nv12,hwupload,scale_vaapi=out_color_matrix=bt709:out_range=tv:format=nv12' will be used.
```

Is that a bug or am I doing something wrong? Please advise.
