### ISSUE TITLE
why transcode audio to aac is not working?

### ISSUE THREAD

**Issue by latel** [AlexxIT/go2rtc#1566]
1. why transcode audio to aac is not working?
2. why there is a `method SETUP failed: 461 Unsupported transport` error log in ffprobe, which also can see in scrypted logs.

Thank you.

go2rtc
```
log:
  level: debug
  
api:
  listen: ":1984"    # default ":1984", HTTP API port ("" - disabled)

rtsp:
  listen: ":8554"    # RTSP Server TCP port, default - 8554
  default_query: "audio&video"  # optional, default codecs filters ?audio

streams:
  tapo_c120: 
    - rtsp://admin_tapo:xxxxx@10.10.10.1/stream1
    - "ffmpeg:tapo_c120#audio=aac"
```

```bash
ffprobe rtsp://10.10.10.11:9554/tapo_c120                 
ffprobe version 7.1 Copyright (c) 2007-2024 the FFmpeg developers
  built with Apple clang version 16.0.0 (clang-1600.0.26.4)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1_3 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
[rtsp @ 0x153b053b0] method SETUP failed: 461 Unsupported transport
Input #0, rtsp, from 'rtsp://10.10.10.11:9554/tapo_c120':
  Metadata:
    title           : go2rtc/1.9.8
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
  Stream #0:1: Video: h264 (High), yuv420p(progressive), 2560x1440, 20 fps, 20 tbr, 90k tbn
```
