### ISSUE TITLE
YouTube Streaming not work

### ISSUE THREAD

**Issue by Loafter** [AlexxIT/go2rtc#1574]
So i followed manual fill config file.
And this is not work, i don't see any evidence that something trying start publishing to youtube server.
i try open fixed stream (Parking_transcode) with aac codec and it's work normal i check it in VLC player.

```
streams:
  Dacha_Basement:
    - rtsp://192.168.3.2:554/11#timeout=10
  Dacha_Kitchen:
    -  rtsp://192.168.3.33:554/user=admin_password=LFjb3Dxx_channel=0_stream=0&protocol=unicast&onvif=ture.sdp?real_stream#timeout=10
  Dacha_Road:
    - rtsp://192.168.3.130:554/11#timeout=10
  Dacha_Heater:
    - rtsp://192.168.3.133:554/user=admin_password=LFjb3Dxx_channel=0_stream=0&protocol=unicast&onvif=ture.sdp?real_stream#timeout=10
  Dacha_Rehab:
    - rtsp://192.168.3.12:554/user=admin_password=LFjb3Dxx_channel=0_stream=0&protocol=unicast&onvif=ture.sdp?real_stream#timeout=10
  Moscow_Garage:
    - rtsp://192.168.6.4:554/11#timeout=10
  Moscow_Caricino:
    - rtsp://192.168.7.179:554/user=admin_password=LFjb3Dxx_channel=0_stream=0&protocol=unicast&onvif=ture.sdp?real_stream#timeout=10
  Pro_Kitchen:
    - rtsp://192.168.2.145:554/user=admin_password=LFjb3Dxx_channel=0_stream=0&protocol=unicast&onvif=ture.sdp?real_stream#timeout=10
  Pyat_Сourtyard:
    - rtsp://192.168.8.95:554/11#timeout=10
  Pyat_Kitchen:
    - rtsp://192.168.8.61:554/user=admin_password=LFjb3Dxx_channel=0_stream=0&protocol=unicast&onvif=ture.sdp?real_stream#timeout=10
  Pro_Parking:
    - rtsp://192.168.2.15:554/11#timeout=10
  Dacha_4K_Garden:
    - rtsp://192.168.3.41:554/stream0#timeout=30
  Dacha_Heater_Low:
    - rtsp://192.168.3.133:554/user=admin_password=LFjb3Dxx_channel=0_stream=1&protocol=unicast&onvif=ture.sdp?real_stream#timeout=10
  Dacha_Basement_Low:
    - rtsp://192.168.3.2:554/22#timeout=10
  Pro_Parking_Low:
    - rtsp://192.168.2.15:554/22#timeout=10
  Parking_transcode:
    - ffmpeg:rtsp://192.168.2.15:554/11#video=copy#audio=aac
publish:
    Parking_transcode:
    - rtmp://a.rtmp.youtube.com/live2/tcjb-xxxx-yfx8-wd2a-b1km
webrtc:
  ice_servers:
    - urls: [stun:stun.l.google.com:19302]
```

**Comment by AlexxIT** [comment]
You haven't provide go2rtc version. And any info about "Parking_transcode" stream. Codecs, etc.

**Comment by Loafter** [comment]
> You haven't provide go2rtc version. And any info about "Parking_transcode" stream. Codecs, etc.

Of course, Sorry
Version: 1.9.8, Docker enviroment on OpenWrt.

![Image](https://github.com/user-attachments/assets/492bd3a7-f8b3-4965-a251-93b8a3c902dc)

**Comment by Loafter** [comment]
And after audio conversion

![Image](https://github.com/user-attachments/assets/722de6bc-f9f0-44a0-91de-680693b44f4e)

**Comment by AlexxIT** [comment]
Codecs are fine. I need to check the same situation.

**Comment by delgado23** [comment]
I am seeing the same thing. 

Version: 1.9.8

Config:
streams:
  weather: rtsp://e0Ed0Kccc5TM:z2uhaehxxxxy@10.248.1.3/live0
publish:
  weather: rtmp://a.rtmp.youtube.com/live2/21m8-m9xb-fpx9-xxx-xxx

I believe my codecs 
![Image](https://github.com/user-attachments/assets/f9cead0b-e92e-4936-9d18-d4a7599edf15)

Please let me know if you need anymore information.

**Comment by delgado23** [comment]
I downgraded to version 1.9.2 and streaming started working again with the same config. I just figured I would provide that information.

**Comment by Tester798** [comment]
RTMP publish doesn't work for me too, starting from 1.8.0 and up to the latest 1.9.8.
Tried with twitch and vkvideo.
In CurrPorts I can see the connection to the RTMP server appears for a second, and then disappears.
On vkvideo in streaming panel I notice "Live" icon and buffering starts for a moment, but then stream goes "Offline" again.


Also noticed that if I launch go2rtc before I start streaming to it in OBS, I'm getting this error and then publish isn't working at all:
![Image](https://github.com/user-attachments/assets/61d40c31-a2bc-45f5-bbb1-1f58d0dd1b86)


My config looks like this:
```
log:
  level: trace

rtsp:
  listen: ""

api:
  listen: ""

webrtc:
  listen: ""

rtmp:
  listen: "127.0.0.1:1935"

publish:
  test:
    - rtmp://ingest.global-contribute.live-video.net/app/live_xxxxxxxx

streams:
  test:
```
