### ISSUE TITLE
Unable to re-encode videos with ffmpeg and get smooth playback in go2rtc

### ISSUE THREAD

**Issue by blakeblackshear** [AlexxIT/go2rtc#1579]
I can't figure out how to generate an mp4 video that plays nicely with go2rtc.

I download the Big Buck Bunny video from here: http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

I run the following to download and use ffmpeg to re-encode the first 60 seconds of the video to a frame rate of 10:
```shell
mkdir videos && cd videos
wget -O BigBuckBunny.mp4 http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4 
ffmpeg -i BigBuckBunny.mp4 -t 60 -r 10 BigBuckBunny_reencoded.mp4
cd ..
```

go2rtc.yaml
```yaml
ffmpeg:
  file: "-re -stream_loop -1 -i {input}"
streams:
  bunny: ffmpeg:/videos/BigBuckBunny.mp4
  bunny_re: ffmpeg:/videos/BigBuckBunny_reencoded.mp4
```

Docker run command
```
docker run --rm -v ${PWD}/go2rtc.yaml:/config/go2rtc.yaml --network host -v ${PWD}/videos/:/videos alexxit/go2rtc
```

I have tried many different encoding options and nothing seems to help.
