### ISSUE TITLE
Network view error

### ISSUE THREAD

**Issue by maksz42** [AlexxIT/go2rtc#1603]
Sometimes, the network view for one of my cameras and the whole network doesn't work:
go2rtc 1.9.8
`http://frigate:1984/network.html?src=cam-p-g`
```
03:06:40.945 Error fetching or updating network data: SyntaxError: Syntax error in part "|nv12,hwupload,scale_vaapi=..."
    Kv dotparser.js:449
    $v dotparser.js:1054
    Xv dotparser.js:673
    Xv dotparser.js:564
    Hv dotparser.js:517
    Nv dotparser.js:488
    Nv dotparser.js:43
    Cy dotparser.js:1445
    update network.html:51
network.html:70:25
```
the response:
```
digraph {
192.168.3.205 [group=host];
73 [group=producer, label="dvrip", title="format_name=dvrip\nprotocol=tcp"];
192.168.3.205 -> 73 [label="0 B"];
73 -> 120 [label="89.85 MB"];
120 [group=node, label="hevc", title="codec_name=hevc"];
73 -> 121 [label="5.72 MB"];
121 [group=node, label="pcm_alaw", title="codec_name=pcm_alaw\nsample_rate=8000"];
127.0.0.1 [group=host];
862 [group=producer, label="rtsp", title="format_name=rtsp\nprotocol=rtsp+tcp\nsource=exec:/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_flags allow_profile_mismatch -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/cam-p-g?video&audio&source=ffmpeg:cam-p-g%23video%3Dh264%23hardware%23audio%3Dopus%23audio%3Daac -map 0:v:0? -c:v:0 h264_vaapi -g 50 -bf 0 -profile:v:0 high -level:v:0 4.1 -sei:v:0 0 -map 0:a:0? -c:a:0 libopus -application:a:0 lowdelay -min_comp 0 -map 0:a:0? -c:a:1 aac -vf \"format=vaapi|nv12,hwupload,scale_vaapi=out_color_matrix=bt709:out_range=tv:format=nv12\" -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/dfa9258a4c39c06558948ec3ab9b23cd\nurl=rtsp://127.0.0.1:8554/cam-p-g?video&audio&source=ffmpeg:cam-p-g%23video%3Dh264%23hardware%23audio%3Dopus%23audio%3Daac\nuser_agent=ffmpeg/go2rtc"];
127.0.0.1 -> 862 [label="100.85 MB"];
862 -> 863 [label="96.54 MB"];
863 [group=node, label="h264", title="codec_name=h264\nprofile=High\nlevel=41"];
862 -> 864 [label="2.32 MB"];
864 [group=node, label="opus", title="codec_name=opus\nsample_rate=48000\nchannels=2"];
862 -> 865 [label="974.03 KB"];
865 [group=node, label="aac", title="codec_name=aac\nsample_rate=8000"];
127.0.0.1 [group=host];
72 [group=consumer, label="rtsp", title="format_name=rtsp\nprotocol=rtsp+tcp\nuser_agent=FFmpeg Frigate/0.15.0-cea210d"];
72 -> 127.0.0.1 [label="92.45 MB"];
120 -> 72 [label="89.85 MB"];
865 -> 72 [label="2.21 MB"];
127.0.0.1 [group=host];
859 [group=consumer, label="rtsp", title="format_name=rtsp\nprotocol=rtsp+tcp\nsource=ffmpeg:cam-p-g#video=h264#hardware#audio=opus#audio=aac\nuser_agent=go2rtc/ffmpeg"];
859 -> 127.0.0.1 [label="42.35 MB"];
120 -> 859 [label="39.18 MB"];
121 -> 859 [label="2.51 MB"];
}
```
My config:
```
rtsp:
  username: user
  password: password
  default_query: mp4
webrtc:
  candidates:
  - 192.168.1.10:8555
  - stun:8555
  listen: :8555
streams:
  cam-p-p:
  - dvrip://admin:admin@cam-p-p
  - ffmpeg:cam-p-p#audio=opus#audio=aac
  cam-p-l:
  - dvrip://admin:admin@cam-p-l
  - ffmpeg:cam-p-l#audio=opus#audio=aac
  cam-ul-p:
  - dvrip://admin:admin@cam-ul-p
  - ffmpeg:cam-ul-p#audio=opus#audio=aac
  cam-ul-l:
  - dvrip://admin:admin@cam-ul-l
  - ffmpeg:cam-ul-l#audio=opus#audio=aac
  cam-ul-f:
  - dvrip://admin:admin@cam-ul-f
  - ffmpeg:cam-ul-f#audio=opus#audio=aac
  cam-p-g:
  - dvrip://admin:admin@cam-p-g
  - ffmpeg:cam-p-g#video=h264#hardware#audio=opus#audio=aac
  cam-p-g_sub:
  - dvrip://admin:admin@cam-p-g?subtype=1

api:
  origin: '*'
hass:
  config: /config
log:
  format: text
ffmpeg:
  bin: /usr/lib/ffmpeg/7.0/bin/ffmpeg
```
