### ISSUE TITLE
Can't get camera from vacuum bot to work in go2rtc

### ISSUE THREAD

**Issue by incline02** [AlexxIT/go2rtc#1615]
Hi Alex

This is a peculiar case. I'll try to be as considerate of your time as possible. (HAOS on a rasp 5, 8go)

I own a vacuum bot which thanks to an integration (from @Tesshack' dreame) exposes the map render of my home as a camera entity. I'm trying to achieve this: Get that feed into homekit:

`Vacuum bot camera entity -> Homekit Bridge -> Homekit`

Didn't work of course so I went with:

`Vacuum bot camera entity -> camera proxy -> Go2RTC -> Homekit Bridge -> Homekit`

same result in homekit: displays a snapshot every ten seconds but when I tap into it, keeps on loading. however, the orignal entity displays correctly in HAOS, dashboard, as well as the proxy

From Go2RTC onwards, problem arises

here's my full config: 

```
streams:
  camera_dynamic:
  - http://192.168.1.157:8123/api/camera_proxy/camera.camera_proxy?token=temporary token from bot
```

Issues:
1. Any codec sources
- original stream.html works
- none of the "Any codec" work. the RTSP gives an error in VLC

> Your input can't be opened
> VLC is unable to open the MRL 'rtsp://homeassistant.local:8554/camera_dynamic'. Check the log for details.

2. none of "H264/265" sources link work. Same error in VLC
3. MJPEG sources
- stream.html works (safari)
- stream.mjpeg shows a bunch of characters which I assume are simply not for safari and frame.jpeg works (safari)
- frame.jpeg works (safari)

My attempts to stream from there to homekit (All Failed):
1. To use generic camera with MPJPEG's stream.html and frame.jpeg as feed and still image. Either / both / swapped
- via the UI, fails by timeout when looking for the stream or can't find a still image in the still image url
- via the config file, shows as unavailable
2. To use MJPEG IP Camera
- requires username and password for the camera, somehow. but wether it's the direct url to the proxy or links via go2rtc, I don't have any credentials since I shouldn't need any
3. with/without ffmpeg in go2rtc file (many combinations of extra args)
4. with/without ffmpeg in HAOS config file (many combinations of extra args)
5. any combination of 1, 2, 3, 4

6. the following gives me gives an error whilst watching farm go2rtc but after 3 seconds which I assume is the refresh rate, indeed displays the map with "MJPEG in the upper right corner

```
streams:
  camera_dynamic:
  - http://192.168.1.157:8123/api/camera_proxy/camera.camera_proxy?token=10c89c4a9581cbde3c703c4f1b3207ba6019c765cd84b9d7615bf82b581a0571
  - "ffmpeg:camera_dynamic#video=h264#hardware"
```
All the above result in homekit not streaming properly as explained above.

7. I also tried to import the source of camera proxy directly from hass but I get a mse: streams: has: wrong response:
```
hass:
  config: "/config"
streams:
  camera_dynamic:
  - http://192.168.1.157:8123/api/camera_proxy/camera.camera_proxy?token=9e6883b824ac44de4b1c9619aed8d2b8447497da98d5cab4e7c6d715b689a459
  camera_hass_bot:
  - hass://192.168.1.157:8123?entity_id=camera.bot_map&token=longlive token
  camera_hass_proxy:
  - hass://192.168.1.157:8123?entity_id=camera.camera_proxy&token=longlive token
```

I've been at this since September with no success., combed through a lot, for exemple that despite the fact the vacuum exposes a camera, the nature of the feed is MJEPG. That I need to use ffmpeg to convert that feed into something I can use to create the right entity that I can use in homekit. Nothing works, can you advise?

I'll be very much thankful for any help.

**Comment by AlexxIT** [comment]
Vacuum cleaner maps in HA, it's always a MJPEG stream. You needs to transcode it to H264.

```yaml
streams:
  v1:
  - http://192.168.1.157:8123/api/camera_proxy/camera.camera_proxy?token=...
  - "ffmpeg:v1#video=h264#hardware"
  v2:
  - ffmpeg:http://192.168.1.157:8123/api/camera_proxy/camera.camera_proxy?token=...#video=h264

homekit:
  v1:
  v2:
```

**Comment by incline02** [comment]
many thanks for the help. I have now the camera exposed to homekit but same issue still:

The preview works, the stream itself when going full screen loads and fails.

```
homekit:
  camera_dynamic:
    device_id: camera_dynamic
    device_private: device_private_key
    name: camera_dynamic
    pairings:
      - client_id=8AFBEDAE-F820-492B-8BAA-0405A3262331&client_public=df2ce8a56d0583d7dd1eb20ebc29d7cb4cde1cc48e5f8d557465806016a18940&permissions=1
    pin: '12345678'
streams:
  camera_dynamic:
  - http://192.168.1.157:8123/api/camera_proxy/camera.camera_proxy?token=
  - ffmpeg:camera_dynamic#video=h264

```

here's what net shows:

<img width="1030" alt="Image" src="https://github.com/user-attachments/assets/8616fb0e-623c-43f5-91a8-7b79e314a76e" />

with occasion error message but I'm unable to pin down the trigger:
undefined error=write tcp homeassitIP:1984->iphoneIP:53397: use of closed network connection caller=github.com/AlexxIT/go2rtc/internal/homekit/homekit.go:185
