### ISSUE TITLE
HomeAssistant add-on : undefined error=EOF

### ISSUE THREAD

**Issue by EnviLine** [AlexxIT/go2rtc#1618]
Добрый день

Уже некоторое время мучает ошибка 

`3:16:05.439 PM	warn	undefined error=EOF url=ffmpeg:aqara_g2hPro_spalna#audio=aac#audio=opus caller=github.com/AlexxIT/go2rtc/internal/streams/producer.go:170
`

И аналогичные для остальных камер.
Использую 3 камеры aqara g2h и g2h_pro . Привеязаны к HomeAssistant через HomeKit Bridge из HA в go2rtc 
И далее в Scripted -> HomeKit  с поддержкой HKSV 

Вот конфигурация:

```
streams:
  aqara_g2h_zal: 
    - hass:Camera-Hub-G2H-3767
    - ffmpeg:aqara_g2h_zal#audio=aac#audio=opus
  aqara_g2hPro_spalna:
    - hass:Camera-Hub-G2HPro-837C
    - ffmpeg:aqara_g2hPro_spalna#audio=aac#audio=opus
  aqara_g2hPro_ulitsa:
    - hass:Camera-Hub-G2HPro-5737
    - ffmpeg:aqara_g2hPro_ulitsa#audio=aac#audio=opus

rtsp:
  listen: ":8554"    # RTSP Server TCP port, default - 8554
  username: "****" 
  password: "****" 
```

Пробовал на master и 1.9.8

Если честно, то не знаю куда думать.
Может ли это быть как-то связано с памятью? Так как заметил при приближении к 21% занятости диска появляется ошибка
