### ISSUE TITLE
HomeAssistant OS add-on: undefined error=EOF

### ISSUE THREAD

**Issue by EnviLine** [AlexxIT/go2rtc#1619]
Hi

I'm struggling with this error for some time

`3:16:05.439 PM	warn	undefined error=EOF url=ffmpeg:aqara_g2hPro_spalna#audio=aac#audio=opus caller=github.com/AlexxIT/go2rtc/internal/streams/producer.go:170 `

Same for other cameras
I have 3 of aqara g2h and g2h_pro. Paired through HomeAssistant HomeKit Bridge -> go2rtc
And after that to Scrypted -> HomeKit Secure Video

My config:

```
streams:
  aqara_g2h_zal: 
    - hass:Camera-Hub-G2H-3767
    - ffmpeg:aqara_g2h_zal#audio=aac#audio=opus
  aqara_g2hPro_spalna:
    - hass:Camera-Hub-G2HPro-837C
    - ffmpeg:aqara_g2hPro_spalna#audio=aac#audio=opus
  aqara_g2hPro_ulitsa:
    - hass:Camera-Hub-G2HPro-5737
    - ffmpeg:aqara_g2hPro_ulitsa#audio=aac#audio=opus

rtsp:
  listen: ":8554"    # RTSP Server TCP port, default - 8554
  username: "****" 
  password: "****" 
```
Tested on master and 1.9.8

Don't even know what to think.
I've been trying on different versions of HomeAssistant but looks like it doesn't matter.
Addon works correctly till some time. 
Recently I have done no updates and it just stops working.
Problem persists after add-on or HomeAssistant reload and only way to fix it for some time is to reload my raspberry Pi completely.

Could it be related to memory? Because I found that it starts failing near 21% of disk usage.
Addon is installed on HomeAssistant OS 

Maybe you could tell what could cause this exception?
