### ISSUE TITLE
Nest source error: webrtc/offer: streams: nest: wrong query

### ISSUE THREAD

**Issue by dannytrigo** [AlexxIT/go2rtc#1621]
When I try to set up a go2rtc stream from a Nest source I get the following error when trying to view the stream:
```
webrtc/offer: streams: nest: wrong query
```

If I try to add Nest through the UI I get a 404 with `no sources` in the UI.

However, I've written my own python script which successfully lists the devices, gets the srtsp URL from google, and can add that URL manually into go2rtc and it works, so I am sure all my parameters are correct.

Do you have any idea what might be the issue?

I'm using version 1.9.2 and it is embedded in Frigate.

**Comment by dannytrigo** [comment]
I think I was missing the `?` after `nest:`, however, correcting that I still get: `webrtc/offer: streams: nest: wrong status: 400 Bad Request`.

And that doesn't apply to adding the Nest details through the UI.

I've tried with 1.9.8 with the same results.

**Comment by AlexxIT** [comment]
You haven't shown your config

**Comment by dannytrigo** [comment]
Here's the go2rtc config part of my Frigate config, with some parts of the sensitive fields masked:

```
go2rtc:
  log:
    level: trace
  streams:
    front_door:
      - rtsp://neolink:8554/front_door/main
    front_door_sub:
      - rtsp://neolink:8554/front_door/sub

    bbq_one:
      - rtsp://wb:mIWU67qaEm5W5hohnUau866EdfngnvhZFfqALjsK@wyze-bridge:8554/bbq-cam-1
    bbq_two:
      - rtsp://wb:mIWU67qaEm5W5hohnUau866EdfngnvhZFfqALjsK@wyze-bridge:8554/bbq-cam-2

    pool:
      - nest:?client_id=***.apps.googleusercontent.com&client_secret=GOCSPX-***_s&refresh_token=1//05oTMT****USNwF-L9IrHCJ******-_rbqG****_zkE*****Q&project_id=879fe9d3-4aa4-4d12-bf63-********&device_id=AVPHw****-Bfh8****N3j_JN-zLGtzUVBGmZ****2ImvoTQ

```

It is the pool camera that gives the above errors. But also just trying to add a Nest source through the UI doesn't work either, which I don't think should need config?
