### ISSUE TITLE
Known problem: Frigate fails to start stream

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/go2rtc#1633]
This usually happens when you use ffmpeg source for the camera.

```yaml
go2rtc:
  streams:
    camera: ffmpeg:rtsp://...
```

FFmpeg adds an extra delay for the first start of the stream. For some cameras the stream start can be 1 second, for some cameras it can be more than 5 seconds. Frigate by default uses a timeout of 5 seconds and drops the connection without waiting for a response from go2rtc.
