### ISSUE TITLE
Aqara Camera Integration Problems. Any help would be appreciated

### ISSUE THREAD

**Issue by umumumu** [AlexxIT/go2rtc#1637]
Hey guys,

I have an Aqara G2H Pro camera. This is what I've done so far:

- Unpaired from Apple Home
- Paired with Home Assistant through Homekit Device Integration
- Every function of the camera and sub-devices are working except the video on the camera
- Installed go2rtc and tried to integrate it via config.
- When I click "stream" on web UI, only black screen with MSE on top right.
- Noticed when I click "stream", go2rtc crashes and it asks me to start the addon again.

What is the problem here?

My config looks like this:
```
hass:
  config: /config
  
streams:
  Camera_1:
    - hass:Camera-Hub-G2HPro-1D5C
    - ffmpeg:Camera_1#audio=aac#audio=opus
```
I would take any help. Thanks in advance!
