### ISSUE TITLE
Transcoding to AAC yields a muted audio track since 1.9.3

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/go2rtc#1643]
This issue may be related to https://github.com/AlexxIT/go2rtc/issues/530 and https://github.com/AlexxIT/go2rtc/issues/1505.

I tested with go2rtc 1.9.9 but I am sure it was already happening before.

Here's how I can repro it:

```yaml
streams:
    rua:
      # H264, PCMA/8000
      - rtsp://192.168.1.33/0/av1
      - ffmpeg:rua#audio=aac
```

1. Start go2rtc with the config above. Audio from camera is PCMA.
2. Play in VLC `rtsp://127.0.0.1:8554/rua?video&audio=pcma`, confirm audio is OK.
3. Play in VLC `rtsp://127.0.0.1:8554/rua?video&audio=pcma`, confirm audio is NOT OK, blank/muted, but there is an AAC/8000 audio track.

The workaround I found was:

```yaml
streams:
    rua:
      - ffmpeg:rtsp://192.168.1.33/0/av1#video=copy#audio=copy#audio=aac
```

But I believe it was supposed to work without this, no?

Please let me know if I can do anything to help debug this. I can share the camera's stream.

**Comment by felipecrs** [comment]
The issue only seems to happen when transcoding to AAC. This does not happen when transcoding to OPUS.

**Comment by felipecrs** [comment]
Just because I was curious, I also tested https://github.com/AlexxIT/go2rtc/pull/1431 against this issue and it didn't help, meaning it's not related.

**Comment by felipecrs** [comment]
Another note is that this issue happens with different cameras. I have to apply the workaround to multiple cameras I have.

**Comment by felipecrs** [comment]
@AlexxIT I found that this broke in 1.9.3. With 1.9.2 I can no longer reproduce it.

**Comment by felipecrs** [comment]
There were a lot of commits...

https://github.com/AlexxIT/go2rtc/compare/v1.9.2...v1.9.3

If you suspect of some commit in particular, please let me know and I can try compiling go2rtc 1.9.3 reverting such commit.

**Comment by felipecrs** [comment]
I tried reverting:

- https://github.com/AlexxIT/go2rtc/commit/78a74da8d6caf6ade3fb63a0fce2d9b62bfb60d0
- https://github.com/AlexxIT/go2rtc/commit/d2346a2aed9519c80d76e814a172dd732c545f1d

None worked, yet.

This one:

* https://github.com/AlexxIT/go2rtc/commit/c41bddbbea59c115afbff1ed697ace11bd275c21

Is more complicated because it caused conflict.

**Comment by felipecrs** [comment]
Found out!!!

- https://github.com/AlexxIT/go2rtc/commit/6d9c7012b012edf2dcb18c01184bd87bb5ca0510

Is causing this issue. Reverting it restores the functionality.

@AlexxIT can you take it now? I don't understand this flag enough.

**Comment by felipecrs** [comment]
For reference this is my patch:

```diff
diff --git a/internal/ffmpeg/ffmpeg.go b/internal/ffmpeg/ffmpeg.go
index 25d61e4..0fe0e4c 100644
--- a/internal/ffmpeg/ffmpeg.go
+++ b/internal/ffmpeg/ffmpeg.go
@@ -72,7 +72,6 @@ var defaults = map[string]string{
 	"output":       "-user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp {output}",
 	"output/mjpeg": "-f mjpeg -",
 	"output/raw":   "-f yuv4mpegpipe -",
-	"output/aac":   "-f adts -",
 	"output/wav":   "-f wav -",
 
 	// `-preset superfast` - we can't use ultrafast because it doesn't support `-profile main -level 4.1`
@@ -367,9 +366,8 @@ func parseArgs(s string) *ffmpeg.Args {
 			args.Output = defaults["output/raw"]
 		}
 	case args.Video == 0 && args.Audio == 1:
-		switch core.Before(query.Get("audio"), "/") {
-		case "aac":
-			args.Output = defaults["output/aac"]
+		codec, _, _ := strings.Cut(query.Get("audio"), "/")
+		switch codec {
 		case "pcma", "pcmu", "pcml":
 			args.Output = defaults["output/wav"]
 		}

```

It works even applying on top of 1.9.9.

**Comment by AlexxIT** [comment]
Maybe related - https://github.com/AlexxIT/go2rtc/issues/1779

**Comment by felipecrs** [comment]
Just FYI: I can still reproduce this issue with go2rtc 1.9.12 and FFmpeg 8.0.0.

In my opinion this is the most serious issue in go2rtc, especially for Frigate users like me. :(

**Comment by felipecrs** [comment]
This suggestion worked for me:

- https://github.com/AlexxIT/go2rtc/issues/856#issuecomment-3448711530

It's the cleanest workaround for now. Thanks a lot, @seydx!

---

@AlexxIT, a nitpick: README says you can override any built-in preset:

> <img width="1246" height="456" alt="Image" src="https://github.com/user-attachments/assets/f040bfe7-4753-4fab-b054-4c24d5c1ae97" />

But this doesn't work:

```yaml
ffmpeg:
  aac: -af aformat=sample_fmts=s16:sample_rates=44100:channel_layouts=stereo -c:a aac

streams:
  test:
    - rtsp://192.168.1.33/0/av1
    - ffmpeg:test#audio=aac
```

While this does:

```yaml
ffmpeg:
  aac_fix: -af aformat=sample_fmts=s16:sample_rates=44100:channel_layouts=stereo -c:a aac

streams:
  test:
    - rtsp://192.168.1.33/0/av1
    - ffmpeg:test#audio=aac_fix
```

**Comment by AlexxIT** [comment]
I can't confirm your words
```yaml
ffmpeg:
  aac: -af aformat=sample_fmts=s16:sample_rates=44100:channel_layouts=stereo -c:a aac

streams:
  tmp1: ffmpeg:c:\Media\bbb.mp4#video=h264#audio=aac
```

```
10:52:22.672 DBG [exec] run rtsp args=["ffmpeg","-hide_banner","-v","error","-readrate_initial_burst","0.001","-re","-i","c:\\Media\\bbb.mp4","-c:v","libx264","-g","50","-profile:v","high","-level:v","4.1","-preset:v","superfast","-tune:v","zerolatency","-pix_fmt:v","yuv420p","-af","aformat=sample_fmts=s16:sample_rates=44100:channel_layouts=stereo","-c:a","aac","-user_agent","ffmpeg/go2rtc","-rtsp_transport","tcp","-f","rtsp","rtsp://127.0.0.1:8554/f1aa11c42e6ef24acdadb553a4d42437"]
```
