### ISSUE TITLE
Can go2rtc Configuration Be Stored in a Database Instead of go2rtc.yaml?

### ISSUE THREAD

**Issue by techsupportsardonyx** [AlexxIT/go2rtc#1653]
I am trying to integrate go2rtc with a database where stream configurations (such as stream_name, stream_url) are stored and managed dynamically. Currently, go2rtc requires the configuration to be manually stored in the go2rtc.yaml file, but I would like to store this configuration in a database and dynamically add or remove streams.

**Is there a way to:**

1. Store go2rtc configuration data (like stream settings) in a database (e.g., SQLite, MySQL)?
2. Dynamically generate or update the go2rtc.yaml file from the database, based on added or removed streams?
3. Automate this process, so changes to the database are reflected in the go2rtc.yaml file without manual edits?

**Comment by vegalou** [comment]
Seems same requirement just issued one day ago for playback & easy configuration.

As I know, it's a realized feature somewhere. 😁 `runOnDemand + RegEx`

https://github.com/AlexxIT/go2rtc/issues/1650

@techsupportsardonyx

**Comment by AlexxIT** [comment]
Check available API https://github.com/AlexxIT/go2rtc/tree/master/api

**Comment by copbr** [comment]
The GO2RTC API does work for this, but I have identified a problem.
When I send multiple add requests for new streams (I tried with 24), the API corrupts the configuration file.
I believe this is a BUG.

**Comment by AlexxIT** [comment]
Yes. This can be a bug. You can create another issue with examples of your config before "bad" API call.
Also check go2rtc version, v1.9.9 has a fix about this problem.

**Comment by techsupportsardonyx** [comment]
```
streams:
  test:
    - rtsp://admin:Admin123@172.25.3.30/cam/realmonitor?channel=1&subtype=0
  test1:
    - rtsp://admin:Admin123@172.25.3.30/cam/realmonitor?channel=1&subtype=0
  test2:
    - rtsp://admin:admin123@172.25.10.34/cam/realmonitor?channel=1&subtype=0
```

The RTSP URL for go2rtc is currently stored in the go2rtc.yaml file, but I would like to store this configuration in a database instead (e.g., SQLite or MySQL).
