### ISSUE TITLE
Allow adding delay (`-ss`) to `/api/frame.jpeg` to avoid frames being dark

### ISSUE THREAD

**Issue by nadiamoe** [AlexxIT/go2rtc#1657]
Heyo!

I've been a happy user of go2rtc for quite a long time, and I'd like to suggest a feature that I think could be useful to me and others.

I use go2rtc to expose a USB-connected webcam to my LAN. My config looks like this:
```yaml
streams:
  webcam:
    - "ffmpeg:device?video=/dev/video0&input_format=h264&video_size=1920x1080&rotate=180"
```

My webcam happens to support sourcing h264 video directly from the hardware, which is pretty neat as that means no transcoding is needed.

However, if I try to take a snapshot via `/api/frame.jpeg` while I'm **not** watching the stream, it looks like this:

![Image](https://github.com/user-attachments/assets/bd36b5d9-16d7-4237-9b90-5ef12e651149)

If I **am** watching the stream, it looks like this:

![Image](https://github.com/user-attachments/assets/e8979b18-8dd9-45f8-bb86-9ad4f6499dd0)

What I believe is happening here is that the webcam needs a bit of time to adapt to the lighting conditions. If the webcam is already initialized, the snapshot comes out good. If it needs to be initialized on the spot, it looks very dark.

I have validated my theory by changing my config so it looks like this:
```yaml
streams:
  webcam:
    - "ffmpeg:device?video=/dev/video0&input_format=h264&video_size=1920x1080&rotate=180#raw=-ss 00:00:00.5"
```

This adds half a second delay to all video processing, which is very much not great, but makes `/api/frame.jpeg` output nice snapshots all the time.

I'd love if this delay could only be used in the jpeg endpoint:
https://github.com/AlexxIT/go2rtc/blob/47f32a5f5597e956b51dc5d0f0beadad6918ebf2/internal/ffmpeg/jpeg.go#L37

Either set via config, or from a get param (that could allow turning the 1s delay on/off).
