### ISSUE TITLE
Go2Rtc on HomeAssistant 2025.03.3 CPU 100% usage

### ISSUE THREAD

**Issue by dmalipie** [AlexxIT/go2rtc#1677]
My environment: 
Raspberry Pi 4 with Home Assistant 2025.03.3
Two Foscam camera (I use the official Foscam Integration in HA).
Go2rtc autogenerated (by HA) config file is:

```
api:
  listen: "127.0.0.1:11984"

rtsp:
  listen: "127.0.0.1:18554"

webrtc:
  listen: ":18555/tcp"
  ice_servers: []
streams:
  camera.ingresso:
    - rtsp://user:pwd@192.168.1.1:554/videoMain
    - ffmpeg:camera.cam01#audio=opus#query=log_level=debug
  camera.giardino:
    - rtsp://user:pwd@192.168.1.2:554/videoMain
    - ffmpeg:camera.cam02#audio=opus#query=log_level=debug
```

In Lovelace I add a Picture glance, with "live" enabled.

Issue:
The process relative to go2rtc use 358% of CPU (i have 4 core).

What can I do to solve this issue ? What kind of information can I give to you for fix this issue ?

thanks
Diego
