### ISSUE TITLE
Adding a second cam in config causes homekit error "unknown host"

### ISSUE THREAD

**Issue by robincle** [AlexxIT/go2rtc#1681]
Hey! I tested a lot with go2rtc and home assistant in the last days. My setup: 1x Aqara G3 and 1x Aqara G4. Everything is fine by streaming the two cameras via go2rtc into home assistant. I want to add both cameras via homekit "bypass" via go2rtc into home assistant because i need the motion sensors of both cameras in ha for automation. I thought that the way to integrate the cameras into go2rtc (for perfect stream) and then add them into ha by homekit "bypass" of go2rtc is the perfect way to go. I can't find any other possible solution for having the perfect stream via go2rtc and access the motion sensors etc. for automation in ha.

Problem:
Everything works fine, if i add one camera into homekit configuration of go2rtc. Both streams are working correctly and i could use the motion sensor of the one cam to do some automation stuff in ha. But if i add the second camera into the homekit configuration of go2rtc, the log of go2rtc is showing error "[homekit] unknown host: 192.168.188.22" continousely and it's not possible two add the second camera by homekit into ha, because it shows the error "step bytearray(b'\x02')" at the interface to enter the homekit code. It doesn't matter if i try it with the g3 or g4 as second cam. Maybe it's a bug if you add the second cam into the configuration?

go2rtc: 1.9.9

Core: 2025.3.4
Supervisor: 2025.03.3
Operating System: 15.0
Frontend: 20250306.0

This is my go2rtc.yaml config:

```
streams:
  cam1: homekit://192.168.188.53:35101?device_id=XXX&device_public=XXX&client_id=XXX&client_private=XXX
  cam2: homekit://192.168.188.43:42075?device_id=XXX&device_public=XXX&client_id=XXX

homekit:
  cam1:
    pin: XXX
    name: cam1
    device_id: cam1
    device_private: cam1
    pairings:
      - client_id=XXX&client_public=XXX&permissions=1
  cam2:
    pin: XXX
    name: cam2
    device_id: cam2
    device_private: cam2
    
```

![Image](https://github.com/user-attachments/assets/87e1de80-43f0-4a4c-928e-bbdfaee275e1)
![Image](https://github.com/user-attachments/assets/8d4d444c-386b-4f26-8278-7e592837aaaa)
