### ISSUE TITLE
How to stream on static html

### ISSUE THREAD

**Issue by newnew01** [AlexxIT/go2rtc#1688]
```
streams:
    my_cam1: rtsp://admin:xxxxxxxx@192.168.1.30:10554/tcp/av0_0
    my_cam2: rtsp://admin:xxxxxxxx@192.168.1.94:554/onvif1

api:
  origin: "*"

webrtc:
  listen: ":8555"
```
I have ip camera with rtsp protocol stream to go2rtc binary version. It work fine on web backend (http://localhost:1984/).
how to put the webrtc streaming on external html page?
