### ISSUE TITLE
EseeCloud NVR and cameras black screen stream

### ISSUE THREAD

**Issue by TalZiv** [AlexxIT/go2rtc#1690]
Hi,

I am trying to add a camera directly to go2rtc, I have tried many configurations but nothing really works.

```
streams:
  test_cam: http://admin:@192.168.1.19:80/livestream/12
  test_custom_header: "http://admin:@192.168.1.19:80/livestream/12#header=Authorization: Basic YWRtaW46"
  snap: http://192.168.1.19/snapshot?r=0.9730670290365486&auth=YWRtaW46
```

![Image](https://github.com/user-attachments/assets/32495e58-4bc6-4231-a360-8a98dfd29096)

I can see the the stream with this command from the terminal
HD:
```ffplay -headers "Authorization: Basic YWRtaW46" -i "http://192.168.1.19/livestream/11"```

SD:
```ffplay -headers "Authorization: Basic YWRtaW46" -i "http://192.168.1.19/livestream/12"```

This is the output from ffplay
```
    Last message repeated 1 times
Input #0, hevc, from 'http://192.168.1.19/livestream/11':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuvj420p(pc, bt709), 3840x2160, 25 fps, 15 tbr, 1200k tbn
```

Any help is appreciated.

**Comment by AlexxIT** [comment]
Your stream has an unknown format. You can share it with me. Or you can use ffmpeg source, because looks like ffmpeg support it.

**Comment by TalZiv** [comment]
Hi, 

Thanks for the quick reply really appreciate it.

I tried this ffmpeg config but I get 401 error, In RTSP and ONVIF:
```
#CAMERA STREAM:
streams:
  ffmpeg_test: ffmpeg:http://admin@192.168.1.19:80/livestream/12
  ffmpeg_test2: ffmpeg:http://admin:@192.168.1.19:80/livestream/12
  ffmpeg_test3: ffmpeg:http://admin@192.168.1.19:80/livestream/12
  onvif_test: onvif://admin:@192.168.1.19:8888
  rtsp: rtsp://admin:@192.168.1.19:554/ch0_0.264

ffmpeg:
  myraw: "-headers 'Authorization: Basic YWRtaW46'"
```

![Image](https://github.com/user-attachments/assets/1e387394-b8a0-4720-a3d3-85f0e424ce70)


I don't mind sharing a stream if needed, just let me know how to pass the details.

WIth RTSP and ONVIF i tested the probe function and I get this output:
```{
  "producers": [
    {
      "id": 2,
      "format_name": "rtsp",
      "protocol": "rtsp+tcp",
      "remote_addr": "192.168.1.19:554",
      "url": "rtsp://admin:@192.168.1.19:554/ch0_0.264",
      "sdp": "v=0\r\no=- 0 0 IN IP4 0.0.0.0\r\ns=session\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\na=control:*\r\na=range:npt=0-\r\nm=audio 0 RTP/AVP 8\r\na=rtpmap:8 PCMA/8000/1\r\na=recvonly\r\na=control:realaudio\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H265/90000\r\na=control:realvideo\r\n",
      "user_agent": "go2rtc/1.9.4",
      "medias": [
        "audio, recvonly, PCMA/8000",
        "video, recvonly, H265"
      ],
      "receivers": [
        {
          "id": 3,
          "codec": {
            "codec_name": "pcm_alaw",
            "codec_type": "audio",
            "sample_rate": 8000
          },
          "childs": [
            4
          ]
        },
        {
          "id": 5,
          "codec": {
            "codec_name": "hevc",
            "codec_type": "video"
          },
          "childs": [
            6
          ]
        }
      ]
    }
  ],
  "consumers": [
    {
      "id": 1,
      "format_name": "probe",
      "protocol": "http",
      "remote_addr": "192.168.1.114:51532",
      "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36",
      "medias": [
        "audio, sendonly, ALL",
        "video, sendonly, ALL",
        "audio, recvonly, ANY"
      ],
      "senders": [
        {
          "id": 4,
          "codec": {
            "codec_name": "pcm_alaw",
            "codec_type": "audio",
            "sample_rate": 8000
          },
          "parent": 3
        },
        {
          "id": 6,
          "codec": {
            "codec_name": "hevc",
            "codec_type": "video"
          },
          "parent": 5
        }
      ]
    }
  ]
}```

**Comment by TalZiv** [comment]
This is a capture I made using this command:
```
ffmpeg -headers "Authorization: Basic YWRtaW46" -i "http://192.168.1.19/livestream/12" test.mp4
```

https://github.com/user-attachments/assets/9cf13134-40f6-4665-827f-c9f62eb61619

**Comment by AlexxIT** [comment]
You can share stream in PM. You can find contacts in GitHub profile.

```yaml
streams:
  ffmpeg_test: ffmpeg:http://admin@192.168.1.19:80/livestream/12#input=httpauth

ffmpeg:
  httpauth: "-headers 'Authorization: Basic YWRtaW46' -fflags nobuffer -flags low_delay -i {input}"
```
