### ISSUE TITLE
Eseecloud isue with adding camera stream to HA green

### ISSUE THREAD

**Issue by subj3ctqt** [AlexxIT/go2rtc#1702]
Hello, I am trying to add my camera stream since I have NV-KIT430-W which is a bit outdated system I am trying to use go2rtc in my HA via esecloud. I use streams:
  camera1: essecloud://username:password@192.168.100.41:34567/essecloud/live?ch=4&stream=0, beside username and password does other info seem to be ok or? 
Thanks for help and patience

**Comment by AlexxIT** [comment]
I don't know where you get this link. I only know links like this:
```yaml
streams:
  dev1: bubble://user:pass@192.168.1.123:5555/bubble/live?ch=0&stream=0
  dev2: eseecloud://user:pass@192.168.1.123:5555/livestream/12
```
