### ISSUE TITLE
Two-way audio in Frigate card when accessing via Home Assistant Cloudflare Tunnelling

### ISSUE THREAD

**Issue by junxulai** [AlexxIT/go2rtc#1719]
I have configured WebRTC and can enable two-way audio in either Frigate web interface or in HA using Frigate card only for local access. When accessing HA locally, the microphone icon can be seen, and two-way audio is working.

![Image](https://github.com/user-attachments/assets/43ed3b31-0859-41f6-b120-6365c9648d7b)

I am accessing my HA via Cloudflare tunnel when I am away. My HA and Frigate instances are behind CGNAT, so I have also configured ngrok as suggested, and I can confirm from ngrok dashboard that the tunneling is online.

![Image](https://github.com/user-attachments/assets/3591258b-ef7f-40d9-be09-e3c916f83e48)

However, after I set up ngrok, although I can see the stream, the microphone icon won't show up for external access, and the video keeps loading. 

![Image](https://github.com/user-attachments/assets/87933b92-2a83-48bd-9e2b-53a78be0b50e)

My setup for go2rtc is:

```
go2rtc:
  ngrok:
    command: /config/ngrok tcp 8555 --authtoken xxxx
  streams:
    hallway:
      - rtsp://admin:password@192.168.50.87:554/h264Preview_01_main
    hallway_sub:
      - rtsp://admin:password@192.168.50.87:554/h264Preview_01_sub
  webrtc:
    listen: ":8555"
    candidates:
      - 192.168.50.37:8555
      - stun: 8555
```

Docker compose file for Frigate is:

```
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: always
    image: ghcr.io/blakeblackshear/frigate:0.14.0
    shm_size: "256mb" 
    network_mode: host
    devices:
      - /dev/bus/usb:/dev/bus/usb 
      - /dev/apex_0:/dev/apex_0 
      - /dev/video11:/dev/video11 
      - /dev/dri/renderD128:/dev/dri/renderD128 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/ssd/config:/config
      - /mnt/ssd/clips:/media/frigate
      - type: tmpfs 
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

Thanks in advance for any help.

**Comment by AlexxIT** [comment]
Try to increase log level for webrtc module to trace and check candidates.
```yaml
go2rtc:
  log:
    webrtc: trace
```
