### ISSUE TITLE
Javascript template doesn't work in "style" section

### ISSUE THREAD

**Issue by TitjyDev** [AlexxIT/go2rtc#1721]
Hello.

Documentation says:

> Templates
> [New in v3.6.0](https://github.com/AlexxIT/WebRTC/releases/tag/v3.6.0).
> 
> Card options shortcuts, style and ptz supports JavaScript templates
> In shortcuts and style you can use states related templates

While javascript template works in `shorcuts` option, it don't in `style` 

```yaml
  shortcuts:
    - name: >-
        Camera Mode :
        ${ states['switch.camera8active'].state === 'on' ? 'Off' : 'On' }
      icon: >-
        ${ states['switch.camera_active'].state === 'on' ?
        'mdi:camcorder' : 'mdi:camcorder-off' }

  style: >-
    ${ states['switch.camera_active'].state === 'on' ? '.shortcuts ha-icon {background-color:red}' : '.shortcuts ha-icon {background-color:green}' }
```

My icon should be displayed with a red or green background regarding the entity state but no icon is displayed.

This works as expected of course:
```yaml
 style: >-
    .shortcuts ha-icon {background-color: red}
```

So what i'm doing wrong?
