### ISSUE TITLE
Huge "network" after setting up Wyoming

### ISSUE THREAD

**Issue by tbrasser** [AlexxIT/go2rtc#1723]
Not sure whether this is expected?

Config:

```yaml
streams:
  tablet1: rtsp://10.9.8.137:8080/h264_pcm.sdp
  tablet2: rtsp://10.9.8.109:8080/h264_pcm.sdp
  tablet3: rtsp://10.9.8.64:8080/h264_pcm.sdp
  tablet4: rtsp://10.9.8.163:8080/h264_pcm.sdp
  steeg: onvif://admin:########@10.9.8.86?subtype=Profile_101
  steegdetect: onvif://admin:########@10.9.8.86?subtype=Profile_102
  steegptz: onvif://admin:########@10.9.8.86?subtype=Profile_201
  steegptzdetect: onvif://admin:########@10.9.8.86?subtype=Profile_202
  birdseye: exec:/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -f rawvideo -pix_fmt
    yuv420p -video_size 1280x720 -r 10 -i /tmp/cache/birdseye -c:v libx264 -g 50 -profile:v
    high -level:v 4.1 -preset:v superfast -tune:v zerolatency -rtsp_transport tcp
    -f rtsp {output}
wyoming:
  tablet1:
    listen: :10700
      # wake_uri: tcp://192.168.1.23:10400  # optional WAKE service
    vad_threshold: 1                      # optional VAD threshold (from 0.1 to 3.5)
    event:
      synthesize: |
        let text = fromJSON(Data).text;
        fetch('http://supervisor/core/api/services/tts/speak', {
          method: 'POST',
          headers: {'Authorization': 'Bearer ${SUPERVISOR_TOKEN}','Content-Type': 'application/json'},
          body: toJSON({
            entity_id: 'tts.google_translate_com',
            media_player_entity_id: 'media_player.eetkamer',
            message: text,
            language: 'en',
          }),
        }).ok
      audio-stop: |
        let timestamp = fromJSON(Data).timestamp;
        let delay = string(timestamp)+'s';
        Sleep(delay) && WriteEvent("played") && Detect()
  tablet2:
    listen: :10702
      # wake_uri: tcp://192.168.1.23:10400  # optional WAKE service
    vad_threshold: 1                      # optional VAD threshold (from 0.1 to 3.5)
  tablet3:
    listen: :10703
      # wake_uri: tcp://192.168.1.23:10400  # optional WAKE service
    vad_threshold: 1                      # optional VAD threshold (from 0.1 to 3.5)
  tablet4:
    listen: :10704
      # wake_uri: tcp://192.168.1.23:10400  # optional WAKE service
    vad_threshold: 1                      # optional VAD threshold (from 0.1 to 3.5)
api:
  origin: '*'
hass:
  config: /config
log:
  format: text
webrtc:
  candidates:
  - 10.9.8.30:8555
  - stun:8555
ffmpeg:
  bin: /usr/lib/ffmpeg/7.0/bin/ffmpeg
```
Network page screenshot:
![Screenshot_2025-05-06-23-16-45-698_com.android.chrome.jpg](https://github.com/user-attachments/assets/f13ffb1f-7488-41d7-b7c6-ac5e687749b6)
