### ISSUE TITLE
How to clear a stream when using PATCH /api/config?

### ISSUE THREAD

**Issue by dzek69** [AlexxIT/go2rtc#1735]
Let's assume this is my config:

```
streams:
    brama2:
        - rtsp://192.168.101.71:8554/live1.264
    kotek:
        - rtsp://whatever/
```

How do I remove `kotek` stream using PATCH `/api/config` endpoint?
I tried using
```
streams:
  kotek: ~
```
```
streams:
  kotek: null
```

But these are just producing errors in response

This only clears the value:
```
streams:
  kotek: []
```

But I'd prefer to not have the `kotek` at all.

Is this somehow possible without rewriting the whole config?
