### ISSUE TITLE
snapshots latency is unreliable / uncontrollable

### ISSUE THREAD

**Issue by mmerickel** [AlexxIT/go2rtc#1736]
Configuring a simple RTSP stream such as the following creates a nice webrtc and mjpeg stream that appears in frigate.

However, when requesting a snapshot via `wget http://go2rtc-host:1984/api/frame.jpeg?src=camera1 -O frame.jpg` the latency is high and variable regularly taking between 1-2 seconds to return a response. I believe this is due to the lazy nature of go2rtc and the fact that it is waiting for a new keyframe from the raw RTSP camera stream after my request for a snapshot.

Is there anything that can be done within go2rtc to make the snapshot more snappy / reliable? My hope would be to configure something such that go2rtc is always listening to this feed and always storing a latest snapshot in memory, even by applying the diffs between keyframes such that it is returned as accurately as possible to the time I'm requesting the snapshot.

I can connect directly of course via `ffmpeg -i rtsp://go2rtc-host:8554/camera1 -update 1 foo.jpg` to get an up-to-date snapshot but this requires me basically setting up my own system on top of go2rtc just to get a live snapshot.

I also tried setting up a separate stream like camera1_mjpeg below as seemingly suggested in https://github.com/AlexxIT/go2rtc/issues/482#issuecomment-1601323057 but all it seems to do is add double latency (camera1_mjpeg waits for a keyframe from camera1 which waits for a keyframe from the source rtsp) when requesting a snapshot from it.

```yaml
streams:
  camera1:
  - rtsp://foo:bar@192.168.81.10:554/stream1
  camera1_mjpeg:
  - ffmpeg:camera1#video=mjpeg

api:
  origin: '*'
hass:
  config: /config
log:
  format: text
webrtc:
  candidates:
  - 192.168.20.5:8555
  - stun:8555
rtsp:
  default_query: mp4
ffmpeg:
  bin: /usr/lib/ffmpeg/7.0/bin/ffmpeg
```

**Comment by mmerickel** [comment]
Ok based on your latest comment I setup the following and that is responding significantly more quickly - wget is down from 1-2 seconds to only around 200-400ms which is certainly an improvement.

```yaml
streams:
  camera1:
  - rtsp://foo:bar@192.168.81.10:554/stream1
  camera1_mjpeg:
  - rtsp://foo:bar@192.168.81.10:554/stream1#video=mjpeg
```

This is in comparison to the following other 2 options that don't work and I really don't understand the differences between them in go2rtc parlance.

```yaml
streams:
  camera1:
  - rtsp://foo:bar@192.168.81.10:554/stream1
  camera1_mjpeg:
  - rtsp://foo:bar@192.168.81.10:554/stream1#video=mjpeg
  camera2:
  - rtsp://foo:bar@192.168.81.10:554/stream1#video=copy#video=mjpeg
  camera3:
  - rtsp://foo:bar@192.168.81.10:554/stream1
  - ffmpeg:camera1_jumbo_separate#video=mjpeg
```

Would you be able to provide any clues on the differences in these definitions? I think it's been one of my biggest hangups that I couldn't find an explanation on in the go2rtc README.

Thank you!
