### ISSUE TITLE
Intel N6005 Hardware Acceleration - Green Screen

### ISSUE THREAD

**Issue by kosmaluk** [AlexxIT/go2rtc#1739]
Hi.

I want to enable hardware acceleration to support h265 to 264 transcoding from Reolink E560 cameras.
Here are my configurations:

1. Dell Optiplex 3000 with Intel Pentium N6005 (Jasper Lake) 8GB PC4 32GB eMMc
2. HA OS bare/metal Core 2025.4.3, System 15.1, Supervisor 2025.05.1

3. Go2RTC master hardware 1.9.9 add-on
4. WebRTC camera 3.6.0 integration
5. Reolink E560 4k h265 cameras

Built-in go2rtc in configuration.yaml
```
go2rtc:
  url: "http://localhost:1984"
```
go2rtc.yaml (shortcut):
```
ffmpeg:
  hwaccel_args: preset-vaapi

streams:

  reolink_garaz_4k: 
     - rtsp://admin:xxxx@192.168.8.9:554/h264Preview_01_main
      - ffmpeg:reolink_garaz_4k#audio=opus
    
  reolink_garaz_plynny: 
    - rtsp://admin:xxxx@192.168.8.9:554/h264Preview_01_sub
    - ffmpeg:reolink_garaz_plynny#audio=opus
    
  reolink_garaz_2k: 
    - ffmpeg:reolink_garaz_4k#video=h264#width=2560#height=1440#audio=opus#hardware
  
  reolink_garaz_hd: 
    - ffmpeg:reolink_garaz_4k#video=h264#width=1920#height=1080#audio=aac#audio=opus#hardware
  
webrtc:
  listen: :8555
  candidates:
    - stun:8555
    - 192.168.8.100:8555
```
I installed a special add-on to enable hardware acceleration, but with these and similar settings, e.g. #harware=vaapi or hwaccel_args: preset-intel-qsv-h264 I get a green screen + sound all the time.

All streams except the main 4k h265 go through RTC in both the ACC card and WebRTC and Chrome PC, so it's ok.

Current processor load with one 2k transcoding is about 50% and hd about 40%.

I would like to use the processor's capabilities.

I don't know what is the reason, whether the input stream, its codec, resolution, or go2RTC settings or drivers.

4k stream parameters: 3840x2160, 20fps, 4096 kbbs

Please advise, thank you
