### ISSUE TITLE
Native support for multiple streams

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/go2rtc#174]
I have had a wish: I want to be able to switch between multiple streams for a single camera in Home Assistant in a better way than through multiple camera entities.

I have been thinking about this since weeks, and I think I came up with some sort of solution. I may be totally wrong though.

First of all, go2rtc to support multiple video tracks in a single stream:

```yaml
streams:
  my_camera:
    - rtsp://admin:12345@192.168.1.33:554/0/av0
    - rtsp://admin:12345@192.168.1.33:554/0/av1#substream=1
```

When streaming from `go2rtc` with `rtsp://127.0.0.1:8554/my_camera`, the substream will never be used, unless I use `rtsp://127.0.0.1:8554/my_camera?substream=1`.

However, go2rtc exposes the list of substreams for a given stream through some API.

Then, the WebRTC integration/card would pull this information when starting the camera feed, and if more than one stream/substreams are found, the card renders a button to switch between them.

What do you think?

**Comment by AlexxIT** [comment]
I do not know the mechanism to safely switch the current stream for WebRTC and for MSE. It could be a different codec. Or a different profile of the same codec. This mechanism needs to be investigated.

The easiest thing to do is to make several streams and a switch in the card. The switch will completely restart the mechanism for requesting a new stream from the beginning.

**Comment by AlexxIT** [comment]
Maybe someday I will make an API to change the active stream for the selected client. This can be useful for tablets on the wall. Something similar Birdseye does in Frigate.

**Comment by felipecrs** [comment]
Interesting! Thanks a lot for your thoughts!

**Comment by lindhe** [comment]
Sorry for hijacking this thread a bit, but I want to ask about what you show there: having the stream object be a list and selecting the substream using the `substream=1` parameter. Does that work as of v0.12.1, or is that something you propose to be implemented?

**Comment by felipecrs** [comment]
It was a feature suggestion, not something already implemented.

**Comment by AlexxIT** [comment]
This feature implemented in the latest WebRTC integration version

**Comment by jcasarini** [comment]
Hi!
I'm trying to implement this, but I can't find a way of actually using it.
I'm running the go2rtc Add-on in Home Assistant, I loaded both streams of each camera in the config.

```
streams:
    fondo: 
        - rtsp://192.168.18.111:554/user=admin_password=REDACTED_channel=0_stream=0.sdp?real_stream
        - rtsp://192.168.18.111:554/user=admin_password=REDACTED_channel=1_stream=1.sdp?real_stream
    frente: 
        - rtsp://192.168.18.113:554/user=admin_password=REDACTED_channel=0_stream=0.sdp?real_stream
        - rtsp://192.168.18.113:554/user=admin_password=REDACTED_channel=1_stream=1.sdp?real_stream
```

Now if I go to the info link it shows:
```

{
  "producers": [
    {
      "url": "rtsp://192.168.18.111:554/user=admin_password=Mo4q8veto_channel=0_stream=0.sdp?real_stream"
    },
    {
      "url": "rtsp://192.168.18.111:554/user=admin_password=Mo4q8veto_channel=1_stream=1.sdp?real_stream"
    }
  ],
  "consumers": []
}
```

How can I switch between them?
Is there anyway of placing a button (service) on the overlay of the WebRTC-card to switch between them? 
This would very useful, as when I'm on a mobile connection the main FHD stream won't even load.

Thanks!
