### ISSUE TITLE
Dahua DHI-VTO1301R-W two way audio

### ISSUE THREAD

**Issue by algoz098** [AlexxIT/go2rtc#1740]
After a couple weeks tryng to make this work with two way audio I'm here asking for some help.

I tried using the documentation and then this: https://github.com/AlexxIT/go2rtc/issues/49#issuecomment-2127107379

But, it did not work.

I can receive audio through go2rtc, but I cannot send it.

RIght now my setup is through docker, so I have go2rtc with frigate container, 0.15, and using another vm which has homeassistant.

All this is accessible through https.

Here is the configuration for dahua:
```

go2rtc:
  streams:
    portao:
    - echo:/config/scripts/fix_vto_codecs.sh
      ffmpeg:rtsp://<USER>:<PASSWORD>@192.168.1.168/cam/realmonitor?channel=1&subtype=0#video=copy#backchannel=0#audio=aac#hardware
   
```

If there's some direction I can take which someone can point me in, I would be gratefull! Thanks.
