### ISSUE TITLE
Support for PNG in HTTP source

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/go2rtc#1749]
Fully Kiosk has an API to get the screenshot in PNG format. It would be great if I could convert it to a stream:

```yaml
streams
  # this works, because camshot returns JPEG
  fully_kiosk_camera:
    - http://192.168.1.50:2323/?cmd=getCamshot&password=remoteadminpassword
    - ffmpeg:fully_kiosk_camera#video=h264
  # this does not work, because screenshot returns PNG
  fully_kiosk_screen:
    - http://192.168.1.50:2323/?cmd=getScreenshot&password=remoteadminpassword
    - ffmpeg:fully_kiosk_screen#video=h264
```
