### ISSUE TITLE
Play UDP Stream via ALSA

### ISSUE THREAD

**Issue by chip131001** [AlexxIT/go2rtc#175]
Is it possible to play a UDP stream via alsa?
The following command in the console works.
`ffmpeg -i udp://localhost:45678 -f alsa plughw:CARD=P610,DEV=0`
Can I configure this in go2rtc?

**Comment by AlexxIT** [comment]
I'm not sure what go2rtc has to do with it.

**Comment by chip131001** [comment]
I want to play the incoming stream through a speaker on a raspberry pi.

**Comment by chip131001** [comment]
OK. thanks!

**Comment by chip131001** [comment]
Can I play the following stream on a Speaker with the incoming source?

`ffmpeg -i udp://localhost:45678 -f alsa plughw:CARD=P610,DEV=0`

Or would you recommend Stream to camera?
How do you have to configure this?

**Comment by AlexxIT** [comment]
You can try to use exec source

**Comment by chip131001** [comment]
Do you think so?

streams:
  speaker: exec:ffmpeg -i udp://localhost:45678 -f alsa plughw:CARD=P610,DEV=0

**Comment by AlexxIT** [comment]
You need RTSP transport for exec

**Comment by chip131001** [comment]
This is not an error, but a question.
I have configured the following stream in simple-rts-server.
```
paths:
  mic:
    runOnInit: /home/pi/ffmpeg/ffmpeg -i udp://localhost:45678 -f alsa plughw:CARD=P610,DEV=0
    runOnInitRestart: yes
```
How can I configure this in go2rtc as an incoming source?
