### ISSUE TITLE
2-way audio through SIP client

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/go2rtc#1750]
This is an alternative to https://github.com/AlexxIT/go2rtc/issues/409.

Most SIP doorbells like Dahua and Hikvision have their own SIP server built-in which other devices can register into.

This means go2rtc does not actually need to act as a SIP server. It could act as a SIP client only.

Example on how this could be configured:

```yaml
stream:
  dahua_doorbell:
    doorbell:
      # H264, PCMA
      - rtsp://admin:pass@192.168.1.40/cam/realmonitor?channel=1&subtype=0
      # 2-way audio over SIP
      - sip://9001:sippassword@192.168.1.40:5060/?call_to=8001
```

```
sip://<username to register in sip server>:<password to register in sip server>@<sip server IP>:<sip server port>/?call_to=<sip number to call>
```

So when 2-way audio is requested, go2rtc would register itself in the SIP server and initiate a call to the number.

**Comment by altserg** [comment]
From my experience SIP often uses low quality PCMU/8000 codec while the native camera stream can be PCM/16000 (For Dahua doorbell)
I also have not managed to connect SIP audio to Dahus SIP server using pjsip lib. Command channel and SDP negotiation work, but the audio channel is not established for some reason. If someone will manage to connect SIP audio Dahua doorbell, I would like to know the recipe
https://github.com/pjsip/pjproject/issues/2823

**Comment by felipecrs** [comment]
Through Asterisk (pjsip) it works just fine. You can refer to my project (https://github.com/felipecrs/dahua-vto-on-home-assistant). Even though I don't use SIP for 2-way audio, it was working last time I tried with the [sip-hass-card](https://github.com/TECH7Fox/sip-hass-card).

**Comment by altserg** [comment]
Dahua embedded SIP server does not work for me, but this might be my local mistake. I do not want to install Asterick as this is yet another level of complexity and dependency. But I did tried it in the past, and indeed Dahua does work via 3rd party SIP server

**Comment by felipecrs** [comment]
Yeah. I was also not able to connect to the embedded SIP server.

**Comment by ngres** [comment]
I'm currently working on integrating both a SIP User Agent Server and Client using sipgo: https://github.com/ngres/go2rtc

My original use case was to connect my Ring doorbell with my telephone system, but I've also added a simple producer implementation. Currently, I've got two-way audio support between a doorbell and SIP telephone (either directly connected to an internal SIP go2rtc server or via a separate PBX and trunk) working. However, the code still requires some refactoring before opening a PR. It also has some basic support for codec negotiations, but without backchannel codec transcoding (https://github.com/AlexxIT/go2rtc/issues/105) two-way audio does not work on most phone systems, since opus support is pretty limited.

This would be an example configuration for the new SIP feature:

```yaml
sip:
  listen: ":5060" # optional built in SIP server
  trunks: # allows to connect external SIP servers as consumers or producers
    mypbx:
      host: pbx.example.com
      port: 5060
      username: "cpbx-doorbell"
      password: "secret"
  routing: # maps SIP user agents to streams to route incoming calls
    doorbell:
      - "cpbx-doorbell"
      - "1002"

streams:
   doorbell: sip:mypbx/1001 # calls a SIP user agent 1001 via the "mypbx" trunk
   internal: sip/400 # calls a SIP phone connected to the integrated SIP server with the user agent 400
```

You can also call a SIP consumer via the publish API:
```bash
curl -X POST http://localhost:1984/api/streams?src=doorbell&dst=sip:mypbx/1003
```
