### ISSUE TITLE
Possible to monitor the Wyoming stream after DSP applied in HA?

### ISSUE THREAD

**Issue by YenLegion** [AlexxIT/go2rtc#1759]
I just got the new Wyoming integration to work in lieu of Stream Assist. It works well, but I am curious if there is a way to listen to the audio after Home Assistant/Wyoming applies noise cancelling and auto gain to see if I have it configured alright? 

This may be more of a Home Assistant or Wyoming question. If so just let me know and I'll close the issue.

Here's my config:

```
streams:
  zte: 
    - rtsp://192.168.0.198:8080/h264_pcm.sdp
    - exec:ffplay -hide_banner -nodisp -probesize 32 -f s16le -ar 22050 -#backchannel=1#audio=s16le/22050

wyoming:
  zte:
    listen: :10700 
    name: "ZTE"                # optional name
    wake_uri: tcp://192.168.0.103:10400&name=hey_jarvis_v0.1  # optional WAKE service
    vad_threshold: 0.1                    # optional VAD threshold (from 0.1 to 3.5)
```
