### ISSUE TITLE
UVC Camera Shows Black Screen When Combined with ALSA Audio Streaming

### ISSUE THREAD

**Issue by 3735943886** [AlexxIT/go2rtc#1770]
When I click on a stream from the `go2rtc` web UI, the internal player shows only a black screen with audio for combined video+audio streams.
Video-only streams work fine.

The configuration was created for testing purposes with various combinations. Of course, they were not played back simultaneously.
```
streams:
  cam1:  # Works
    - v4l2:device?video=/dev/video0&input_format=mjpeg&video_size=640x480
  cam2:  # Works
    - ffmpeg:device?video=/dev/video0&input_format=mjpeg&video_size=640x480
  cam3:  # Black screen with audio only
    - v4l2:device?video=/dev/video0&input_format=mjpeg&video_size=640x480
    - exec:ffmpeg -f alsa -channels 1 -ar 48000 -i hw:0,0 -rtsp_transport tcp -f rtsp {output}
  cam4:  # Black screen with audio only
    - ffmpeg:device?video=/dev/video0&input_format=mjpeg&video_size=640x480
    - exec:ffmpeg -f alsa -channels 1 -ar 48000 -i hw:0,0 -rtsp_transport tcp -f rtsp {output}
  cam5:  # Black screen with audio only
    - exec:ffmpeg -f v4l2 -i /dev/video0 -f alsa -channels 1 -ar 48000 -i hw:0,0 -rtsp_transport tcp -f rtsp {output}
```

Is this a bug, or am I missing something?
If there's anything I can try or check on my side, please let me know.
