### ISSUE TITLE
How to import homeassistant cameras when homeassistant and go2rtc are not on the same machine?

### ISSUE THREAD

**Issue by latel** [AlexxIT/go2rtc#1772]
```
hass:
  config: "/config"  # skip this setting if you Hass Add-on user

streams:
  generic_camera: hass:Camera1  # Settings > Integrations > Integration Name
  aqara_g3: hass:Camera-Hub-G3-AB12
```
