### ISSUE TITLE
I bought a Aqara new G100 camera, it plays well in vlc app and scrypted, but not in go2rtc and frigate

### ISSUE THREAD

**Issue by latel** [AlexxIT/go2rtc#1775]
1. I'm using go2rtc with frigate,  the rtsp stream plays well in scrypted and vlc app. 

<img width="807" alt="Image" src="https://github.com/user-attachments/assets/97f27434-0cc8-4927-baa3-55124ef00252" />

<img width="819" alt="Image" src="https://github.com/user-attachments/assets/aff34c86-385f-4fb6-8af6-bd3d70910566" />

2. but in frigate the video size ratio sometimes kept changing, some times turn inro wrong ratio,  like this:

the video size ratrio is absolutely not right, the resolution is 2304×1296, which ratio equals 1.7.

3. if I play stream directly from frigate's built in go2rtc, the stream cannot be played.

![Image](https://github.com/user-attachments/assets/7cf400ac-4133-4b66-9bd0-be11b6bfe5f4)

my frigate's go2rtc config:
```
log:
  level: trace
  format: text
streams:
  aqara_g100_main: rtsp://10.10.10.11:44425/9e5ccb0b76f30cc9
  aqara_g100_sub: rtsp://localhost:44425/6b87b152d593bcf6
  aqara_g100_low: rtsp://localhost:44425/fadcc01a79fe0599
  living_room: rtsp://532:846@10.10.10.149:8554/ch3

api:
  origin: '*'
hass:
  config: /config
webrtc:
  candidates:
  - stun:8555
ffmpeg:
  bin: /usr/lib/ffmpeg/7.0/bin/ffmpeg

```

related frigate config
```
cameras:
  living_room:
    enabled: true
    ffmpeg:
      inputs:
        - input_args: preset-rtsp-restream
          path: rtsp://532:846@10.10.10.149:8554/ch1
          roles:
            - record
            - detect
    record:
      enabled: true
      retain:
        days: 2
    detect:
      enabled: true
```

I also make a ffprobe, it reports errors:

```
ffprobe rtsp://532:846@10.10.10.149:8554/ch1
ffprobe version 7.1.1 Copyright (c) 2007-2025 the FFmpeg developers
  built with Apple clang version 17.0.0 (clang-1700.0.13.3)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1.1_3 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.101 / 61. 19.101
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
[h264 @ 0x126005e60] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x126005e60] decode_slice_header error
[h264 @ 0x126005e60] no frame!
[h264 @ 0x126005e60] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x126005e60] decode_slice_header error
[h264 @ 0x126005e60] no frame!
[h264 @ 0x126005e60] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x126005e60] decode_slice_header error
[h264 @ 0x126005e60] no frame!
[h264 @ 0x126005e60] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x126005e60] decode_slice_header error
[h264 @ 0x126005e60] no frame!
[h264 @ 0x126005e60] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x126005e60] decode_slice_header error
[h264 @ 0x126005e60] no frame!
[h264 @ 0x126005e60] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x126005e60] decode_slice_header error
[h264 @ 0x126005e60] no frame!
[h264 @ 0x126005e60] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x126005e60] decode_slice_header error
[h264 @ 0x126005e60] no frame!
[h264 @ 0x126005e60] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x126005e60] decode_slice_header error
[h264 @ 0x126005e60] no frame!
[h264 @ 0x126005e60] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x126005e60] decode_slice_header error
[h264 @ 0x126005e60] no frame!
[h264 @ 0x126005e60] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x126005e60] decode_slice_header error
[h264 @ 0x126005e60] no frame!
[h264 @ 0x126005e60] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x126005e60] decode_slice_header error
[h264 @ 0x126005e60] no frame!
[h264 @ 0x126005e60] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x126005e60] decode_slice_header error
[h264 @ 0x126005e60] no frame!
[h264 @ 0x126005e60] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x126005e60] decode_slice_header error
[h264 @ 0x126005e60] no frame!
[h264 @ 0x126005e60] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x126005e60] decode_slice_header error
[h264 @ 0x126005e60] no frame!
[h264 @ 0x126005e60] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x126005e60] decode_slice_header error
[h264 @ 0x126005e60] no frame!
[h264 @ 0x126005e60] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x126005e60] decode_slice_header error
[h264 @ 0x126005e60] no frame!
[h264 @ 0x126005e60] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x126005e60] decode_slice_header error
[h264 @ 0x126005e60] no frame!
[h264 @ 0x126005e60] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x126005e60] decode_slice_header error
[h264 @ 0x126005e60] no frame!
[h264 @ 0x126005e60] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x126005e60] decode_slice_header error
[h264 @ 0x126005e60] no frame!
[h264 @ 0x126005e60] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x126005e60] decode_slice_header error
[h264 @ 0x126005e60] no frame!
```
