### ISSUE TITLE
"- ffmpeg:rtsp://<camera>" vs "- rtsp://<camera> - ffmpeg:<stream_name>"

### ISSUE THREAD

**Issue by spoolr** [AlexxIT/go2rtc#1777]
Given:
```

go2rtc:
  streams:
    front_window:
      - "rtsp://<camera>"
      - "ffmpeg:front_window#video=copy#audio=aac#hardware"
    back_window:
      - "ffmpeg:rtsp://<camera>#video=copy#audio=aac#hardware 

```

Are "front_window" and "back_window" ultimately two different ways of writing exactly the same thing?  Or is there some meaningful difference?
