### ISSUE TITLE
OPUS to AAC transcoding not working

### ISSUE THREAD

**Issue by johnc2k** [AlexxIT/go2rtc#1779]
**Environment:** Docker on Ubuntu 22.04.5 LTS
**go2rtc Version:** 1.9.9 (tested on both the `latest` and `master` images)
**Camera:** Google Nest Cam (outdoor or indoor, battery)

**go2rtc Config:**
```
logs:
  api: trace
  level: trace
  onvif: trace
  rtsp: trace
  streams: trace

# Google Nest Cameras ##
streams:
  driveway:
    - nest:?client_id=xxxmyworkingconfigxxx
    - ffmpeg:driveway#audio=aac
```

**Issue:**

I have seen there have been some previous reports similar to this issue (e.g. #1643 , #1505) however they claim to be resolved. 

The Nest integration produces a h264 video and Opus audio streams which work fine:

`rtsp://192.168.xxx.xxx:8554/driveway`
![Image](https://github.com/user-attachments/assets/e9217209-f371-446b-9fa7-6eaed32dbe33)

However when I add the option to transcode the audio to AAC (as per config above) the audio track is muted:

`rtsp://192.168.xxx.xxx:8554/driveway?video=all&audio=aac`
![Image](https://github.com/user-attachments/assets/09dd0307-1078-4aa5-94be-e27487735e98)

As per one of the other issue threads I tried reverting to `1.9.2` and that worked fine with the same configuration.
