### ISSUE TITLE
Stream to Youtube does not start automatically

### ISSUE THREAD

**Issue by jbec230** [AlexxIT/go2rtc#1787]
Hi,
I run go2rtc with a stream that I send from OBS via go2rtc to a YouTube account. But it only becomes visible/active there if I enter the link again in the web-gui under publish links and click on send. Watching the stream on another local device with VLC works at all times.
Go2rtc 1.9.9 runs under Ubuntu Server as a service including autostart at boot. The stream comes from OBS with rtmp, H264 and AAC.
Here is the excerpt from go2rtc.yaml:
```
rtmp:
  listen: ":1935"  # by default - disabled!

streams:
  youtube:
    - rtmp://192.168.151.67  #IP go2rtc-device

publish:
  youtube:
    - rtmp://a.rtmp.youtube.com/live2/[MyYoutubeKey]
```
How can I start the stream to Youtube automatically? 
Have I forgotten something else in the config file for this?
