### ISSUE TITLE
Advice on using go2rtc with Home Assistant + advanced-camera-card: Ingress URL 401 issue

### ISSUE THREAD

**Issue by F0x06** [AlexxIT/go2rtc#1788]
Hi, first of all, thank you for this great addon!

I'm using the go2rtc addon in Home Assistant to stream from my Tapo C230 camera, and I'm displaying it on my dashboard using the `custom:advanced-camera-card` like this:

```yaml
type: custom:advanced-camera-card
cameras:
  - live_provider: go2rtc
    go2rtc:
      stream: camera_go2rtc_2w_door
      url: >-
        https://hass.mydomain.com:8123/api/hassio_ingress/SOME_LONG_TOKEN/
      modes:
        - webrtc
```

This works well *at first*. However, after I close the browser (or restart the Home Assistant Android app), then open the dashboard again, I get a `401 Unauthorized` error from the `hassio_ingress` URL.

**What’s interesting is**: if I click the go2rtc addon icon in the Home Assistant sidebar (just to open its UI), it seems to "refresh" or re-enable the token, and the stream starts working again on the dashboard.

So it looks like the ingress token expires or becomes invalidated when unused for a while, and opening the addon regenerates or refreshes it?

### My question:

Is there a recommended/better way to integrate the go2rtc stream with `advanced-camera-card` to avoid this issue?
Or maybe there’s a setting that allows the ingress token to persist longer or refresh automatically?

Any suggestions or best practices would be very appreciated!

Thanks 🙏
