### ISSUE TITLE
Frigate issue due to use of ffmpeg v4 on arm64

### ISSUE THREAD

**Issue by jherby2k** [AlexxIT/go2rtc#179]
Bear with me as i'm using go2rtc via the latest frigate beta (-4) and i'm struggling to get debug logging to show up...

I'm trying to transcode audio from my camera from a-law to opus and/or aac.

This appears to crash go2rtc with exit code 1:

```yaml
  streams:
    driveway: ffmpeg:rtsp://192.168.2.206:80/ch0_0.264#video=copy#audio=opus
```

This doesn't work either but at least lets me use the stream without opus:

```yaml
  streams:
    driveway:
      - rtsp://192.168.2.206:80/ch0_0.264
      - ffmpeg:driveway#audio=opus
```

same behavior with AAC. This is on a raspberry Pi 4 tested with and without HW decode acceleration in ffmpeg.

`2023-01-17 17:11:23.815818233  17:11:23.815 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:52 > error="exec: exit status 1" url=ffmpeg:driveway#audio=aac#audio=opus`
