### ISSUE TITLE
A way to specify the default audio codec supplied when none is specified

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/go2rtc#194]
For example, let's say I have:

```yaml
streams:
  rua_hd:
    - rtsp://admin:12345@192.168.1.33:554/0/av0
    - ffmpeg:rtsp://127.0.0.1:8554/rua_hd?audio=copy#audio=aac
```

When I use VLC to play `rtsp://<go2rtc>:8554/rua_hd`, the audio codec is:

![image](https://user-images.githubusercontent.com/29582865/214099420-40b3beb2-edcd-4bfd-9888-d9dcb7308a74.png)

Which is the first audio track from the stream sources.

I'm aware that I can add `?video=copy&audio=aac` to select the AAC audio, but this isn't applicable everywhere.

I'm proposing this as a cleaner solution for this issue:

- https://github.com/blakeblackshear/frigate-hass-integration/issues/418
