### ISSUE TITLE
Cuda Hardware Acceleration can only be used with max 3 stream

### ISSUE THREAD

**Issue by LckySndays** [AlexxIT/go2rtc#210]
Whenever I use Nvidia CUDA hardware acceleration ```#hardware=cuda``` it works properly up to 3 stream.
When I added the 4th stream with cuda, it failed with this log.
```
2023-01-26 14:51:36.772733997  14:51:36.772 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:52 > error="exec: exit status 1" url=ffmpeg:TestCam3#video=h264#audio=opus#hardware=cuda
2023-01-26 14:51:36.970781484  14:51:36.970 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:52 > error="exec: exit status 1" url=ffmpeg:TestCam3#video=h264#audio=opus#hardware=cuda
```
With 4 Cuda Stream, sometimes 3 stream can be loaded properly but sometime only 2. its not guarantee which stream will be loaded properly, kinda have race condition.
```
go2rtc version 1.0.1 linux/amd64
```

```yaml
mqtt:
  enabled: False
  
birdseye:
  enabled: False
  
detect:
  enabled: False

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  input_args: preset-rtsp-restream
  
go2rtc:
  streams:
    TestCam1: 
      - rtsp://user:pass@192.168.1.7/ch1/main/av_stream
      - ffmpeg:TestCam1#video=h264#audio=opus#hardware=cuda
    TestCam1Live: rtsp://localhost:8554/TestCam1?video=h264&audio=aac&audio=opus
    TestCam2: 
      - rtsp://user:pass@192.168.1.7/ch3/main/av_stream
      - ffmpeg:TestCam2#video=h264#audio=opus#hardware=cuda
    TestCam2Live: rtsp://localhost:8554/TestCam2?video=h264&audio=aac&audio=opus
    TestCam3: 
      - rtsp://user:pass@192.168.1.7/ch5/main/av_stream
      - ffmpeg:TestCam3#video=h264#audio=opus#hardware=cuda
    TestCam3Live: rtsp://localhost:8554/TestCam3?video=h264&audio=aac&audio=opus
    TestCam4: 
      - rtsp://user:pass@192.168.1.7/ch6/main/av_stream
      - ffmpeg:TestCam3#video=h264#audio=opus#hardware=cuda
    TestCam4Live: rtsp://localhost:8554/TestCam4?video=h264&audio=aac&audio=opus
  webrtc:
    candidates:
      - 192.168.1.109:8555
      - stun:8555
  log:
    level: error
      
cameras:
  TestCam1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/TestCam1?video=h264
    live:
      stream_name: TestCam1Live
      
  TestCam2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/TestCam2?video=h264
    live:
      stream_name: TestCam2Live

  TestCam3:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/TestCam3?video=h264
    live:
      stream_name: TestCam3Live

  TestCam4:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/TestCam4?video=h264
    live:
      stream_name: TestCam4Live
```

**Comment by AlexxIT** [comment]
Well. This is Nvidia problem. They have limitations on simultaneous transcoding. Based on GPU model. You can search advanced info in Google.

**Comment by LckySndays** [comment]
I tried to use CPU before and for my testing setup it managed to get all my core to roughly 75% (WebRTC delay around 0.5 sec).
Now. with this patch (https://github.com/keylase/nvidia-patch) I got around the GPU simultaneous transcoding limitation but my WebRTC hugely delayed (more than 6 sec)

**Comment by LckySndays** [comment]
https://github.com/AlexxIT/go2rtc/wiki/Hardware-acceleration stated that 
```yaml
streams:
  # auto select hardware encoder
  camera1_hw: ffmpeg:rtsp://rtsp:12345678@192.168.1.123/av_stream/ch0#video=h264#hardware
  
  # manual select hardware encoder (vaapi, cuda, v4l2m2m, dxva2, videotoolbox)
  camera1_vaapi: ffmpeg:rtsp://rtsp:12345678@192.168.1.123/av_stream/ch0#video=h264#hardware=vaapi
```

I tried all of the combination and can't go back to utilize my CPU unless I use ```hardware=libopus```
