### ISSUE TITLE
ffmpeg #width not working when not transcoding

### ISSUE THREAD

**Issue by LckySndays** [AlexxIT/go2rtc#219]
When not transcoding (same codec as source), the ffmpeg width and probably height parameter as well not working
```#video=h264#width=720``` , ```#video=copy#width=720```, ```#width=720```
```yaml
go2rtc:
  streams:
    TestCam1: 
      - rtsp://user:pass@192.168.1.194/Streaming/Channels/101 (h264)
      - ffmpeg:TestCam1#width=720#audio=opus 
```
```
go2rtc version 1.0.1 linux/amd64
```

**Comment by NickM-27** [comment]
that is expected, if you are going to change something about the stream you NEED to set a video encoding other than copy as the video will be decoded and reencoded to the specified video codec

**Comment by LckySndays** [comment]
so what should I use? I tried 3 combinations and all not working
```#video=h264#width=720``` set the encoding with same coding (other than copy as you mentioned)
```#video=copy#width=720``` set the encoding with copy
```#width=720``` not set the encoding at all

**Comment by NickM-27** [comment]
you have to name the stream something different, otherwise it will pick the track from the original stream which doesn't require ffmpeg since they are both h264

```yaml
go2rtc:
  streams:
    TestCam1: 
      - rtsp://user:pass@192.168.1.194/Streaming/Channels/101
    TestCam1_sub:
      - ffmpeg:TestCam1#video=h264#width=720#audio=opus 
```

works for me
