### ISSUE TITLE
go2rtc 1.1.1 in frigate ran for close to 3 hours then crashed

### ISSUE THREAD

**Issue by bagobones** [AlexxIT/go2rtc#237]
Config:

```
go2rtc:
  webrtc:
    candidates:
      - 192.168.102.30:8555
      - stun:8555
  streams:
    doorbell:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD2}@192.168.103.8:554
      - "ffmpeg:doorbell#audio=opus" # transcodes audio to opus for webrtc compatibility
    basement:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.103.4:554
      - "ffmpeg:basement#audio=opus" # transcodes audio to opus for webrtc compatibility
    living_room:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.103.5:554
      - "ffmpeg:living_room#audio=opus" # transcodes audio to opus for webrtc compatibility
    kitchen:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.103.7/live
      - "ffmpeg:kitchen#audio=opus#audio=aac" # transcodes audio to opus for webrtc compatibility
    basement_hall:
      - rtsp://tapo_admin:{FRIGATE_RTSP_PASSWORD}@192.168.103.145/stream1
      - "ffmpeg:basement_hall#audio=opus#audio=aac" # transcodes audio to opus for webrtc compatibility
    main_hall:
      - rtsp://tapo_admin:{FRIGATE_RTSP_PASSWORD}@192.168.103.225/stream1
      - "ffmpeg:main_hall#audio=opus#audio=aac" # transcodes audio to opus for webrtc compatibility
    garage_front:
      - http://192.168.103.3/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_RTSP_PASSWORD}
    backyard:
      - http://192.168.103.2/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_RTSP_PASSWORD}
```

go2rtc logs: https://pastebin.com/iX7PYAWC
