### ISSUE TITLE
WebRTC via Cloudflare Tunnel

### ISSUE THREAD

**Issue by nima-1102** [AlexxIT/go2rtc#251]
Hello,

I'm trying to reach WebRTC via Cloudflare Tunnel, unfortunately I can't get a connection.
Use the Cloudflared HA addon with a Remote Tunnel + WebRTC custom component. (on Home Assistant Operating System)

My current steps:

1. Added Hostname in Cloudflare Zero Trust - Tunnels (With the same tunnel which HomeAssistant also uses.)
Public hostname = "rtc.domain.tld"
Service = "TCP" :// "LAN-HA-IP:8880"

2. Added go2rtc.yaml Config File in my HA Config Folder:
```
api:
  listen: "127.0.0.1:1984" # localhost

rtsp:
  listen: "127.0.0.1:8554" # localhost

webrtc:
  listen: ":8880"
  candidates:
    - rtc.domain.tld:8880
    # - stun:8880  # dynamic public IP-address
```

I took port 8880 from here: https://developers.cloudflare.com/fundamentals/get-started/reference/network-ports/

Have also tested several other ports, etc., unfortunately without success.
Am I doing something wrong or is it not possible to route WebRTC through Cloudflare Tunnel?
