### ISSUE TITLE
Dahua VTO 2202F-P-S2 `codecs not match: H264,L16,VND.ONVIF.METADATA`

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/go2rtc#260]
Hello,

I have a [Dahua VTO 2202F-P-S2](https://www.dahuasecurity.com/products/productDetail/60597), and honestly, its RTSP interface is pretty bad. I can't change its audio codecs at all.

However, there is one problem that keeps happening:

- Every now and then, not every time, the doorbell simply decides to switch the audio codecs in its RTSP and this pops up in my go2rtc logs:

```
2023-02-14 18:10:56.264686479  15:10:56.264 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:52 > error="exec: exit status 1" url=ffmpeg:video_porteiro#audio=opus#audio=aac
2023-02-14 18:10:56.265367189  15:10:56.264 WRN [rtsp] error="codecs not match: H264,L16,VND.ONVIF.METADATA" stream=video_porteiro
```

This is how I have it configured:

```yaml
streams:
  video_porteiro:
    - rtsp://admin:<pass>@192.168.1.40/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    - "ffmpeg:video_porteiro#audio=opus#audio=aac"
```

The second the contains both opus and AAC because that was the attempt to filter the audio so it works even when the doorbell supplies L16 audio codec. But it actually keeps issuing the same error in my logs.

So... I don't know. Maybe there is something that can be done in go2rtc itself to better handle this (just a hope)?

Note that I can't use the solution presented in https://github.com/AlexxIT/go2rtc/issues/49 to change the codec using an echo source. When I do that, audio stops working over SIP/Asterisk, which is the main function of the doorbell.
