### ISSUE TITLE
WebRTC works but RTSP does not

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/go2rtc#272]
I'm streaming from a Hikvision DVR into go2rtc, and WebRTC works but consuming its RTSP does not work. The following happens:

https://user-images.githubusercontent.com/29582865/221070995-3063b961-6c42-469b-8bc5-e3324f8a09b3.mp4

Which is also causing Frigate to fail with:

```
ffmpeg.chafariz.detect         ERROR   : rtsp://127.0.0.1:8554/chafariz?video=copy: Connection refused
```

Config:

```yaml
rtsp:
  default_query: mp4
go2rtc:
  streams:
    chafariz:
      - rtsp://admin:pass@192.168.1.12:554/Streaming/Channels/501
```

If I add `ffmpeg:` to this stream then this error does not happen, but the stream becomes very buggy like it goes forward and behind, gives me some green screens and so on.
