### ISSUE TITLE
MSE player can't play Big Buck Bunny stream

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/go2rtc#275]
```yaml
streams:
  demo:
    - rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4
```

Audio works fine, but the video apparently stops at the first frame.

https://user-images.githubusercontent.com/29582865/221618182-1f797f05-18a2-4915-b296-4a0f8989b7c8.mp4

The issue seems to be only applicable to the MSE player, since viewing it from VLC (rtsp://192.168.1.10:8554/demo) works just fine.
