### ISSUE TITLE
Remote Access

### ISSUE THREAD

**Issue by ItsJamesMurray** [AlexxIT/go2rtc#29]
Hello friends —

I've setup go2rtc and am able to view my homeassistant generic camera card on my local network on desktop and mobile (when connected to the same internet connection as the server my go2rtc instance is on).

However, when trying to view from my homeassistant app on MOBILE data i have no luck.  I get the following error in the logs:

```
21:57:51.786 DBG [webrtc] stun public address addr=MYIPV6ADDRESS:8554
21:57:51.786 WRN [webrtc] candidate error="address MYIPV6ADDRESS:8554: too many colons in address"
```

In my `go2rtc.yaml` i have the following (tried to follow the docs to a T):
```yaml
webrtc:
  listen: ":8554"  # address of your local server (TCP)
  candidates:
    - stun:8554  # if you have dynamic public IP-address

streams:
  camera_1: rtsp://user:pass@mycamIP:554/cam/realmonitor?channel=1&subtype=1
  camera_2: rtsp://user:pass@mycamIP:554/cam/realmonitor?channel=2&subtype=1
  camera_3: rtsp://user:pass@mycamIP:554/cam/realmonitor?channel=3&subtype=1

log:
  level: info # default level
  api: trace
  exec: debug
  ngrok: info
  rtsp: debug
  streams: debug
  webrtc: debug
```

I've also port forwarded port 8554 on my router for the server with go2rtc.  I access my homeassistant through a custom domain using cloudflare for dynamic dns routing if that matters.

Any idea what I could be doing wrong?

**Comment by AlexxIT** [comment]
You shouldn't select 8554 port. It is for RTSP

**Comment by ItsJamesMurray** [comment]
Ahhh thank you!  I've changed my yaml to the following and it seems to be working as intended.

```yaml
webrtc:
  listen: ":8555"  # address of your local server (TCP)
  candidates:
    - stun:8555  # if you have dynamic public IP-address

...
```

**Comment by AndLindemann** [comment]
I'd like to reopen this. Even with the STUN server, it sometimes returns my external IPv6 address (which should be fine - I have a dual-stack connection with both IPv4 and IPv6 addresses) and then I get the same error as the OP, "too many colons in address".
So it seems using STUN likely won't work reliably if you have both IPv4 and IPv6 public addresses, unless the STUN server can be convinced to only report back IPv4 addresses.

```
15:06:39.117 DBG [webrtc] stun public address addr=2003:a4:7687:3010::1610:8557
15:06:39.118 WRN [webrtc] candidate error="address 2003:a4:7687:3010::1610:8557: too many colons in address"

```

```
webrtc:
  listen: ":8557"
  candidates:
    - stun:8557

```
@AlexxIT
