### ISSUE TITLE
Restreaming a region (cropping) from a source stream does not work

### ISSUE THREAD

**Issue by uklatt** [AlexxIT/go2rtc#299]
I try to create a new rtsp stream out of an existing stream.
This is my yaml file:

```
go2rtc:
  streams:
    cam1: rtsp://192.168.180.94/11
    cam1_crop: ffmpeg:rtsp://192.168.180.94/11#video=h264#hardware#raw=-vf crop=800:600:640:100
```
The source stream is a h264 stream.

When I try to open the new stream I get the following error message:
`WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF`

I'm using the Frigate 0.12.0-e454daf Docker image on an Intel CPU with vaapi hardware codecs.

Uwe
