### ISSUE TITLE
Transcoded ffmpeg audio not working in 1.3.1

### ISSUE THREAD

**Issue by Mr-HaleYa** [AlexxIT/go2rtc#309]
I'm using a Reolink E1 Zoom and HassOS on an i5-6500T mini Pc

I was using the WebRTC Camera integration that has go2rtc 1.2.0 and had the go2rtc config set like this 

```
streams:
  lvrm_cam:
    - rtsp://admin:password@192.168.50.164:554/h264Preview_01_main
    - ffmpeg:rtsp://admin:password@192.168.50.164:554/h264Preview_01_main#audio=opus

rtsp:
  listen: ":8554"
  default_query: "video&audio=opus"


webrtc:
  listen: ":8555"
  candidates:
    - stun:8555
```

this works great for getting an RTC connection and audio out of the webRTC Lovelace card

```
type: custom:webrtc-camera
entity: camera.lvrm_cam
poster: null
ui: true
muted: true
mode: webrtc
```

I wanted to try out the go2rtc 1.3.0 to see if it would fix my problems with connecting outside the network and it did. I uninstalled WebRTC Camera and installed go2rtc 1.3.0 then reinstalled WebRTC Camera and it identified the rtsp server of go2rtc when adding the integration and everything worked, I had less than 1-sec latency from 3 states away. Everything except audio... I read through both the go2rtc forum post and the WebRTC camera forum post and messed with it for 11+ hours and no matter what I do I can't get audio in the WebRTC Camera card. 

I can get audio in the `camera.lvrm_cam` stream in the UI but when I add that entity to the card it creates a new stream in the UI `lvrm_cam` and that stream has no audio. 

All streams do have audio in MSE mode just nothing in RTC

Any help would be appreciated
