### ISSUE TITLE
basebath breaks ingress panel

### ISSUE THREAD

**Issue by calisro** [AlexxIT/go2rtc#32]
When using something like this in the go2rtc config, the ingress panel in HA is broken for go2rtc.  The basepath should be added to the panel.

api:
  base_path: "/webrtc"

**Comment by AlexxIT** [comment]
I don't think this is bug. Because you shouldn't use base path with Hass ingress. It's for another tasks.

**Comment by calisro** [comment]
I'm using the basepath so I can piggyback on the nginx proxy manager config to have the api under https on the /webrtc location.  Unfortunately that makes it so I can't access via ingress.  Was hoping to have both.  But I'll just create a panel for now.

```
panel_iframe:
  go2rtc:
    title: "GotoRTC"
    url: "https://hass.xxxxxxx.xxx/webrtc/"
    icon: mdi:cctv
```
