### ISSUE TITLE
Transcoding H265 to H264 isn't working?  (re: Chrome + Frigate + Dahua)

### ISSUE THREAD

**Issue by sofakng** [AlexxIT/go2rtc#363]
I'm using Frigate with go2rtc and Dahua cameras set to H265.

I'm recording 24/7 so I'd like to use the camera H265 output to save disk space but my browser (Chrome) doesn't support WebRTC H265 (and I can't use MSE because iOS doesn't support it)

It should be possible for go2rtc to support H265 (native stream) and H265 (ffmpeg transcode), right?

Here is my configuration:
```
go2rtc:
  streams:
    frontdoor:
      - rtsp://redacted:redacted@192.168.20.2:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:rtsp://redacted:redacted@192.168.20.2:554/cam/realmonitor?channel=1&subtype=0
```

However, when I open the WebRTC stream I do not have any video.  (if I change the camera to H264 then the video works)

Can anybody help me or give me any suggestions?

My goal is to use H265 from the camera to save disk (and not use the CPU/GPU to transcode my 24/7 recording) and also use my Chrome browser and iOS devices for streaming (with audio).
