### ISSUE TITLE
Remote WebRTC not working with Ngrok

### ISSUE THREAD

**Issue by luisiam** [AlexxIT/go2rtc#367]
I am running frigate with go2rtc. I bind mount the ngrok binary so that I can enable ngrok. I am accessing my frigate/go2rtc instance with cloudflare tunnelling. However, I cannot get webrtc streaming remotely. I only see this warning in the log:
```
11:45:12.412 WRN error="websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header"
```

This is my config:
```
go2rtc:
  ngrok:
    command: /config/ngrok tcp 8555 --authtoken 2Mmx5UnqEp4fn3Ru8cEX7TTzJ2x_4ACHb9nEJEQSNvpt6bNgo
  streams:
    backyard:
      - ffmpeg:http://192.168.10.24/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_RTSP_USERNAME}&password={FRIGATE_RTSP_PASSWORD}
      - ffmpeg:backyard#audio=opus
      - http://192.168.10.24/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=go2rtc&user={FRIGATE_RTSP_USERNAME}&password={FRIGATE_RTSP_PASSWORD}
    backyard_sub:
      - ffmpeg:http://192.168.10.24/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_RTSP_USERNAME}&password=
  webrtc:
    listen: ":8555"
    candidates:
      - 192.168.10.3:8555
      - stun:8555
```
I did not do any port forwarding in the router. I believe that's not needed if I am using ngrok. Please correct me if I am wrong.
