### ISSUE TITLE
What's a recommended way to watch streams outside of the network?

### ISSUE THREAD

**Issue by mortenmoulder** [AlexxIT/go2rtc#37]
Hi - first off I wanna say, that this is great work. Both go2rtc and WebRTC is really great. However, my wife has a problem with her iPhone and the Home Asisstant companion app: She cannot view the WebRTC cameras outside of our network, and sometimes not on our network either. My Android phone can easily view the cameras. What my wife tends to do, is open the TuYa app we have for one of our Sonoff cameras and use that. It's not great, because only 1 of our cameras is in that app.

Our RTSP cameras are set up like this in Home Assistant (Dahua and Sonoff):

```
type: custom:webrtc-camera
url: rtsp://cam:cam@192.168.1.111:554/live
```

I've now tried go2rtc and I'm guessing it's the same, because of how Home Assistant proxies the network traffic from the cameras.

I want my wife to be able to open an app (or browser) and view all of our cameras nice and easily in one app. I have the following stuff to help:

- Home Assistant
- Unraid on a server (meaning I can spawn any VM or Docker container)
- I'm a web developer, so creating a page with the streams on it is not a problem
- I have a domain and can easily do proxying to that domain

What would you recommend? Obviously keeping it in Home Assistant would be the best, so we have everything in one place, but I honestly cannot figure out why her phone cannot view the streams, so I'm forced to find an alternative.

**Comment by AlexxIT** [comment]
[WebRTC](https://github.com/AlexxIT/go2rtc#module-webrtc)

**Comment by mortenmoulder** [comment]
@AlexxIT Yes, I read that. I'm asking what you would do. Setting up Ngrok would be pointless, seeing I already have a domain and the option to easily proxy the traffic to that domain. Is it a pretty solution? Absolutely not. That's what I want. I want an user friendly way of showing the cameras instantly either via an app or a website. Something static that never changes, like the URL to Ngrok does (unless I pay for it).

**Comment by AlexxIT** [comment]
WebRTC technology can't use your "domain" HTTP or HTTPS port. It should own personal port for media data. The way how you setup this port depends on your network configuration. For static or dynamic public IP address you do not need to use Ngrok. You need to read docs more carfelly.

**Comment by cataseven** [comment]
> Hi - first off I wanna say, that this is great work. Both go2rtc and WebRTC is really great. However, my wife has a problem with her iPhone and the Home Asisstant companion app: She cannot view the WebRTC cameras outside of our network, and sometimes not on our network either. My Android phone can easily view the cameras. What my wife tends to do, is open the TuYa app we have for one of our Sonoff cameras and use that. It's not great, because only 1 of our cameras is in that app.
> 
> Our RTSP cameras are set up like this in Home Assistant (Dahua and Sonoff):
> 
> ```
> type: custom:webrtc-camera
> url: rtsp://cam:cam@192.168.1.111:554/live
> ```
> 
> I've now tried go2rtc and I'm guessing it's the same, because of how Home Assistant proxies the network traffic from the cameras.
> 
> I want my wife to be able to open an app (or browser) and view all of our cameras nice and easily in one app. I have the following stuff to help:
> 
> * Home Assistant
> * Unraid on a server (meaning I can spawn any VM or Docker container)
> * I'm a web developer, so creating a page with the streams on it is not a problem
> * I have a domain and can easily do proxying to that domain
> 
> What would you recommend? Obviously keeping it in Home Assistant would be the best, so we have everything in one place, but I honestly cannot figure out why her phone cannot view the streams, so I'm forced to find an alternative.

https://github.com/AlexxIT/go2rtc/issues/38

Just use picture glance or picture element card after go2rtc integration. (I am using Elements)

**Comment by mortenmoulder** [comment]
@AlexxIT Okay, I don't think you understand what I am asking here.

I want an app where I can open the app and instantly view the cameras I have. Alternatively a web page with each camera embedded. As explained in the post, Home Assistant is not an option because of how it proxies the network (won't work outside of my local network, but ONLY on my wife's phone).

Shinobi is an example of an app that can do most of what go2rtc can do, but they also have an app or alternatively if you port forward their web UI, you can log into your account from the outside and view your cameras that way. go2rtc doesn't have a nice frontend or an app I can open to view my cameras, and that's exactly what I am looking for.

**Comment by mortenmoulder** [comment]
@cataseven No, as I said before, Home Assistant cannot proxy the feed to my wife's iPhone in the companion app. My iPad had the same issue through the browser as well. Not sure if it's an iOS issue, though.

**Comment by AlexxIT** [comment]
Well. What iOS version we talking about?

**Comment by mortenmoulder** [comment]
@AlexxIT iOS 15.6.1. I also experience some glitching on Windows in Chrome with webrtc, but I also did that with picture glance and the RTSP stream, so I doubt the issue is with anything you have created, but rather how Home Assistant does the proxying. I'm running HA in Docker on a server with a 3900X, 32GB RAM, and NVMe SSD, so I doubt the reason is hardware.

**Comment by cataseven** [comment]
> @cataseven No, as I said before, Home Assistant cannot proxy the feed to my wife's iPhone in the companion app. My iPad had the same issue through the browser as well. Not sure if it's an iOS issue, though.

I tried with my wife's iphone right now. It is working. I have an android phone and all settings are same for both iphone and android. No problem with iphone.

Here is my config

- deleted rtsptoweb add on.
- deleted webrtc integration
- deleted motion eye add on
- deleted all folders remainnin config folder related to above addons
- installed go2rtc
- created generic cams with rtsp links. Generic cam settings: tcp or udp, frame rate: 24, auth: basic, verify ssl: false, username: null, password:null, rtsp links of cameras taken from onvif manager
- picture glance card

No problem for iphone 11.

Btw, ı am not a developer, i have limited technical knowledge, may be ı couldnt understand your problem but I can view 3 cameras on iphone 11 via home assiststant app. Hope this helps

**Comment by mortenmoulder** [comment]
@cataseven Does it also work while on mobile network? Outside of your own network and own WiFi.

**Comment by AlexxIT** [comment]
It may not work outside your network if you don't do anything with your setup!

**Comment by cataseven** [comment]
> @cataseven Does it also work while on mobile network? Outside of your own network and own WiFi.

It is working for both phones via mobile data

**Comment by mortenmoulder** [comment]
@AlexxIT What do you mean? Home Assistant is running on a subdomain and is very public. It works fine on my Android phone, as I've said a few times now.

@cataseven Okay, that's odd. So you use a picture glance card, and you just use go2rtc with the example from your own issue #38 ? Then I'm not sure where the problem is, because I've tried the exact same thing.

**Comment by cataseven** [comment]
I will create a backup and try to understand :) If @AlexxIT says "It should not work" probably I forget something to delete somewhere. I will write to u if I found something

**Comment by cataseven** [comment]
> @AlexxIT What do you mean? Home Assistant is running on a subdomain and is very public. It works fine on my Android phone, as I've said a few times now.
> 
> @cataseven Okay, that's odd. So you use a picture glance card, and you just use go2rtc with the example from your own issue #38 ? Then I'm not sure where the problem is, because I've tried the exact same thing.

Deleted everthing and tried. No problem via mobile data once again. My cameras connected via etherhet cable directly to my router. I remember that wifi connection creates problem even it has a strong signal connection.

My Camera (Cheap Chinese Cam)
![2022-09-12 11_03_14-fjramirez1987_PTZ-YCC365](https://user-images.githubusercontent.com/52464808/189603332-86d610a5-e878-468d-b674-4bf0c6283845.png)

My Add-on page
![2022-09-12 11_05_48-Home Assistant](https://user-images.githubusercontent.com/52464808/189603488-d8447ca3-4792-4cb3-92f9-758a335da16c.png)

Add-on Repos
![2022-09-12 11_07_01-Home Assistant](https://user-images.githubusercontent.com/52464808/189603735-f2170308-afa5-41b1-8d6b-c4eccfcb57b9.png)

My Integrations
![2022-09-12 11_07_44-Settings – Home Assistant](https://user-images.githubusercontent.com/52464808/189604389-7ff40733-1435-4f8d-8539-07f20de87597.png)

Generic Cam Settings: It "sometimes" takes 5-10 seconds to start (Maybe you should use UDP)
![2022-09-12 11_11_33-Settings – Home Assistant](https://user-images.githubusercontent.com/52464808/189604641-5c8f67b9-81f1-4b7c-abc6-7d4661cd2b03.png)

I am using ptz-ycc365 add on to control camera movement
https://github.com/fjramirez1987/PTZ-YCC365

I only added go2rtc.yaml
![2022-09-12 11_18_03-Studio Code Server – Home Assistant](https://user-images.githubusercontent.com/52464808/189605869-f02a6135-5803-4b00-b87d-0199fd77c90b.png)


My card config:

```
......... bla bla bla

          - type: picture-elements
            camera_view: live
            camera_image: camera.frontyard
            elements:
              - type: icon
                icon: mdi:arrow-left-drop-circle
                tap_action:
                  action: call-service
                  service: ptz_camera.move_left
                  service_data:
                    host: 192.168.1.143
                style:
                  bottom: 45%
                  left: 2%
                  color: white
                  opacity: 1
                  transform: scale(1.25, 1.25)
              - type: icon
                icon: mdi:arrow-right-drop-circle
                tap_action:
                  action: call-service
                  service: ptz_camera.move_right
                  service_data:
                    host: 192.168.1.143
                style:
                  bottom: 45%
                  right: 2%
                  color: white
                  opacity: 1
                  transform: scale(1.25, 1.25)
              - type: icon
                icon: mdi:arrow-up-drop-circle
                tap_action:
                  action: call-service
                  service: ptz_camera.move_up
                  service_data:
                    host: 192.168.1.143
                style:
                  top: 2%
                  left: 46%
                  color: white
                  opacity: 1
                  transform: scale(1.25, 1.25)
              - type: icon
                icon: mdi:arrow-down-drop-circle
                tap_action:
                  action: call-service
                  service: ptz_camera.move_down
                  service_data:
                    host: 192.168.1.143
                style:
                  bottom: 2%
                  left: 46%
                  color: white
                  opacity: 1
                  transform: scale(1.25, 1.25)
              - type: icon
                icon: mdi:fullscreen
                tap_action:
                  action: more-info
                entity: camera.frontyard
                style:
                  top: 1%
                  right: 2%
                  color: white
                  opacity: 0.5
                  transform: scale(1.25, 1.25)

...... bla bla bla
```
