### ISSUE TITLE
Choose video resolution

### ISSUE THREAD

**Issue by chip131001** [AlexxIT/go2rtc#375]
Hello,
I have a configuration with 2 video streams and 1 audio stream.

The first video stream has a resolution of 1920x1080, the second has 640x360.

How can I select a video stream?

<img width="1700" alt="Bildschirmfoto 2023-04-20 um 17 50 05" src="https://user-images.githubusercontent.com/38818613/233420071-796f1f49-905f-494d-a7e0-bcc7d451f14d.png">

**Comment by AlexxIT** [comment]
You have configuration with 3 sources and 1 stream.
Just make configuration with 2 streams and select any of them

**Comment by chip131001** [comment]
you mean like that?

<img width="1700" alt="Bildschirmfoto 2023-04-20 um 18 30 52" src="https://user-images.githubusercontent.com/38818613/233430255-cc605b4d-c622-490e-a276-2a28b7c0e193.png">

So audio is transcoded 2 times. I would like to achieve the audio is transcoded only once.

**Comment by AlexxIT** [comment]
So make three streams and add audio stream as source for two main streams. It will be RTSP loopback connection.

**Comment by chip131001** [comment]
Ok I understand. Can you show me an example please?

**Comment by AlexxIT** [comment]
something like this
```yaml
streams:
  audio: exec:ffmpeg -f alsa...
  video1:
    - exec:ffmpeg...
    - rtsp://localhost:8554/audio
  video2:
    - exec:ffmpeg...
    - rtsp://localhost:8554/audio
```
