### ISSUE TITLE
Problem to get a variant of the ESP32Cam working

### ISSUE THREAD

**Issue by AussiSG** [AlexxIT/go2rtc#381]
So I'm currently trying to get my camera's which I use in frigate to take use of Go2RTC.
Sadly enough one of camera's is struggling to work with it.

It's a variant of an Esp32cam running Esphome and I enabled the stream on it on port :8080.

This is my config at the moment:

``` yaml
go2rtc:
  streams:
    front1: # <- for RTSP streams
      - rtsp://xxxxxxxx:554/ # <- stream which supports video & aac audio
    doorbell: # <- for other streams
      - "ffmpeg:http://xxxxxxxxxx::8080/?width=800&height=600#video=h264"
  webrtc:
    candidates:
      - xxxxxxxxxxxx:8555
      - xxxxxxxxxxxx:8555
  log:
    exec: trace
``` 
I've also tried - "ffmpeg:http://xxxxxxxxxx::8080/?width=800&height=600#video=h264#hardware"

But also no success.

Checking the log files gives met the following after implementing the following in the stream part 

```
"exec:ffmpeg -hide_banner -fflags nobuffer -flags low_delay -i http://xxxxxxxxxxx:8080/?width=800&height=600 -c:v libx264 -g 50 -profile:v high -level:v 4.1 -preset:v superfast -tune:v zerolatency -an -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://localhost:8554/9adf881d5b6cc08c3a6d698a88fd197d\"
```

https://pastebin.com/pjxT0AWx

**Comment by AlexxIT** [comment]
I think you need to add `#raw=-pix_fmt yuv420p`
Also hardware transcoding not worked for you.

**Comment by AussiSG** [comment]
Thanks for the reply. 
Not sure where to put that part you mentioned?

I've put it in the exec line like this:

``` yaml
go2rtc:
  streams:
    front1: # <- for RTSP streams
      - rtsp://192.168.0.17:554/ # <- stream which supports video & aac audio
    doorbell: # <- for other streams
      - exec:ffmpeg -hide_banner -fflags nobuffer -flags low_delay -i http://xxxxxxxxx:8080/?width=800&height=600 _**raw=-pix_fmt yuv420p**_ -c:v libx264 -g 50 -profile:v high -level:v 4.1 -preset:v superfast -tune:v zerolatency -an -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://localhost:8554/9adf881d5b6cc08c3a6d698a88fd197d\
  webrtc:
    candidates:
      - 192.168.0.14:8555
  log:
    exec: trace
````

**Comment by AussiSG** [comment]
@AlexxIT  have tried several places to put `#raw=-pix_fmt yuv420p` but not sure if i'm doing it at the correct position.
Could please clarify were to use it ?

**Comment by AlexxIT** [comment]
```
go2rtc:
  streams:
    doorbell: # <- for other streams
      - "ffmpeg:http://xxxxxxxxxx::8080/?width=800&height=600#video=h264#raw=-pix_fmt yuv420p"
```
