### ISSUE TITLE
Unclear how to set the ffmpeg input="rtsp/udp" option in go2rtc.yaml

### ISSUE THREAD

**Issue by dlavrantonis** [AlexxIT/go2rtc#386]
I'm talking about this: 

_You can use input param to override default input template (ex. #input=rtsp/udp will change RTSP transport from TCP to UDP+TCP)_

Please share an example on how to configure this in go2rtc.yaml. 
E.g. tried
`ffmpeg:
  myinput: "input=rtsp/udp"`

but it doesnt work.

https://github.com/AlexxIT/go2rtc#:~:text=You%20can%20use%20input%20param%20to%20override%20default%20input%20template%20(ex.%20%23input%3Drtsp/udp%20will%20change%20RTSP%20transport%20from%20TCP%20to%20UDP%2BTCP

**Comment by NickM-27** [comment]
you would do it like this:

```
  ffmpeg:
    rtsp/udp: "-rtsp_transport udp"
```

**Comment by AlexxIT** [comment]
rtsp/udp preset already build-in
https://github.com/AlexxIT/go2rtc/blob/e3f6c459c7580b83e2f605af4649401c1148e737/cmd/ffmpeg/ffmpeg.go#L51

```yaml
sources:
  camera1: ffmpeg:rtsp://...#input=rtsp/udp
```

**Important!** If you using docker - container with go2rtc SHOULD have network host option.

**Comment by dlavrantonis** [comment]
thanks!

**Comment by ivanjx** [comment]
@AlexxIT is it possible to use `minport` and `maxport` arguments for the ffmpeg input? i used to do that before so i dont need to make my container to have host network.

**Comment by ivanjx** [comment]
i think i kind of figured it out but not sure if this is correct:
```yaml
go2rtc:
    ffmpeg:
        caminput1: "-avoid_negative_ts make_zero -err_detect aggressive -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -rtsp_transport udp -min_port 5011 -max_port 5015 -i {input}"
        caminput2: "-avoid_negative_ts make_zero -err_detect aggressive -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -rtsp_transport udp -min_port 5016 -max_port 5020 -i {input}"
    streams:
        cam1:
            - "ffmpeg:rtsp://user:pass@192.168.1.21/stream1#input=caminput1#video=copy#audio=aac"
        cam2:
            - "ffmpeg:rtsp://user:pass@192.168.1.22/stream1#input=caminput2#video=copy#audio=aac"
```
