### ISSUE TITLE
rotate stream with haccel not working

### ISSUE THREAD

**Issue by caublet** [AlexxIT/go2rtc#389]
```
go2rtc:
  streams:
    Side:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.23:554/Streaming/Channels/1
      - "ffmpeg:Side#audio=aac"
    Side_Rotated:
      - "ffmpeg:Side#video=h264#rotate=90#hardware"
```
```
Error : ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url=ffmpeg:Side#video=h264#rotate=90#hardware
```

**Comment by NickM-27** [comment]
you'll need to enable trace logs for exec so the ffmpeg crash log is visible

**Comment by caublet** [comment]
not sure how to do this through Frigate... :\

**Comment by NickM-27** [comment]
```yaml
go2rtc:
  log:
    exec: trace

  streams:
    Side:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.23:554/Streaming/Channels/1
      - "ffmpeg:Side#audio=aac"
    Side_Rotated:
      - "ffmpeg:Side#video=h264#rotate=90#hardware"
```

**Comment by caublet** [comment]
2023-04-27 14:11:49.510054034  14:11:49.509 DBG [exec] run url="exec:ffmpeg -hide_banner -hwaccel cuda -hwaccel_output_format cuda -extra_hw_frames 2 -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_transport tcp -i rtsp://localhost:8554/Side?video -c:v h264_nvenc -g 50 -profile:v high -level:v auto -preset:v p2 -tune:v ll -an -vf transpose=1 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://localhost:8554/ca6170ccc6f47777b83f3ba8e420fff9"
2023-04-27 14:11:54.155157536  192.168.1.106 - - [27/Apr/2023:14:11:54 -0400] "GET /live/webrtc/api/ws?src=Side_Rotated HTTP/1.1" 101 149 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
2023-04-27 14:11:54.164761688  192.168.1.106 - - [27/Apr/2023:14:11:54 -0400] "GET /favicon.ico HTTP/1.1" 200 6641 "http://192.168.1.15:5000/live/webrtc/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
2023-04-27 14:11:54.776108105  frame=  772 fps= 15 q=-1.0 size=N/A time=00:00:53.45 bitrate=N/A speed=1.04x    
size=N/A time=00:00:51.37 bitrate=N/A speed=0.997x    
size=N/A time=00:00:51.36 bitrate=N/A speed=0.996x    
size=N/A time=00:00:53.54 bitrate=N/A speed=0.997x    
frame=  778 fps= 15 q=-1.0 size=N/A time=00:00:53.91 bitrate=N/A speed=1.04x    
size=N/A time=00:00:53.80 bitrate=N/A speed=0.997x    
frame=  779 fps= 15 q=-1.0 size=N/A time=00:00:53.96 bitrate=N/A speed=1.04x    
size=N/A time=00:00:51.88 bitrate=N/A speed=0.997x    
size=N/A time=00:00:51.86 bitrate=N/A speed=0.996x    
size=N/A time=00:00:54.05 bitrate=N/A speed=0.996x    
frame=  786 fps= 15 q=-1.0 size=N/A time=00:00:54.41 bitrate=N/A speed=1.04x    
size=N/A time=00:00:54.31 bitrate=N/A speed=0.997x    
frame=  787 fps= 15 q=-1.0 size=N/A time=00:00:54.48 bitrate=N/A speed=1.04x    
size=N/A time=00:00:52.40 bitrate=N/A speed=0.996x    
size=N/A time=00:00:52.56 bitrate=N/A speed=   1x    
size=N/A time=00:00:54.56 bitrate=N/A speed=0.996x    
frame=  794 fps= 15 q=-1.0 size=N/A time=00:00:54.92 bitrate=N/A speed=1.04x    
size=N/A time=00:00:54.82 bitrate=N/A speed=0.997x    
frame=  795 fps= 15 q=-1.0 size=N/A time=00:00:55.00 bitrate=N/A speed=1.04x    
size=N/A time=00:00:53.02 bitrate=N/A speed=0.998x    
size=N/A time=00:00:52.90 bitrate=N/A speed=0.995x    
size=N/A time=00:00:55.08 bitrate=N/A speed=0.995x    
frame=  801 fps= 15 q=-1.0 size=N/A time=00:00:55.52 bitrate=N/A speed=1.04x    
size=N/A time=00:00:55.33 bitrate=N/A speed=0.997x    
frame=  803 fps= 15 q=-1.0 size=N/A time=00:00:55.52 bitrate=N/A speed=1.04x    
size=N/A time=00:00:53.54 bitrate=N/A speed=0.998x    
size=N/A time=00:00:53.57 bitrate=N/A speed=0.998x    
size=N/A time=00:00:55.59 bitrate=N/A speed=0.995x    
frame=  809 fps= 15 q=-1.0 size=N/A time=00:00:55.98 bitrate=N/A speed=1.04x    
size=N/A time=00:00:55.84 bitrate=N/A speed=0.997x    
frame=  810 fps= 15 q=-1.0 size=N/A time=00:00:56.04 bitrate=N/A speed=1.04x    
size=N/A time=00:00:54.08 bitrate=N/A speed=0.998x    
size=N/A time=00:00:54.04 bitrate=N/A speed=0.997x    
size=N/A time=00:00:56.23 bitrate=N/A speed=0.997x    
size=N/A time=00:00:56.36 bitrate=N/A speed=0.997x    
frame=  818 fps= 15 q=-1.0 size=N/A time=00:00:56.53 bitrate=N/A speed=1.04x    
frame=  818 fps= 15 q=-1.0 size=N/A time=00:00:56.56 bitrate=N/A speed=1.04x    
size=N/A time=00:00:54.57 bitrate=N/A speed=0.998x    
size=N/A time=00:00:54.58 bitrate=N/A speed=0.997x    
size=N/A time=00:00:56.74 bitrate=N/A speed=0.997x    
frame=  825 fps= 15 q=-1.0 size=N/A time=00:00:57.00 bitrate=N/A speed=1.03x    
size=N/A time=00:00:56.87 bitrate=N/A speed=0.997x    
frame=  826 fps= 15 q=-1.0 size=N/A time=00:00:57.04 bitrate=N/A speed=1.03x    
size=N/A time=00:00:55.07 bitrate=N/A speed=0.997x    
size=N/A time=00:00:55.08 bitrate=N/A speed=0.997x    
size=N/A time=00:00:57.25 bitrate=N/A speed=0.996x    
frame=  833 fps= 15 q=-1.0 size=N/A time=00:00:57.56 bitrate=N/A speed=1.04x    
frame=  834 fps= 15 q=-1.0 size=N/A time=00:00:57.56 bitrate=N/A speed=1.03x    
size=N/A time=00:00:57.38 bitrate=N/A speed=0.996x    
size=N/A time=00:00:55.72 bitrate=N/A speed=0.999x    
size=N/A time=00:00:55.63 bitrate=N/A speed=0.997x    
size=N/A time=00:00:57.76 bitrate=N/A speed=0.996x    
frame=  841 fps= 15 q=-1.0 size=N/A time=00:00:58.04 bitrate=N/A speed=1.03x    
frame=  840 fps= 15 q=-1.0 size=N/A time=00:00:58.12 bitrate=N/A speed=1.04x    
size=N/A time=00:00:58.02 bitrate=N/A speed=0.998x    
size=N/A time=00:00:56.22 bitrate=N/A speed=0.998x    
size=N/A time=00:00:56.13 bitrate=N/A speed=0.996x    
size=N/A time=00:00:58.28 bitrate=N/A speed=0.996x    
frame=  849 fps= 15 q=-1.0 size=N/A time=00:00:58.60 bitrate=N/A speed=1.03x    
frame=  849 fps= 15 q=-1.0 size=N/A time=00:00:58.62 bitrate=N/A speed=1.03x    
size=N/A time=00:00:58.53 bitrate=N/A speed=0.998x    
Input #0, rtsp, from 'rtsp://localhost:8554/Side?video':
2023-04-27 14:11:54.776113788    Metadata:
2023-04-27 14:11:54.776115135      title           : go2rtc/1.2.0
2023-04-27 14:11:54.776116357    Duration: N/A, bitrate: N/A
2023-04-27 14:11:54.776150301    Stream #0:0: Video: h264 (Baseline), yuvj420p(pc, bt709, progressive), 3072x1728, 15 fps, 15 tbr, 90k tbn
2023-04-27 14:11:54.854256789  Stream mapping:
2023-04-27 14:11:54.854262504    Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_nvenc))
2023-04-27 14:11:54.854263733  Press [q] to stop, [?] for help
2023-04-27 14:11:56.165052069  size=N/A time=00:00:56.74 bitrate=N/A speed=0.999x    
size=N/A time=00:00:56.75 bitrate=N/A speed=0.998x    
size=N/A time=00:00:58.79 bitrate=N/A speed=0.995x    
frame=  856 fps= 15 q=-1.0 size=N/A time=00:00:59.08 bitrate=N/A speed=1.03x    
frame=  856 fps= 15 q=-1.0 size=N/A time=00:00:59.17 bitrate=N/A speed=1.03x    
size=N/A time=00:00:59.04 bitrate=N/A speed=0.998x    
size=N/A time=00:00:57.13 bitrate=N/A speed=0.996x    
size=N/A time=00:00:57.26 bitrate=N/A speed=0.998x    
frame=  864 fps= 15 q=-1.0 size=N/A time=00:00:59.65 bitrate=N/A speed=1.03x    
size=N/A time=00:00:59.43 bitrate=N/A speed=0.997x    
frame=  864 fps= 15 q=-1.0 size=N/A time=00:00:59.64 bitrate=N/A speed=1.03x    
size=N/A time=00:00:59.56 bitrate=N/A speed=0.998x    
size=N/A time=00:00:57.63 bitrate=N/A speed=0.995x    
size=N/A time=00:00:57.76 bitrate=N/A speed=0.997x    
size=N/A time=00:00:59.81 bitrate=N/A speed=0.995x    
Impossible to convert between the formats supported by the filter 'graph 0 input from stream 0:0' and the filter 'auto_scale_0'
2023-04-27 14:11:56.166695527  Error reinitializing filters!
2023-04-27 14:11:56.166699081  Failed to inject frame into filter network: Function not implemented
2023-04-27 14:11:56.166700543  Error while processing the decoded data for stream #0:0
2023-04-27 14:11:56.192670401  frame=  872 fps= 15 q=-1.0 size=N/A time=00:01:00.16 bitrate=N/A speed=1.03x    
Conversion failed!
2023-04-27 14:11:56.215952538  frame=  872 fps= 15 q=-1.0 size=N/A time=00:01:00.12 bitrate=N/A speed=1.03x    
14:11:56.215 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url=ffmpeg:Side#video=h264#rotate=90#hardware
2023-04-27 14:11:56.216062603  14:11:56.215 ERR github.com/AlexxIT/go2rtc/cmd/mjpeg/mjpeg.go:159 > error="source 0 error: exec: exit status 1"

**Comment by AlexxIT** [comment]
@NickM-27 This will waste significant CPU time rotating and double-transforming the frame.
You can search how to rotate the frame with Nvidia. But there may be problems with the drivers there:
https://www.reddit.com/r/ffmpeg/comments/7ydi7z/rotate_with_nvenc_doesnt_use_gpu/

**Comment by NickM-27** [comment]
Yeah, frigate can't get a build of ffmpeg with transpose_npp since nvidia does not allow that to be built into any redistributable binary, so as far as I have found the only option is the inefficient command I put above.

**Comment by AlexxIT** [comment]
@caublet also if you have Intel GPU, you can try to use it `#hardware=vaapi`.
GPU rotation should work there. But only on latest release
https://github.com/AlexxIT/go2rtc/blob/9268acf1cac4327f8b6fc2d1c9922494b11565cc/cmd/ffmpeg/hardware.go#L58-L64

**Comment by caublet** [comment]
I do have a i7 3rd#Ivy bridge intel CPU.. 

Modified my docker-compose and added : 
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware

Then changed config in webrtc to : 
    Side_Rotated:
      - "ffmpeg:Side#rotate=90#hardware=vaapi"

And got error : 
2023-04-27 14:37:52.918609814  [2023-04-27 14:37:52] watchdog.Side                  ERROR   : Ffmpeg process crashed unexpectedly for Side.
2023-04-27 14:37:52.918615364  [2023-04-27 14:37:52] watchdog.Side                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-04-27 14:37:52.918617183  [2023-04-27 14:37:52] ffmpeg.Side.detect             ERROR   : [rtsp @ 0x557d7c926080] method DESCRIBE failed: 404 Not Found
2023-04-27 14:37:52.918618828  [2023-04-27 14:37:52] ffmpeg.Side.detect             ERROR   : rtsp://127.0.0.1:8554/Side_Rotated: Server returned 404 Not Found

**Comment by NickM-27** [comment]
@caublet you need to be running go2rtc 1.4 for that I believe

**Comment by caublet** [comment]
It's v1.2 within Frigate for now..

Also, as I'm using a Proxmox VM, configured with Ubuntu as a Docker host with portainer, passing through Nvidia GPU and Coral as pci devices.. I may have to passthrough the intel graphic processor as well? 

![image](https://user-images.githubusercontent.com/581162/234960978-2f71f469-a9d5-47a1-8ea7-2c63760bf609.png)

That wont work.. I won't have monitor on server after that!

**Comment by plloppii** [comment]
Hi all, 
Commenting here as I was just trying to configure a rotated stream with haccel last night. Wondering if i can get some clarification between the docs in frigate vs the docs in go2rtc. (I am running frigate on hassos on a x86 nuc, with Intel® Core™ i7-7567U, Kaby Lake.)

In[ frigate docs](https://docs.frigate.video/configuration/hardware_acceleration#via-vaapi) on hardware acc, I see that the following lines need to be defined:
```
ffmpeg:
  hwaccel_args: preset-vaapi
```
With it defined, i dont see any reduction in my cpu load with the rotated stream being processed. 

In [go2rtc docs](https://github.com/AlexxIT/go2rtc/wiki/Hardware-acceleration), I see what you, @AlexxIT mentioned of defining, `#hardware=vaapi`. In doing so, I see frigate picking up on my iGPU, and my cpu load dropping by about 40%. 

<img width="1339" alt="image" src="https://github.com/AlexxIT/go2rtc/assets/31411394/65ad5467-4030-4aa1-9d71-c28671d9c69b">


Could i get some clarification for the difference between these adding `#hardware=vaapi` in my stream uri, vs the `hwaccel_args` definition in my frigate.yml file?
Would also greatly appreciate any tips on my config file for any further optimizations. 

complete `frigate.yml` as follows:
```
detectors:
  coral:
    type: edgetpu
    device: usb

environment_vars:
  LIBVA_DRIVER_NAME: i965
ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

go2rtc:
  streams:
    wyzeLeft: ffmpeg:rtsp://<REDACTED>#video=h264#rotate=90#hardware=vaapi
    wyzeLeftSub: ffmpeg:rtsp://<REDACTED>#video=h264#rotate=90#hardware=vaapi
    wyzeRight: ffmpeg:rtsp://<REDACTED>#video=h264#rotate=-90#hardware=vaapi
    wyzeRightSub: ffmpeg:rtsp://<REDACTED>#video=h264#rotate=-90#hardware=vaapi
    ptz: rtsp://<REDACTED>
    ptzSub: rtsp://<REDACTED>

cameras:
  wyzeLeft:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/wyzeLeftSub
          input_args: preset-rtsp-restream
          roles:
              - detect
        - path: rtsp://localhost:8554/wyzeLeft
          input_args: preset-rtsp-restream
          roles:
              - record
    detect:
      width: 360
      height: 640
  wyzeRight:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/wyzeRightSub
          input_args: preset-rtsp-restream
          roles:
              - detect
        - path: rtsp://localhost:8554/wyzeRight
          input_args: preset-rtsp-restream
          roles:
              - record
    detect:
      width: 360
      height: 640
  ptz:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/ptzSub
          input_args: preset-rtsp-restream
          roles:
              - detect
        - path: rtsp://localhost:8554/ptz
          input_args: preset-rtsp-restream
          roles:
              - record
    detect:
      width: 640
      height: 480

record:
  enabled: true
  retain:
    days: 3
    mode: active_objects
  events:
    retain:
      default: 3
      mode: active_objects
```
