### ISSUE TITLE
Roborock 2 way audio

### ISSUE THREAD

**Issue by peteh** [AlexxIT/go2rtc#406]
I'm trying to get 2 Way Audio to work with roborock S6 MaxV from homeassistant. 

When I test it with google tts which works with other players I can hear "Remote viewing activated" and then the call fails. So the stream is actually opened but seems like audio data is failing. 

I'm using the webrtc hacs integration configured to use the docker container g2rtc. 

Robot is S6 maxv. 

go2rtc.yaml running in docker
```
streams: 
    dustin_camera: roborock://****
```

HA configuration.yaml running in docker
```
media_player:
  - platform: webrtc
    name: Dustin Player
    stream: dustin_camera
    audio: opus
```

Any idea where to further analyze?
