### ISSUE TITLE
Snapshot won't work with Reolink camera with 1.5.0

### ISSUE THREAD

**Issue by luisiam** [AlexxIT/go2rtc#417]
I am adding a snapshot stream using the reolink snapshot URL
```
streams:
  backyard:
    - http://192.168.10.24/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=go2rtc&user=xxx&password=xxx
```
I am using the `frame.jpeg` url to feed that snapshot to other services like scrypted.
![image](https://user-images.githubusercontent.com/16310467/236352197-ca916d8f-0268-4635-b86d-5e10c01fff6d.png)

It was working fine in previous version till I updated to go2rtc 1.5.0. Now, when I click that `frame.jpeg` link, I am getting `exit status 1`.
![image](https://user-images.githubusercontent.com/16310467/236352288-3450ce0f-c717-4fe8-8b86-6bbbd311e6f1.png)

I had another amcrest camera and I am doing the same thing which still works with go2rtc 1.5.0

**Comment by Mr-HaleYa** [comment]
Tried with both my Reolink E1 Zooms, did what you are saying and the first one gave me the same error then the other did not. When I tried the first one again the error didn't show and I've restarted and retried many times and it has not come back...
I also have a Reolink Doorbell and it also worked fine. So I was able to recreate it once then never again...

running frigate 0.12.0 with go2rtc 1.15.0 binary installed

go2 rtc config snip
```
streams:
    loft_cam_test:
      - http://192.168.50.***/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=go2rtc&user=***&password=***
    lvrm_cam_test:
      - http://192.168.50.***/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=go2rtc&user=admin&password=***
    doorbell_cam_test:
      - http://192.168.50.***/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=go2rtc&user=***&password=***
```

What camera(s) are you using?

 Do you have http access enable in the camera config? I tried using the snapshot feature without it enabled a while ago and it threw a lot of errors.
![image](https://user-images.githubusercontent.com/42821995/236381237-7a0f8efa-1947-45e2-9c0f-2a83b70748bf.png)
