### ISSUE TITLE
Add the ability to resolve an ip address from a domain name in the webrtc settings

### ISSUE THREAD

**Issue by DaN66O** [AlexxIT/go2rtc#42]
I would like to enter not the ip address but the domain name in these settings:
```
webrtc:
  listen: ":8555" 
  candidates:
    - domain_name.com:8555 

```
