### ISSUE TITLE
No Access to Roborock S7 MaxV Cam

### ISSUE THREAD

**Issue by Kroeger02** [AlexxIT/go2rtc#436]
Hey,

im trying to access the video signal from my Roborock s7 maxv, but i cant get a Video out of my bot.

What did i wrong?

I installled go2rtc via HACS WebRTC Integration.

This is my go2rtc.yaml

```
api:
  listen: ":1984"
  base_path: ""
  static_dir: ""
  origin: ""

ffmpeg:
  bin: "ffmpeg"
  global: "-hide_banner"
  file: "-re -stream_loop -1 -i {input}"
  http: "-fflags nobuffer -flags low_delay -i {input}"
  rtsp: "-fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_transport tcp -i {input}"
  output: "-user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp {output}"

hass:
  config: ""

log:
  format: ""
  level: "info"

ngrok:
  command: ""

rtsp:
  listen: ":8554"
  username: ""
  password: ""

srtp:
  listen: ":8443"

roborock:
 username: "XXX"
 password: "XXX"

streams:
  Roborock: roborock://X.X.X.X/

webrtc:
  listen: ":8555"
  candidates: []
  ice_servers:
    - urls: [ "stun:stun.l.google.com:19302" ]
      username: ""
      credential: ""
```
