### ISSUE TITLE
JPEG Snapshot doesn't work with 1.5.0 and AMCREST

### ISSUE THREAD

**Issue by pyrodex** [AlexxIT/go2rtc#442]
Just upgraded to 1.5.0 for the JPEG snapshot feature but can't it working. From the go2rtc web UI I click on the links of the camera(s) and when I click the link (http://frigate.iot:5000/live/webrtc/api/frame.jpeg?src=driveway) I get a 404 not found.

Any help is appreciated as I would love to have snapshot JPEG for IPCams using the go2rtc streams.

Here is my go2rtc configuration in Frigate:

```
go2rtc:
  webrtc:
    candidates:
      - stun:8555
  rtsp:
    username: "login"
    password: "password"
  streams:
    driveway:
      - rtsp://login:password@192.168.24.90:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - "ffmpeg:driveway#audio=opus"
    driveway_sub:
      - rtsp://login:password@192.168.24.90:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
```

Here is my configuration for one of my cameras:

```
{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://192.168.24.90:554/cam/realmonitor?channel=1\u0026subtype=0\u0026unicast=true\u0026proto=Onvif/",
      "remote_addr": "192.168.24.90:554",
      "user_agent": "go2rtc/1.5.0",
      "medias": [
        "video, recvonly, H.264 Main 5.1",
        "audio, recvonly, MPEG4-GENERIC/8000",
        "application, recvonly, VND.ONVIF.METADATA",
        "audio, sendonly, L16/8000, L16/16000, L16/32000, L16/48000, L16/64000, PCMA/8000, PCMA/16000, PCMA/32000, PCMA/48000, PCMA/64000, PCMU/8000, PCMU/16000, PCMU/32000, PCMU/48000, PCMU/64000, G726-40/8000, G726-40/16000, G726-40/32000, G726-40/48000, G726-40/64000, MPEG4-GENERIC/8000, MPEG4-GENERIC/16000, MPEG4-GENERIC/32000, MPEG4-GENERIC/48000, MPEG4-GENERIC/64000, 122, 123, 124, 125, 126"
      ],
      "receivers": [
        "96 H264, bytes=154501391, senders=2",
        "97 MPEG4-GENERIC/8000, bytes=387650, senders=2"
      ],
      "recv": 156224461
    },
    {
      "url": "ffmpeg:driveway#audio=opus"
    }
  ],
  "consumers": [
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/driveway",
      "remote_addr": "127.0.0.1:58608",
      "user_agent": "FFmpeg Frigate/0.12.0-da3e197",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "senders": [
        "96 H264, bytes=154501391, receivers=1",
        "97 MPEG4-GENERIC/8000, bytes=387650, receivers=1"
      ],
      "send": 156664481
    },
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/driveway",
      "remote_addr": "172.19.0.1:42448",
      "user_agent": "Lavf59.27.100",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "senders": [
        "96 H264, bytes=153244460, receivers=1",
        "97 MPEG4-GENERIC/8000, bytes=383786, receivers=1"
      ],
      "send": 155389094
    }
  ]
}
```
