### ISSUE TITLE
Increase volume in two way audio using ffmpeg

### ISSUE THREAD

**Issue by ondoteam** [AlexxIT/go2rtc#447]
Hello! This is a question. When using two way audio the sound in my smartphone is too low.

### Working two way audio cofiguration with sound too low
```
streams:
  dahua_camera:
    - rtsp://admin:admin@192.168.13.2/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    - rtsp://admin:admin@192.168.13.2/cam/realmonitor?channel=1&subtype=1
```

If I try to use the following configuration, the sound in my smartphone is fine, but the two way audio is lost.

### Not working two way audio cofiguration but sound is fine
```
streams:
  dahua_camera:
    - ffmpeg:rtsp://admin:admin@192.168.13.2/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif#video=copy#audio=copy
    - rtsp://admin:admin@192.168.13.2/cam/realmonitor?channel=1&subtype=1
```

I was experimenting with ffmpeg configurations without results:

### Not working two way audio cofiguration but sound is fine (audio filter ignored).
```
    - ffmpeg:rtsp://admin:admin@192.168.13.2/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif#video=copy#audio=volume
    - rtsp://admin:admin@192.168.13.2/cam/realmonitor?channel=1&subtype=1
ffmpeg:
  bin: ffmpeg  # path to ffmpeg binary
  volume: "-af \"volume=0.5\""
```

It is there any way to increase volume of sound coming from the camera microphone using ffmpeg while maintaining the two way audio functionality? Thanks.

**Comment by AlexxIT** [comment]
Just add audio source first, so go2rtc will select it.
I don't knot what parameters you should use for ffmpeg for increasing volume. I think it should be transcoding.

```
streams:
  dahua_camera:
  - ffmpeg:rtsp://admin:admin@192.168.13.2/cam/realmonitor?channel=1&subtype=1#audio...
  - rtsp://admin:admin@192.168.13.2/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
```

**Comment by ondoteam** [comment]
I am on a trip with a small screen. I will be brief. Doing what @AlexxIT told in his comment works for me. Final config:

```
log:
  level: info  # default level
  api: info
  exec: trace
  ngrok: info
  rtsp: info
  streams: trace
  webrtc: info
  
streams:
  dahua_camera:
#Audio
    - ffmpeg:rtsp://admin:admin@192.168.13.2/cam/realmonitor?channel=1&subtype=1#audio=pcm#audio=volume
#Video
    - rtsp://admin:admin@192.168.13.2/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif

ffmpeg:
  bin: ffmpeg  # path to ffmpeg binary
  volume: "-af \"volume=5\""
```

The backslash is important in the ffmpeg custom configuration. If using windows: ffmpeg should be in PATH configuration.
