### ISSUE TITLE
Can not stream USB camera

### ISSUE THREAD

**Issue by Koushikphy** [AlexxIT/go2rtc#450]
I have a USB web cam connected to a linux machine. Here, using `ffmpeg` I can record video and audio with these `ffmpeg` flags
```
-f video4linux2 -vcodec mjpeg -video_size 1280x720 -i /dev/video0  -f alsa -ac 1 -i hw:1
```

How do I set the same thing up with `go2rtc`. I have mad this config 
```
streams:
  linux_usbcam:   ffmpeg:device?video=/dev/video0&video_size=1280x720#video=mjpeg
```
But this does not show up anything

**Comment by AlexxIT** [comment]
Can you see your camera in the go2rtc WebUI add page?

**Comment by Koushikphy** [comment]
So it seems, I can open the webcam stream going to the `127.0.0.1:1984/stream.html?src=linux_usbcam` in the local machine, but cant open it in other machine in the same LAN when going to the `192.168.**.**:1984/stream.html?src=linux_usbcam` . Do I have to configure it to access the stream from other machine on the same LAN ?

**Comment by AlexxIT** [comment]
By default go2rtc listen on all interfaces. If it listen only on localhost - that's how you setup it

**Comment by Koushikphy** [comment]
How do you set it up then, I mean what changes do I have to make to the config file?

**Comment by AlexxIT** [comment]
Empty config file listen on all interfaces

**Comment by Koushikphy** [comment]
> Can you see your camera in the go2rtc WebUI add page?

I can see this in the add page.

![image](https://github.com/AlexxIT/go2rtc/assets/43264301/ecd64434-d307-4c2b-9a32-eab83722ac6e)

**Comment by Koushikphy** [comment]
No thats fixed. So, here's my config
```yaml
streams:
    t1: ffmpeg:device?video=/dev/video0&input_format=mjpeg&video_size=1280x720#video=h264
    t2: ffmpeg:device?video=/dev/video0&input_format=yuyv422&video_size=1280x720&#video=h264#hardware
```
I can watch the stream only on `http://<IP>:1984/api/stream.mp4?src=t1&mp4=all`.

Now my only question, how do I add the sound to this stream ?

**Comment by AlexxIT** [comment]
You need to search other issues with your new question. One user has had success with alsa input.

**Comment by Koushikphy** [comment]
If anyone stumbles upon this issue, I am finally able to stream audio and video with this config

```yaml
streams:
    s1:
        - ffmpeg:device?video=/dev/video0&input_format=yuyv422&video_size=640x480#video=h264#hardware
        - exec:ffmpeg -hide_banner -f alsa -ac 1 -i default  -c:a libopus  -ac:a 2 -c:v copy -f rtsp {output}
    s2:
        - ffmpeg:device?video=/dev/video0&input_format=mjpeg&video_size=1280x720#video=h264
        - exec:ffmpeg -hide_banner -f alsa -ac 1 -i hw:1  -c:a libopus -c:v copy  -ac:a 2 -f rtsp {output}
```
