### ISSUE TITLE
cannot establish connection to camera in night mode

### ISSUE THREAD

**Issue by cagivacode** [AlexxIT/go2rtc#451]
Head Scratcher here: using go2rtc in frigate with zmodo cameras (hardwired). They are native h264.

```
go2rtc:
    streams:
        Cam17: "ffmpeg: rtsp://redact@192.168.1.17:10554/udp/av0_0#video=copy#audio=copy#input=-timeout 5000000 -buffer_size 300000 -i {{input}}"
        Cam18: "ffmpeg: rtsp://redact@192.168.1.18:10554/udp/av0_0#video=copy#audio=copy#input=-timeout 5000000 -buffer_size 300000 -i {{input}}"
        Cam19: "ffmpeg: rtsp://redact@192.168.1.19:10554/udp/av0_0#video=copy#audio=copy#input=-timeout 5000000 -buffer_size 300000 -i {{input}}"
        Cam20: "ffmpeg: rtsp://redact@192.168.1.20:10554/udp/av0_0#video=copy#audio=copy#input=-timeout 5000000 -buffer_size 300000 -probesize 700000 -analyzeduration 700000 -i {{input}}"
```

Cameras ran for a longtime in zoneminder with the buffers and timeout setting.

The camera run fine and stable 24/7 with the buffers and timeout setting in go2rtc.

Unless I reboot when the cameras are in night mode. Then I cannot get a connection.

I can get a connection from ffmpeg / vlc / zoneminder.....when in night mode just not go2rtc. There is no indication of a stream frame rate change in night mode.

If I go and force the cameras (flashlight) back into day mode it will reconnect.

I tried numerous settings like probesize ....it just has me stumped.
 Any suggestion would be appreciated.
