### ISSUE TITLE
Quality drop when transcoding h265 to h264 - Is there a way to increate bitrate?

### ISSUE THREAD

**Issue by brendann993** [AlexxIT/go2rtc#459]
I see quite a noticable quality drop when transcoding h265 to h264. From what I understand its bound to happen with the transcode but can be reduced by increasing the bitrate of the h264. How can this be done with go2rtc?
```
  streams:
    frontyard_fullres: 
      - rtsp://user:password@10.1.1.25:554/h265Preview_01_main
      - ffmpeg:rtsp://user:password@10.1.1.25:554/h265Preview_01_main#video=h264#hardware#audio=opus
  log:
    level: trace
  api:
    listen: ":1984"  # HTTP API port ("" - disabled)
  rtsp:
    listen: ":8554"
  webrtc:
    listen: ":8555"
    candidates:
      - 10.1.1.150:8555 # <--- enter frigate host IP here
      - stun:8555
```
Example: left stream is the rtsp from http://localhost:8554/frontyard_fullres and right stream is from http://localhost:8554/frontyard_fullres?video=h264
![image](https://github.com/AlexxIT/go2rtc/assets/6630349/6710bda4-c02d-4b97-817e-3f2aa8c49534)
