### ISSUE TITLE
401 Unauthorized when I try to embed it

### ISSUE THREAD

**Issue by estradanet** [AlexxIT/go2rtc#463]
Hi Alex,

Great tool, I use it with Home assistant and works perfectly.

However, I get this 401 Unauthorized when I try to embed it in another device in my local network (MagicMirror).

Does this have a sort of ip whitelist to allow using it embedded?

**Comment by AlexxIT** [comment]
Probably you trying to embed Home Assistant webpage (addon ingress). You can't do it because all Home Assistant web pages protected with Home Assistant auth.

If you trying to embed go2rtc WebUI, you need to disable go2rtc api auth (disabled by default) or add it to embed link

**Comment by estradanet** [comment]
Thank you, I used docker instead and not home assistant and it worked. Thank you

**Comment by Matssa56** [comment]
Hey, I'm having the same issue. I'm trying to add the 2 way audio link that is available under the "links" menu in go2rtc webpage to an iframe in Lovelace for Home Assistant.

I get 401 Unauthorized. When I open go2rtc and open the link from there, I can now open the embeded link, until the server reboots or something.

How can I fix this? I didn't activate go2rtc api auth, here is my current config:

```
streams:
  camera.salon: tapo://admin:<redacted>@192.168.<redacted>
  camera.babyphone_eliott: tapo://admin:<redacted>@192.168.<redacted>
  camera.garage: tapo://admin:<redacted>@192.168.<redacted>

webrtc:
  listen: ":8555" # external TCP port
  candidates:
    - stun:8555 # if you have dynamic public IP-address
```

The webrtc config is to make these camera strems available from outside the local network (not really sure if it really needed or correctly configured since I'm doing go2rtc --> RTSPtoWebRTC --> Frigate card using camera entity and live_provider: ha)

THanks for your help, not sure if I need to open this ticket again
