### ISSUE TITLE
Aqara Camera Hub G3

### ISSUE THREAD

**Issue by Lockie85** [AlexxIT/go2rtc#495]
Hey,

I'm using go2rtc via Frigate.

I'm trying to create a stream for my Aqara Camera Hub G3 which I believe utilises HomeKit.

To achieve this I've the following:
go2rtc:
  streams:
    Bedroom_2:
      - hass:Camera-Hub-G3-E44E
      - ffmpeg:Bedroom_2#audio=aac#audio=opus#async

However, when trying to access the camera via the stream link here:
![image](https://github.com/AlexxIT/go2rtc/assets/7091582/76193dc1-4eb7-4862-8d14-0c0721f27df4)

I get a never ending loading screen:
![image](https://github.com/AlexxIT/go2rtc/assets/7091582/de045a4b-0085-4d1f-a6da-02441d87eee6)

Any idea what I might be doing wrong?

**Comment by AlexxIT** [comment]
Check logs

**Comment by Lockie85** [comment]
Adding my Go2rtc log:

```
2023-06-29 12:47:22.640867593  [INFO] Preparing go2rtc config...
2023-06-29 12:47:22.664838328  [INFO] Got IP address from supervisor: 192.168.1.4
2023-06-29 12:47:22.684269638  [INFO] Got WebRTC port from supervisor: 8555
2023-06-29 12:47:22.895958540  [INFO] Starting go2rtc...
2023-06-29 12:47:22.947481306  13:47:22.947 INF go2rtc version 1.2.0 linux/amd64
2023-06-29 12:47:22.947765777  13:47:22.947 INF [api] listen addr=:1984
2023-06-29 12:47:22.947945732  13:47:22.947 INF [rtsp] listen addr=:8554
2023-06-29 12:47:22.948135687  13:47:22.948 INF [srtp] listen addr=:8443
2023-06-29 12:47:22.948265093  13:47:22.948 INF [webrtc] listen addr=:8555
2023-06-29 12:47:32.643245882  [INFO] Starting go2rtc healthcheck service...
2023-06-29 12:47:51.217778376  13:47:51.217 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="unsupported scheme: hass:Camera-Hub-G3-E44E" url=hass:Camera-Hub-G3-E44E
2023-06-29 12:47:51.221557085  13:47:51.221 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="unsupported scheme: hass:Camera-Hub-G3-E44E" url=hass:Camera-Hub-G3-E44E
2023-06-29 12:47:51.223770603  13:47:51.223 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="unsupported scheme: hass:Camera-Hub-G3-E44E" url=hass:Camera-Hub-G3-E44E
2023-06-29 12:47:56.330191058  13:47:56.330 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url=ffmpeg:Bedroom_2#audio=aac#audio=opus#async
2023-06-29 12:47:56.330203748  13:47:56.330 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="unsupported scheme: hass:Camera-Hub-G3-E44E" url=hass:Camera-Hub-G3-E44E
2023-06-29 12:47:56.333191563  13:47:56.333 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="unsupported scheme: hass:Camera-Hub-G3-E44E" url=hass:Camera-Hub-G3-E44E
2023-06-29 12:48:01.441101028  13:48:01.441 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url=ffmpeg:Bedroom_2#audio=aac#audio=opus#async
2023-06-29 12:48:01.442568788  13:48:01.442 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="unsupported scheme: hass:Camera-Hub-G3-E44E" url=hass:Camera-Hub-G3-E44E
2023-06-29 12:48:01.443745138  13:48:01.443 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="unsupported scheme: hass:Camera-Hub-G3-E44E" url=hass:Camera-Hub-G3-E44E
2023-06-29 12:48:06.550947339  13:48:06.550 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url=ffmpeg:Bedroom_2#audio=aac#audio=opus#async
2023-06-29 12:48:06.551012250  13:48:06.550 WRN [rtsp] error="source 0 error: unsupported scheme: hass:Camera-Hub-G3-E44E" stream=Bedroom_2
2023-06-29 12:48:06.561267075  13:48:06.561 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="unsupported scheme: hass:Camera-Hub-G3-E44E" url=hass:Camera-Hub-G3-E44E
```

Not sure I understand the meaning of this error.

**Comment by AlexxIT** [comment]
go2rtc enables Hass integration only when Hass config folder available. Are you sure you have Hass config folder inside Frigate container? If yes, try to set config path:
```yaml
hass:
  config: "/config"
```

**Comment by Lockie85** [comment]
> go2rtc enables Hass integration only when Hass config folder available. Are you sure you have Hass config folder inside Frigate container? If yes, try to set config path:
> 
> ```yaml
> hass:
>   config: "/config"
> ```

Thanks for your reply again @AlexxIT but sorry I don't think I'm quite following how I check that.

If it helps, I can confirm that I can access/view other cameras in Home Assistant > Frigate > go2rtc. I didn't mention those as they are working but I have other streams likes so:

go2rtc:
  streams:
    Bedroom_2:
      - hass:Camera-Hub-G3-E44E
      - ffmpeg:Bedroom_2#audio=aac#audio=opus#async
    Driveway_Low:  
      - rtsp://username:password@192.168.85.5/stream2
    Garden_Low:
      - rtsp://username:password@192.168.85.6/stream2

"Driveway_Low" and "Garden_Low" are working fine, so I assume my setup in terms of this "_go2rtc enables Hass integration only when Hass config folder available_" must be correct?

**Comment by NickM-27** [comment]
Frigate uses the /config so odds are the HA setup is not going to work unless you separately map whatever the ha configure directory is and override the hass config. 

> Given "Driveway_Low" and "Garden_Low" are working fine, I assume my setup in terms of this "go2rtc enables Hass integration only when Hass config folder available" must be correct?

No, that does not mean that at all

**Comment by Lockie85** [comment]
> Frigate uses the /config so odds are the HA setup is not going to work unless you separately map whatever the ha configure directory is and override the hass config.
> 
> > Given "Driveway_Low" and "Garden_Low" are working fine, I assume my setup in terms of this "go2rtc enables Hass integration only when Hass config folder available" must be correct?
> 
> No, that does not mean that at all

K, that's fine. So what do I need to check sorry?

**Comment by NickM-27** [comment]
are you running frigate via addon or docker?

**Comment by Lockie85** [comment]
> are you running frigate via addon or docker?

Home Assistant Add-on.

**Comment by NickM-27** [comment]
Okay, then you likely just need to add

```
hass:
  config: "/config"
```

to the go2rtc config

**Comment by Lockie85** [comment]
Assuming this is correct:
```
go2rtc:
  hass:
    config: "/config"
  streams:
    Bedroom_2:
      - hass:Camera-Hub-G3-E44E
      - ffmpeg:Bedroom_2#audio=aac#audio=opus#async
```

I'm now getting this in the Go2rtc log:
```
2023-06-29 14:00:14.859086289  [INFO] Preparing go2rtc config...
2023-06-29 14:00:14.883476458  [INFO] Got IP address from supervisor: 192.168.85.4
2023-06-29 14:00:14.903183065  [INFO] Got WebRTC port from supervisor: 8555
2023-06-29 14:00:15.020870619  [INFO] Starting go2rtc...
2023-06-29 14:00:15.101449547  15:00:15.101 INF go2rtc version 1.2.0 linux/amd64
2023-06-29 14:00:15.102431097  15:00:15.101 INF [api] listen addr=:1984
2023-06-29 14:00:15.102432819  15:00:15.101 INF [rtsp] listen addr=:8554
2023-06-29 14:00:15.102436044  15:00:15.102 INF [hass] load stream url=hass:Aqara-Hub-M2-B4D3
2023-06-29 14:00:15.102437244  15:00:15.102 INF [hass] load stream url=hass:Camera-Hub-G3-E44E
2023-06-29 14:00:15.102438308  15:00:15.102 INF [srtp] listen addr=:8443
2023-06-29 14:00:15.102702726  15:00:15.102 INF [webrtc] listen addr=:8555
2023-06-29 14:00:24.865199753  [INFO] Starting go2rtc healthcheck service...
2023-06-29 14:00:34.344393908  2023/06/29 15:00:34 [INFO] mdns: Closing client {true false 0xc0002c8058 <nil> 0xc0002c8068 <nil> 1 0xc00007c120}
2023-06-29 14:00:44.671984864  15:00:44.671 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error=EOF url=ffmpeg:Bedroom_2#audio=aac#audio=opus#async
2023-06-29 14:00:54.935647239  15:00:54.935 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error=EOF url=ffmpeg:Bedroom_2#audio=aac#audio=opus#async
2023-06-29 14:01:05.197635884  15:01:05.197 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error=EOF url=ffmpeg:Bedroom_2#audio=aac#audio=opus#async
```

**Comment by AlexxIT** [comment]
@NickM-27 by default go2rtc search Hass config in CWD. I don't know what CWD for go2rtc in Frigate.

@Lockie85 I think HomeKit source won't work for go2rtc in Frigate addon because of closed ports. Go2rtc uses mDNS for searching HomeKit camera address and port.

**Comment by Lockie85** [comment]
> @NickM-27 by default go2rtc search Hass config in CWD. I don't know what CWD for go2rtc in Frigate.
> 
> @Lockie85 I think HomeKit source won't work for go2rtc in Frigate addon because of closed ports. Go2rtc uses mDNS for searching HomeKit camera address and port.

Does this mean I won't be able to get my Aqara Camera-Hub-G3 working with Frigate + Go2rtc?

What confuses me is I can view the camera via on of Home Assistants card using this code:
`type: custom:frigate-card
cameras:
  - camera_entity: camera.camera_hub_g3_e44e
`

But I can't get it to display in the Addon Frigate. Or is this because you are saying Home Assistant isn't allowing Frigate access, in short?

**Comment by AlexxIT** [comment]
Hass support only MJPEG codec for HomeKit cameras. And Hass docker container has open ports.

You can try your luck with go2rtc addon or Frigate docker (not addon).

**Comment by Lockie85** [comment]
> Hass support only MJPEG codec for HomeKit cameras. And Hass docker container has open ports.
> 
> You can try your luck with go2rtc addon or Frigate docker (not addon).

Yep using the Go2rtc addon work.

I simply made the file "go2rtc.yaml" and defined within it:
```
streams:
  aqara_g3: hass:Camera-Hub-G3-E44E
```

Instantly worked. I guess something odd is going on with the Frigate integration as you say. Many thanks.

**Comment by NickM-27** [comment]
one difference is that go2rtc addon uses go2rtc 1.5.0 and frigate uses 1.2.0 currently (though it is easy to change which version is used)

**Comment by Lockie85** [comment]
> one difference is that go2rtc addon uses go2rtc 1.5.0 and frigate uses 1.2.0 currently (though it is easy to change which version is used)

Is that something I can control/update. Or is it to be pushed by the owner to Frigate?

**Comment by NickM-27** [comment]
You can change the version https://docs.frigate.video/configuration/advanced#custom-go2rtc-version

**Comment by AlexxIT** [comment]
@NickM-27 docker container must have UDP 8443 and UDP 5353 ports open or use network host. Frigate addon uses closed network. Hass and go2rtc addon uses network host.

**Comment by NickM-27** [comment]
ah right forgot about that part

**Comment by kmanan** [comment]
Were you able to get the Aqara camera working in Frigate?

**Comment by heroash88** [comment]
For those looking to add Aqara G3 and G2 added to Hass via the HomeKit integration and go2rtc and Frigate add-ons. I still need to make some edits to Frigate but at least it works. I am still having issues adding my Ecobee camera. 

I added this to go2rtc config: 
`streams:
#Aqara G3 HomeKit
  aqara_g3: 
    - hass:Camera-Hub-G3-3CDE  #the name of the device not camera entity in HA
    - ffmpeg:aqara_g3#audio=aac#audio=opus#async
    
#Aqara G2 HomeKit
  aqara_g2:
    - hass:g2
    - ffmpeg:aqara_g2#audio=aac#audio=opus#async

 #Nest Outdoor Camera through Nest integration
  driveway: hass://supervisor?entity_id=camera.driveway_camera


rtsp:
  listen: ":8554"    # RTSP Server TCP port, default - 8554
  username: "user" # change the username
  password: "pass" # change the password
  default_query: "video&audio"  # optional, default codecs filters `

Add this to Frigate config: 
`mqtt:
  host: localhost
  user: ha
  password: mqttpassword
detectors:
  coral:
    type: edgetpu
    device: usb
ffmpeg:
  hwaccel_args: preset-vaapi
objects:
  track:
    - person
    - bicycle
    - car
    - cat
    - dog
    - bird
    - bear
go2rtc:
  streams:
    aqara_g3:
      - >-
        rtsp://user:pass@192.168.0.1:8554/aqara_g3?video=all&audio=all
      - 'ffmpeg:rtsp_cam#audio=opus'
    driveway:
      - 'rtsp://user:pass@192.168.0.1:8554/driveway'
      - 'ffmpeg:rtsp_cam#audio=opus'
    aqara_g2:
      - >-
        rtsp://user:pass@192.168.0.1:8554/aqara_g2?video=all&audio=all
      - 'ffmpeg:rtsp_cam#audio=opus'

cameras:
  Aqara:
    enabled: true
    ffmpeg:
      inputs:
        - path: 'rtsp://127.0.0.1:8554/aqara_g3'
          roles:
            - record
        - path: 'rtsp://127.0.0.1:8554/aqara_g3'
          roles:
            - detect
    detect:                 
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10
    record:
      enabled: True
      retain: 
        days: 2 
  AqaraG2:
    ffmpeg:
      inputs:
        - path: 'rtsp://127.0.0.1:8554/aqara_g2'
          roles:
            - record
        - path: 'rtsp://127.0.0.1:8554/aqara_g2'
          roles:
            - detect
    detect:                 
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10
    record:
      enabled: True
      retain: 
        days: 2 
  Driveway:
    ffmpeg:
      inputs:
        - path: 'rtsp://127.0.0.1:8554/driveway'
          roles:
            - record
        - path: 'rtsp://127.0.0.1:8554/driveway'
          roles:
            - detect
    detect:                 
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10
    record:
      enabled: True
      retain: 
        days: 2 
 `
I hope this helps.

**Comment by heroash88** [comment]
For those looking to add Aqara G3 and G2 added to Hass via the HomeKit integration and go2rtc and Frigate add-ons. I still need to make some edits to Frigate but at least it works. I am still having issues adding my Ecobee camera. 

I added this to go2rtc config: 
```
`streams:
#Aqara G3 HomeKit
  aqara_g3: 
    - hass:Camera-Hub-G3-3CDE  #the name of the device not camera entity in HA
    - ffmpeg:aqara_g3#audio=aac#audio=opus#async
    
#Aqara G2 HomeKit
  aqara_g2:
    - hass:g2
    - ffmpeg:aqara_g2#audio=aac#audio=opus#async

 #Nest Outdoor Camera through Nest integration
  driveway: hass://supervisor?entity_id=camera.driveway_camera
```


```
rtsp:
  listen: ":8554"    # RTSP Server TCP port, default - 8554
  username: "user" # change the username
  password: "pass" # change the password
  default_query: "video&audio"  # optional, default codecs filters `

Add this to Frigate config: 
`mqtt:
  host: localhost
  user: ha
  password: mqttpassword
detectors:
  coral:
    type: edgetpu
    device: usb
ffmpeg:
  hwaccel_args: preset-vaapi
objects:
  track:
    - person
    - bicycle
    - car
    - cat
    - dog
    - bird
    - bear
go2rtc:
  streams:
    aqara_g3:
      - >-
        rtsp://user:pass@192.168.0.1:8554/aqara_g3?video=all&audio=all
      - 'ffmpeg:rtsp_cam#audio=opus'
    driveway:
      - 'rtsp://user:pass@192.168.0.1:8554/driveway'
      - 'ffmpeg:rtsp_cam#audio=opus'
    aqara_g2:
      - >-
        rtsp://user:pass@192.168.0.1:8554/aqara_g2?video=all&audio=all
      - 'ffmpeg:rtsp_cam#audio=opus'

cameras:
  Aqara:
    enabled: true
    ffmpeg:
      inputs:
        - path: 'rtsp://127.0.0.1:8554/aqara_g3'
          roles:
            - record
        - path: 'rtsp://127.0.0.1:8554/aqara_g3'
          roles:
            - detect
    detect:                 
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10
    record:
      enabled: True
      retain: 
        days: 2 
  AqaraG2:
    ffmpeg:
      inputs:
        - path: 'rtsp://127.0.0.1:8554/aqara_g2'
          roles:
            - record
        - path: 'rtsp://127.0.0.1:8554/aqara_g2'
          roles:
            - detect
    detect:                 
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10
    record:
      enabled: True
      retain: 
        days: 2 
  Driveway:
    ffmpeg:
      inputs:
        - path: 'rtsp://127.0.0.1:8554/driveway'
          roles:
            - record
        - path: 'rtsp://127.0.0.1:8554/driveway'
          roles:
            - detect
    detect:                 
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10
    record:
      enabled: True
      retain: 
        days: 2 
 `
```
I hope this helps.

**Comment by heroash88** [comment]
For those looking to add Aqara G3 and G2 added to Hass via the HomeKit integration and go2rtc and Frigate add-ons. I still need to make some edits to Frigate but at least it works. I am still having issues adding my Ecobee camera. 

I added this to go2rtc config: 

go2rtc config

```
streams:
#Aqara G3 HomeKit
  aqara_g3: 
    - hass:Camera-Hub-G3-3CDE  #the name of the device not camera entity in HA
    - ffmpeg:aqara_g3#audio=aac#audio=opus#async
    
#Aqara G2 HomeKit
  aqara_g2:
    - hass:g2
    - ffmpeg:aqara_g2#audio=aac#audio=opus#async

 #Nest Outdoor Camera through Nest integration
  driveway: hass://supervisor?entity_id=camera.driveway_camera

rtsp:
  listen: ":8554"    # RTSP Server TCP port, default - 8554
  username: "user" # change the username
  password: "pass" # change the password
  default_query: "video&audio"  # optional, default codecs filters 
```

Add this to Frigate config: 
Frigate config

```
mqtt:
  host: localhost
  user: ha
  password: mqttpassword
detectors:
  coral:
    type: edgetpu
    device: usb
ffmpeg:
  hwaccel_args: preset-vaapi
objects:
  track:
    - person
    - bicycle
    - car
    - cat
    - dog
    - bird
    - bear
go2rtc:
  streams:
    aqara_g3:
      - >-
        rtsp://user:pass@192.168.0.1:8554/aqara_g3?video=all&audio=all
      - 'ffmpeg:rtsp_cam#audio=opus'
    driveway:
      - 'rtsp://user:pass@192.168.0.1:8554/driveway'
      - 'ffmpeg:rtsp_cam#audio=opus'
    aqara_g2:
      - >-
        rtsp://user:pass@192.168.0.1:8554/aqara_g2?video=all&audio=all
      - 'ffmpeg:rtsp_cam#audio=opus'

cameras:
  Aqara:
    enabled: true
    ffmpeg:
      inputs:
        - path: 'rtsp://127.0.0.1:8554/aqara_g3'
          roles:
            - record
        - path: 'rtsp://127.0.0.1:8554/aqara_g3'
          roles:
            - detect
    detect:                 
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10
    record:
      enabled: True
      retain: 
        days: 2 
  AqaraG2:
    ffmpeg:
      inputs:
        - path: 'rtsp://127.0.0.1:8554/aqara_g2'
          roles:
            - record
        - path: 'rtsp://127.0.0.1:8554/aqara_g2'
          roles:
            - detect
    detect:                 
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10
    record:
      enabled: True
      retain: 
        days: 2 
  Driveway:
    ffmpeg:
      inputs:
        - path: 'rtsp://127.0.0.1:8554/driveway'
          roles:
            - record
        - path: 'rtsp://127.0.0.1:8554/driveway'
          roles:
            - detect
    detect:                 
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10
    record:
      enabled: True
      retain: 
        days: 2 
```
I hope this helps.
