### ISSUE TITLE
Reolink Argus 3 Pro and Neolink

### ISSUE THREAD

**Issue by Veuchez** [AlexxIT/go2rtc#501]
Hello everyone, I'm having trouble understanding what I'm doing wrong in my configuration.
I'm experiencing audio synchronization issues in the recorded footage, while the live audio is perfect.
The stream I'm working with is an RTSP stream coming from NEOLINK (https://github.com/QuantumEntangledAndy/neolink) for Reolink Argus 3 Pro cameras.
I have Frigate installed in Docker and updated go2rtc to version 1.5.
Could I have misconfigured something?
Is there a way to improve the configuration?
For the audio, if I don't use AAC, I can't hear anything, while the video is clear and doesn't require any conversion.
I'm using a Coral USB and Intel HD630 GPU.
Thank you in advance!

Here is my Frigate and go2rtc setup
```
mqtt:
  enabled: False  

logger:
  default: info
    
detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: True
  mode: continuous

objects:
  track:
    - car
    - person
    - bicycle
    - cat
    - dog

go2rtc:
  streams:
    ingresso:
      - rtsp://192.168.0.150:8889/ingresso/mainstream
      - ffmpeg:ingresso#audio=aac#async

    ingresso_sub:
      - rtsp://192.168.0.150:8889/ingresso/substream
      - ffmpeg:ingresso_sub#audio=aac#async

    poggiolo:
      - rtsp://192.168.0.150:8889/poggiolo/mainstream
      - ffmpeg:poggiolo#audio=aac#async

    poggiolo_sub:
      - rtsp://192.168.0.150:8889/poggiolo/substream
      - ffmpeg:poggiolo_sub#audio=aac#async

cameras:
  ingresso:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/ingresso
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/ingresso_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: ingresso_sub
    record:
      enabled: True
      retain:
        days: 7
        mode: all
    detect:
      width: 896
      height: 512
      fps: 5
    snapshots:
      enabled: True


  poggiolo:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/poggiolo
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/poggiolo_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: poggiolo_sub
    record:
      enabled: True
      retain:
        days: 7
        mode: all
    detect:
      width: 896
      height: 512
      fps: 5
    snapshots:
      enabled: True
```

Here are some go2rtc errors
```
2023-07-04 14:37:14.792394882  14:37:14.792 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:159 > error=EOF url=ffmpeg:ingresso#audio=aac#async
2023-07-04 14:38:13.995617434  14:38:13.995 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:159 > error=EOF url=ffmpeg:poggiolo_sub#audio=aac#async
2023-07-04 14:41:06.793026249  14:41:06.792 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:159 > error=EOF url=ffmpeg:ingresso#audio=aac#async
2023-07-04 14:42:40.955652737  14:42:40.955 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:159 > error=EOF url=ffmpeg:poggiolo_sub#audio=aac#async
2023-07-04 14:46:38.914264939  14:46:38.914 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:159 > error=EOF url=ffmpeg:poggiolo_sub#audio=aac#async
2023-07-04 14:50:08.233589036  14:50:08.233 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:159 > error=EOF url=ffmpeg:poggiolo_sub#audio=aac#async
```

**Comment by AlexxIT** [comment]
Similar #392
Try to increase log level and temporary remove ffmpeg sources

**Comment by Veuchez** [comment]
How do I increase the LOG level? Thank you!

**Comment by Veuchez** [comment]
@AlexxIT How do I increase the LOG level? Thank you!

**Comment by AlexxIT** [comment]
Just read docs https://github.com/AlexxIT/go2rtc#module-log

**Comment by Veuchez** [comment]
Thanks, maybe I expressed myself badly... 
Do I add all the entries or do you need one in particular?
```
log:
  level: info  # default level
  api: trace
  exec: debug
  ngrok: info
  rtsp: warn
  streams: error
  webrtc: fatal
```
