### ISSUE TITLE
Docker error gpu intel HD630

### ISSUE THREAD

**Issue by Veuchez** [AlexxIT/go2rtc#520]
I just tried to install go2rtc on docker with docker compose: 
```
services:
  go2rtc:
    container_name: go2rtc
    image: alexxit/go2rtc
    network_mode: host       # important for WebRTC, HomeKit, UDP cameras
    privileged: true         # only for FFmpeg hardware transcoding
    restart: unless-stopped  # autorestart on fail or config change from WebUI
    environment:
      - TZ=Europe/Rome  # timezone in logs
    volumes:
      - "~/go2rtc:/config"   # folder for go2rtc.yaml file (edit from WebUI)
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
```

I can not see the intel GPU, why?
![Senza titolo](https://github.com/AlexxIT/go2rtc/assets/59020055/c67c6652-3edc-4c91-9e90-4a940c620486)

**Comment by AlexxIT** [comment]
What OS is on your host?
What is the Linux kernel version?
Have you this file on your host? `/dev/dri/renderD128`

**Comment by Veuchez** [comment]
Ubuntu 23.04 Kernel 6.2.0-24
Yes I have the file but even if I do a docker compose so I give the same error
```
services:
  go2rtc:
    container_name: go2rtc
    image: alexxit/go2rtc
    network_mode: host       # important for WebRTC, HomeKit, UDP cameras
    privileged: true         # only for FFmpeg hardware transcoding
    restart: unless-stopped  # autorestart on fail or config change from WebUI
    environment:
      - TZ=Europe/Rome  # timezone in logs
    volumes:
      - "~/go2rtc:/config"   # folder for go2rtc.yaml file (edit from WebUI)
```
