### ISSUE TITLE
v1.6.0 ffmpeg issues - Filtering and streamcopy cannot be used together

### ISSUE THREAD

**Issue by conorlap** [AlexxIT/go2rtc#522]
My camera feed doesn't work when setup as follows, it worked fine on v1.5.0

```
go2rtc:
  streams:
    frontdoor-audio: 
      - "ffmpeg:http://192.168.0.30/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=secretpassword#video=copy#audio=copy#audio=opus#raw= -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000"
    frontdoor-sub: 
      - "ffmpeg:http://192.168.0.30/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=secretpassword#video=copy#audio=copy#audio=opus#raw= -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000"

```
I've also tried these ways:

```
ffmpeg:http://192.168.0.30/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=secretpassword#video=copy#audio=copy#audio=opus#raw= -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000
"ffmpeg:http://192.168.0.30/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=secretpassword#video=copy#audio=copy#audio=opus"
```
