### ISSUE TITLE
Copying audio only works after opening original stream once

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/go2rtc#530]
go2rtc version: 1.6.0

config:

```yaml
streams:
  camera_01:
    - rtsp://192.168.1.20/Streaming/Channels/101
  # Used to discard audio track, workaround for:
  # https://github.com/AlexxIT/go2rtc/issues/198
  camera_03_internal:
    - rtsp://192.168.1.20/Streaming/Channels/301
  camera_03:
    - rtsp://127.0.0.1:8554/camera_03_internal?video
    - rtsp://127.0.0.1:8554/camera_01?audio
```

Basically, I want to copy the audio from camera_01 to camera_03, discarding the existing audio from camera_03 (https://github.com/AlexxIT/go2rtc/issues/198).

However, when I first try to stream camera_03, there is no audio. But if I stream camera_01, and unmute the audio, now audio starts working with camera_03 too.

https://github.com/AlexxIT/go2rtc/assets/29582865/a86bee78-97ee-4e2c-a511-44a5bc51e8ec

**Comment by AlexxIT** [comment]
Is problem relevant on 1.6.2?

**Comment by felipecrs** [comment]
Testing, one sec.

**Comment by felipecrs** [comment]
Yes, the exact same problem happens with 1.6.2.

**Comment by felipecrs** [comment]
Just to update, this still happens on 1.7.0, my config is now:

```yaml
  # Copy audio from camera_03 to camera_01:
  camera_01:
    - rtsp://admin:pass@192.168.1.20/Streaming/Channels/101#media=video
    - rtsp://127.0.0.1:8554/camera_03?audio
  camera_03:
    - rtsp://admin:pass@192.168.1.20/Streaming/Channels/301
```
