### ISSUE TITLE
IPv6 support now disabled (previously working)

### ISSUE THREAD

**Issue by gtxaspec** [AlexxIT/go2rtc#532]
I noticed with the latest release, go2rtc no longer listens on ipv6.  I see on commit https://github.com/AlexxIT/go2rtc/commit/e4b68518e54ff869174d08b9917153d7c36289c8 it was disabled.  

Example usage:
```
api:
  listen: "[2041:0:140F::875B:131B]:1984"
rtsp:
  listen: "[::]:8554"    
```

error:  
`02:05:09.315 FTL [api] listen error="listen tcp4: address 2041:0:140F::875B:131B: no suitable address found"`  
The rtsp setting also does nothing.

Previous release (1.6.0) worked fine with this same IPv6 config.

IPv6 is very important in today's networking,  and we use it almost exclusively in our ip video setups.  

Is further IPv6 support planned?   Thanks!
