### ISSUE TITLE
Unable to restream Nest doorbell from hass

### ISSUE THREAD

**Issue by dmascord** [AlexxIT/go2rtc#541]
I have attempted to configure the hass url in frigate.yaml, but I am seeing the following error:

```
2023-07-22 00:21:02.623115510  10:21:02.622 WRN [rtsp] error="unsupported scheme: hass://supervisor?entity_id=camera.front_door_doorbell" stream=doorbell
```

The frigate.yaml looks like:
```
mqtt:
  host: homeassistant.local
ffmpeg:
  hwaccel_args: preset-nvidia-h264
cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
go2rtc:
  streams:
    doorbell: hass://supervisor?entity_id=camera.front_door_doorbell
```

Frigate 0.12.1 is installed via the HACS Add-on, is the Full Access version, and has protection has been lifted.  go2rtc executable version 1.6.2 has been placed in the /config directory and is corrected detected and used by Frigate.

The camera stream works fine, with audio, via the Lovelace card through the Google Nest integration.
