### ISSUE TITLE
Video hangs, freeze sometimes?

### ISSUE THREAD

**Issue by Jumbo125** [AlexxIT/go2rtc#549]
Hello
I love your work! Great. 
But i have a big problem....
i use go2rtc to embed my rtsp/onvif cameras in my browser (fully kiosk).
How can i setup my coonfigs, to get the best reallife screen(it will be okay to loss some quality, when the video runs without freezing)
Thank you a lot!

I will get you tip, is there a way?

**Comment by porly1985** [comment]
Hi,

did you try different browsers? I made some tests and benchmarks while my streams were hanging sometimes. I went from Firefox to MS Edge which is a lot faster for my configuration. No freezing anymore.

**Comment by AlexxIT** [comment]
Open stream info (from WebUI) in the moment of freezing and past result here.

**Comment by Jumbo125** [comment]
this is my info output
{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://10.0.0.152:8554/Streaming/Channels/101",
      "remote_addr": "10.0.0.152:8554",
      "user_agent": "go2rtc/1.6.0",
      "medias": [
        "video, recvonly, H.264 Main 5.1",
        "audio, recvonly, PCMU/8000"
      ],
      "receivers": [
        "96 H264, bytes=95778650, senders=1",
        "0 PCMU/8000, bytes=12595520, senders=1"
      ],
      "recv": 109742494
    }
  ],
  "consumers": [
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "udp4 host 10.0.0.145:60905",
      "user_agent": "Mozilla/5.0 (Linux; Android 12; T10Pro Build/X900_EEA; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.196 Safari/537.36",
      "medias": [
        "video, sendonly, VP8, RTX, VP9, AV1, H264, RED, ULPFEC, FLEXFEC-03",
        "audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16"
      ],
      "senders": [
        "102 H264, bytes=95778650, receivers=1",
        "0 PCMU/8000, bytes=12595520, receivers=1"
      ],
      "send": 109625500
    }
  ]
}

**Comment by AlexxIT** [comment]
Try to use `mode: webrtc/tcp` or `mode: mse`

**Comment by Jumbo125** [comment]
unfortunately it still hangs.... by the way: how can i setup, that the audio not start automatically? can i set it in the url parameter?

**Comment by AlexxIT** [comment]
ONVIF it's just an API for receive RTSP link

**Comment by Jumbo125** [comment]
okay. i see.
sorry to ask you again, but if there any solution to mute the audio on the loading?

#backchannel=0 not work

**Comment by Jumbo125** [comment]
WebRTC integration has mute option

how can i set this?

**Comment by Jumbo125** [comment]
sorry to bother you again.
do you knwo, where i can ask my questions for your project? is there a community or something else?
i only want to know, where i set mode=webrtc/tcp ???

in the streaming url, or in the config file?
if i can set it in the config file,
do i need to set it behind the stream url?

```
streams:
    vorne: 
        - rtsp://us:pw@10.0.0.152:8554/Streaming/Channels/101/mode=webrtc/tcp
    terrasse:
        - rtsp://us:pw@10.0.0.151:8554/Streaming/Channels/101?/
    katze1:
        - rtsp://10.0.0.153:554/onvif1/
    katze2:
        - rtsp://10.0.0.154:554/onvif1/
webrtc:
  listen: ":8554"
```

or should i set it in the webrtc section:
```
streams:
    vorne: 
        - rtsp://us:pw@10.0.0.152:8554/Streaming/Channels/101/
    terrasse:
        - rtsp://us:pw@10.0.0.151:8554/Streaming/Channels/101?/
    katze1:
        - rtsp://10.0.0.153:554/onvif1/
    katze2:
        - rtsp://10.0.0.154:554/onvif1/
webrtc:
  listen: ":8554"
 mode: webrtc/tcp
```
do i need to set it in quotation marks?
thank you a lot!!!
