### ISSUE TITLE
Remote WebRTC using STUN/TURN server

### ISSUE THREAD

**Issue by aflat00n** [AlexxIT/go2rtc#554]
```
webrtc:
  ice_servers:
    - urls: [stun:stun.l.google.com:19302]
    - urls: [turn:a.relay.metered.ca:443]
      username: <username>
      credential: <password>
```
I was able to configure TURN server to access my stream through internet, the TURN server is running. My only query is how am i able to generate a permanent link and view camera stream over internet?

**Comment by AlexxIT** [comment]
If you have public IP, you can port forward go2rtc WebUI (with basic auth). If not - use webtorrent (check readme).

**Comment by aflat00n** [comment]
Yes i am using webtorrent, i configured webtorrent according to the readme and added the webtorrent stream. Kindly have a look:

```
streams:
  dahua6_101: rtsp://admin:abc12345@192.168.100.6:554/cam/realmonitor?channel=1&subtype=0
  webtorrent1: webtorrent:?share=test&pwd=password

webtorrent:
  shares:
    test:  # share name, should be unique among all go2rtc users!
      pwd: password
      src: dahua6_101   # stream name from streams section

webrtc:
  ice_servers:
    - urls: [stun:stun.l.google.com:19302]
    - urls: [turn:a.relay.metered.ca:443]
      username: <username>
      credential: <password>
```
How will i be able to view it on lets say a mobile device on cellular data or from some other computer over the internet?

Any help is much appreciated!
