### ISSUE TITLE
Fix redirect for rtspx source

### ISSUE THREAD

**Issue by jneilliii** [AlexxIT/go2rtc#565]
receive the following error on windows 10 running go2rtc version 1.6.2
```
15:56:26.569 ERR github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:178 > error="wrong response on DESCRIBE"
```
with following simple config
```
streams:
  bambu_camera: rtspx://user:password@192.168.126.9:322/streaming/live/1
ffmpeg:
  bin: "C://go2rtc_win64/ffmpeg.exe"
```

found similar error in #391, but there are no port conflicts like in that case. using `ffmpeg:rtsps://user:password@192.168.126.9:322/streaming/live/1` seems to work ok but is pretty glitchy/laggy with the error `EOF url=ffmpeg:rtsps://user:password@192.168.126.9:322/streaming/live/1` repeatedly and wasn't sure if the other rtspx method would work better or not.
