### ISSUE TITLE
How go2rtc works? Any docs?

### ISSUE THREAD

**Issue by jiekechoo** [AlexxIT/go2rtc#572]
Go2rtc is very good, I like it. I need some docs to learn. 
such as: 

my config, using onvif camera:
```
api:
  listen: ":1984"
streams:
  office: onvif://admin:a12345678@192.168.123.37
  haikang: onvif://admin:a12345678@192.168.123.109
  tplink: onvif://admin:a12345678@192.168.123.13
```
but I did't find any stream process in docker container:
```
/config # ps -ef
PID   USER     TIME  COMMAND
    1 root      0:00 /sbin/tini -- go2rtc -config /config/go2rtc.yaml
    7 root      1:55 go2rtc -config /config/go2rtc.yaml
   19 root      0:00 /bin/sh
   29 root      0:00 ps -ef
/config # 
```

if I use `ffmpeg` as stream source, process 'ffmpeg' is listed.
```
/config # ps -ef  |grep ffmpeg
   32 root      0:00 ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://admin:a12345678@192.168.123.37/live/main -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/f22af3ad44cfc00d453aae5114910535
   44 root      0:00 grep ffmpeg
/config # 

```

How it works?
