### ISSUE TITLE
Best solution for tcp YUV source 

### ISSUE THREAD

**Issue by deepnxg** [AlexxIT/go2rtc#576]
Hi , Go2rtc is an impressive solution especially at 4k. Thank you for your contribution. I have the following scenario to resolve. Receive raw packets of YUV 422 from DVR SDK for eg: Hikvision and stream it to the local host html browser(go2rtc will need to run on a windows PC). I plan to host the YUV stream from the SDK callback on a TCP end point . What are the possible options Exec or FFmpeg be used ? How to avoid need for h.264 conversion that will introduce significant latency & CPU/GPU usage. Appreciate your feedback. Thank you for your time.

**Comment by AlexxIT** [comment]
It's hard to draw YUV422 in the browser. It's easier to have JPEG or H264.
Also JPEG size much more than H264. And YUV422 size much more than JPEG. There may not be enough network bandwidth for that at all.

So you can transcode YUV422 to H264/MJPEG via FFmpeg. I'm not sure about example, try to play with it:

```
ffmpeg:
  mytcp: -r 25.0 -f rawvideo -s 1920x1080 -pix_fmt yuv422p -i {input}
streams:
  camera1: ffmpeg:tcp://xxx#input=mytcp#video=h264#hardware
```
