### ISSUE TITLE
HomeKit Camera 2 Way Audio

### ISSUE THREAD

**Issue by seydx** [AlexxIT/go2rtc#579]
Hey, my HomeKit camera "Eve Outdoor Cam" runs great with go2RTC! Thanks for the great software.

What I'm wondering now is, is it somehow possible to get "Two Way Audio" working? Since it's a pure HomeKit camera and works without a third party app, I can't say how the Two Way Audio comes about.

Do you know of any way to figure it out?

### Info
```
{
  "producers": [
    {
      "type": "HomeKit active producer",
      "url": "homekit://192.168.178.72:62856?device_id=XXX\u0026device_public=XXX\u0026client_id=XXX\u0026client_private=XXX",
      "medias": [
        "video, recvonly, H264",
        "audio, recvonly, ELD/16000/1"
      ],
      "receivers": [
        "0 H264, bytes=2823676766, senders=3",
        "0 ELD/16000/1, bytes=30779465, senders=3"
      ],
      "recv": 2910946951
    },
    {
      "type": "RTSP passive producer",
      "url": "rtsp://127.0.0.1:8554/00fe64e283c8e733f5016ae5a80f5f3a",
      "remote_addr": "127.0.0.1:41504",
      "user_agent": "ffmpeg/go2rtc",
      "medias": [
        "audio, recvonly, OPUS/48000/2"
      ],
      "receivers": [
        "96 OPUS/48000/2, bytes=105212597, senders=1"
      ],
      "recv": 111628953
    }
  ],
  "consumers": [
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://192.168.178.133:8554/eingang_kamera?video=h264\u0026audio=opus",
      "remote_addr": "192.168.178.133:41090",
      "user_agent": "Lavf58.76.100",
      "medias": [
        "video, sendonly, H264",
        "audio, sendonly, OPUS"
      ],
      "senders": [
        "96 H264, bytes=6610917308, receivers=1",
        "97 OPUS/48000/2, bytes=246052797, receivers=1"
      ],
      "send": 6959575497
    },
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/eingang_kamera?audio",
      "remote_addr": "127.0.0.1:39658",
      "user_agent": "go2rtc/ffmpeg",
      "medias": [
        "audio, sendonly, ANY"
      ],
      "senders": [
        "96 ELD/16000/1, bytes=30779465, receivers=1"
      ],
      "send": 36429929
    },
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://192.168.178.133:8554/eingang_kamera",
      "remote_addr": "192.168.178.133:39700",
      "user_agent": "Lavf60.3.100",
      "medias": [
        "audio, sendonly, ANY",
        "video, sendonly, ANY"
      ],
      "senders": [
        "96 ELD/16000/1, bytes=30773028, receivers=1",
        "97 H264, bytes=2822940869, receivers=1"
      ],
      "send": 2894787721
    },
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://192.168.178.133:8554/eingang_kamera",
      "remote_addr": "192.168.178.133:39702",
      "user_agent": "Lavf60.3.100",
      "medias": [
        "audio, sendonly, ANY",
        "video, sendonly, ANY"
      ],
      "senders": [
        "96 ELD/16000/1, bytes=30772579, receivers=1",
        "97 H264, bytes=2822922961, receivers=1"
      ],
      "send": 2894769028
    }
  ]
}
```

### Config
```
streams:
  eingang_kamera:
    - homekit://192.168.178.72:51959?client_id=XXX&client_private=XXX_id=XXX&device_public=XXX
    - ffmpeg:eingang_kamera#audio=opus
  eingang_kamera2:
    - ffmpeg:rtsp://192.168.178.133:8554/eingang_kamera#audio=opus#input=vaapi_input#video=vaapi_h264_scale1280x720

  eingang_kamera3:
    - ffmpeg:rtsp://192.168.178.133:8554/eingang_kamera#audio=opus#input=vaapi_input#video=vaapi_h264_scale480x360
  
ffmpeg:
  vaapi_input: >-
    -hwaccel vaapi -hwaccel_output_format vaapi -fflags nobuffer -flags low_delay -i {input}
  vaapi_h264_scale480x360: >-
    -c:v h264_vaapi -g 50 -bf 0 -profile:v high -level:v 4.1 -sei:v 0
    -vf "format=vaapi|nv12,hwupload,scale_vaapi=w=480:h=360"
  vaapi_h264_scale1280x720: >-
    -c:v h264_vaapi -g 50 -bf 0 -profile:v high -level:v 4.1 -sei:v 0
    -vf "format=vaapi|nv12,hwupload,scale_vaapi=w=1280:h=720"
```
