### ISSUE TITLE
Add support L16/16000/2

### ISSUE THREAD

**Issue by moskovskiy82** [AlexxIT/go2rtc#580]
Have a Reolink 800 cam working through the neolink integration. 

The config is simple as
```yaml
streams:
  camera:
  - rtsp://192.168.1.8:8551/Main  
```
With the audio enabled on the cam i received the following errors
ERROR: MP4 unsupported codec: 96 L16/16000/2

Disabling the audio didn't help that much. As i don't need this stream is there a simple way just to discard it?

**Comment by AlexxIT** [comment]
What go2rtc version you using? Show your config.

**Comment by moskovskiy82** [comment]
> What go2rtc version you using? Show your config.
It's Version: 1.6.2 running in Frigate (replaced the stock one)

So there is nothing much to show

frigate config
```
go2rtc:
  streams:
    cam1
    - url:
    cam2
    cam3
```
e.t.c.
For the camera in question the url part ia above

rtsp://192.168.1.8:8551/Main

If i expand the go2rtc config in frigate than i get stock options

```
api:
  origin: '*'
log:
  format: text
rtsp:
  default_query: mp4
streams:
  cam1:
  - rtsp://xxx:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
  - ffmpeg:kalitka#audio=aac
  cam2:
  - rtsp://xxx/xxx&channel=1&stream=0?.sdp#input=rtsp/udp
 cam3:
  - ffmpeg:http://xxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxx
  camera:
  - rtsp://192.168.1.8:8551/Main  
  
  
webrtc:
  candidates:
  - stun:8555
```
