### ISSUE TITLE
unable to populate media section, RTPSender created with no codecs

### ISSUE THREAD

**Issue by jakepricedev** [AlexxIT/go2rtc#582]
I'm running go2rtc with Docker Compose, and I'm seeing the below error when I load a stream.

```log
ha_go2rtc-01  | 23:17:59.153 INF go2rtc version 1.6.2 linux/amd64
ha_go2rtc-01  | 23:17:59.153 INF [api] listen addr=0.0.0.0:1984
ha_go2rtc-01  | 23:17:59.153 INF [rtsp] listen addr=0.0.0.0:8554
ha_go2rtc-01  | 23:17:59.153 INF [webrtc] listen addr=0.0.0.0:8555/tcp
ha_go2rtc-01  | 23:17:59.154 INF [srtp] listen addr=0.0.0.0:8443
ha_go2rtc-01  | 23:19:23.860 ERR github.com/AlexxIT/go2rtc/internal/webrtc/webrtc.go:181 > error="unable to populate media section, RTPSender created with no codecs"
```

My compose config looks like this:

```yaml
  go2rtc:
    image: alexxit/go2rtc
    container_name: ha_go2rtc-01
    privileged: true
    restart: unless-stopped
    user: 1000:1000
    environment:
      - TZ=Europe/London
    volumes:
      - $PWD/go2rtc:/config
```

and my go2rtc.yaml is as bare as the below (just with more streams configured (all the same though, just different IP's).

```yaml
streams:
  landing: rtsp://<username>:<password>@<ip>/stream1
```` 

I'm not sure if this is an error I need to fix, or an error that can be ignored. Any help would be much appreciated.

**Comment by AlexxIT** [comment]
You need to increase log level. For some additional info before error

**Comment by jakepricedev** [comment]
Thanks increased the level to debug, by adding the below to `go2rtc.yml`.

```yaml
log:
  level: debug
```

Nothing obviously going on to suggest what the error is about?

```
ha_go2rtc-01  | 15:54:22.206 INF go2rtc version 1.6.0 linux/amd64
ha_go2rtc-01  | 15:54:22.207 INF [api] listen addr=:1984
ha_go2rtc-01  | 15:54:22.208 INF [rtsp] listen addr=:8554
ha_go2rtc-01  | 15:54:22.208 INF [webrtc] listen addr=:8555/tcp
ha_go2rtc-01  | 15:54:22.208 DBG [hass] can't import config: open .storage/core.config_entries: no such file or directory
ha_go2rtc-01  | 15:54:22.209 INF [srtp] listen addr=:8443
ha_go2rtc-01  | 15:56:05.423 DBG [webrtc] new consumer src=rtsp://go2rtc.int.price.gb.net/front-door_hd
ha_go2rtc-01  | 15:56:05.460 DBG [webrtc] new consumer src=rtsp://go2rtc.int.price.gb.net/car-port_hd
ha_go2rtc-01  | 15:56:05.488 DBG [webrtc] new consumer src=rtsp://go2rtc.int.price.gb.net/garden_hd
ha_go2rtc-01  | 15:56:05.508 DBG [webrtc] new consumer src=rtsp://go2rtc.int.price.gb.net/side-alley_hd
ha_go2rtc-01  | 15:56:05.947 DBG [streams] start producer url=rtsp://<username>:<password>@<ip-address>/stream1
ha_go2rtc-01  | 15:56:05.948 ERR github.com/AlexxIT/go2rtc/internal/webrtc/init.go:177 > error="unable to populate media section, RTPSender created with no codecs"
ha_go2rtc-01  | 15:56:05.978 DBG [streams] start producer url=rtsp://<username>:<password>@<ip-address>/stream1
ha_go2rtc-01  | 15:56:05.978 ERR github.com/AlexxIT/go2rtc/internal/webrtc/init.go:177 > error="unable to populate media section, RTPSender created with no codecs"
```

Not to worry, everything seems to work fine.

**Comment by AlexxIT** [comment]
Can you try latest go2rtc version? Maybe problem fixed already. WebRTC shouldn't work for you because of this error.
Also you can try to increase log level to trace.

**Comment by cpadil** [comment]
I'm getting the exact same error, I'm using Frigate v13 beta 1 (dev-080d7a2) which is using the last version of go2rtc 1.7.1

I've noticed that I get the error ONLY when I try to see the WebRTC stream in Firefox in Linux (it never loads)

the re-stream to frigate is restarted 

here is the log 
```2023-09-21 12:49:44.271871870  12:49:44.271 DBG [webrtc] new consumer src=bed_cam
2023-09-21 12:49:44.272205998  12:49:44.272 DBG [exec] run url="exec:ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/bed_cam?audio -c:a libopus -application:a lowdelay -frame_duration 20 -min_comp 0 -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp {output}"
2023-09-21 12:49:44.275025312  12:49:44.274 DBG [rtsp] new consumer stream=bed_cam
2023-09-21 12:49:44.425305341  12:49:44.425 DBG [exec] run launch=153.0571ms
2023-09-21 12:49:44.425316718  12:49:44.425 DBG [streams] stop producer url=ffmpeg:bed_cam#audio=opus
2023-09-21 12:49:44.425470657  av_interleaved_write_frame(): Broken pipe
2023-09-21 12:49:44.425655761      Last message repeated 1 times
2023-09-21 12:49:44.425956454  12:49:44.425 DBG [rtsp] handle=EOF
2023-09-21 12:49:44.425996748  12:49:44.425 DBG [streams] can't stop none producer
2023-09-21 12:49:44.425997918  12:49:44.425 DBG [rtsp] disconnect stream=bed_cam
2023-09-21 12:49:44.426101932  12:49:44.426 ERR github.com/AlexxIT/go2rtc/internal/webrtc/webrtc.go:181 > error="unable to populate media section, RTPSender created with no codecs"
```


this is the config
```
go2rtc: 
  streams: 
    bed_cam: 
      - rtsp://usr:pwd@XXX:554/live
      - "ffmpeg:bed_cam#audio=opus" 
    main_cam:  
      - rtsp://usr:pwd@XXX:554/live 
      - "ffmpeg:main_cam#audio=opus" 

  webrtc: 
    candidates: 
      - XXX:8555 
      - stun:8555 
  log:
    level: debug
```
