### ISSUE TITLE
Fix panic from roborock source (iot.Dial error)

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/go2rtc#601]
I have also problems since the last HA Update. The Add-On does no longer start. Once i restart it it will immediately shutdown. I got those error log

```
09:37:02.904 INF go2rtc version 1.6.2 linux/arm64
09:37:02.906 INF [api] listen addr=0.0.0.0:1984
09:37:02.907 INF [rtsp] listen addr=0.0.0.0:8554
09:37:02.908 INF [webrtc] listen addr=0.0.0.0:8555/tcp
09:37:02.915 INF [srtp] listen addr=0.0.0.0:8443
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x53cc84]
goroutine 9 [running]:
net/rpc.(*Client).send(0x400042a008?, 0x0?)
	net/rpc/client.go:72 +0x24
net/rpc.(*Client).Go(0x40000bf708?, {0x7d1a3e, 0x1a}, {0x0?, 0x0}, {0x68e6a0?, 0x4000428060}, 0x40004100c0)
	net/rpc/client.go:315 +0x160
net/rpc.(*Client).Call(...)
	net/rpc/client.go:321
github.com/AlexxIT/go2rtc/pkg/roborock.(*Client).GetHomesecConnectStatus(0x4000220000)
	github.com/AlexxIT/go2rtc/pkg/roborock/client.go:208 +0x78
github.com/AlexxIT/go2rtc/pkg/roborock.(*Client).Connect(0x4000220000)
	github.com/AlexxIT/go2rtc/pkg/roborock/client.go:61 +0x4c
github.com/AlexxIT/go2rtc/internal/roborock.handle({0x400003a480, 0x87})
	github.com/AlexxIT/go2rtc/internal/roborock/roborock.go:23 +0x6c
github.com/AlexxIT/go2rtc/internal/streams.GetProducer({0x400003a480, 0x87})
	github.com/AlexxIT/go2rtc/internal/streams/handlers.go:40 +0x3c
github.com/AlexxIT/go2rtc/internal/streams.(*Producer).Dial(0x40001883f0)
	github.com/AlexxIT/go2rtc/internal/streams/producer.go:62 +0xd0
github.com/AlexxIT/go2rtc/internal/streams.(*Stream).AddConsumer(0x40001cc3c0, {0x8d8de0?, 0x40002d8b40})
	github.com/AlexxIT/go2rtc/internal/streams/stream.go:61 +0x490
github.com/AlexxIT/go2rtc/internal/rtsp.tcpHandler.func1({0x6affa0?, 0x8d23d8?})
	github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:189 +0x584
github.com/AlexxIT/go2rtc/pkg/core.(*Listener).Fire(...)
	github.com/AlexxIT/go2rtc/pkg/core/listener.go:16
github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Accept(0x40002d8b40)
	github.com/AlexxIT/go2rtc/pkg/rtsp/server.go:94 +0xa54
github.com/AlexxIT/go2rtc/internal/rtsp.tcpHandler(0x40002d8b40)
	github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:221 +0x198
created by github.com/AlexxIT/go2rtc/internal/rtsp.Init.func1
	github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:75 +0x3c
```

_Originally posted by @smartmatic in https://github.com/AlexxIT/go2rtc/issues/596#issuecomment-1696932008_

**Comment by erbmur** [comment]
I get this error as well.
If the roborock is running, then I start go2rtc, then it works fine. As soon as the roborock docks, the plugin fails again.

**Comment by mattyg-repo** [comment]
same here
For a temporary workaround, you can use an automation like this

```
alias: roborock - restart stream
description: ""
trigger:
  - platform: device
    device_id: 872c758f00f6a1811d1492a3880c76a6
    domain: vacuum
    entity_id: 099071e6b07507d86c51d3eaba97ced4
    type: cleaning
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: hassio.addon_restart
    data:
      addon: a889bffc_go2rtc
mode: single
```
