### ISSUE TITLE
Nest Doorbell Wired (2nd Gen) go2rtc stream with audio from HA source shows as corrupted in frigate after stream reconnects

### ISSUE THREAD

**Issue by EvanGrote** [AlexxIT/go2rtc#604]
I initially opened https://github.com/blakeblackshear/frigate/issues/7515 about this issue but the frigate devs think the underlying issue could be with go2rtc or the doorbell's stream itself so I wanted to open an issue here as well to get some more eyes on this.

I have a Nest Doorbell Wired (2nd Gen) configured with a home assistant source in go2rtc which works perfectly with the default mp4 stream (`rtsp://frigate_local_ip:8554/entryway_doorbell_frigate?mp4` but contains no audio. When I change to a stream with audio (`rtsp://frigate_local_ip:8554/entryway_doorbell_frigate?audio&video`) the stream works initially but eventually leads to an endless log stream of `WARNING : Discarding a corrupt recording segment: /tmp/cache/entryway_doorbell_frigate-<timestamp>.mp4` errors about 5-10 minutes after frigate startup. The issue persists regardless of whether the OPUS audio from the doorbell is transcoded to AAC in frigate or in go2rtc, so I don't think the transcoding is the problem.

I'm running everything in docker on a NAS using a version `1.6.2` binary of go2rtc in frigate with frigate version `0.12.1-367D724`

Here is a gist of the log output I'm seeing from go2rtc and frigate when the issue occurs: https://gist.github.com/EvanGrote/47208bca7fd9758aab2ce31019a2d2e7

**Comment by NickM-27** [comment]
To be clear, what I said was:

> I'd think it's more than likely an issue with the doorbells stream, but I suppose it could be go2rtc as well.

**Comment by EvanGrote** [comment]
@NickM-27 My apologies, I read "the doorbells stream" in your comment and conflated that with the doorbell's stream _from go2rtc_. I didn't intend to misrepresent what you said. I've reworded my description to reflect that.

**Comment by AlexxIT** [comment]
What source you using for this connection? Nest devices drops connection every 5 minutes.

**Comment by EvanGrote** [comment]
I'm using the hass source in go2rtc. The source in Home Assistant is their [Nest Integration](https://www.home-assistant.io/integrations/nest).

My go2rtc config in frigate:
```
go2rtc:
  hass:
    config: "/home_assistant_config"
  streams:
    entryway_doorbell_frigate: 
      - hass://redacted_HA_local_ip:8123?entity_id=camera.entryway_doorbell&token=redacted_HA_long_term_access_token
  webrtc:
    candidates:
      - redacted_frigate_local_ip:8555
      - stun:8555
```
