### ISSUE TITLE
Fix support HomeKit server on macOS

### ISSUE THREAD

**Issue by OskarLebuda** [AlexxIT/go2rtc#626]
Hi, 
I’m not familiar with this lib so let me know if there are some answers for my questions 

I found that I can use my homekit cameras (Aqara G2H Pro) into my custom app using this lib. But all of the docs told me that I have to known the `homekit://` url. But... There is no information about "How to get `homekit://` url".

Can someone tell me what should I do to get stream from my Aqara cameras into Go2RTC? 
What should I do?
How to configure it?

I've tried to use docker image on mac to add my other camera (Eufy indoor cam) and I've got an error:
![image](https://github.com/AlexxIT/go2rtc/assets/10373127/6e1bd552-9971-4f6e-802c-8a9b5f6d896e)

my config:
```yml
api:
  origin: "*"
streams:
  eufy1:
    - rtsp://username:password@192.168.1.33/live0
    - ffmpeg:eufy1#video=h264#hardware
    - ffmpeg:eufy1#audio=opus
homekit:
  eufy1:
    pin: 19550224
    name: Eufy cam
    device_id: eufy1
    device_private: eufy1
```

I really don't know if I doing it right so let me know. 

Another problem is that docker on mac does not support `network_mode: host` so I proxy ports like:
```yml
version: "3.7"

services:
  go2rtc:
    container_name: cube-home-go2rtc
    image: alexxit/go2rtc:1.7.1
    privileged: true
    restart: unless-stopped
    ports:
      - 1984:1984
      - 8554:8554
      - 8555:8555
    environment:
      - TZ=Europe/Berlin
    volumes:
      - "./docker/go2rtc:/config"
```

Let me know if it's a problem for this lib
