### ISSUE TITLE
The camera channel gets stuck when I open it from HA with ffmpeg.

### ISSUE THREAD

**Issue by gleanlux** [AlexxIT/go2rtc#627]
Hello!
I would like to ask for help in finding the problem:

I have a new Reolink Doorbell PoE camera.
If I add it to the configuration with default settings, I can get an image almost instantly without any problems in HA.
In this case, if I open the stream from go2rtc webUI, I see that it works in MSE mode, I get sound here, but no sound under HA.

Based on what I read on the internet, I set up ffmpeg in go2rtc.
I saw that this was necessary to handle the camera in RTC mode and to have sound during HA, as well as two-way sound.

After that, when I open the camera from the go2rtc webUI, it starts ffmpeg without error and switches to RTC mode.
No matter how many times I open it, close it, it works every time.

![image](https://github.com/AlexxIT/go2rtc/assets/10788037/a2e80bad-77e1-46ba-a81b-bc4c379b6a36)

However, when I open the camera under HA, it always starts with a "stop producer" message first, and from that moment on it doesn't work even from the go2rtc webUI. It will not start ffmpeg anymore and keeps displaying "can't stop none producer" message.
This state persists until I restart go2rtc.

![image](https://github.com/AlexxIT/go2rtc/assets/10788037/65b94e2d-0a88-4975-8368-048ad484bf9c)
20:43:01 Start stream from HA.
20:43:21 Stop stream from HA.
20:44:45 Start stream from go2rtc webUI.

**I also experienced a third case:
If I start the stream on the go2rtc webUI and it is running in rtc mode properly, I can open it from HA without any problems any number of times, and it has sound properly!**

Thanks in advance for your help!
If you need any further information, I am at your disposal!

System data:
Used on all local networks.
go2rtc x64 1.6.4, 1.7.0, 1.7.1 (tried all three versions)
ffmpeg 6.0 x64 
Home Assistant 2023.7.3 on 10.3 core
  - RTSPtoWebRTC

go2rtc config:

```
ffmpeg:
  bin: "d:/Programs/ffmpeg/bin/ffmpeg.exe"
  rtsp: "-fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_transport tcp -i {input}"

  
log:
  format: ""
  level: "debug"

streams:
  camera.camera1_sub:
    - rtsp://admin:xxxyyy@192.168.xx.xx:554/h264Preview_01_sub
    - ffmpeg:camera.camera1_sub#audio=pcm
```
