### ISSUE TITLE
Multiple Nvidia Cards?

### ISSUE THREAD

**Issue by domenicdistefano** [AlexxIT/go2rtc#639]
Below is a [cross post question](https://github.com/blakeblackshear/frigate/discussions/7792) I asked over on the Frigate Discussion board. 

In response @NickM-27 over there says 

> [need to use manual args](https://saturncloud.io/blog/how-to-specify-the-gpu-for-nvenc-in-ffmpeg/#:~:text=Specifying%20the%20GPU%20for%20nvenc%20in%20FFmpeg,-Now%20that%20we&text=To%20do%20this%2C%20we'll,the%20video%20encoder%20to%20use) 

The link Nick points to says to use this ffmpeg command / syntax to specify which GPU to use for encode / decode  - `ffmpeg -hwaccel_device 1 -i input.mp4 -c:v h264_nvenc -preset slow output.mp4`

Not sure how to translate that into a proper go2rtc command. Here is an example of one of the cameras I have setup. How would I  (or does go2rtc currently support) incorporate the `-hwaccel_device 1 `parameter using go2rtc syntax?

```
go2rtc:
  streams:
    back_yard:
      - rtsp://admin:Goldfish10-@10.10.10.72:554/media/video0
    back_yard_sub:
       - "ffmpeg:back_yard#video=h264#width=1920#height=1080#raw=-fpsmax 10#hardware=vaapi"
```

-------------------------------------------
I found a good deal on an Nvidia T400 card I ordered to go alongside my existing P600. I currently have 12 cameras balancing between the iGPU and P600 but the discreet card is nearly maxed out with its 2GB of VRAM. The T400 has 4GB so I would like to add  instead of replacing the p600 if possible.

So according to the below examples from the docs enabling both cards in the Docker Compose file seems straight forward. My question however is how exactly do you assign a particular camera stream for detection to a particular NVIDIA GPU?

Its easy to assign / differentiate between the iGP & a single NVIDIA card by adding ether `hardware=vaapi `or `hardware=cuda `to the end of the go2rtc section of the ffmpeg config for a particular substream of a camera. Problem is I am not seeing any way on the go2rtc [Hardware Acceleration wiki page](https://github.com/AlexxIT/go2rtc/wiki/Hardware-acceleration) around how to assign a camera's substream to a particular NVIDA card if more than one is present.

Anyone figured this out?

Frigate Docs:
```
services:
  frigate:
    ...
    image: ghcr.io/blakeblackshear/frigate:stable
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0'] # this is only needed when using multiple GPUs
              count: 1 # number of GPUs
              capabilities: [gpu]
```

Docker Docs:
[Access specific devices](https://docs.docker.com/compose/gpu-support/#access-specific-devices) 
To allow access only to GPU-0 and GPU-3 devices:
```
services:
  test:
    image: tensorflow/tensorflow:latest-gpu
    command: python -c "import tensorflow as tf;tf.test.gpu_device_name()"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0', '3']
            capabilities: [gpu]
```

**Comment by AlexxIT** [comment]
You can always use exec source instead of ffmpeg source. And use whatever parameters you need there

**Comment by domenicdistefano** [comment]
With was solved - see below - [full thread](https://github.com/blakeblackshear/frigate/discussions/7792) over on the Frigate forum.


```
go2rtc:

  ffmpeg:
    cuda0: "-fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -hwaccel_device 0 -rtsp_transport tcp -i {input}"
    cuda1: "-fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -hwaccel_device 1 -rtsp_transport tcp -i {input}"
    cuda2: "-fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -hwaccel_device 2 -rtsp_transport tcp -i {input}"

  streams:
    back_porch:
      - rtsp://admin:redacted10.10.10.71:554/media/video0
    back_porch_sub:
      - "ffmpeg:back_porch#input=cuda1#video=h264#width=1920#height=1080#raw=-fpsmax 10 -gpu 1#hardware=cuda"
```
