### ISSUE TITLE
Weird Stream Format? Vlc crashes

### ISSUE THREAD

**Issue by gotschi** [AlexxIT/go2rtc#640]
Thank you for go2rtc first off!

I have a small problem where when I stream a pi cam with audio from usb mic it crashes my vlc. other player works fine but it seems frigate also doesn't cope well with it (I don't get audio mainly)

Config:
```yaml
streams:
  cam: 
    - exec:libcamera-vid --width 1296 --height 730 --codec h264 -b 600000 -t 0 --framerate 15 --inline -o -
    - exec:ffmpeg -f alsa -channel_layout mono -ac 1 -i dsnoop:CARD=Device,DEV=0 -map 0:a:0 -map 0:a:0 -ac:a:0 1 -ac:a:1 1 -ac:a:2 1 -c:a:0 aac -b:a:0 64k -c:a:1 libopus -b:a:1 64k -ar:a:0 16000 -ar:a:1 16000 -filter:a:0 "volume=8.0,adelay=0ms" -filter:a:1 "volume=8.0,adelay=0ms" -rtsp_transport tcp -f rtsp {output}
  ```

URL: rtsp://ip:8554/cam?**video=all&audio=all**

As soon as vlc crashes (it stalls, not reacting anymore) go2rtc outputs:
`WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:224 > error="read tcp 10.0.40.2:8554->10.0.59.1:63847: i/o timeout"`
`20:42:05.440 DBG [rtsp] handle=read tcp 10.0.40.2:8554->10.0.59.1:63724: read: connection reset by peer`
`20:42:05.441 DBG [rtsp] disconnect stream=cam`

other players work fine (IINA, Browsers with MSE and RTC)

I'm not sure what the issue is here but Frigate also does not pick up the audio stream, video gets received and detection runs without trouble though.

ffprobe results in:
```
ffprobe version 5.1.3-1 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x55795d3e1700] method SETUP failed: 461 Unsupported transport
[h264 @ 0x55795d3e5080] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55795d3e5080] decode_slice_header error
[h264 @ 0x55795d3e5080] no frame!
Input #0, rtsp, from 'rtsp://ip:8554/cam?video=all&audio=all':
  Metadata:
    title           : go2rtc/1.5.0
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 1296x730, 15 fps, 15 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
  Stream #0:2: Audio: opus, 48000 Hz, stereo, fltp
  ```

and something else just came to my mind:
can we implement a /playlist endpoint to get a m3u8 with all the cams? that would be a cool feature I think
