### ISSUE TITLE
Exec and drawtext problem

### ISSUE THREAD

**Issue by LordXaosa** [AlexxIT/go2rtc#649]
Hi, I'm trying to restream with adding a timestamp to original video but no luck. Here is my config:
```
go2rtc:
  streams:
    kids_cam: >-
      exec:ffmpeg
      -rtsp_transport tcp -i "rtsp://user:password@192.168.x.x/live"
      -rtsp_transport tcp
      -c:a aac
      -reset_timestamps 1 -strftime 1
      -filter:a "volume=20dB"
      -f rtsp
      -vf "drawtext=text='%{localtime}':x=2:y=20:fontsize=72:fontcolor=white:box=1:boxcolor=black:boxborderw=2" 
      {{output}}
```
Volume filter is for volume gain to make audio detection fine.

So it fails and I can't realise why. In record section all works fine, but I want timestamp in live preview.

Record section:
```
cameras:
  kids:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/kids_cam
        roles:
        - detect
        - record
        - audio
      output_args:
        record: >-
          -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1
          -strftime 1 -c:a aac 
          -vf "drawtext=text='%{localtime}':x=2:y=20:fontsize=72:fontcolor=white:box=1:boxcolor=black:boxborderw=2"
```
Using latest beta version of frigate 0.13.0 beta 1, go2rtc 1.6.2
