### ISSUE TITLE
Error="streams: magic: unsupported header: 3c21444f"

### ISSUE THREAD

**Issue by frakman1** [AlexxIT/go2rtc#650]
I get this error when trying to view the [Contacam](https://www.contaware.com/contacam.html) security camera home page as a feed (I get this error for all provided stream links)

`18:31:14.170 ERR github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:166 > error="streams: magic: unsupported header: 3c21444f"`

This method works when I point to an individual camera's feed using the following form:

`http://CONTACAM-PC1:PORT/CAMERA_NAME/push.php?username=xxx&password=xxx`

I would use this entry in the configuration file with the uppercase values substituted for real ones:

```yaml
streams:
  garage:
    - http://CONTACAM-PC1:PORT/CAMERA_NAME/push.php?username=xxx&password=xxx
```
This works.

However, when I try to use the `CONTACAM-PC1:PORT` directly without the `CAMERA_NAME` portion i.e.:

`http://CONTACAM-PC1:PORT/?username=xxx&password=xxx`

```yaml
streams:
  contacam:
    - http://CONTACAM-PC1:PORT/?username=xxx&password=xxx
```

I get the above error even though that URL works and loads fine in a browser

I want to be able to view the entire summary page with all the cameras as one stream/feed.

Using latest version of `go2rtc` as of today `Version: 1.7.1` via an Unraid docker container
