### ISSUE TITLE
streams: codecs not matched: H264 => VP8, RTX, VP9, OPUS, G722, PCMU, PCMA, TELEPHONE-EVENT, S16B, S16L

### ISSUE THREAD

**Issue by mr-manuel** [AlexxIT/go2rtc#665]
Hello,

when I try to access the `http://192.168.1.205:1984/stream.html` page I get this error in the logs:

```bash
DBG [webrtc] add consumer error="streams: codecs not matched: H264 => VP8, RTX, VP9, OPUS, G722, PCMU, PCMA, TELEPHONE-EVENT, S16B, S16L"
```

Same error with these URLS:
```
http://192.168.1.205:1984/stream.html?src=Gitter&mode=webrtc
http://192.168.1.205:1984/stream.html?src=Gitter&mode=mse
```

The RTSP camera stream is `h264` from what I understand:

```bash
root@e4ce871a31f5:/root# ffprobe rtsp://192.168.1.80:554/11
Input #0, rtsp, from 'rtsp://192.168.1.80:554/11':
  Metadata:
    title           : 10
  Duration: N/A, start: 0.080000, bitrate: N/A
    Stream #0:0: Video: h264, yuvj420p(pc, bt709, progressive), 2560x1920, 12.50 fps, 12.50 tbr, 90k tbn, 180k tbc
```

Config file:

```yml
api:
  origin: '*'
hass:
  config: /config
log:
  api: trace
  exec: debug
  format: text
  level: info
  ngrok: info
  rtsp: trace
  streams: trace
  webrtc: trace
rtsp:
  default_query: mp4
streams:
  Driveway:
  - rtsp://192.168.1.80:554/11
webrtc:
  candidates:
  - 192.168.1.205:8555
  listen: :8555
```

From further tests I discovered that it's working with Microsoft Edge, but not with Firefox 118.0.1. Anyway it seems very strange to me.

Have you some idea what the problem could be?
