### ISSUE TITLE
Reolink Doorbell 2 way audio No audio Output at doorbell

### ISSUE THREAD

**Issue by Wpeter86** [AlexxIT/go2rtc#670]
Hi im currently trying to setup 2-way-audio for my reolink doorbell poe.
Unfortunalty, the audio output at the doorbell does not work, even if I toggle on the microphone on home assistant (https enabled and see the mic indicator on my phone)

My setup is:
- frigate docker 
- home assistant VM

This is my go2rtc config for the doorbell:
```
    doorbell:
      - rtsp://USER:PASSWORD@192.168.178.10:554/h264Preview_01_sub
      - ffmpeg:doorbell#audio=opus
```

this is my config in home assistant:
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.doorbell
    live_provider: go2rtc
    frigate: {}
    go2rtc:
      modes:
        - webrtc
      stream: doorbell
menu:
  style: overlay
  buttons:
    microphone:
      enabled: true
      alignment: opposing
      type: toggle
    frigate:
      enabled: false
    cameras:
      enabled: false
    substreams:
      enabled: false
    live:
      enabled: false
    clips:
      enabled: false
    snapshots:
      enabled: false
    download:
      enabled: false
    camera_ui:
      enabled: false
    fullscreen:
      enabled: false
    timeline:
      enabled: false
    media_player:
      enabled: false
    mute:
      enabled: true
```

In the go2rtc log i see the following:
2023-10-02 07:35:04.889760060  07:35:04.889 WRN github.com/AlexxIT/go2rtc/cmd/webrtc/candidates.go:20 > error="write udp 192.168.178.20:46048->173.xxx.xxx.xxx:19302: i/o timeout

Hope someone knows how to set this up correctly.

Thanks :-)

**Comment by calisro** [comment]
ONVIF Profile T is there but according to this it isn't connected to 2-way audio.  

https://community.reolink.com/topic/4740/onvif-profile-t-with-2-way-audio-support-for-poe-doorbell

**Comment by Wpeter86** [comment]
Thanks for your reply and the given information.
Then i Hope, there will be an Update available soon.
While Reading through this issue [here](https://github.com/AlexxIT/go2rtc/issues/331) , It seemed that some people managed to get It working

**Comment by AlexxIT** [comment]
Show stream info from go2rtc WebUI

**Comment by Wpeter86** [comment]
> Show stream info from go2rtc WebUI
thanks for your reply
You mean I should paste the content of the info link unter go2rtc WEBUI / online column here?

**Comment by AlexxIT** [comment]
Yes. If you want, you may send it in PM

**Comment by Wpeter86** [comment]
@AlexxIT Is there somethink that has to be blurred out? 
If not I can send the output here, since I can't find a PM field

Thannks

**Comment by Wpeter86** [comment]
Thanks for your reply. 
Checked the firmware, its the latest (v3.0.0.2033_23041302)

**Comment by AlexxIT** [comment]
@NickM-27 do you know latest fw for doorbell?

**Comment by NickM-27** [comment]
that is the latest "stable" firmware, there is a beta firmware available at https://www.reddit.com/r/reolinkcam/comments/15h2kar/testers_wanted_for_doorbell_camera_new_firmware/

**Comment by Wpeter86** [comment]
Installed the latest Beta Firmware from the provided Link but still No audio Output (still sendonly)

**Comment by AlexxIT** [comment]
I'm not sure if it's related to old version of go2rtc. Because you using very old one

**Comment by Wpeter86** [comment]
I'll Check If i can Setup a newer one. I'm using the one, which is included into the frigate docker on unraid

**Comment by NickM-27** [comment]
https://docs.frigate.video/configuration/advanced#custom-go2rtc-version

**Comment by Wpeter86** [comment]
@AlexxIT @NickM-27 thank you guys... it's working now. I added the newest go2rtc binary and now its running perfectly 👍

**Comment by AlexxIT** [comment]
Interesting. Don't know why it not work with 1.2 version. Maybe doorbell has some broken SDP. Because RTSP backchannel was supported in this version.

**Comment by joe-cole1** [comment]
> @AlexxIT @NickM-27 thank you guys... it's working now. I added the newest go2rtc binary and now its running perfectly 👍

The newest meaning 1.7.1? Curious if you experienced any other issues setting it up? Could you please post your config?

**Comment by Wpeter86** [comment]
@joe-cole1 yes i'm using 1.7.1 

This is the config of the frigate Card in HomeAssistant:
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.doorbell
    live_provider: go2rtc
    frigate: {}
    go2rtc:
      modes:
        - webrtc
      stream: doorbell
menu:
  style: overlay
  buttons:
    microphone:
      enabled: true
      alignment: opposing
      type: toggle
    frigate:
      enabled: false
    cameras:
      enabled: false
    substreams:
      enabled: false
    live:
      enabled: false
    clips:
      enabled: false
    snapshots:
      enabled: false
    download:
      enabled: false
    camera_ui:
      enabled: false
    fullscreen:
      enabled: false
    timeline:
      enabled: false
    media_player:
      enabled: false
    mute:
      enabled: true
```

This is the config in go2rtc
```
doorbell:
      - rtsp://USER:PASSWORD@192.168.178.10:554/h264Preview_01_sub
      - ffmpeg:doorbell#audio=opus
```

It works with the stable reolink Firmware.


Hope this helps?
