### ISSUE TITLE
Integrate iCatch DVR

### ISSUE THREAD

**Issue by fulviomeomartini** [AlexxIT/go2rtc#676]
Hi, 
I was unable to integrate my DVR in any way. I cannot find its RTSP URL even though I see that when I open the native app and establish a connection, Wireshark notifies me that the connection uses an RTSP stream. If I analyze the TCP stream, it tells me that it connects to the path: "/cgi-bin/net_video.cgi?hq=0&iframe=65535&pframe=65535&audio=0", but when I connect, it fails to extract the video stream. How can I find the URL and integrate it? I was only able to integrate an MJPEG stream, which is low quality, while with the native app (SoCatch), I can view in high definition.
I found the low-resolution URL through the browser, which only allows connecting in high resolution through Internet Explorer and an ActiveX plugin.
I have attached some Wireshark screenshots that may be helpful to you.
The screeshots of go2rtc are in order of the configuration
My configuration:
```
streams:
  casameomartini: http://admin:pass@192.168.1.92:9000/cgi-bin/net_jpeg.cgi?ch=0&time=1696623164023
  casameomartini2: bubble://admin:pass@192.168.1.92:9000/cgi-bin/net_video.cgi?hq=1&iframe=65535&pframe=65535&audio=65535
  casameomartini3: rtsp://admin:pass@192.168.1.92:9000/cgi-bin/net_video.cgi?hq=1&iframe=65535&pframe=65535&audio=65535
  casameomartini4: dvrip://admin:pass@192.168.1.92:9000/
```

![Screenshot 2023-10-07 alle 12 39 30](https://github.com/AlexxIT/go2rtc/assets/93532601/d07f5945-3c0c-4b60-8ee4-4f34059d081f)
![Screenshot 2023-10-07 alle 12 12 04](https://github.com/AlexxIT/go2rtc/assets/93532601/0b473da6-2ac8-436b-b594-fb716a24808d)
![Screenshot 2023-10-07 alle 12 43 24](https://github.com/AlexxIT/go2rtc/assets/93532601/b0031570-6935-4476-8701-abed3c0b2126)
![Screenshot 2023-10-07 alle 12 43 38](https://github.com/AlexxIT/go2rtc/assets/93532601/05d926c4-9e61-4de7-aa51-f89874e7f50e)
![Screenshot 2023-10-07 alle 12 44 07](https://github.com/AlexxIT/go2rtc/assets/93532601/3509e5f9-5c01-4f91-9480-3fb1d3f5f3ba)
