### ISSUE TITLE
WebRTC through WAN while client is on the same LAN

### ISSUE THREAD

**Issue by 7floor** [AlexxIT/go2rtc#681]
Environment: HomeAssistant on RPI4 64 bit, HASSIO addon Frigate (Full Access) 0.12.1

Since some version of go2rtc, when client is on same LAN as HA, in some cases WebRTC candidate is chosen of type **srflx** which causes traffic to go through WAN interface back and forth. This really bad for my 4G connection with limited traffic.

go2rtc versions checked: 1.2.0, 1.6.2, 1.7.1

v1.2.0 (bundled with addon) works correctly, i.e. while client on same LAN as HA, the **host** candidate is always chosen, both for Chrome on wired desktop and for HA Companion app on Android phone (WiFi)

v1.6.2 and 1.7.1 (placed one by one to config directory) - issue is the same for both. For wired desktop with Chrome, **srflx** candidate is chosen, and all traffic goes through WAN interface. Surprisingly, HA Companion App still works throug LAN.

My config:

```
mqtt:
  host: homeassistant.local
  user: ***
  password: ***

ffmpeg:
  hwaccel_args: preset-rpi-64-h264

detectors:
  cpu1:
    type: cpu
    num_threads: 3

objects:
  track:
    - person
    - car
    - cat
    - dog

record:
  enabled: true
  retain:
    days: 14
    mode: motion

snapshots:
  enabled: true

go2rtc:
  streams:
    rtsp_outdoor_hq:
      - rtsp://***:***@192.168.2.201:554/cam/realmonitor?channel=1&subtype=0
    rtsp_outdoor_lq:
      - rtsp://***:***@192.168.2.201:554/cam/realmonitor?channel=1&subtype=1

cameras:
  outdoor:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/rtsp_outdoor_hq
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://localhost:8554/rtsp_outdoor_lq
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: rtsp_outdoor_lq
    detect:
      width: 640
      height: 480
    motion:
      mask:
        - 640,0,640,225,252,0
    zones:
      driveway:
        coordinates: 150,480,640,480,640,327,398,125,44,224
      gate:
        coordinates: 248,480,109,480,29,241,78,230
```

**Comment by AlexxIT** [comment]
You need to open chrome://webrtc-internals/ before webrtc connection start and show candidates tables for old and new versions. You can send them in PM.

**Comment by 7floor** [comment]
Please check in attachment.
My LAN is 192.168.2.0/24, homeassistant is 192.168.2.3, client PC is 192.168.2.101
My external WAN IP in this particular session is 46.56.186.235

[WebRTC Internals.zip](https://github.com/AlexxIT/go2rtc/files/12884791/WebRTC.Internals.zip)

**Comment by 7floor** [comment]
Sorry for bothering Alex, but any ideas on my issue?

**Comment by AlexxIT** [comment]
Can check this on next week

**Comment by AlexxIT** [comment]
I can't see the candidates section in your config. Did you remove it when you posted to github?
https://docs.frigate.video/configuration/live#webrtc-extra-configuration

**Comment by 7floor** [comment]
I have no such section in frigate.yaml at all.

But when I check go2rtc dashboard at http://192.168.2.3:5000/live/webrtc/editor.html, I see the actual config go2rtc is using, and it has the same for all versions as follows:
```
webrtc:
  candidates:
  - 192.168.2.3:8555
  - stun:8555
```

**Comment by AlexxIT** [comment]
OK. This is a problem. Both candidates with same priority. I will think for solution.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.8.2

**Comment by 7floor** [comment]
No luck, it didn't help - still through WAN IP in my setup. Details attached. 
LAN IPs 192.168.2.101 browser, 192.168.2.3 homeassistant; WAN IP 95.47.61.240

In log, I've noticed there's candidate advertisement as 2918e18d-56b7-4900-a25d-eb1fc2b86956.local - which is Chrome's way to obfuscate IPs of local candidates. Can this be a problem? Found this on topic: https://groups.google.com/g/discuss-webrtc/c/4Yggl6ZzqZk/m/nV24XkXXAQAJ?pli=1 and https://bloggeek.me/psa-mdns-and-local-ice-candidates-are-coming/
These are pretty old though, and do not explain how it was working with go2rtc 1.2.0

I'm absolutely not into topic, so please excuse my probably naive assumptions.

[details.zip](https://github.com/AlexxIT/go2rtc/files/13257568/details.zip)

**Comment by AlexxIT** [comment]
Do you have webrtc listen params in the config?

**Comment by 7floor** [comment]
Added to frigate config as you suggesting:
```
go2rtc:
  log:
    #level: trace
  webrtc:
    listen: ":8555"
  ffmpeg:
    esp32cam: "-avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -i {input}"
  streams:
    outdoor_hq:
      - rtsp://*****
    outdoor_lq:
      - ffmpeg:rtsp://*****#video=h264#width=704#height=528#raw=-pix_fmt yuv420p
    indoor:
      - ffmpeg:http://*****#input=esp32cam#video=h264#raw=-pix_fmt yuv420p -vf scale=1024:768,drawtext=text='%{{localtime}}':x=(w-tw)-w/25:y=h/25:fontsize=h/25:fontcolor=white:shadowx=2:shadowy=2
```

And that's didn't change anything.
The final config (seen at go2rtc dashboard on port 5000) doesn't have it:
```
api:
  origin: '*'
ffmpeg:
  esp32cam: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict
    experimental -fflags +genpts+discardcorrupt -i {input}
  rtsp: -fflags nobuffer -flags low_delay -stimeout 5000000 -user_agent go2rtc/ffmpeg
    -rtsp_transport tcp -i {input}
log:
  format: text
rtsp:
  default_query: mp4
streams:
  indoor:
  - ffmpeg:http://*****#input=esp32cam#video=h264#raw=-pix_fmt yuv420p
    -vf scale=1024:768,drawtext=text='%{localtime}':x=(w-tw)-w/25:y=h/25:fontsize=h/25:fontcolor=white:shadowx=2:shadowy=2
  outdoor_hq:
  - rtsp://*****
  outdoor_lq:
  - ffmpeg:rtsp://*****#video=h264#width=704#height=528#raw=-pix_fmt
    yuv420p
webrtc:
  candidates:
  - 192.168.2.3:8555
  - stun:8555
```

The log is like this (note WebRTC port was provided by supervisor):
```
2023-11-05 07:57:47.347970242  [INFO] Preparing go2rtc config...
2023-11-05 07:57:47.528518694  [INFO] Got IP address from supervisor: 192.168.2.3
2023-11-05 07:57:47.671867401  [INFO] Got WebRTC port from supervisor: 8555
2023-11-05 07:57:48.486777350  [WARN] Using go2rtc binary from '/config/go2rtc' instead of the embedded one
2023-11-05 07:57:48.486791423  [INFO] Starting go2rtc...
2023-11-05 07:57:48.713450290  10:57:48.713 INF go2rtc version 1.8.2 linux/arm64
2023-11-05 07:57:48.715114297  10:57:48.714 INF [api] listen addr=:1984
2023-11-05 07:57:48.716836172  10:57:48.716 INF [rtsp] listen addr=:8554
2023-11-05 07:57:48.717953152  10:57:48.717 INF [webrtc] listen addr=:8555
2023-11-05 07:57:57.391853647  [INFO] Starting go2rtc healthcheck service...
```

The final config and log go2rtcv output was the same regardless if I include into frigate config this:
```
go2rtc:
  webrtc:
    listen: ":8555"
```

The webrtc-internals still shows WAN IP local/remote candidates pair chosen.
