### ISSUE TITLE
Extend `#media=` filter to more sources

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/go2rtc#690]
The `#media=video` can be used in RTSP sources to include only video. But it would be great if I could use the same in more sources like `dvrip`, `onvif`, `echo`:

```yaml
streams:
  rua:
    - dvrip://user:pass@192.168.1.21:34567?channel=0&subtype=1
    - ffmpeg:rua_h265#audio=aac
  rua_hd:
    - dvrip://user:pass@192.168.1.21:34567?channel=0&subtype=0#media=video
    - rtsp://127.0.0.1:8554/rua?audio=all
```

The workaround for now is to figure out the RTSP link and change the `dvrip` source to use `rtsp` directly.
