### ISSUE TITLE
Reolink TrackMix shows first frame then freezes

### ISSUE THREAD

**Issue by RobinBeismann** [AlexxIT/go2rtc#699]
Hi,

I've bought a Reolink TrackMix and tried to add it via go2rtc into Frigate (tested with version 1.7.1 and now 1.8.1) using this config:
```
    garten_vorne: 
      - rtsp://{FRIGATE_USER}:{FRIGATE_PASSWORD}@ip:554/h264Preview_01_main
      - ffmpeg:garten_vorne#audio=opus
```

However I only see the first 1-3 frames if I view the stream via the Frigate Go2RTC Dashboard, then the stream instantly freezes and I can refresh to see the first 1-3 frames again.
The same config works fine for two other Reolink cameras (one E1 Outdoor and one RLC-523).

Any idea what is causing this or how to debug further? All cameras are in the same L2 network as the frigate container (and therefor as Go2RTC).

These are the settings on the new Reolink TrackMix (Wifi):
![image](https://github.com/AlexxIT/go2rtc/assets/8145269/3f324f0f-abe3-40cd-8938-f61f495282bf)

The Camera is a hardware ID IPC_529SD78MP and on firmware v3.0.0.1817_23022701.

Thanks!

**Comment by AlexxIT** [comment]
You need to read readme about RTSP and Reolink

**Comment by porly1985** [comment]
Hi Robin,
you said that your config is working fine for the E1 Outdoor. Do you also have audio when you click on the stream? I have 2 E1 Outdoor and one E1 Zoom where the Audio is not working since version 1.6.1. so I have to stay on version 1.6.0 (issue #540 ).  I have the same config the only difference is that I am not using Frigate. I also tried different configs (like http) but its all working without audio.

**Comment by RobinBeismann** [comment]
> You need to read readme about RTSP and Reolink

Thanks. I've seen the doc about it and tried both ways.
So here is my current config:
```
    garten_vorne_sub_0: 
      - "ffmpeg:http://{FRIGATE_CAM_GARTEN_VORNE}/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user={FRIGATE_USER}&password={FRIGATE_PASSWORD}#video=copy#audio=copy#audio=opus"
    garten_vorne_autotrack: 
      - "ffmpeg:http://{FRIGATE_CAM_GARTEN_VORNE}/flv?port=1935&app=bcs&stream=channel0_autotrack.bcs&user={FRIGATE_USER}&password={FRIGATE_PASSWORD}#video=copy#audio=copy#audio=opus"

    garten_vorne_rtsp: 
      - rtsp://{FRIGATE_USER}:{FRIGATE_PASSWORD}@{FRIGATE_CAM_GARTEN_VORNE}:554/h265Preview_01_main
      - ffmpeg:garten_vorne_rtsp#video=h264#audio=opus
    garten_vorne_http: 
      - http://{FRIGATE_CAM_GARTEN_VORNE}/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_USER}&password={FRIGATE_PASSWORD}
      - ffmpeg:garten_vorne_http#video=h264#audio=copy#audio=opus
```

The streams `garten_vorne_sub_0` and `garten_vorne_autotrack` work fine in both, the Go2RTC Web Interface and Frigate.
While the `garten_vorne_rtsp` stream works fine on the Go2RTC Webinterface if I open the WebRTC URL, the MSE stream shows the first stream and then stops.
On the other hand, the `garten_vorne_http` stream doesn't work at all, neither in WebRTC nor in MSE.

To my understanding, the camera is using H265 on the main stream, therefor I've added the options to transcode it to H264 for compatibility - was this correct?

I've tried to embed garten_vorne_rtsp into Frigate as it seems to be running fine with WebRTC on Go2RTC but that fails also..
Config:
```
  garten_vorne:
    ffmpeg: 
      inputs:   
        - path: rtsp://127.0.0.1:8554/garten_vorne_rtsp?video=copy&audio=aac
          roles:
            - detect
            - record
```

It errors out with:
```
frigate  | 2023-10-18 20:37:50.965439133  [2023-10-18 20:37:50] frigate.video                  ERROR   : flur: Unable to read frames from ffmpeg process.
frigate  | 2023-10-18 20:37:50.965785318  [2023-10-18 20:37:50] frigate.video                  ERROR   : flur: ffmpeg process is not running. exiting capture thread...
frigate  | 2023-10-18 20:37:50.997875435  [2023-10-18 20:37:50] frigate.video                  ERROR   : garten_vorne: Unable to read frames from ffmpeg process.
frigate  | 2023-10-18 20:37:50.998138679  [2023-10-18 20:37:50] frigate.video                  ERROR   : garten_vorne: ffmpeg process is not running. exiting capture thread...
```

**Comment by RobinBeismann** [comment]
Finally found time to figure out a configuration that works for me.

There is one thing that puzzles me through, once I turn on hardware encoding via `#hardware`, then I get a lot of pixel fragments. The load is however fine on my box so I will just leave it off. 

```
    garten: 
      - rtsp://{FRIGATE_USER}:{FRIGATE_PASSWORD}@{FRIGATE_CAM_GARTEN_VORNE}:554/h265Preview_01_main
      - ffmpeg:garten#video=h264#audio=opus #no hardware decoding - that generates fragments..
    garten_trackmix: 
      - rtsp://{FRIGATE_USER}:{FRIGATE_PASSWORD}@{FRIGATE_CAM_GARTEN_VORNE}:554/h264Preview_02_main
      - ffmpeg:garten_trackmix#video=h264#audio=opus
    garten_sub: 
      - ffmpeg:rtsp://{FRIGATE_USER}:{FRIGATE_PASSWORD}@{FRIGATE_CAM_GARTEN_VORNE}:554/h264Preview_01_sub
      - ffmpeg:garten_sub#audio=opus
```
