### ISSUE TITLE
Tapo C210 two way audio not working

### ISSUE THREAD

**Issue by LockManipulator** [AlexxIT/go2rtc#701]
Home Assistant is installed as an OS on a Pi 4 4gb. Accessing site with Chrome on Xubuntu 22.04. 

I can see and hear through the camera but can't speak. I click "links" and the video+audio+microphone option. I have enabled microphone access through the steps at https://stackoverflow.com/questions/52759992/how-to-access-camera-and-microphone-in-chrome-without-https and chrome says the website is using my mic. This is my config from following this video https://www.youtube.com/watch?v=WnRJxneCUYE:

streams:

    camera.frontdoor:
        - rtsp://user:pass@192.168.0.100:554/stream1
        - tapo://admin:md5hash@192.168.0.100
    
    camera.livingroom:
        - rtsp://user:pass@192.168.0.217:554/stream1
        - tapo://admin:md5hash@192.168.0.217

Trying to use this config from the github page does not even show the video:

```
streams:
     camera.livingroom: tapo://admin:MD5-PASSWORD-HASH@192.168.0.217
```

If there's any info I left out let me know and I can provide it.

**Comment by AlexxIT** [comment]
Show stream info

**Comment by NeZios** [comment]
Hi, same issue here, video is working but no audio with the tapo C210. 

Here is the go2rtc logs from Frigate : 
```
2023-10-28 12:46:23.130210659  [INFO] Preparing go2rtc config...
2023-10-28 12:46:27.482469681  [INFO] Starting go2rtc...
2023-10-28 12:46:27.638689247  12:46:27.638 INF go2rtc version 1.2.0 linux/amd64
2023-10-28 12:46:27.638867279  12:46:27.638 INF [api] listen addr=:1984
2023-10-28 12:46:27.639030374  12:46:27.639 INF [rtsp] listen addr=:8554
2023-10-28 12:46:27.639206450  12:46:27.639 INF [srtp] listen addr=:8443
2023-10-28 12:46:27.639335611  12:46:27.639 INF [webrtc] listen addr=:8555
2023-10-28 12:46:33.044436975  [INFO] Starting go2rtc healthcheck service...
```

And here is my config file : 
```

go2rtc:
  streams:
    buanderie:
      - rtsp://xxxx:xxxxxxxx@192.168.1.23:554/stream1
      - tapo://xxxxxxx@192.168.1.23
```

Both RTSP and Tapo protocols are having the issue : video without audio.

**Comment by seydx** [comment]
same problem, its working fine when i use only the tapo:// link (but this use always the first stream for the camera)

I want to use the second stream from my tapo camera with the 2 way functionality. I though with a config like this it would be able


With following config, ONLY video/audio WITHOUT microphone is working (it would be great if go2rtc would auto detect the second source and use it only for 2 way functionality while using the first rtsp source for streaming)
```yaml
test_camera:
    - rtsp://user:pass@192.2.3.4:554/stream2
    - tapo://PASSWORD@192.2.3.4
```

With this config, microphone is working fine (but again, im not able to use a different stream source from the same camera with this config, its always stream1)
```yaml
test_camera:
    - tapo://PASSWORD@192.2.3.4
```

**Comment by seydx** [comment]
nvm its working as intended

tapo (tapo://) blocks any request if more than 3 client are watching the stream (the rtsp link from the tapo camera works fine)

**Comment by ignacio82** [comment]
@seydx could you share your full configs for the C210?  I'm [struggling](https://github.com/AlexxIT/go2rtc/issues/922) to get this to work.

**Comment by AlexxIT** [comment]
Please let me know if the problem is relevant

**Comment by joaopedros2** [comment]
![image](https://github.com/user-attachments/assets/3f72efd4-afeb-44d6-a508-1c5b1f4a2e0c)

Unfortunately, I don't have audio from the streaming, and I can't communicate via the microphone to the camera.

___
Here is how I have the Frigate card configured.
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.cam_fg_quarto_lourenco
    live_provider: go2rtc
    go2rtc:
      modes:
        - webrtc
live:
  auto_unmute:
    - visible
    - selected
    - microphone
  auto_play:
    - selected
    - visible
  controls:
    builtin: false
    thumbnails:
      mode: none
    ptz:
      hide_zoom: true
      hide_home: true
      hide_pan_tilt: true
  preload: true
  lazy_unload:
    - unselected
    - hidden
  draggable: false
  zoomable: true
status_bar:
  style: none
menu:
  style: hover-card
  position: top
  alignment: top
  buttons:
    mute:
      enabled: true
      alignment: opposing
      priority: 4
    microphone:
      enabled: true
      alignment: opposing
      priority: 3
      type: toggle
    media_player:
      alignment: opposing
      priority: 2
    fullscreen:
      alignment: opposing
      priority: 1
    cameras:
      enabled: false
    clips:
      enabled: false
    snapshots:
      enabled: false
    timeline:
      enabled: false
    frigate:
      enabled: false
    live:
      enabled: false
performance:
  style:
    box_shadow: false
```

Here is how I have the Frigate camera configuration.
```
# Restream configuration
go2rtc:
  webrtc:
    candidates:
      - localhost:8555
      - stun:8555
  streams:
    cam_fg_quarto_lourenco:
      - ffmpeg:rtsp://user:pw@192.168.X.XXX:554/stream1#video=copy#audio=aac
      - tapo://admin:PW-SHA-256@192.168.X.XXX
```
