### ISSUE TITLE
Video shows in Android but not Desktop

### ISSUE THREAD

**Issue by blind-coder** [AlexxIT/go2rtc#709]
Hello,

I have spent today setting up an ICSee camera "XM30-4MP-BY" with go2rtc and webrtc.
The video and audio work fine on Android's HomeAssistant app, and shows fine in ffplay as well.

However, I am unable to get the video feed in a browser, neither Firefox nor Chrome show the video. Audio comes through fine, though.
I only see the "MSE" watermark in the top right.

Card configuration:
```yaml
type: custom:webrtc-camera
url: entrance_dvrip_mini
```

go2rtc Add-On configuration:
```yaml
api:
  listen: :1984
rtsp:
  listen: :8554
webrtc:
  candidates:
    - <my public DNS name>:8555
streams:
  entrance_dvrip:
    - dvrip://admin:<password>@camentrance.lan:34567
  entrance_dvrip_mini:
    - dvrip://admin:<password>@camentrance.lan:34567?channel=0&subtype=0
  entrance: # try this if the video is choppy or audio is out of synch
    - ffmpeg:entrance_dvrip#audio=copy#async#video=copy#async
  entrance_tts:
    - dvrip://admin:<password>@camentrance.lan:34567?backchannel=1
```

In the DEBUG log for webrtc I only see lines like this:
2023-10-20 12:51:58.428 DEBUG (MainThread) [custom_components.webrtc] New client: {'authSig': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIzNWI3YTIzZDM0Nzc0ODVhOGE2MTllMDk5MmVhNDQ0ZSIsInBhdGgiOiIvYXBpL3dlYnJ0Yy93cyIsInBhcmFtcyI6W10sImlhdCI6MTY5Nzc5OTExNywiZXhwIjoxNjk3Nzk5MTQ3fQ.S7Kw75ng54cKGUgp3mgLvXubq1JlnYtHJG8XCuLODZY', 'url': 'entrance'}

Any help would be greatly appreciated!
