### ISSUE TITLE
hass: no entity_id

### ISSUE THREAD

**Issue by jhchenchong** [AlexxIT/go2rtc#710]
![Snipaste_2023-10-20_21-17-11](https://github.com/AlexxIT/go2rtc/assets/19201316/30bf4cf1-4298-4246-9f8f-379ae75bfb20)
![Snipaste_2023-10-20_21-16-29](https://github.com/AlexxIT/go2rtc/assets/19201316/5e2682e8-ec3c-478d-a829-009ae171dd57)
![Snipaste_2023-10-20_21-15-50](https://github.com/AlexxIT/go2rtc/assets/19201316/79060e49-41ab-40a7-9acd-0306d2bc4d2e)
Hello AlexxIT, I'm running go2rtc in Docker, and I've integrated my Aqara G3 camera with HomeKit on Hass. I'm getting the error mentioned above. I'm not sure where I went wrong with that step.

**Comment by julioarruda** [comment]
Same issue here

**Comment by AlexxIT** [comment]
Goto WebUI > Add > HomeAssistant. Show result. You can hide private data.

**Comment by jhchenchong** [comment]
no hass config

**Comment by AlexxIT** [comment]
So you can't use `hass:` source without hass config.

**Comment by jhchenchong** [comment]
hass:
  config: "/config"
I've tried adding Hass configuration in the confi.yaml file, but I'm not sure how to set the 'config' parameter. I've tried both '/config' and the path where I installed Home Assistant via Docker, which is '/root/homeassistant', but I'm still getting the same error.

**Comment by AlexxIT** [comment]
If you running go2rtc in docker and Hass in docker on same server, you need to pass config folder:

```yaml
  go2rtc:
    image: alexxit/go2rtc
    network_mode: host
    privileged: true
    restart: unless-stopped
    environment:
      - TZ=Atlantic/Bermuda  # timezone in logs
    volumes:
      - /usr/share/hassio/homeassistant/:/config
```
