### ISSUE TITLE
Q: How to convert an input (h265 RTSP) and make available as h264 RTSP and Homekit

### ISSUE THREAD

**Issue by gspannu** [AlexxIT/go2rtc#720]
**Help needed !**
Running on a linux VM as `go2rtc_linux_amd64` version 1.8.1

Q: How to convert an **input (h265 RTSP in 4K resolution)** and make available **as h264 RTSP** and **Homekit compatible video**

I have been trying all sorts of combinations.. but cannot get something basic to work.

YAMl file looks like this..

```
streams:
  CAM01: 
    - rtsp://user1:password1@192.168.60.170/H265/ch1/main/av_stream
    #- rtsp://user1:password1@192.168.60.170/H265/ch1/sub/av_stream
    - ffmpeg:CAM01#video=h264#audio=opus#hardware

homekit:
    CAM01:                    # same stream ID from streams list
    pin: 12345678           # custom PIN, default: 19550224
    name: CAM01             # custom camera name, default: generated from stream ID
    device_id: CAM01        # custom ID, default: generated from stream ID
    device_private: CAM01   # custom key, default: generated from stream ID

rtsp:
  listen: ":8554"
  username: "admin"
  password: "password"
  default_query: "video=h264&audio=opus"
```

Essentially, what I have is 4K resolution h265 RTSP stream coming from a camera... and **I wish to convert it to** 
**a)** HomeKit compatible stream
**b)** RTSP stream (that is H264)
Also, how do I ensure that the output is only 1920x1080

My camera does not support H264 option; hence using go2rtc to try and convert it to a H264 compatible stream.

---
Thanks
