### ISSUE TITLE
Kasa source doesn't work for old models - KC120, KC200

### ISSUE THREAD

**Issue by unknown1818** [AlexxIT/go2rtc#725]
Hi,

Cant integrate to go2rtc KC120 camera when im using that code:

```
curl -vv -k -u <login>:<base64pass> --ignore-content-length "https://192.168.0.x:19443/https/stream/mixed?video=h264&audio=g711&resolution=hd" --output - | ffmpeg -y -i - test.mp4
```

its working and saving output test.mp4
 but with link 

```
'kasa://<login>:<base64pass>@192.168.0.x:19443/https/stream/mixed?video=h264&audio=g711&resolution=hd'
```

i got error on go2rtc "invalid byte on chunk length...HTTP 1 transport connection broken, bad content length -1"

im using latest frigate beta 3 + go2rtc 1.8.1

**Comment by AlexxIT** [comment]
Can check it if you provide external access
https://github.com/AlexxIT/go2rtc/wiki/Tunnel-RTSP-camera-to-Intenet

**Comment by charlieamer** [comment]
Hello. I have same problem in frigate the issue seems to be related to go2rtc. The full error is: ` WRN [rtsp] error="streams: Get \"https://XXX:XXX@CAMERA_IP:19443/https/stream/mixed?video=h264&audio=g711&resolution=hd\": net/http: HTTP/1.x transport connection broken: bad Content-Length \"-1\", exec: exit status 1" stream=outside_go2rtc`

My frigate config:
```yml
go2rtc:
  streams:
    outside_go2rtc:
      - "kasa://EMAIL:BASE64PASS@CAMERA_IP:19443/https/stream/mixed?video=h264&audio=g711&resolution=hd"
      - "ffmpeg:outside_go2rtc#video=h264#audio=opus"
```

I can give privately external access to my camera to @AlexxIT . Is there a private way I can sand you link with external access ? Maybe email or something like that ?
