### ISSUE TITLE
domru: tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config

### ISSUE THREAD

**Issue by twocolors** [AlexxIT/go2rtc#731]
```
Get "https://cctv-sa1-dmfn.vs.ru:18080/rtsp/8409150469/FSjF4sggtw6pBlbz6Otn": tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config
```

**Comment by AlexxIT** [comment]
Fixed in latest master version

**Comment by twocolors** [comment]
```
go2rtc  | 16:28:09.585 INF [webrtc] listen addr=:8555
go2rtc exited with code 2
go2rtc  | panic: interface conversion: interface {} is nil, not *tls.Config
go2rtc  |
go2rtc  | goroutine 66 [running]:
go2rtc  | github.com/AlexxIT/go2rtc/pkg/tcp.Do.func2({0xd2cf08, 0xc0001aa150}, {0xc11ec2?, 0xd2c958?}, {0xc000154960?, 0xb421a0?})
go2rtc  |       github.com/AlexxIT/go2rtc/pkg/tcp/request.go:51 +0x1e5
go2rtc  | net/http.(*Transport).customDialTLS(0x0?, {0xd2cf08?, 0xc0001aa150?}, {0xc11ec2?, 0x0?}, {0xc000154960?, 0x0?})
go2rtc  |       net/http/transport.go:1335 +0x4a
go2rtc  | net/http.(*Transport).dialConn(0xc00019c140, {0xd2cf08, 0xc0001aa150}, {{}, 0x0, {0xc0001260c0, 0x5}, {0xc000154960, 0x28}, 0x0})
go2rtc  |       net/http/transport.go:1601 +0x3df
go2rtc  | net/http.(*Transport).dialConnFor(0x707665?, 0xc0001486e0)
go2rtc  |       net/http/transport.go:1467 +0x9f
go2rtc  | created by net/http.(*Transport).queueForDial in goroutine 54
go2rtc  |       net/http/transport.go:1436 +0x3cb
```

**Comment by AlexxIT** [comment]
Fixed again in master version... :)

Also you can try to use expr source. It works in current release:
https://github.com/AlexxIT/go2rtc/blob/master/internal/expr

**Comment by twocolors** [comment]
if use "expr" , all work and i see stream in web

but not work on HomeKit

p.s. add support env for "expr"

**Comment by AlexxIT** [comment]
Show expr example, how do you want use env

**Comment by twocolors** [comment]
In docker
```
  go2rtc:
    container_name: "go2rtc"
    hostname: "go2rtc"
    image: "alexxit/go2rtc:latest"
    #image: "alexxit/go2rtc:master-hardware"
    privileged: true
    environment:
      - TZ=Europe/Moscow
      - TOKEN=1111111111111111
      - OPERATOR=42
    volumes:
      - "/home/dietpi/.go2rtc:/config"
    restart: unless-stopped
    network_mode: host
```
in config
```
streams:
  intercom_child: |
    expr:
    let camera = "123";
    fetch("https://myhome.novotelecom.ru/rest/v1/forpost/cameras/"+camera+"/video", {
      headers: {Authorization: env('TOKEN'), Operator: env('OPERATOR')}
    }).json().data.URL
  intercom_homeowner: |
    expr:
    let camera = "321";
    fetch("https://myhome.novotelecom.ru/rest/v1/forpost/cameras/"+camera+"/video", {
      headers: {Authorization: env('TOKEN'), Operator: env('OPERATOR')}
    }).json().data.URL
```
