### ISSUE TITLE
Fix support Tapo C210 firmware v1.3.9

### ISSUE THREAD

**Issue by mickaelmarin** [AlexxIT/go2rtc#733]
Hi,

All is in the title, since firmware update of camera the authentication not work anymore.

I use this in the go2rtc.yaml file:
```yaml
streams:
  camera.salon:
    - rtsp://<user>:<pass>@192.168.1.152/stream1
    - tapo://<cloud password md5 hash upercase>@192.168.1.152
```
thanks

**Comment by seydx** [comment]
> Factory reset camera / readd to tapo app, there is a bug in camera for some users where it does not properly load the new password hash.

See https://github.com/JurajNyiri/pytapo/issues/80

**Comment by JurajNyiri** [comment]
While above is true, there might be more work needed on go2rtc, see https://github.com/JurajNyiri/pytapo/pull/76 .

Also, use sha256 hash not md5 anymore.

**Comment by mickaelmarin** [comment]
thanks @JurajNyiri, after replace md5 by sha256 it work

**Comment by kksligh** [comment]
same issue here - I tried the sha256 hash and it didnt work for me.

**Comment by AlexxIT** [comment]
I need remote access to this camera to fix it.

**Comment by kksligh** [comment]
Confirming that I also used the sha256 hash instead of the md5 - stopped the errors and the camera works with sounds - however, the 2 way audio no longer works.  

I have 2 of the same Tapo C211 cameras, with the exact same config, but one has Firmware: 1.3.9 Build 231019 (not working) and the other has Firmware: 1.3.7 Build 230823 (working)

I'm willing to help in any way you need.

**Comment by mickaelmarin** [comment]
I have tapo c210 with 1.3.9 firmware un two way audio work. 
You need to add **microphone** in the media setting of webrtc-camera card.

**media: video,audio,microphone**


the conf of stream in go2rtc.yaml:

**streams:
  camera.salon:
    - tapo://admin:<cloud password sha256 hash upercase>@192.168.1.152**

**Comment by AlexxIT** [comment]
So this method worked for you?

```yaml
streams:
  # cloud password without username
  camera1: tapo://cloud-password@192.168.1.123
  # admin username and UPPERCASE MD5 cloud-password hash
  camera2: tapo://admin:MD5-PASSWORD-HASH@192.168.1.123
  # Tapo C210 with firmware 1.3.9+
  camera3: tapo://admin:SHA256-PASSWORD-HASH@192.168.1.123
```
