### ISSUE TITLE
Having trouble setting up a stream using exec

### ISSUE THREAD

**Issue by midget214** [AlexxIT/go2rtc#743]
I am trying to setup a stream using the exec option.  The issue I am facing is trying to transcode a h265 stream to h264 by partially using the CPU and partially the GPU (atleast that is what I think is happening.  I basically know nothing about ffmpeg).  i've been brute forcing the parameters on my PC to get the stream from a camera to encode to mp4 successfully using the command below

```
ffmpeg -hide_banner -hwaccel_output_format cuda -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://192.168.12.2:8554/garage_front?video -vf "hwupload_cuda" -c:v h264_nvenc -g 50 -bf 0 -profile:v high -level:v auto -preset:v p2 -tune:v ll -an -user_agent ffmpeg/go2rtc -c:a copy test.mp4
```

Now I am trying to encode the stream in go2rtc directly.   I've tried the following

```
go2rtc:
  log:
    exec: trace
  streams:
    garage_front: exec:ffmpeg -hide_banner -hwaccel_output_format cuda -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://192.168.12.2:8554/garage_front -vf "hwupload_cuda" -bf 0 -c:v h264_nvenc -rtsp_transport tcp -f rtsp {output}
```

The problem I'm running into is that go2rtc is just crashing with 

```
2023-11-09 20:18:57.846172504  [INFO] Preparing go2rtc config...
2023-11-09 20:18:57.962081387  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2023-11-09 20:18:57.978622122  [INFO] The go2rtc service exited with code 1 (by signal 0)
```

Could someone please help me figure out what I did wrong?
(The 2 commands are not 100% identical.  They were initially but I had the same error since the start.  I've since removed more and more parameters from the exec command to try and get it to work with no luck)

**Comment by fuatakgun** [comment]
I do not know the root cause but I suggest you to set the log level in global settings to trace to see what is going all in all modules.

```
go2rtc:
  log:
    level: trace
    exec: trace
```
