### ISSUE TITLE
Using HW Accel and image overlay together

### ISSUE THREAD

**Issue by R3STEAS** [AlexxIT/go2rtc#752]
Hey,

I want to use HW Accel and have a .png file as a overlay on the stream. This is my config:

```yaml
go2rtc:
  streams:
    carport:
      #- "ffmpeg:rtsp://8hXEp81X:CeSn9rhyPXBcB8S7@192.168.178.107:554/live/ch0#video=h264#hardware#raw=-i \"/config/carport_overlay.png\" -filter_complex [0][1]overlay=x=(main_w-overlay_w)/2:y=(main_h-overlay_h)/2,drawtext=\"expansion=strftime:fontfile=/config/Cantarell-Regular.ttf:fontsize=42:fontcolor=white:shadowcolor=black:shadowx=2:shadowy=1:text='%d.%m.%Y\ %H\\:%M\\:%S':x=1830:y=8\""
      - "ffmpeg:rtsp://8hXEp81X:CeSn9rhyPXBcB8S7@192.168.178.107:554/live/ch0#video=h264#hardware"
```

as you can see I am currently using #hardware which works fine. But if I want to use the commented command, it doesn't work.
Otherwise if I remove the #hardware tag before #raw, my overlay is perfectly displaying. But without HW Accel of course..

How could I add the overlay and still get HW Accel?

E: uargh. Can anybody explain me, how to tell github to interpret my code as yml :/
