### ISSUE TITLE
Integrate Reolink's (reverse engineered) proprietary protocol?

### ISSUE THREAD

**Issue by SpeakingOfBrad** [AlexxIT/go2rtc#755]
Reolink's RTSP (and RTMP) stream sucks and is pretty unstable. But their own protocol is more reliable, but it's proprietary. 

[George Hilliard has reverse engineered Reolink's proprietary protocol](https://www.thirtythreeforty.net/posts/2020/05/hacking-reolink-cameras-for-fun-and-profit/) and even created a [software client (Neolink) to take the Reolink protocol and spit it out into an RTSP stream](https://github.com/thirtythreeforty/neolink). (A more recently updated fork of the software is available here: [https://github.com/QuantumEntangledAndy/neolink](https://github.com/QuantumEntangledAndy/neolink)) 

It would be great if this protocol was integrated directly into go2rtc!

**Comment by AlexxIT** [comment]
I know about this project https://github.com/thirtythreeforty/neolink/issues/341. I just haven't had time to implement it

**Comment by si458** [comment]
just womdered if the was any progress with this?
i have a battery powered reolink camera and would love to be able to check it every so often!
from what im aware the neolink project has moved here now https://github.com/QuantumEntangledAndy/neolink

**Comment by AlexxIT** [comment]
Not engaged in this task. And there are other tasks in the immediate plans

**Comment by si458** [comment]
@AlexxIT no thats perfectly fine! i just wondered!

as is the was a bug with the neolink where it kept dropping the connection to my camera!
but now it seems if i build neolink from scratch, it seems to work and not drop the connection!

keep up the amazin work tho with go2rtc! its amazing and works so much quicker in HA than HAs native camera !

**Comment by bagobones** [comment]
saw a post on neolink recently and thought I would check here, sure enough it has been seen.

Given the proprietary tapo:// protocol for TP-links cameras it does seem fitting for this project and might widen camera support for other projects using go2rtc however pressuring reolink via the works with home assistant program to just fix its ONVIF / RTSP implementations might be a better path.

**Comment by Legendhidde** [comment]
I think this solution would solve all my random crashes and lost recordings with Reolink Trackmix. Sure, requesting Reolink fix their stuff would be nice but apparently they won’t. I really really want to have my cameras work in Frigate, Scrypted seems to be doing fine with my cameras with the Baichuan protocol.

**Comment by petertjmills** [comment]
Using neolink as a basis, I've implemented the reolink proprietary protocol (because I was having some neolink issues) into  [go2rtc here](https://github.com/petertjmills/go2rtc). Currently only with h264 streams. Audio is WIP and haven't tested with h265. @AlexxIT, happy for a PR?

**Comment by AlexxIT** [comment]
Of course I will be happy with PR. With Reolink, the next release could be very rich in new sources.

**Comment by TheRealSimon42** [comment]
That would really be amazing @petertjmills

Once this is available for Beta-Testing, I would love to try it out and give some feedback if that would help (I have over 6 Reolink-Cameras here).

**Comment by petertjmills** [comment]
@TheRealSimon42 Just for testing, my fork linked in the previous comment should just about work using a connection string like:
`reolink://admin:[YOURPASS]@[YOURREOLINKIP]:9000/mainStream`

But otherwise I'll open a PR after Xmas 🙂

**Comment by AlexxIT** [comment]
In any case, these changes will stop at me. I'm currently working on a different source. But after that, I was planning to switch to Reolink.

**Comment by xconverge** [comment]
@petertjmills I am messing around with the code from your fork and had to adjust:

`FmtpLine:    h264.GetFmtpLine(annexb.EncodeToAVCC(packet.Data)),` to get ffprobe and frigate (recordings) to play nice, but so far this is looking great!

https://github.com/xconverge/go2rtc/commit/6775471c44eb843f743f31190f757f6723159bb5

**Comment by ykorzikowski** [comment]
Hi @petertjmills, is there already something we can test? Just bought two Reolinks E330 and ONVIF is quite unreliable. Using the config below now, but this won't allow two-way-audio (which was working before with ONVIF)

```
    reolink_front: ffmpeg:rtsp://admin:xxx@10.xx.xx.xx:554/h264Preview_01_main
    reolink_front_sub: ffmpeg:rtsp://admin:xxx@10.xx.xx.xx:554/h264Preview_01_sub
```

~And I noticed with LAN only the ONVIF API can't be reached by go2rtc/frigate, but wifi is fine. Video stream works with both wifi and lan.~

Edit: Nevermind this, I configured it wrong in the config.

**Comment by xconverge** [comment]
> Hi [@petertjmills](https://github.com/petertjmills), is there already something we can test? Just bought two Reolinks E330 and ONVIF is quite unreliable. Using the config below now, but this won't allow two-way-audio (which was working before with ONVIF)
> 
> ```
>     reolink_front: ffmpeg:rtsp://admin:xxx@10.xx.xx.xx:554/h264Preview_01_main
>     reolink_front_sub: ffmpeg:rtsp://admin:xxx@10.xx.xx.xx:554/h264Preview_01_sub
> ```
> 
> And I noticed with LAN only the ONVIF API can't be reached by go2rtc/frigate, but wifi is fine. Video stream works with both wifi and lan.

I built a binary and started testing it myself with frigate and it is super solid. I have no audio needs and use h264. It will take more work if that's not the case for you

**Comment by ykorzikowski** [comment]
okay thanks. Its about the "propertary" API running on port 9000 right? 

Is there an option to configure go2rtc use a different video stream (the stable one) and still onvif for 2 way talk?

```

mqtt:
  enabled: true
  host: 10.0.xx.xx
  port: 1883
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"

tls:
  enabled: false

go2rtc:
  streams:
    # reolink_front: onvif://admin:xxx!@10.0.11.xxx:8000 # Two way talk working, but video stream crashes
    reolink_front: ffmpeg:rtsp://admin:xxx!@10.0.11.xxx:554/h264Preview_01_main
    reolink_front_sub: ffmpeg:rtsp://admin:xxx!@10.0.11.xxx:554/h264Preview_01_sub

  webrtc:
    ice_servers:
      - urls: ["stun:sturn.xxx.com:443"]
      - urls: ["turn:sturn.xxx.com:443"]
        username: coturn_user
        credential: xxx
detect:
  enabled: false
version: 0.16-0

cameras:
  reolink_front:
    detect:
      enabled: false
    ffmpeg:
      input_args: -rtsp_transport tcp
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_front # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            #- detect
            #- audio # <- only necessary if audio detection is enabled
    onvif:
      host: 10.0.11.xxx
      port: 8000
      user: admin
      password: xxx
    live:
      streams:
        Flur: reolink_front

```

**Comment by xconverge** [comment]
I think if you don't break up the testing for yourself (understanding if the video from the proprietary protocol adds any value for your usage for example), you are going to need to be patient because the short answer is no, I dont believe anything is formally ready for testing.

I was able to make the changes/build the binary I need that work for my setup and I think the fork/code in the fork is a GREAT starting point for when a formal PR ends up being opened by someone.

**Comment by ykorzikowski** [comment]
ok thanks for the heads up. I will just experiment a bit with the https://github.com/QuantumEntangledAndy/neolink/tree/master project itself :)

**Comment by petertjmills** [comment]
> is a GREAT starting point for when a formal PR ends up being opened by someone.

Thank you 😇

I’m still aiming to open a PR (unless someone gets there first!). Life’s just been busy. When I get back to it, I’ll post here.

@ykorzikowski - I need it for a doorbell so I’d like to get 2 way audio working too, but I’ve heard that that can be more complicated. iirc neolink doesn’t even do audio.

**Comment by AlexxIT** [comment]
Reolink RTSP only works well in UDP mode. It is disabled by default in go2rtc. But it can be used via ffmpeg source.

I don't like RTSP UDP because it's much more difficult to work with and can cause frame drops, which can completely break the stream's display in the browser.

On the other hand, the RTSP TCP in Reolink cameras is so poor that it can also cause frame drops. Reolink is practically the only company to experience this. Most other companies' RTSP TCP is very reliable and lossless.

**Comment by AlexxIT** [comment]
My users sent me two Reolink cameras to debug this protocol. But I've been stuck in Xiaomi camera support for a whole month now. That's why this source is delayed.

**Comment by Hellysonrp** [comment]
I have two Reolink cameras: a RLC-520A and a RLC-810A. The 810A RTSP implementation is fine and never had any problems. However, the 520A is just garbage. The maximum frame rate I could get from its RTSP was 5. 5 FPS.

I had some urgency to record the 520A camera.
[I forked the fork](https://github.com/Hellysonrp/go2rtc) and, with the help of the neolink repository and a ~~very dumb~~ AI, implemented what I could of the protocol, including a way to select the substream. I just couldn't implement audio. Every time I tried, the stream would just not work. ~~Neither myself or the AI are smart enough to implement it...~~ I'll try to implement it again when I have some time.
In any case, I've been using that implementation in frigate for some days now without problems (apart from the missing audio).

I don't know if it is of any help or use, but I just thought of letting you know.

**Comment by bagobones** [comment]
Looks like another "native reolink" proxy has popped up https://github.com/Shareed2k/reolinkproxy

**Comment by Legendhidde** [comment]
> Looks like another "native reolink" proxy has popped up https://github.com/Shareed2k/reolinkproxy

I am using Scrypted as a more visual Baichuan restreamer. It finally works perfectly when I ingest my scripted streams into frigate. I haven’t had errors in days.

**Comment by fzurita** [comment]
With the help of gemini (AI) and all the work that reolinkproxy by Shareed2k did, I was able to implement the native reolink protocol directly in go2rtc: https://github.com/fzurita/go2rtc/commits/reolink_protocol/. A lot of code was borrowed from [reolinkproxy](https://github.com/Shareed2k/reolinkproxy).

It seems to work correctly for at least all my cameras including talkback, h264, h265 and I think all various audio formats. I'm not sure how well it will work with battery only cameras since I don't have any of those.

https://github.com/fzurita/go2rtc/blob/reolink_protocol/internal/reolink/README.md

**Comment by gr33nh07n** [comment]
> With the help of gemini (AI) and all the work that reolinkproxy by Shareed2k did, I was able to implement the native reolink protocol directly in go2rtc: https://github.com/fzurita/go2rtc/commits/reolink_protocol/. A lot of code was borrowed from [reolinkproxy](https://github.com/Shareed2k/reolinkproxy).
> 
> It seems to work correctly for at least all my cameras including talkback, h264, h265 and I think all various audio formats. I'm not sure how well it will work with battery only cameras since I don't have any of those.
> 
> https://github.com/fzurita/go2rtc/blob/reolink_protocol/internal/reolink/README.md

Just wanted to say that I used this Go2RTC fork in my Frigate instance, my errors from Reolink are gone for 2 days. I had reoccurring errors regardless of RTSP/FLV. It has been rock solid so far.

Lovely work @fzurita

**Comment by mew1033** [comment]
Thanks! This is working fantastically. I compiled the go binary by using the same steps as the [github actions workflow](https://github.com/AlexxIT/go2rtc/blob/master/.github/workflows/build.yml) and then put the resulting binary in the config folder like it says [here](http://docs.frigate.video/configuration/advanced#custom-go2rtc-version).

My config for my doorbell looks like this:

```yaml
go2rtc:
  streams:
      doorbell_camera:
      - reolink://user:pass@x.x.x.x/main
      - reolink://user:pass@x.x.x.x/extern
      - ffmpeg:doorbell_camera#audio=opus
    doorbell_camera_sub:
      - reolink://user:pass@x.x.x.x/extern?channel=0
      - ffmpeg:doorbell_camera_sub#audio=opus

cameras:
  doorbell_camera:
    enabled: true
    friendly_name: Doorbell Camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_camera
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/doorbell_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
```
