### ISSUE TITLE
Icsee Camera with double video 2 way audio issue

### ISSUE THREAD

**Issue by cnopix** [AlexxIT/go2rtc#774]
hello ,

i have this camera : [https://fr.aliexpress.com/item/1005005873039152.html?spm=a2g0o.order_list.order_list_main.5.14bc5e5bWn4M5U&gatewayAdapt=glo2fra](url)

Compression : H.265

i have video on chrome, android and iphone but impossible to have 2 way audio. just audio on chrome and android (not on iphone) but the microphone don't work. i've had the microphone allowed message on both.

My stream config : 
```
streams: 
  camera1:
    - dvrip://admin:----------@IP:34567
  camera1_mic_on:
    - dvrip://admin:-------------@ip:34567
    - dvrip://admin:-------------@ip:34567?backchannel=1
```
my webrtc camera card: 
```
type: custom:webrtc-camera
streams:
  - url: camera1
    name: 😶
    mode: webrtc,hls,mse
  - url: camera1_mic_on
    name: 🎙️
    mic: true
    muted: false
ui: true
```
it's working great on web ui of the camera.

What did i do worng ?

Cnopix.
