### ISSUE TITLE
TP-Link Tapo C225 auth fails after camera update to 1.0.27

### ISSUE THREAD

**Issue by RobinBeismann** [AlexxIT/go2rtc#781]
Hi,

in reference to #733, it looks like the new firmware 1.0.27 for the Tapo C225 introduces the same authentication issues as on the C210. All three of my C225 now show log "streams: 401 unauthorized". 
Previously, I've been passing the credentials in cleartext via:
```
    kueche:
      - tapo://{FRIGATE_PASSWORD_TAPO}@{FRIGATE_CAM_KUECHE_EG}
```
However I've now tested it with an SHA265 hashed password but that didn't solve it either.

Happy to provide all logs needed.

Thanks alot for go2rtc, really appreciate it!

**Comment by RobinBeismann** [comment]
So I've tested all combinations I could think off this evening.
I can stream it using rtsp just fine, however this way I don't have two way audio.

For reference, the variables I'm using are:
`FRIGATE_USERNAME_TAPO` -> The username set as local user in the Tapo App
`FRIGATE_PASSWORD_TAPO_CLEAR` -> Clear Text Password (for testing I've set it to be the same as the cloud account
`FRIGATE_PASSWORD_TAPO_SHA256` -> Password hashed as SHA in uppercase
`FRIGATE_PASSWORD_TAPO_MD5` -> Password hashed as MD5 in uppercase

This works via rtsp:
```
    # Camera Küche EG
    kueche:
      - rtsp://{FRIGATE_USERNAME_TAPO}:{FRIGATE_PASSWORD_TAPO_CLEAR}@{FRIGATE_CAM_KUECHE_EG}:554/stream1
      - ffmpeg:kueche_sub#audio=opus
    kueche_sub:
      - rtsp://{FRIGATE_USERNAME_TAPO}:{FRIGATE_PASSWORD_TAPO_CLEAR}@{FRIGATE_CAM_KUECHE_EG}:554/stream2
      - ffmpeg:kueche_sub#audio=opus
    
    # Camera Wohnzimmer EG
    wohnzimmer:
      - rtsp://{FRIGATE_USERNAME_TAPO}:{FRIGATE_PASSWORD_TAPO_CLEAR}@{FRIGATE_CAM_WOHNZIMMER_EG}:554/stream1
      - ffmpeg:wohnzimmer_sub#audio=opus
    wohnzimmer_sub:
      - rtsp://{FRIGATE_USERNAME_TAPO}:{FRIGATE_PASSWORD_TAPO_CLEAR}@{FRIGATE_CAM_WOHNZIMMER_EG}:554/stream2
      - ffmpeg:wohnzimmer_sub#audio=opus

    # Camera Flur EG
    flur:
      - rtsp://{FRIGATE_USERNAME_TAPO}:{FRIGATE_PASSWORD_TAPO_CLEAR}@{FRIGATE_CAM_FLUR_EG}:554/stream1
      - ffmpeg:flur_sub#audio=opus
    flur_sub:
      - rtsp://{FRIGATE_USERNAME_TAPO}:{FRIGATE_PASSWORD_TAPO_CLEAR}@{FRIGATE_CAM_FLUR_EG}:554/stream2
      - ffmpeg:flur_sub#audio=opus
```

However I can't find a working way via the `tapo://` protocol.
Before the update to 1.0.27 I was using this just fine:
`- tapo://{FRIGATE_PASSWORD_TAPO_CLEAR}@{FRIGATE_CAM_KUECHE_EG}`

The variations I've tested to no avail are:
```
- tapo://admin:{FRIGATE_PASSWORD_TAPO_CLEAR}@{FRIGATE_CAM_KUECHE_EG}
- tapo://admin:{FRIGATE_PASSWORD_TAPO_SHA256}@{FRIGATE_CAM_KUECHE_EG}
- tapo://admin:{FRIGATE_PASSWORD_TAPO_MD5}@{FRIGATE_CAM_KUECHE_EG}
- tapo://{FRIGATE_USERNAME_TAPO}:{FRIGATE_PASSWORD_TAPO_CLEAR}@{FRIGATE_CAM_KUECHE_EG}
- tapo://{FRIGATE_USERNAME_TAPO}:{FRIGATE_PASSWORD_TAPO_SHA256}@{FRIGATE_CAM_KUECHE_EG}
- tapo://{FRIGATE_USERNAME_TAPO}:{FRIGATE_PASSWORD_TAPO_MD5}@{FRIGATE_CAM_KUECHE_EG}
- tapo://{FRIGATE_PASSWORD_TAPO_CLEAR}@{FRIGATE_CAM_KUECHE_EG}
- tapo://{FRIGATE_PASSWORD_TAPO_SHA256}@{FRIGATE_CAM_KUECHE_EG}
- tapo://{FRIGATE_PASSWORD_TAPO_MD5}@{FRIGATE_CAM_KUECHE_EG}
```

Anyone has an idea?
