### ISSUE TITLE
Add error for wrong HomeKit source

### ISSUE THREAD

**Issue by metril** [AlexxIT/go2rtc#805]
I am running v1.8.4 of the go2rtc addon in Home Assistant 2023.12.

I have added the Aqara G4 Doorbell to Home Assistant via Homekit.

My go2rtc config looks like the following:

```
streams:
  aqara_g4_doorbell: homekit://some_address_here_copied_from_Add_tab_in_go2rtc
  
rtsp:
  listen: ":8554"
  username: "someusername"
  password: "somepassword"

webrtc:
  listen: ":9555"

homekit:
  aqara_g4_doorbell:
    pin: 12345678
    name: Aqara G4 Doorbell
    device_id: aqara_g4_doorbell
    device_private: aqara_g4_doorbell
```

I can see the Aqara G4 Doorbell in the Home app on IOS. I go to add it and then I get an error, unable to add accessory. In the go2rtc logs, I see:

`ERR github.com/AlexxIT/go2rtc/internal/homekit/homekit.go:179 > error="ed25519: invalid params"
`

I expect to be able to proxy and successfully add the Aqara G4 Doorbell to the IOS Home app.
