### ISSUE TITLE
Kasa I/O timeout

### ISSUE THREAD

**Issue by Phil-Barker** [AlexxIT/go2rtc#826]
I'm trying to use go2rtc inside frigate with 3 kasa cameras

I tried a year or so ago but could never get it to work, seeing that now there is a kasa:// setting I thought I'd try again

I played around for hours and kept getting authentication errors, eventually got that sorted using settings others had posted in previous issues, but now I just get i/o timeout.

```
2023-12-12 19:50:32.982 WRN [rtsp] error="streams: Get \"https://mail@my-email:***@192.168.2.243:19443/https/stream/mixed?video=h264&audio=g711&resolution=hd#backchannel=0\": dial tcp 192.168.2.243:19443: i/o timeout, exec: exit status 1" stream=garagecam

2023-12-12 19:51:32.987760601  19:51:32.987 WRN [rtsp] error="streams: Get \"https://mail@my-email.com:***@192.168.2.206:19443/https/stream/mixed?video=h264&audio=g711&resolution=hd#backchannel=0\": dial tcp 192.168.2.206:19443: i/o timeout, exec: exit status 1" stream=doorcam
```

My config file is like this currently
```
---
mqtt:
  enabled: false

go2rtc:
  streams:
    doorcam: 
      - "kasa://mail%my-email.com:--base64password-@192.168.2.206:19443/https/stream/mixed?video=h264&audio=g711&resolution=hd#backchannel=0"
      - "ffmpeg:doorcam#video=h264#audio=copy"
    garagecam: 
      - "kasa://mail%my-email.com:--base64password-@192.168.2.243:19443/https/stream/mixed?video=h264&audio=g711&resolution=hd#backchannel=0"
      - "ffmpeg:doorcam#video=h264#audio=copy"
    
cameras:
  doorcam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorcam?video=copy&audio=copy
          roles:
            - detect   
            - record
    
  garagecam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garagecam?video=copy&audio=copy
          roles:
            - detect   
            - record
    
    detect:
      width: 1920
      height: 1080
```

As I say, I was originally getting auth errors so it is connecting to the IP the cameras are on.

I have very similar settings in scrypted and it works absolutely fine. But scrypted doesn't support hardware transcoding so I'd like to use frigate if possible.

Has anyone come across this before?
I added the `#backchannel=0` last night after finding that in a similar issue but it's made no difference
