### ISSUE TITLE
Convert not Working / FFMPEG USB multiple devices

### ISSUE THREAD

**Issue by boyfromgermany** [AlexxIT/go2rtc#827]
Hello, i am trying to setup a usb camera and get it into homeassistant

i can use the mjpeg stream and the transcoded h264 stream
however i cannot use both of them at the same time
i also tryed to convert the already existing mjpeg stream to h264 but without success

The reason i want to do this is because i want to use the camera in homeassistant as device(camera.xyz) for taking a video but also want to see the live stream but the h264 stream is laggy 
```
streams:
    usbcam:   ffmpeg:device?video=/dev/video0&input_format=mjpeg&video_size=1920x1080
    usbcam_test:   ffmpeg:device?video=/dev/video0&input_format=mjpeg&video_size=1920x1080#video=h264
    usbcam_h264:   ffmpeg:usbcam#video=h264
```
