### ISSUE TITLE
`fatal error: concurrent map iteration and map write`

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/go2rtc#828]
I'm having this panic in my go2rtc 1.8.4. Initially reported at https://github.com/AlexxIT/go2rtc/issues/762.

Config:

```yaml
api:
  origin: '*'
ffmpeg:
  h264/rk: -c:v h264_rkmpp_encoder -g 50 -bf 0
  h265/rk: -c:v hevc_rkmpp_encoder -g 50 -bf 0
hass:
  config: /config
log:
  format: text
rtsp:
  default_query: mp4
streams:
  birdseye: exec:ffmpeg -hide_banner -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_device
    /dev/dri/renderD128 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -r 10 -i
    /tmp/cache/birdseye -c:v h264_vaapi -g 50 -bf 0 -profile:v high -level:v 4.1 -sei:v
    0 -an -vf format=vaapi|nv12,hwupload -rtsp_transport tcp -f rtsp {output}
  camera_01:
  - rtsp://admin:hidden@192.168.1.20/Streaming/Channels/101#media=video
  - rtsp://127.0.0.1:8554/rua?audio=all
  camera_02:
  - rtsp://admin:hidden@192.168.1.20/Streaming/Channels/201#media=video
  - rtsp://127.0.0.1:8554/rua?audio=all
  camera_03:
  - ffmpeg:rtsp://admin:hidden@192.168.1.20/Streaming/Channels/301#video=copy
  - rtsp://127.0.0.1:8554/rua?audio=all
  camera_04:
  - rtsp://admin:hidden@192.168.1.20/Streaming/Channels/401#media=video
  - rtsp://127.0.0.1:8554/rua?audio=all
  camera_05:
  - rtsp://admin:hidden@192.168.1.20/Streaming/Channels/501
  - rtsp://127.0.0.1:8554/rua?audio=all
  camera_06:
  - rtsp://admin:hidden@192.168.1.20/Streaming/Channels/601
  camera_07:
  - rtsp://admin:hidden@192.168.1.20/Streaming/Channels/701
  camera_08:
  - rtsp://admin:hidden@192.168.1.20/Streaming/Channels/801
  camera_09:
  - rtsp://admin:hidden@192.168.1.20/Streaming/Channels/901
  camera_10:
  - rtsp://admin:hidden@192.168.1.20/Streaming/Channels/1001
  camera_11:
  - rtsp://admin:hidden@192.168.1.20/Streaming/Channels/1101
  camera_12:
  - rtsp://admin:hidden@192.168.1.20/Streaming/Channels/1201
  - rtsp://127.0.0.1:8554/rua?audio=all
  camera_13:
  - rtsp://admin:hidden@192.168.1.20/Streaming/Channels/1301
  camera_14:
  - rtsp://admin:hidden@192.168.1.20/Streaming/Channels/1401
  camera_15:
  - rtsp://admin:hidden@192.168.1.20/Streaming/Channels/1501
  camera_16:
  - rtsp://admin:hidden@192.168.1.20/Streaming/Channels/1601
  rua:
  - ffmpeg:rua_h265#audio=copy#audio=aac#video=h264#hardware=vaapi
  - dvrip://admin:hidden@192.168.1.21:34567?backchannel=1
  rua_h265:
  - rtsp://192.168.1.21/user=admin_password=hidden_channel=0_stream=1&onvif=0.sdp?real_stream
  rua_hd:
  - rtsp://192.168.1.21/user=admin_password=hidden_channel=0_stream=0&onvif=0.sdp?real_stream#media=video
  - rtsp://127.0.0.1:8554/rua?audio=all
webrtc:
  candidates:
  - 192.168.1.10:8555
  - stun:8555
```

[panic.txt](https://github.com/AlexxIT/go2rtc/files/13660986/panic.txt)
