### ISSUE TITLE
Doorbird microphone

### ISSUE THREAD

**Issue by oeiber** [AlexxIT/go2rtc#841]
Hi everybody! Thank you for go2rtc! It's fantastic :-)

At the moment my go2rtc config looks like this:

```
ffmpeg:
    input_mulaw: "-f mulaw -ar 8000 -i {input}"
    noise_filter: "-af highpass=200,lowpass=3000,afftdn"
streams:
  doorbird:
    - ffmpeg:http://user:pass@192.168.178.13/bha-api/bha-api/audio-receive.cgi#media=audio#backchannel=0#input=input_mulaw#audio=opus#audio=noise_filter
    - rtsp://user:pass@192.168.178.13/mpeg/720p/media.amp#media=video
```

Video with audio works fine. But unfortunately doorbird has a seperate http endpoint for audio output (audio-receive.cgi) and audio output (audio-transmit.cgi). Both uses mulaw with a bitrate of 8000. Data have to be sent as http post. Rtsp audio is not supported :-(

Du you have an idea, how to achieve this?
For my opinion, I have to send browsers rstp backchannel audio using ffmpeg. But how can I access the stream? Maybe there is a variable I can use for?

Thank you so much and happy holidays!
