### ISSUE TITLE
AD410 - Request for a copy of a Working config file please

### ISSUE THREAD

**Issue by dhtguru** [AlexxIT/go2rtc#844]
I have an AD410 doorbell camera and have the sound from the microphone, but am unable to send audio to it's speaker.
I have seen from a previous issue raised (#141) that webrtc needs to have audio output of PCMA/8000 or OPUS/48000/2.  However, I am unable to figure out how to do this.  I have read the "codec-madness" section but it was still not clear to me.
```
"medias": [
        "video, recvonly, H.264 Main 5.0",
        "audio, recvonly, MPEG4-GENERIC/8000"
```
Please help.

___________________________________________________________________________

```
mqtt:
  host: 192.168.0.172
  user: admin
  password: psw

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  input_args: preset-rtsp-restream-low-latency
  output_args:
    record: preset-record-generic-audio-copy


go2rtc:
  webrtc:
    candidates:
      - localhost:8555
      - stun:8555  
  api:
    origin: '*'

  rtsp:
    default_query: flac

  streams:
    doorbell:
      - rtsp://usr:psw@192.168.0.166:554/cam/realmonitor?channel=1&subtype=1#backchannel=0
    doorbell_2way_audio:
      - rtsp://usr:psw@192.168.0.166:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - "ffmpeg:doorbell_2way_audio#audio=opus"
snapshots:
  enabled: true
  clean_copy: false

ui:
  live_mode: webrtc
```
