### ISSUE TITLE
ICsee Camera 2 way audio

### ISSUE THREAD

**Issue by alexsagaidak** [AlexxIT/go2rtc#845]
Hi!
Thanks a lot for your hard work. I want to ask for a help with two way audio in cheap China's Camera. I already made all settings, and my conf file looks like:
```
  video_audio_micro: 
    - dvrip://admin:pass@192.168.2.77:34567?channel=0&subtype=0
    - dvrip://admin:pass@192.168.2.77:34567?backchannel=1
```
When I streaming video with such configuration, it is OK. I can hear sounds and picture is fine. But if I try to set mode as WebRTC to add two way audio, picture is in status "loading" and no sound in and out, I can't find where the problem is. Can you help me to solve out?

My yaml card looks like:
```
      - type: custom:webrtc-camera
        ui: true
        mode: webrtc
        streams:
          - url: video_audio
            name: Mic_off
          - url: video_audio_micro
            media: video,audio,microphone
            name: Mic_on
```
In this configuration it's not working. No picture and no sound.
![image](https://github.com/AlexxIT/go2rtc/assets/56589962/75274831-a7be-418f-89ec-048cf947c3b6)

If I commenting mode: webrtc, picture and sound appears, but microphone is not working. Stream opening in MSE mode;
![image](https://github.com/AlexxIT/go2rtc/assets/56589962/fbac8e1d-0fb1-4786-bf4f-b8451d16b337)

In go2rtc panel the same:
![image](https://github.com/AlexxIT/go2rtc/assets/56589962/7896879f-39f3-4e8f-9d18-d17a2970d702)

I push stream button, and no picture...
