### ISSUE TITLE
TP-Link Tapo C120 401 Unauthorized using Tapo Protocol

### ISSUE THREAD

**Issue by grantland** [AlexxIT/go2rtc#849]
I have two C120 units on the same Tapo Cloud account and am having authentication issues using the Tapo Protocol `tapo://` on only one of them.

My config:
```
go2rtc:
  streams:
   c120_A_stream1: 
      - "rtsp://{username_A}:{password_A}@{ip_A}/stream1"
      - "ffmpeg:c120_A_stream1#audio=opus"
    c120_A_stream2: 
      - "rtsp://{username_A}:{password_A}@{ip_A}/stream2"
      - "ffmpeg:c120_A_stream2#audio=opus"
    c120_A_2way: "tapo://admin:{UPPERCASE-MD5}@{ip_A}"

   c120_B_stream1: 
      - "rtsp://{username_B}:{password_B}@{ip_B}/stream1"
      - "ffmpeg:c120_B_stream1#audio=opus"
    c120_B_stream2: 
      - "rtsp://{username_B}:{password_B}@{ip_B}/stream2"
      - "ffmpeg:c120_B_stream2#audio=opus"
    c120_B_2way: "tapo://admin:{UPPERCASE-MD5}@{ip_B}"
```

Using the `stream` link for `c120_B_2way` results in a viewer with the following errors, while using the `stream` link for `c120_A_2way` works just fine: `webrtc/offer: streams: 401 Unauthorized` and sometimes `mse: streams: 401 Unauthorized`

Unsure if related, but I'm seeing the following logs:
```
2023-12-28 22:12:39.766041191  22:12:39.765 ERR github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:166 > error="streams: 401 Unauthorized"
```

What's weird is that I was originally having this issue with both `c120_A_2way` and `c120_B_2way` and found #781 so I attempted to remove and reconnect `c120_B_2way`. After,`c120_A_2way` started working again and `c120_B_2way` still didn't work.

Also before I reconnected `c120_B_2way`, I attempted to use `tapo://{cloud-password}@{IP_A}` and changed by password to not have special characters and this didn't resolve anything.

Lastly, the normal RTSP streams for both A and B work just fine and I've double checked that the passwords between `c120_A_2way` and `c120_B_2way` are the same as well as the IPs on `c120_B_stream1` and `c120_B_2way` are the same.
