### ISSUE TITLE
Webrtc Stream Not Loading

### ISSUE THREAD

**Issue by Maxcodesthings** [AlexxIT/go2rtc#85]
I am able to configure go2rtc however cameras being intercepted by Hoem Assistant do not load their webrtc stream, and the stream doesnt load in the go2rtc web ui either. Other streams work like MSE or HLS, but thats not the point as i want webrtc to work.

It looks like the webrtc stream simply does not load but the rtsp stream behind it is working just fine

My Configuration is as follows:

1. go2rtc.yaml
```
log:
  level: info  # default level
  api: debug
  rtsp: debug
  streams: debug
  webrtc: debug
```
2. go2rtc running as docker using a docker network, not host mode
```
  go2rtc:
    container_name: go2rtc
    image: alexxit/go2rtc
    restart: unless-stopped
    networks:
      - nextcloud_network
    ports:
      - 1984:1984 # API
      - 8443:8443 # srtp
      - 8555:8554 # rtsp
    volumes:
      - "/opt/go2rtc/go2rtc.yaml:/config/go2rtc.yaml"
```
I also had to make the rtsp host port something other than 8554 but that doesnt matter since I configure home assistant with the docker hostname and not IP

3. Installed RTPStoWebRTC and pointed at go2rtc container
![chrome_vfPpTsCLZ5](https://user-images.githubusercontent.com/85802950/197368242-6ba2a260-3d07-4b30-ae87-eb4aec0a13d2.png)

4. Used generic camera for a single camera stream
![chrome_bkDEtKyOKf](https://user-images.githubusercontent.com/85802950/197368245-5f29d9df-1dc1-462c-b79b-5e0f48821481.png)

5. go2rtc portal shows the camera loaded
![chrome_iVAtxe64Hh](https://user-images.githubusercontent.com/85802950/197368250-08c69f04-25f5-4869-ba31-a1756acd4a32.png)

6. No useful logs reported
```
02:14:47.405 INF [api] listen addr=:1984
02:14:47.406 INF [srtp] listen addr=:8443
02:14:47.406 INF [rtsp] listen addr=:8554
02:15:04.878 DBG [streams] probe producer url=rtsp://user:password@192.168.1.58:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
02:15:04.998 DBG [streams] start producer url=rtsp://user:password@192.168.1.58:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
02:15:26.535 DBG [webrtc] new consumer url=camera.192_168_1_58
02:15:56.651 DBG [streams] stop producer url=rtsp://user:password@192.168.1.58:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
```

And of course the problem is webrtc link in both the go2rtc portal and in a picture glance card do not load. MSE seems to work however, but I dont know how to get thet into Home Assistant and I'd rather have webrtc anyways
![chrome_gmvHCYb7hb](https://user-images.githubusercontent.com/85802950/197368310-a9357ec8-2646-4e86-aea0-f1a6b4891bcb.png)

```
- type: picture-glance
          title: Doorbell Cam Glance
          camera_view: live
          entities: []
          camera_image: camera.192_168_1_58
```

Adding the camera streams to the go2rtc.yaml directly and then making a Generic Camera in Home Assistant out of it works fine but it's an HLS stream which is sad
