### ISSUE TITLE
One camera working one other camera not working - i/o timeout

### ISSUE THREAD

**Issue by marcgarciamarti** [AlexxIT/go2rtc#860]
I have 2 anpviz cameras. I managed to get go2rtc working easily with one of the them, whereas regarless of what I do, I can't seem to get it to work with the other camera. 

These are the two cameras:
- working: https://www.amazon.es/gp/product/B07PNSGMGH/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
- not working: https://www.amazon.es/gp/product/B08PNL78LB/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

When the non-working camera is selected on the go2rtc front-end, this is the error message that I see:

```
10:42:48.713 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 192.168.1.5:47862->192.168.1.31:554: i/o timeout" url=rtsp://192.168.1.31:554/stream0
10:42:53.823 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 192.168.1.5:47874->192.168.1.31:554: i/o timeout" url=rtsp://192.168.1.31:554/stream0
10:42:58.931 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 192.168.1.5:57876->192.168.1.31:554: i/o timeout" url=rtsp://192.168.1.31:554/stream0
```

This is my current configuration:

```
streams:
  anpviz-camera-dome-recibidor:
    - rtsp://192.168.1.32:554/stream0
  #  - ffmpeg:dahua1#video=h264#hardware  # if your camera doesn't support H264, important for HomeKit
  #  - ffmpeg:dahua1#audio=opus           # only OPUS audio supported by HomeKit

  anpviz-camera-dome-comedor:
    - rtsp://192.168.1.31:554/stream0
  #  - ffmpeg:dahua1#video=h264#hardware  # if your camera doesn't support H264, important for HomeKit
  #  - ffmpeg:dahua1#audio=opus           # only OPUS audio supported by HomeKit

```

192.168.1.32 is the camera that works. 192.168.1.31 is the camera that does not work.

I think it is important to mention that I can get ONVIF stream off the cameras and that can be displayed on Home Assistant just fine. Moreover, I managed to set up frigate with both cameras and I can even get frigate to motion detect off the low resolution stream (this is a tip that I got when investigated how to reduce the cpu pressure on my setup) and stream recording off the highest resolution stream. 

All my testing with go2rtc has been done with frigate disablede, in order to reduce potential clashes in the backend. I even went ahead and disabled the secondary and third streams on the non-working camera to no avail. I don't see anything on the device configuration that may explain why this other camera is not working correctly, even though both look very much alike, work very much alike and are branded the same. I even tried with the [restream](https://docs.frigate.video/configuration/restream#reduce-connections-to-camera) feature in Frigate, and it does not work either. 

I created an issue with Frigate a few weeks back. I thought I made sense to link it here as it may contain information that may help find a clue to determine how to move forward: https://github.com/blakeblackshear/frigate/issues/8781 
The outputs that I got when testing frigate built-in go2rtc are consistent with what I see now that frigate is not part of the equation. So either my camera has a setting that creates confusion, or the previous and the newest camera firmware are buggy, or there is something in the go2rtc implementation that needs further refinement on my side. I tried all the combinations that I could think of (different encoding profiles, voice enabled/disabled, all streams on, only one stream on, etc.), and that does not make any difference. I even tested go2rtc off the secondary stream and that did not change anything.

Any idea? I would very much appreciate your support in determining next troubleshooting steps. Really looking forward solving this issues.

Thanks in advance!
