### ISSUE TITLE
libcamera-vid executable file not found in $PATH

### ISSUE THREAD

**Issue by luis15pt** [AlexxIT/go2rtc#866]
When using 

streams:
  picam_h264: exec:libcamera-vid -t 0 --inline -o -
  picam_mjpeg: exec:libcamera-vid -t 0 --codec mjpeg -o -

i get this error in docker logs:
go2rtc-1  | 01:15:32.096 ERR github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:166 > error="streams: exec: \"libcamera-vid\": executable file not found in $PATH"

Current docker-compose:
```
services:
  go2rtc:
    image: alexxit/go2rtc:latest
    network_mode: host       # important for WebRTC, HomeKit, UDP cameras
    privileged: true         # only for FFmpeg hardware transcoding
    restart: unless-stopped  # autorestart on fail or config change from WebUI
    volumes:
      - /home/luis/go2rtc:/config   # folder for go2rtc.yaml
```

root@raspberrypi-zero2:/home/luis/go2rtc# libcamera-vid --list-camera
```
Available cameras
-----------------
0 : ov5647 [2592x1944] (/base/soc/i2c0mux/i2c@1/ov5647@36)
    Modes: 'SGBRG10_CSI2P' : 640x480 [58.92 fps - (16, 0)/2560x1920 crop]
                             1296x972 [43.25 fps - (0, 0)/2592x1944 crop]
                             1920x1080 [30.62 fps - (348, 434)/1928x1080 crop]
                             2592x1944 [15.63 fps - (0, 0)/2592x1944 crop]
```
