### ISSUE TITLE
Dahua's camera sound affected when 2-way audio is enabled, but microphone not used

### ISSUE THREAD

**Issue by aanikei** [AlexxIT/go2rtc#872]
Hello,

I'm using Dahua's camera (DH-IPC-HDW1430DT-STW, System Version V2.800.0000000.17.R, Build Date: 2023-07-06, ONVIF Version 21.12(V2.0.1.66848)) with dockerized Frigate (0.12.1) and go2rtc (version 1.8.5 linux/amd64).
When camera's microphone is enabled in it's Web UI (AAC/16000, noise filter disabled), the sound that camera sends becomes muffled, and after microphone is disabled it's loud and clear.
With the config 
```
go2rtc:
  streams:
    camera:
      - rtsp://user:pass@1.2.3.4:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
```

the 2-way audio works fine, but it seems the camera "thinks" that microphone is always enabled and the sound is always muffled. If I remove 
`&unicast=true&proto=Onvif`
or add
`#backchannel=0`
and restart container while listening to camera's sound, the sound becomes loud and clear right away, but of course the 2-way audio no longer works.

Is it separate issue or it's related to https://github.com/AlexxIT/go2rtc/issues/247? Are there plans to fix it in the future?

**Comment by AlexxIT** [comment]
At the moment a working solution is to use two separate streams, for two way audio and without it.

**Comment by aanikei** [comment]
I've tried this configuration:
```
go2rtc:
  streams:
    camera:
      - rtsp://user:pass@1.2.3.4:554/cam/realmonitor?channel=1&subtype=0
    camera_lowres:
      - rtsp://user:pass@1.2.3.4:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
```
and this one
```
go2rtc:
  streams:
    camera:
      - rtsp://user:pass!@1.2.3.4:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    camera_lowres:
      - rtsp://user:pass!@1.2.3.4:554/cam/realmonitor?channel=1&subtype=1
```
with camera having these settings:
![Untitled](https://github.com/AlexxIT/go2rtc/assets/130101347/c029cf9d-06d2-4920-8ec2-ada095762b16)

but in both cases 2 streams are muffled at the same time (may be it makes sense as built-in speaker will not overload camera's sound).
