### ISSUE TITLE
Undefined error=streams: codecs not matched: H264, PCMA => JPEG 

### ISSUE THREAD

**Issue by WebDev-Den** [AlexxIT/go2rtc#885]
Hello everyone. I ran into a problem when receiving an MJPEG source stream. I use a TP-LINK Tapo C110 camera with the following configuration:

```
api:
  origin: "*"
log:
  level: error 
streams:
  web3D: 
   - rtsp://login:password@192.168.1.65:554/stream1
   - onvif://login:password@192.168.1.65:2020?subtype=profile_1 
```

I'm trying to get a stream:
 
`http://192.168.1.40:1984/api/stream.mjpeg?src=web3D`

As a result, I get an error in the logs: 
undefined error=streams: codecs not matched: 

`H264, PCMA => JPEG caller=github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:166`

I tried to install all possible codecs, but the problem persisted.
