### ISSUE TITLE
Android IP Webcam 2 way communication

### ISSUE THREAD

**Issue by zyznos321** [AlexxIT/go2rtc#887]
I have home assistant with frigate extension and go2rtc stream in config. Camera stream is from Android IP webcam app on android phone.

```
go2rtc:
  streams:
    rtsp_cam: # <- for RTSP streams
      - rtsp://log:pass@192.168.0.232:8080/h264_opus.sdp 
      - 
```
Camera stream from ip webcam app is not supporting backchannel. Audio can be sent only via this command:

curl --data-binary @rec.wav http://ip:port/audioin.wav

Is possible to configure 2 way audio communication in stream preview in home assistant?
