### ISSUE TITLE
Unable to override ffmpeg input

### ISSUE THREAD

**Issue by figadore** [AlexxIT/go2rtc#891]
I'm attempting to follow the documentation to override the input template, but it always crashes with little to no indication of the reason. Here's my minimal config

```yaml
go2rtc:
  log:
    level: trace
  webrtc:
    candidates:
      - 10.1.2.2:8555
      - stun:8555
  streams:
    nursery_265:
      - "ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.1.2.12:554/h265Preview_01_main"
    nursery_new:
      - "ffmpeg:nursery_265#input=-i \"{input}\""
```

The only entries in the logs are the following lines (repeated)
```
2024-01-19 20:14:31.887787105  [INFO] Starting go2rtc healthcheck service...
2024-01-19 20:14:32.242689635  [INFO] Preparing go2rtc config...
2024-01-19 20:14:32.662799984  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2024-01-19 20:14:32.703026865  [INFO] The go2rtc service exited with code 1 (by signal 0)
```

I may be misunderstanding the documentation. It currently reads
> You can use raw input value (ex. `#input=-timeout 5000000 -i {input}`)

Which I interpret as meaning that I can add things like `-hwaccel cuda -i {input}`, but whenever I add `{input}` it crashes as described.

Potentially related:
> You can add your own input templates

~What does this mean and how do I do it?~ I think I've got the answer to this. Adding keys to the `ffmpeg` section allows you to reference them in the stream specification with `#my-custom-ffmpeg-template`, for example

For context, I'm trying to reproduce the ffmpeg exec that results from `#video=h264` so that I can modify a few parameters, e.g. 
```
      - "ffmpeg:nursery_265#video#audio=opus#hardware#input=-hwaccel cuda -hwaccel_output_format cuda -extra_hw_frames 2 -i \"{input}\"#raw=-rc vbr -c:v h264_nvenc -g 50 -profile:v high -level:v auto -preset:v p2 -tune:v ll"
```

**Comment by Twanislas** [comment]
Hi, here's how I'm replicating Frigate's `preset-http-reolink` to apply it to my go2rtc sources :
```
ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

go2rtc:
  ffmpeg:
    preset-http-reolink: "-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i {input}"
  streams:
    cam01:
      - ffmpeg:http://cam01.iot/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password={FRIGATE_RTSP_PASSWORD}#video=copy#audio=opus#input=preset-http-reolink

cameras:
  cam01:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/cam01?video=copy&audio=copy
        input_args: preset-rtsp-restream
        roles:
        - record
        - detect
        - audio
```
Works well for me and fixed most of the lag/rebuffer issue I had when viewing streams over WebRTC.

Hope it helps 🤗
