### ISSUE TITLE
Only first-selected camera works ( exit status 228 or EOF)

### ISSUE THREAD

**Issue by RomchikL** [AlexxIT/go2rtc#893]
I have two USB web cameras Logitech.
Is it possible to use both cameras at the same time?

with such conf:
```
streams:
  laxi_camera: ffmpeg:rtsp://login:pass@IP:PORT/Streaming/Channels/101#video=copy
  logitech_3000: ffmpeg:device?video=/dev/video2&input_format=yuyv422&video_size=640x480#video=h264#hardware
  logitech_c525: ffmpeg:device?video=/dev/video4&input_format=yuyv422&video_size=1920x1080#video=h264#hardware
```
I got the following error (when I open a stream from the second camera, e.g. the first cam (3000) works and the second one (c525) gives this error)
```
undefined error=streams: exec: exit status 228 caller=github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:166
```

and with such conf:
```
streams:
  laxi_camera: ffmpeg:rtsp://login:pass@IP:PORT/Streaming/Channels/101#video=copy
  logitech_3000: ffmpeg:device?video=/dev/video2&input_format=yuyv422&video_size=640x480#video=h264#hardware
  logitech_c252: ffmpeg:device?video=/dev/video4&input_format=mjpeg&video_size=1920x1080
```
I got the error (with the same
```
undefined error=streams: EOF caller=github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:166
```
