### ISSUE TITLE
Combine 2 RTSP Streams

### ISSUE THREAD

**Issue by mavinV6** [AlexxIT/go2rtc#901]
I am trying to combine the RTSP of two identical cameras (Reolink E1 Zoom) into one stream.

Under Windows it works fine with the following command:

ffmpeg 
-rtsp_transport tcp -i "rtsp://192.168.170.196:8554/kind1?video=all" 
-rtsp_transport tcp -i "rtsp://192.168. 170.196:8554/kind2?video=all" 
-filter_complex ""crop=1152:1296:0:0[v0];crop=1152:1296:0:0[v1];[v0][v1]hstack[v]"" 
-map [v] 
-vcodec libx264 
-pix_fmt yuv420p 
-preset ultrafast "test.avi"

How do I reformat this so that go2rtc understands it correctly?

My attempt was:
```
go2rtc:
  streams:
    child1:
      - "rtsp://x:x@192.168.170.14:554/h264Preview_01_main#video=h264"
    child2:
      - "rtsp://x:x@192.168.170.15:554/h264Preview_01_main#video=h264"
    children:
      - ffmpeg:child1#raw=-rtsp_transport tcp -i "rtsp://192.168.170.196:8554/child2? video=all" -filter_complex "crop=1152:1296:0:0[v0];crop=1152:1296:0:0[v1];[v0][v1]hstack[v]" -map [v] -rtsp_transport tcp -f rtsp {[output}}

```

Unfortunately it does not work.

Does anyone have a tip?

Thanks in advance!
