### ISSUE TITLE
How to add a go2rtc stream into HomeKit

### ISSUE THREAD

**Issue by krlc** [AlexxIT/go2rtc#909]
Spent hours trying to understand the process, to no avail.

I want to add a H264 camera, which I stream through go2rtc, into my HomeKit home. If I understand correctly, it's possible.
However what I don't understand is how the pairing process works.

- Apple Home app expects a QR code (which I don't have?),
- or I can see locally discovered devices (which doesn't list my camera),
- or I can enter a password manually (which does nothing).

So how is the process supposed to work? Documentation (the readme file) doesn't mention that at all...

Does go2rtc use mDNS for announcing the camera? If so, what kind of configuration from the mDNS daemon is needed? (I use avahi, so in  `/etc/avahi/avahi-daemon.conf` I set `publish-workstation=yes`, tried also with `no`.)
I also monitored new mDNS announcements (via macOS's `dns-sd -B`) and saw no new devices appear.
I did disable firewall (in case of random ports?), but that changed nothing.

Here's my config:
```yaml
streams:
  car:
    - rtsp://login:pass@192.168.1.5/live
    - ffmpeg:car#audio=opus

homekit:
  car:
    name: Car camera

webrtc:
  candidates:
  - 192.168.1.15:8555

rtsp:
  listen: ":8554"    # RTSP Server TCP port, default - 8554
  username: "admin"  # optional, default - disabled
  password: "pass"   # optional, default - disabled
  default_query: "video&audio"
```

Here's the output log (that's all I get):
```
[test@tyan-epyc go2rtc]$ ./go2rtc_linux_amd64
00:41:02.620 INF go2rtc version 1.8.5 linux/amd64
00:41:02.621 INF [api] listen addr=:1984
00:41:02.621 INF [rtsp] listen addr=:8554
00:41:02.621 INF [webrtc] listen addr=:8555
```

Tried with `1.8.2`.

In web GUI in `Add` tab, under Apple HomeKit, I can see my own camera as `Car-camera	go2rtc/1.8.5	homekit://192.168.1.15:1984?device_id=39:DB:AB:1A:2B:C8&feature=0&status=1`, so something seems working.

I'm extremely confused what I'm wrong.
