### ISSUE TITLE
webRTC does not work from some IPs

### ISSUE THREAD

**Issue by mainmaster** [AlexxIT/go2rtc#914]
Hello! I'm using go2rtc on a server with an external IP and using external port 8555 and thought that now they could easily connect to me.
However, I notice that some users can watch the video, but some cannot. With what it can be connected?

```
streams:
  enter:
    - rtsp://admin:admin@192.168.90.157:554/ISAPI/Streaming/Channels/102
  exit:
    - rtsp://admin:admin@192.168.90.158:554/ISAPI/Streaming/Channels/102
  street:
    - rtsp://admin:admin1234@192.168.90.159:554/RVi/1/1
api:
  listen: ":1984"    # default ":1984", HTTP API port ("" - disabled)
  origin: "*"        # default "", allow CORS requests (only * supported)
webrtc:
  candidates:
    - 85.*.*.*:8555  # if you have static public IP-address
log:
  level: debug  # default level
  api: debug
  exec: debug
  ngrok: debug
  rtsp: debug
  streams: debug
  webrtc: debug

username: "admin"  # default "", Basic auth for WebUI
password: "admin12345"   # default "", Basic auth for WebUI

```
