### ISSUE TITLE
Help wanted: Tapo C210 + amd gpu + frigate?

### ISSUE THREAD

**Issue by ignacio82** [AlexxIT/go2rtc#922]
I'm trying to understand what is the best way of configuring my tapo c210 cameras with frigate. This is what I'm doing with the go2rtc container

```
services:
  go2rtc:
    image: alexxit/go2rtc:master-hardware
    network_mode: host       # important for WebRTC, HomeKit, UDP cameras
    privileged: true         # only for FFmpeg hardware transcoding
    restart: unless-stopped  # autorestart on fail or config change from WebUI
    environment:
      - TZ=America/Los_Angeles  # timezone in logs
    volumes:
      - "nfs-go2rtc:/config"   # folder for go2rtc.yaml file (edit from WebUI)
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/kfd:/dev/kfd
      - /dev/dri/card0:/dev/dri/card0      
volumes:
  nfs-go2rtc:
    external: true      
```
And this is what I currently have in my config for go2rtc

```
streams:
  family_room: onvif://ignacio:MYLOCALPASSWORD@192.168.86.156:2020?subtype=profile_1#video=h264#hardware
  family_room_sub: onvif://ignacio:MYLOCALPASSWORD@192.168.86.156:2020?subtype=profile_2#video=h264#hardware
  tapo_family_room: tapo://MYPASSWORD@192.168.86.156#video=h264#hardware
```
I have the following questions:

1.  Am I configuring hardware acceleration correctly? 
2. Is it better to use onvif or tapo for my cameras? 
3. If the answer is tapo, do i only get one stream out of it? If so, how does quality compares to the two that I get with onvif? 
4. Based on my configuration, how should I configure the cameras section of my frigate? I tried this:

```
cameras:
           
  family_room:
    ffmpeg:
      inputs:
        - path: rtsp://mini-server.local:8554/tapo_family_room?mp4
          roles:
            - record 
            - detect   
            - audio         
    onvif:
      host: 192.168.86.156
      port: 2020
      user: ignacio
      password: MYLOCALPASSWORD
```

Thanks for the help!
