### ISSUE TITLE
RTSP Streaming: problems with Apple devices

### ISSUE THREAD

**Issue by francescobianca** [AlexxIT/go2rtc#927]
Hi, I am using this library with nginx in front for streaming rtsp. Tested without problems with linux and windows while it gives us problems with Apple devices (any browser). This is my go2rtc.yaml

```
streams:
  stream_key: rtsp://{USERNAME}:{PASSWORD}@{SERVER_IP}:{SERVER_PORT}/cam/realmonitor?channel=1&subtype=2#timeout=30

log:
  level: info  # default level
  rtsp: debug
  streams: debug
  webrtc: debug
```

My docker compose:
```
version: '3.7'

services:

  nginx:
    image: my_registry/openresty-nginx-jwt:0.1.0
    ports:
      - "443:443"
    volumes:
      - ./nginx/conf/nginx.conf:/nginx.conf
      - ./nginx/conf/bearer.lua:/bearer.lua
      - ./nginx/certs:/conf/certs:ro
    environment:
      JWT_SECRET: ${JWT_SECRET}

  go2rtc:
    image: alexxit/go2rtc
    volumes:
      - ./go2rtc/go2rtc.yaml:/config/go2rtc.yaml
```

The nginx only does the proxy pass on the 1984 internal go2rtc. With the mac we are only able to view MSE. Instead, the link we would like to reproduce is as follows:

**https://{addresss}/webrtc.html?src=stream_key&media=video**

NB: it works correctly on other operating systems while giving errors only on Apple. Has anyone ever had such problems?
