### ISSUE TITLE
Nest camera video corruption only when go2rtc and camera on same network

### ISSUE THREAD

**Issue by clasoncj** [AlexxIT/go2rtc#937]
Video corruption is occurring on all of my Nest camera feeds but only if the system running go2rtc is on the same network as the Nest cameras. Issue occurs on multiple hosts running go2rtc (Mac laptop, 2 x RPis with Ubuntu and Linux VM) and with all of the Nest camera feeds. 

The video corruption issue goes away if running go2rtc on a machine that is not on the same network as the cameras. Have tested with a GCP VM and my laptop. Debug logs from go2rtc are identical in both passing and failing case. No issues with RTSP streams from standard IP cameras and no issues with displaying the camera feeds through Google Home app when on the local network. 

Fails every time, happy to collect additional logs or provide remote access to debug.

```
log:
  level: debug
  streams: debug
  webrtc: debug

webrtc:
  listen: ":8555"

streams:
nest-doorbell:
    - nest:?<redacted> 
```

<img width="1349" alt="Screenshot 2024-02-10 at 11 27 03 AM" src="https://github.com/AlexxIT/go2rtc/assets/11299976/2a392f75-a359-4f97-9d4e-219b8d91c2b5">
