### ISSUE TITLE
Nest doorbell stream has no audio

### ISSUE THREAD

**Issue by backslashV** [AlexxIT/go2rtc#938]
Hi,
I'm unable to add audio to the Nest doorbell camera stream. The original camera entity from the Nest integration does have audio. Currently, I am using the [hass-expose-camera-stream-source](https://github.com/felipecrs/hass-expose-camera-stream-source) integration to be able to use this camera in Frigate. My Frigate go2rtc config:
```
go2rtc:
  streams:
    doorbell:
      - echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.doorbell
      - "ffmpeg:doorbell#audio=aac"
```
Tried without the `ffmpeg:doorbell#audio=aac` also w/o luck.
Relevant log snippet:

`2024-02-11 04:10:29.601473759  20:10:29.601 WRN [rtsp] error="streams: codecs not matched: AAC => ANY" stream=doorbell`
