### ISSUE TITLE
Using a different webtorrent tracker

### ISSUE THREAD

**Issue by jjorosa** [AlexxIT/go2rtc#943]
Hi everyone,

I've setup an independent webtorrent tracker using the [openwebtorrent-tracker](https://github.com/OpenWebTorrent/openwebtorrent-tracker) utility.

From the example, I've changed in the go2rtcex.html so it points to my openwebtorrent tracker.

However, it seems that the go2rtc keeps calling the `wss://tracker.openwebtorrent.com/` (it appears in the log as a debug entry).

`
[webtorrent] connect to tracker: wss://tracker.openwebtorrent.com
`

Is there any way that I can change in the configuration the tracker that should be used?

Thank you in advance!

**Comment by AlexxIT** [comment]
Trackers. Undocumented feature
https://github.com/AlexxIT/go2rtc/blob/5fa31fe4d6cf0e77562b755d52e8ed0165f89d25/internal/webtorrent/init.go#L19-L29

**Comment by jjorosa** [comment]
I changed the go2rtc.yaml to include the trackers section:

```
webtorrent:
    shares:
        mysecretshare3132123:  # share name, should be unique among all go2rtc users!
            pwd: xxxxxxx
            src: camera1
    trackers:
        [wss://trackers.mytrackersxxxx.com]
```

That did the trick!

Thanks, @AlexxIT
