### ISSUE TITLE
HomeKit video freezing (only show key frame)

### ISSUE THREAD

**Issue by 0x5e** [AlexxIT/go2rtc#944]
Hi, I'm trying to push ffmpeg lavfi testsrc & anoisesrc stream to go2rtc, and watch the video via ffplay & homekit app.
ffplay works well, but on homekit app, the video is always stuck, image update every 5 seconds which is maching the gop size 125 (25fps * 5seconds).

go2rtc config:
```
streams:
    lavfi:

log:
    format: ""
    level: "debug"

homekit:
    lavfi:
        pin: 12345678
        name: lavfi camera
        pairings:
          - client_id=xxxxx&client_public=xxxxx&permissions=1
          - client_id=xxxxx&client_public=xxxxx&permissions=0
```

push stream command:
```
ffmpeg -hide_banner -loglevel warning \
    -re -f lavfi -i testsrc=size=1280x720:rate=30 \
    -re -f lavfi -i anoisesrc=c=3 \
    -r 25 -codec:v libx264 -g 125 \
    -codec:a pcm_s16be -ar 8k -ac 2 \
    -rtsp_transport tcp -f rtsp rtsp://:8554/lavfi
```
If I change `-g` to `50`, image update every 2 seconds then.

ffplay command:
```
ffplay -fflags nobuffer -flags low_delay -rtsp_transport tcp "rtsp://localhost:8554/lavfi"
```

any suggestions? thanks in advance.
