### ISSUE TITLE
RTMP Stream Failure Post go2rtc Upgrade from 1.7.1 to 1.8.0+

### ISSUE THREAD

**Issue by VoidNullNil** [AlexxIT/go2rtc#947]
After updating the go2rtc version from 1.7.1 to 1.8.0 or later, the RTMP stream, sourced from [datarhei Restreamer](https://github.com/datarhei/restreamer), has ceased functioning. Prior to the upgrade, the configuration for the stream was working as expected. Post-upgrade, the stream no longer initiates successfully.

#### Current Configuration:
```yaml
streams:
  corner:
  - rtmp://192.168.1.20/stream/2b3ef742-e0af-4248-8ba5-949ac7666ef0.stream
```

To workaround this issue, I modified the stream configuration to use ffmpeg, which allowed the stream to start. However, this adjustment led to a significant increase in CPU usage, indicating it's not a viable long-term solution.

#### Modified Configuration (With High CPU Usage):
```yaml
streams:
  corner:
  - ffmpeg:rtmp://192.168.1.20/stream/2b3ef742-e0af-4248-8ba5-949ac7666ef0.stream
```

I am seeking assistance to resolve the RTMP stream failure post-upgrade and to find a solution that does not adversely affect the system's CPU performance.
