### ISSUE TITLE
Sending 2 Way Audio From Apple Home App

### ISSUE THREAD

**Issue by lingxide** [AlexxIT/go2rtc#950]
Hello,

I have setup a ONVIF Camera with opus audio which converted from ffmpeg and exported to Homekit. Both audio/video from the camera works perfectly. However when I say something in Apple Home App it seems to be not working. 

I want to understand if it a config error my side or some features haven't been implemented yet?

From #162 I understand it could be something not implemented yet?

Many thanks. 

Configs:

```
streams:
  xyt: onvif://admin:pass@192.168.1.136:80?subtype=profile_1
  pet: onvif://admin:pass@192.168.1.137:80?subtype=profile_1
  xyt_converted: ffmpeg:rtsp://ha.esxi:8554/xyt#audio=opus#video=h264
  pet_converted: ffmpeg:rtsp://ha.esxi:8554/pet#audio=opus#video=h264
homekit:
  xyt_converted:
    pin: MASKED
    name: XYT Converted
    pairings:
      - client_id=MASKED
      - client_id=MASKED
  pet_converted:
    pin: MASKED
    name: PET Converted
    pairings:
      - client_id=MASKED
      - client_id=MASKED

```

Reason I use a new entity with *_converted* is seems it doesn't work when converting an onvif source to ffmpeg directly.
