### ISSUE TITLE
Video stops playing, spinner starts spinning - restarting go2rtc works

### ISSUE THREAD

**Issue by mortenmoulder** [AlexxIT/go2rtc#953]
A few days ago I went from an old ASUS router to opnSense. Since then, I think, a few of my cameras has started acting weird. The video stops playing and it starts spinning. If I refresh the page, I get 1 new frame, but it just keeps spinning. Refresh again, new frame.

After a while it starts playing again (usually about an hour), but then fails again after a while. What always works: Restarting the go2rtc container.

It seems like it's only the consuming of the feed via go2rtc that fails. This can also be confirmed by opening up VLC and accessing the stream via the RTSP URL like this: `rtsp://rtsp:password@192.168.1.94:554/av_stream/ch0` which works perfectly.

Not a single one of the stream URLs from the go2rtc web interface work.

I am unsure where to go from this. Could it be an opnSense issue? Traffic doesn't go through opnSense, because opnSense only acts like a router and firewall. My go2rtc is up to date (1.8.5) and there are no errors in the log at all.

go2rtc config:

```
streams:
  camera1: rtsp://rtsp:password@192.168.1.94:554/av_stream/ch0
webrtc:
  listen: ":8555"
  candidates:
    - public_ip:8555
    - homeassistant.example.com:8555
    - 192.168.1.1/24:8555
```

EDIT: The camera this primarily happens to is a Sonoff GK-200MP2-B
