### ISSUE TITLE
Please help, can read go2rtc.yaml under Windows

### ISSUE THREAD

**Issue by Barabba11** [AlexxIT/go2rtc#954]
Hi, I'm wasting time for something so simple. I've Win7 64, I created folder C:\1, I copied there go2rtc.exe, created next to it go2rtc.yaml and pasted inside this:
```
streams:
  enter:
    - rtsp://root:password@192.168.24.104:5404/live.sdp
api:
  listen: ":1984"    # default ":1984", HTTP API port ("" - disabled)
  origin: "*"        # default "", allow CORS requests (only * supported)
webrtc:
  candidates:
    - *.*.*.*:8555  # if you have static public IP-address
log:
  level: debug  # default level
  api: debug
  exec: debug
  ngrok: debug
  rtsp: debug
  streams: debug
  webrtc: debug

username: "admin"  # default "", Basic auth for WebUI
password: "admin12345"   # default "", Basic auth for WebUI
```

With or without go2rtc.yaml I always have the same output:
```
12:37:59.055 INF go2rtc version 1.8.5 windows/amd64
12:37:59.081 12:37:59.081INF  [rtsp] listen INFaddr= [api] listen :8554
addr=:1984
12:37:59.082 INF [webrtc] listen addr=:8555
```
I've tried specifing the file and not
C:\1>go2rtc c:\1\go2rtc.yaml
no way,

I open the browser on the same server and type  http://127.0.0.1:8555 or https://127.0.0.1:8555 and I can't see nothing
on http://127.0.0.1:1984/ I don't see streams, I added it manually but nothing solved

It's very complicated to find a simple valid go2rtc.yaml where I can try to figure out mself (
I just need to create a web server and ashow there the only video stream froma camera. Can you kindly help me? Thank you

**Comment by jiekechoo** [comment]
It's a docker issue,you should make a `volume` to container,like:

```
docker run -v folder:folder …
```

**Comment by jiekechoo** [comment]
Maybe you should use docker instead of the exe app.

**Comment by Barabba11** [comment]
> Maybe you should use docker instead of the exe app.

Come on, I can't believe it. If there is an exe version should work properly, especially the mein thing, reading go2rtc.yaml, I'll wait for someone who explain me the trick

**Comment by jiekechoo** [comment]
try this: 
`go2rtc -config c:\1\go2rtc.yaml`

**Comment by Barabba11** [comment]
> try this: `go2rtc -config c:\1\go2rtc.yaml`

Thank you for you kind reply, unfortunately any positive result, the exe starts in the same way as before, -version works. The file is ANSI coded, so it should work.
I can't find a declared valid example, I can try only to guess, so I've tried with this simple thing
```
go2rtc:
  streams:
    back:
      - rtsp://user:password@10.0.10.10:554/cam/realmonitor?channel=1&subtype=2
```
the difference is slight, 

WIth first script:
```
C:\1>go2rtc -config go2rtc.yaml
22:11:46.567 INF go2rtc version 1.8.5 windows/amd64
22:11:46.59422:11:46.594  INFINF [api] listen addr= [rtsp] listen :1984
addr=:8554
22:11:46.597 INF [webrtc] listen addr=:8555
exit with signal: interrupt
```

And with the simple example:
C:\1>go2rtc -config go2rtc.yaml
22:12:59.773 INF go2rtc version 1.8.5 windows/amd64
22:12:59.80122:12:59.801  INFINF [api] listen  [rtsp] listen addr=addr=:1984
:8554
22:12:59.805 INF [webrtc] listen addr=:8555

Why it is so complicated? 
Can please the author help me having it work? Thanks

**Comment by Barabba11** [comment]
I tried also with web page setup, I added stream, changed configuration and runned it, no changes. on logs I still always see 
```
21/2/2024, 22:49:56	info	go2rtc version 1.8.5 windows/amd64
21/2/2024, 22:49:56	info	[rtsp] listen addr=:8554
21/2/2024, 22:49:56	info	[api] listen addr=:1984
21/2/2024, 22:49:56	info	[webrtc] listen addr=:8555
```

what is wrong with this program? Why it refuses to accept any changes I try to make?

**Comment by Barabba11** [comment]
I managed to have it working, this program is really sensible, a little mistake will not make it work and there are no outputs that helping you understand you wrong with something.
First, the 64 version is a bit bugging I guess, I couldn't manage the ports with first config files while 32bit did. So I keep working with 32 and I understood that there should be a logic nto the yaml file, you cant messy with arguments. You don't have to leave blanks before the key word (for example api: or streams:) and don't leave empty lines between them. I sould understand it only with help of web editor, which shows if there are problems, but not all the problems.

A good way is to use the editor instead of yamb file, and work with yamb only when you have a well written script, use only editor and check on streams if it catched that correctlym enable logs (in editor) if you want to go deeper, because if it works there are no signs that it opened correctly the rtsp source for example, or somebody has been connected.
the web page with editor, logs etc can also drive you to the result, using the path
http://IpAddressOfTheServer/stream.html?src=TheNameOfStreamYouGave, in my case http://127.0.0.1/stream.html?src=Detskaya

I used this script with version 1.85, please copy past it as it is and adapt with your rtsp:
```
api:
  listen: ":80"    # default ":1984", HTTP API port ("" - disabled)
  origin: "*"        # default "", allow CORS requests (only * supported)
streams:
    Detskaya:
    - rtsp://user:password@192.168.24.113:5413/live.sdp 
webrtc:
    candidates:
    - stun:8555

```

my goal is to have web server working directly on 80, when I tested it ofer internet my phone browser pretended to open https link, horrible, I'll manage it tomorrow. Video stream works great with audio too, starts automatically, low latency, fluent, no trancoding, no CPU usage, perfect. 
I've tried then to replace exe with 64, works too but while starting/buffering there are appearing some artifacts, so I sta on 32bit version.

This is what I desidered to read as beginner, at least an example that works 100% and where is possible to start developing from this base, something else.

In end of all I would thank the author for such cool thing he created!
