### ISSUE TITLE
go2rtc+frigate USB cam stream

### ISSUE THREAD

**Issue by Andr3WTF** [AlexxIT/go2rtc#958]
Can you please help me go2rtc stream working in frigate? in original addon 1.8.5 such config go2rtc.yaml **working fine** 
`streams:
    front_door: ffmpeg:device?video=/dev/video0&input_format=yuyv422&video_size=1280x720#video=h264#hardware `
But in included in frigate go2rtc version 1.8.4 such config isn't working and unfortunately not providing logs tab
`api:
  origin: '*'
ffmpeg:
  h264/rk: -c:v h264_rkmpp_encoder -g 50 -bf 0
  h265/rk: -c:v hevc_rkmpp_encoder -g 50 -bf 0
hass:
  config: /config
log:
  format: text
rtsp:
  default_query: mp4
streams:
  front_door: ffmpeg:device?video=/dev/video0&input_format=yuyv422&video_size=1280x720#video=h264#hardware
webrtc:
  candidates:
  - 192.168.1.10:8555
  - stun:8555`
All i see is error: `mse: streams: exec: exit status 1`

**Comment by AlexxIT** [comment]
Probably inside Frigate your camera is inaccessible

**Comment by Andr3WTF** [comment]
Yes! i fixed it by adding this string into frigate config: `input_args: preset-rtsp-restream`
```
go2rtc:
  streams:
   front_door: ffmpeg:device?video=/dev/video0&input_format=yuyv422&video_size=1280x720#video=h264#hardware  inputs:
        - path: /dev/video0
          input_args: preset-rtsp-restream
```
but it stop showing live preview into frigate... Maybe usb cam can't be accesible for multiple instances? Confusing...
