### ISSUE TITLE
ISAPI audio input not working to Hikvision DS-2CD2386G2-ISU/SL

### ISSUE THREAD

**Issue by f1d094** [AlexxIT/go2rtc#962]
Although I am able to send audio to the camera via curl, audio via the ISAPI connection via go2rtc fails to send. Modifying client.go to call '/ISAPI/System/TwoWayAudio/channels/1/close' before '/ISAPI/System/TwoWayAudio/channels/1/open' allows the connection to actually open...but it isn't reliable.

curl --digest "http://$USER:$PASS@192.168.10.4/ISAPI/System/TwoWayAudio/channels"

Output:          
```
<?xml version="1.0" encoding="UTF-8"?>
<TwoWayAudioChannelList version="2.0" xmlns="http://www.hikvision.com/ver20/XMLSchema">
<TwoWayAudioChannel version="2.0" xmlns="http://www.hikvision.com/ver20/XMLSchema">
<id>1</id>
<enabled>false</enabled>
<audioCompressionType>G.711ulaw</audioCompressionType>
<speakerVolume>100</speakerVolume>
<noisereduce>true</noisereduce>
<audioInputType>MicIn</audioInputType>
</TwoWayAudioChannel>
</TwoWayAudioChannelList>
```
          
curl --digest -X PUT "http://$USER:$PASS@192.168.10.4/ISAPI/System/TwoWayAudio/channels/1/close"

Output:          
```
<?xml version="1.0" encoding="UTF-8"?><ResponseStatus version="2.0" xmlns="http://www.hikvision.com/ver20/XMLSchema">
<requestURL></requestURL>
<statusCode>1</statusCode>
<statusString>OK</statusString>
<subStatusCode>ok</subStatusCode>
</ResponseStatus>
```

curl --digest -X PUT "http://$USER:$PASS@192.168.10.4/ISAPI/System/TwoWayAudio/channels/1/open"

Output:          
```
<?xml version="1.0" encoding="UTF-8"?>
<TwoWayAudioSession version="2.0" xmlns="http://www.hikvision.com/ver20/XMLSchema">
<sessionId>2135689571</sessionId>
</TwoWayAudioSession>
```
Finally, sending audio file which works:

curl --digest -X PUT -H "Content-Length: 0" -H "Content-Type: application/octet-stream" -d @duck.ulaw "http://$USER:$PASS@192.168.10.4/ISAPI/System/TwoWayAudio/channels/1/audioData"

Review of .pcaps revealed constant authorization errors. After a lot of poking, I found that if I did:

curl --digest -X PUT "http://$USER:$PASS@192.168.10.4/ISAPI/System/TwoWayAudio/channels/1/close"

Before opening the MicOn view then it would work. This is the card config:

```
type: custom:webrtc-camera
ui: true
streams:
  - url: Front_Door-Live
    mode: webrtc
    media: video,audio
    muted: true
    name: Mic Off
    style: '.pictureinpicture {display: none} .screenshot {display: none}'
  - url: Front_Door-Intercom
    mode: webrtc
    muted: false
    media: video,audio,microphone
    name: Mic On
    style: '.pictureinpicture {display: none} .screenshot {display: none}'
```

I tried to modify /pkg/isapi/client.go to do a 'close' before 'open' and that kindof works but isn't reliable, go2rtc sometimes not returning with a stream when switching the from microphone off/on.
