### ISSUE TITLE
Tapo protocol slower then direct rtsp link, anything to do to improve this?

### ISSUE THREAD

**Issue by borgqueenx** [AlexxIT/go2rtc#977]
I have a camera with not ideal range, and when using the following configuration in frigate...

```
 go2rtc:
   streams:
     basement-cam:
     - rtsp://***********:**********@192.168.1.145/stream1
#     - tapo://************@192.168.1.145
     - ffmpeg:basement-cam#audio=aac
```

I am getting quite a good connection, some frames being skipped but i can always see whats happening.

Where as the following configuration...

```
 go2rtc:
   streams:
     basement-cam:
#     - rtsp://***********:**********@192.168.1.145/stream1
     - tapo://************@192.168.1.145
     - ffmpeg:basement-cam#audio=aac
```

Causes a lot of "no frames received" in frigate, and opening the link barely works.

You can reproduce this by having a tapo camera (c125 in my case) in a not ideal wifi spot and swapping between the protocols like i did above. It also seems that enabling them both together, go2rtc picks the slow option and i get the issues.
