### ISSUE TITLE
Question: How to specify which stream when camera has multiple streams

### ISSUE THREAD

**Issue by NickM-27** [AlexxIT/go2rtc#98]
Let's say I have go2rtc setup:

```yaml
streams:
  camera: 
    - rtsp://ip:554/feed # audio on this is PCMA
    - ffmpeg: rtsp://ip:554/feed#video=copy#audio=aac
```

how would I go about specifying that I want the stream with aac for MSE and the stream with PCMA for webRTC? Does go2rtc do this automatically?

**Comment by AlexxIT** [comment]
You don't need video in ffmpeg. 
```
streams:
  camera: 
    - "rtsp://ip:554/feed # audio on this is PCMA"
    - "ffmpeg: rtsp://ip:554/feed#audio=aac"
```

**Comment by NickM-27** [comment]
> You don't need video in ffmpeg. It will run faster.
> ```
> streams:
>   camera: 
>     - "rtsp://ip:554/feed # audio on this is PCMA"
>     - "ffmpeg: rtsp://ip:554/feed#audio=aac"
> ```

Okay thanks that's good to know, if I open the MSE stream will it automatically know to use the stream with AAC audio?

**Comment by AlexxIT** [comment]
Yes. Each consumer has capabilities

https://github.com/AlexxIT/go2rtc/blob/764a9ed5ebf38c4aab9a916705a5ab8fb311355a/pkg/mp4/consumer.go#L25

**Comment by AlexxIT** [comment]
MP4 should be updated to dynamic capabilities, because not all browsers support H265 for this source.

**Comment by NickM-27** [comment]
Thanks that explains what I needed to know 😄

**Comment by AlexxIT** [comment]
Also there is no `aac` template for ffmpeg. There is `aac/16000`:

https://github.com/AlexxIT/go2rtc/blob/master/cmd/ffmpeg/ffmpeg.go

**Comment by felipecrs** [comment]
> Also there is no aac template for ffmpeg.

Believe you or not, the following works fine for me:

```yaml
streams:
  rua_hd_acc:
    - ffmpeg:rtsp://admin:pass@192.168.1.33:554/0/av0#video=copy#audio=aac
```

I.e. it properly transcodes audio to AAC:

![image](https://user-images.githubusercontent.com/29582865/200692196-887f5ca0-5751-4d4b-ab40-6f3d24ab7601.png)
19419ede44d5.png)
