### ISSUE TITLE
microphone not always working, what can i do to debug?

### ISSUE THREAD

**Issue by borgqueenx** [AlexxIT/go2rtc#980]
I have some Annke camera's, where i sometimes try to use the build-in speaker of.
I notice that most of the times, there is no sound being played while i talk to the cameras. But sometimes it works. I cant figure out yet why and when this happens.
I use the following link as example to use the microphone: https://sub.domain.site/webrtc.html?src=camera&media=video+audio+microphone
This is happening with camera's set to h265 on the main stream, and use h264 as substream. ffmpeg has AAC enabled, the cameras itself use G7.11ulaw as audio codec.
here is the configuration used in frigate:
```
go2rtc:
  streams:
    house-corner-garden-view:
    - rtsp://admin:***********@192.168.1.242:554/Streaming/Channels/101/
    - rtsp://admin:***********@192.168.1.242:554/Streaming/Channels/102/
    - ffmpeg:house-corner-garden-view#audio=aac
```

Some time to help find the cause and then hopefully solve it in a later release would be appriciated! :)
