### ISSUE TITLE
Select http jpeg source when creating snapshot for homekit

### ISSUE THREAD

**Issue by latargere** [AlexxIT/go2rtc#996]
Hi, 

I have started using this module for homekit support and I have a bunch of Reolink camera that has a snapshot urls.
When using homekit, it would be great if the source used for creating a snapshot will select the jpeg source instead of using the full stream that needs to be transcoded.

**Comment by AlexxIT** [comment]
If stream will have jpeg source earlier than video source - jpeg source will be used for snapshot.
But first source (jpeg) will be called on each open stream. This process should be optimized in the future.

**Comment by alyyousuf7** [comment]
my front doorbell video source is pretty tall (Nest HASS integration):
<img width="1027" alt="image" src="https://github.com/user-attachments/assets/37f22f16-ac47-4386-8b4a-881a147ab1ac">

```yaml
streams:
    front_doorbell:
        - hass://supervisor?entity_id=camera.front_doorbell
```

but for some reason the snapshot HomeKit takes from the video stream does not seem right (aspect ratio gets screwed up):
<img width="245" alt="image" src="https://github.com/user-attachments/assets/a2b2a978-ee9c-406b-b826-cfc0857a4be6">

to fix that, i have to create another stream, so that i can use `ffmpeg` to output an `mjpeg` stream for snapshot:

```yaml
streams:
    front_doorbell_og:
        - hass://supervisor?entity_id=camera.front_doorbell
    front_doorbell:
        - ffmpeg:front_doorbell_og#video=mjpeg
        - hass://supervisor?entity_id=camera.front_doorbell
```

this works fine ^

but is there a better way, to avoid creating another named stream? it seems i cannot do the following:

```yaml
streams:
    front_doorbell:
        - ffmpeg:hass://supervisor?entity_id=camera.front_doorbell#video=mjpeg
        - hass://supervisor?entity_id=camera.front_doorbell
OR
streams:
    front_doorbell:
        - ffmpeg:front_doorbell#video=mjpeg
        - hass://supervisor?entity_id=camera.front_doorbell
```
